<?php namespace FGTA4\apis;

if (!defined('FGTA4')) {
	die('Forbiden');
}

require_once __ROOT_DIR.'/core/sqlutil.php';
require_once __ROOT_DIR . "/core/sequencer.php";
require_once __DIR__ . '/xapi.base.php';


use \FGTA4\exceptions\WebException;
use \FGTA4\utils\Sequencer;



/**
 * finact/procurement/orderout/apis/save.php
 *
 * ====
 * Save
 * ====
 * Menampilkan satu baris data/record sesuai PrimaryKey,
 * dari tabel header orderout (trn_orderout)
 *
 * Agung Nugroho <agung@fgta.net> http://www.fgta.net
 * Tangerang, 26 Maret 2021
 *
 * digenerate dengan FGTA4 generator
 * tanggal 09/10/2021
 */
$API = new class extends orderoutBase {
	
	public function execute($data, $options) {
		$tablename = 'trn_orderout';
		$primarykey = 'orderout_id';
		$autoid = $options->autoid;
		$datastate = $data->_state;

		$userdata = $this->auth->session_get_user();

		try {

			// cek apakah user boleh mengeksekusi API ini
			if (!$this->RequestIsAllowedFor($this->reqinfo, "save", $userdata->groups)) {
				throw new \Exception('your group authority is not allowed to do this action.');
			}

			$result = new \stdClass; 
			
			$key = new \stdClass;
			$obj = new \stdClass;
			foreach ($data as $fieldname => $value) {
				if ($fieldname=='_state') { continue; }
				if ($fieldname==$primarykey) {
					$key->{$fieldname} = $value;
				}
				$obj->{$fieldname} = $value;
			}

			// apabila ada tanggal, ubah ke format sql sbb:
			// $obj->tanggal = (\DateTime::createFromFormat('d/m/Y',$obj->tanggal))->format('Y-m-d');
			$obj->orderout_dtstart = (\DateTime::createFromFormat('d/m/Y',$obj->orderout_dtstart))->format('Y-m-d');
			$obj->orderout_dtend = (\DateTime::createFromFormat('d/m/Y',$obj->orderout_dtend))->format('Y-m-d');

			$obj->partnerbank_name = strtoupper($obj->partnerbank_name);
			$obj->partnerbank_bankacc = strtoupper($obj->partnerbank_bankacc);
			$obj->partnerbank_bankaccname = strtoupper($obj->partnerbank_bankaccname);
			$obj->partnerbank_bankname = strtoupper($obj->partnerbank_bankname);
			$obj->partnercontact_upname = strtoupper($obj->partnercontact_upname);
			$obj->partnercontact_position = strtoupper($obj->partnercontact_position);
			$obj->partnercontact_upphone = strtoupper($obj->partnercontact_upphone);
			$obj->partnercontact_email = strtoupper($obj->partnercontact_email);
			$obj->deliver_city = strtoupper($obj->deliver_city);
			$obj->deliver_upname = strtoupper($obj->deliver_upname);
			$obj->deliver_uptelp = strtoupper($obj->deliver_uptelp);
			$obj->doc_id = strtoupper($obj->doc_id);


			if ($obj->deliver_siteaddress=='') { $obj->deliver_siteaddress = '--NULL--'; }
			if ($obj->deliver_city=='') { $obj->deliver_city = '--NULL--'; }
			if ($obj->deliver_upname=='') { $obj->deliver_upname = '--NULL--'; }
			if ($obj->deliver_uptelp=='') { $obj->deliver_uptelp = '--NULL--'; }


			unset($obj->orderout_iscommit);
			unset($obj->orderout_commitby);
			unset($obj->orderout_commitdate);
			unset($obj->orderout_isapprovalprogress);
			unset($obj->orderout_isapproved);
			unset($obj->orderout_approveby);
			unset($obj->orderout_approvedate);
			unset($obj->orderout_isdeclined);
			unset($obj->orderout_declineby);
			unset($obj->orderout_declinedate);
			unset($obj->orderout_isclose);
			unset($obj->orderout_closeby);
			unset($obj->orderout_closedate);
			unset($obj->orderout_isautogenerated);



			$this->db->setAttribute(\PDO::ATTR_AUTOCOMMIT,0);
			$this->db->beginTransaction();

			try {

				$action = '';
				if ($datastate=='NEW') {
					$action = 'NEW';
					if ($autoid) {
						$obj->{$primarykey} = $this->NewId([]);
					}
					$obj->_createby = $userdata->username;
					$obj->_createdate = date("Y-m-d H:i:s");
					$cmd = \FGTA4\utils\SqlUtility::CreateSQLInsert($tablename, $obj);
				} else {
					$action = 'MODIFY';
					$obj->_modifyby = $userdata->username;
					$obj->_modifydate = date("Y-m-d H:i:s");				
					$cmd = \FGTA4\utils\SqlUtility::CreateSQLUpdate($tablename, $obj, $key);
				}
	
				$stmt = $this->db->prepare($cmd->sql);
				$stmt->execute($cmd->params);

				\FGTA4\utils\SqlUtility::WriteLog($this->db, $this->reqinfo->modulefullname, $tablename, $obj->{$primarykey}, $action, $userdata->username, (object)[]);




				// result
				$where = \FGTA4\utils\SqlUtility::BuildCriteria((object)[$primarykey=>$obj->{$primarykey}], [$primarykey=>"$primarykey=:$primarykey"]);
				$sql = \FGTA4\utils\SqlUtility::Select($tablename , [
					$primarykey
					, 'orderout_id', 'unit_id', 'request_id', 'orderout_isunref', 'inquirytype_id', 'trxmodel_id', 'request_dept_id', 'orderout_descr', 'orderout_dtstart', 'orderout_dtend', 'curr_id', 'curr_rate', 'ppn_taxtype_id', 'pph_taxtype_id', 'partner_id', 'ordercontract_id', 'orderout_quot', 'paymtype_id', 'partnerbank_id', 'partnerbank_name', 'partnerbank_bankacc', 'partnerbank_bankaccname', 'partnerbank_bankname', 'partnercontact_id', 'partnercontact_upname', 'partnercontact_position', 'partnercontact_upphone', 'partnercontact_email', 'project_id', 'projecttask_id', 'projbudget_id', 'projbudgettask_id', 'orderout_isunbudgetted', 'site_id', 'user_dept_id', 'recv_dept_id', 'deliver_siteaddress', 'deliver_city', 'deliver_upname', 'deliver_uptelp', 'inquiry_id', 'orderout_ismultirequest', 'inquirymodel_id', 'inquiryselect_id','inquiry_selectfield',  'itemmanage_id', 'owner_dept_id', 'orderout_dept_id', 'doc_id', 'orderout_version', 'orderout_isdateinterval', 'orderout_iscommit', 'orderout_commitby', 'orderout_commitdate', 'orderout_isapprovalprogress', 'orderout_isapproved', 'orderout_approveby', 'orderout_approvedate', 'orderout_isdeclined', 'orderout_declineby', 'orderout_declinedate', 'orderout_isclose', 'orderout_closeby', 'orderout_closedate', 'orderout_isadvance', 'orderout_isautogenerated', 'orderout_isitemdeptuser', 'orderout_isitemdeptowner', '_createby', '_createdate', '_modifyby', '_modifydate', '_createby', '_createdate', '_modifyby', '_modifydate'
				], $where->sql);
				$stmt = $this->db->prepare($sql);
				$stmt->execute($where->params);
				$row  = $stmt->fetch(\PDO::FETCH_ASSOC);			

				$record = [];
				foreach ($row as $key => $value) {
					$record[$key] = $value;
				}
				$result->dataresponse = (object) array_merge($record, [
					//  untuk lookup atau modify response ditaruh disini
				'unit_name' => \FGTA4\utils\SqlUtility::Lookup($record['unit_id'], $this->db, 'mst_unit', 'unit_id', 'unit_name'),
				'request_descr' => \FGTA4\utils\SqlUtility::Lookup($record['request_id'], $this->db, 'trn_request', 'request_id', 'request_descr'),
				'inquirytype_name' => \FGTA4\utils\SqlUtility::Lookup($record['inquirytype_id'], $this->db, 'mst_inquirytype', 'inquirytype_id', 'inquirytype_name'),
				'trxmodel_name' => \FGTA4\utils\SqlUtility::Lookup($record['trxmodel_id'], $this->db, 'mst_trxmodel', 'trxmodel_id', 'trxmodel_name'),
				'request_dept_name' => \FGTA4\utils\SqlUtility::Lookup($record['request_dept_id'], $this->db, 'mst_dept', 'dept_id', 'dept_name'),
				'orderout_dtstart' => date("d/m/Y", strtotime($row['orderout_dtstart'])),
				'orderout_dtend' => date("d/m/Y", strtotime($row['orderout_dtend'])),
				'curr_name' => \FGTA4\utils\SqlUtility::Lookup($record['curr_id'], $this->db, 'mst_curr', 'curr_id', 'curr_name'),
				'ppn_taxtype_name' => \FGTA4\utils\SqlUtility::Lookup($record['ppn_taxtype_id'], $this->db, 'mst_taxtype', 'taxtype_id', 'taxtype_name'),
				'pph_taxtype_name' => \FGTA4\utils\SqlUtility::Lookup($record['pph_taxtype_id'], $this->db, 'mst_taxtype', 'taxtype_id', 'taxtype_name'),
				'partner_name' => \FGTA4\utils\SqlUtility::Lookup($record['partner_id'], $this->db, 'mst_partner', 'partner_id', 'partner_name'),
				'ordercontract_descr' => \FGTA4\utils\SqlUtility::Lookup($record['ordercontract_id'], $this->db, 'trn_ordercontract', 'ordercontract_id', 'ordercontract_descr'),
				'paymtype_name' => \FGTA4\utils\SqlUtility::Lookup($record['paymtype_id'], $this->db, 'mst_paymtype', 'paymtype_id', 'paymtype_name'),
				'partnerbank_accnum' => \FGTA4\utils\SqlUtility::Lookup($record['partnerbank_id'], $this->db, 'mst_partnerbank', 'partnerbank_id', 'partnerbank_accnum'),
				'partnercontact_name' => \FGTA4\utils\SqlUtility::Lookup($record['partnercontact_id'], $this->db, 'mst_partnercontact', 'partnercontact_id', 'partnercontact_name'),
				'project_name' => \FGTA4\utils\SqlUtility::Lookup($record['project_id'], $this->db, 'mst_project', 'project_id', 'project_name'),
				'projbudget_name' => \FGTA4\utils\SqlUtility::Lookup($record['projbudget_id'], $this->db, 'mst_projbudget', 'projbudget_id', 'projbudget_name'),
				'projecttask_name' => \FGTA4\utils\SqlUtility::Lookup($record['projbudgettask_id'], $this->db, 'view_projbudgettask', 'projbudgettask_id', 'projbudgettask_name'),
				'site_name' => \FGTA4\utils\SqlUtility::Lookup($record['site_id'], $this->db, 'mst_site', 'site_id', 'site_name'),
				'user_dept_name' => \FGTA4\utils\SqlUtility::Lookup($record['user_dept_id'], $this->db, 'mst_dept', 'dept_id', 'dept_name'),
				'recv_dept_name' => \FGTA4\utils\SqlUtility::Lookup($record['recv_dept_id'], $this->db, 'mst_dept', 'dept_id', 'dept_name'),
				'inquiry_descr' => \FGTA4\utils\SqlUtility::Lookup($record['inquiry_id'], $this->db, 'trn_inquiry', 'inquiry_id', 'inquiry_descr'),
				'doc_name' => \FGTA4\utils\SqlUtility::Lookup($record['doc_id'], $this->db, 'mst_doc', 'doc_id', 'doc_name'),
				'orderout_commitby' => \FGTA4\utils\SqlUtility::Lookup($record['orderout_commitby'], $this->db, $GLOBALS['MAIN_USERTABLE'], 'user_id', 'user_fullname'),
				'orderout_approveby' => \FGTA4\utils\SqlUtility::Lookup($record['orderout_approveby'], $this->db, $GLOBALS['MAIN_USERTABLE'], 'user_id', 'user_fullname'),
				'orderout_declineby' => \FGTA4\utils\SqlUtility::Lookup($record['orderout_declineby'], $this->db, $GLOBALS['MAIN_USERTABLE'], 'user_id', 'user_fullname'),
				'orderout_closeby' => \FGTA4\utils\SqlUtility::Lookup($record['orderout_closeby'], $this->db, $GLOBALS['MAIN_USERTABLE'], 'user_id', 'user_fullname'),

					'_createby' => \FGTA4\utils\SqlUtility::Lookup($record['_createby'], $this->db, $GLOBALS['MAIN_USERTABLE'], 'user_id', 'user_fullname'),
					'_modifyby' => \FGTA4\utils\SqlUtility::Lookup($record['_modifyby'], $this->db, $GLOBALS['MAIN_USERTABLE'], 'user_id', 'user_fullname'),
				]);



				$this->db->commit();
				return $result;

			} catch (\Exception $ex) {
				$this->db->rollBack();
				throw $ex;
			} finally {
				$this->db->setAttribute(\PDO::ATTR_AUTOCOMMIT,1);
			}

		} catch (\Exception $ex) {
			throw $ex;
		}
	}

	public function NewId($param) {
		
			$seqname = 'PO';

			$dt = new \DateTime();	
			$ye = $dt->format("y");
			$mo = $dt->format("m");
			$seq = new Sequencer($this->db, 'seq_generalmonthly', $seqname, ['ye', 'mo']);
			$raw = $seq->getraw(['ye'=>$ye, 'mo'=> $mo]);
			$id = $seqname . $raw['ye'] . $raw['mo'] . str_pad($raw['lastnum'], 4, '0', STR_PAD_LEFT);
			return $id;		
			
	}

};