<?php require_once dirname(__FILE__).'/payment-list.phtml' ?>
<?php require_once dirname(__FILE__).'/payment-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/payment-detilgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/payment-detilform.phtml' ?>
<?php require_once dirname(__FILE__).'/payment-payment.phtml' ?>
<?php require_once dirname(__FILE__).'/payment-referencegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/payment-referenceform.phtml' ?>
<?php require_once dirname(__FILE__).'/payment-responsegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/payment-responseform.phtml' ?>



<div id="pnl_edit_record_custom" style="display: none">
	<div class="form_row">
		<div class="form_label_col">Commit By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Commit Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitdate"></span>
		</div>
	</div> 
</div>		
		
