<div id="pnl_upload">
	<div class="fgta-page-title">Upload Tagihan Keluar</div>

	<div>
	Untuk melakukan upload tagihan, gunakan template yang telah disediakan.<br> 
	Setelah diisi, silakan copy paste ke box paste di bawah.
	</div>

	<div id="pnl_upload-paste-box" class="pastebox" contenteditable placeholder="Paste template disini..." oninput="if(this.innerHTML.trim()==='<br>')this.innerHTML=''" ></div>



</div>