<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Recv</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_recv_id" class="easyui-textbox" mapping="recv_id"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Unit</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_unit_id" class="easyui-combo" style="width: 400px" mapping="unit_id" display="unit_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Order</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_orderout_id" class="easyui-combo" style="width: 400px" mapping="orderout_id" display="orderout_descr" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Order inquiry harus diisi'"   validType="requiredcombo['pnl_edit-cbo_orderout_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Reference</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_recv_ref" class="easyui-textbox" mapping="recv_ref"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_recv_descr" class="easyui-textbox" mapping="recv_descr"  maxlength="255" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Descr harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Date Receive</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_recv_date" class="easyui-datebox" style="width: 400px" mapping="recv_date" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Receive From</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partner_id" class="easyui-combo" style="width: 400px" mapping="partner_id" display="partner_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Receive At</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_site_id" class="easyui-combo" style="width: 400px" mapping="site_id" display="site_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Site harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_site_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Receive By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_empl_id" class="easyui-combo" style="width: 400px" mapping="empl_id" display="empl_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Receive By harus diisi'"   validType="requiredcombo['pnl_edit-cbo_empl_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Receiver Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_recv_dept_id" class="easyui-combo" style="width: 400px" mapping="recv_dept_id" display="recv_dept_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Departemen harus diisi', disabled: true"   validType="requiredcombo['pnl_edit-cbo_recv_dept_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>



		<?=$this->Section('Information', true, true)?>
		<div class="fgta_section_collapsible" style="display: none">


			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Model Trx</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_trxmodel_id" class="easyui-textbox" mapping="trxmodel_id"  maxlength="10" style="width: 400px" data-options="multiline: false , disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Inquiry Model</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_inquirymodel_id" class="easyui-textbox" mapping="inquirymodel_id"  maxlength="1" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Inquiry Model harus diisi', disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Inquiry Select</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_inquiryselect_id" class="easyui-textbox" mapping="inquiryselect_id"  maxlength="1" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Inquiry Select harus diisi', disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Item Manage As</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_itemmanage_id" class="easyui-textbox" mapping="itemmanage_id"  maxlength="2" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Item Manage Model harus diisi', disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Owner Dept</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_owner_dept_id" class="easyui-textbox" mapping="owner_dept_id"  maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Owner Dept harus diisi', disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>recvitem_totalvalue
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Request Dept</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_request_dept_id" class="easyui-textbox" mapping="request_dept_id"  maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Request Dept harus diisi', disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>


			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Orderout Dept</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_orderout_dept_id" class="easyui-textbox" mapping="orderout_dept_id"  maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Orderout Dept harus diisi', disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">User Dept</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_user_dept_id" class="easyui-textbox" mapping="user_dept_id"  maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Owner Dept harus diisi', disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Project</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_project_id" class="easyui-textbox" mapping="project_id"  maxlength="30" style="width: 400px" data-options="multiline: false , disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Project Task</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_projecttask_id" class="easyui-textbox" mapping="projecttask_id"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Budget</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_projbudget_id" class="easyui-textbox" mapping="projbudget_id"  maxlength="30" style="width: 400px" data-options="multiline: false , disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Budget Task</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_projbudgettask_id" class="easyui-textbox" mapping="projbudgettask_id"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>


			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">RevItem Total Value</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_recvitem_totalvalue" class="easyui-numberbox" mapping="recvitem_totalvalue" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Curr</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_curr_id" class="easyui-textbox" mapping="curr_id"  maxlength="10" style="width: 400px" data-options="multiline: false , disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Curr Rate</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_curr_rate" class="easyui-numberbox" mapping="curr_rate" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">RevItem Total IDR</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_recvitem_totalidr" class="easyui-numberbox" mapping="recvitem_totalidr" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">PPN Taxtype</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_ppn_taxtype_id" class="easyui-textbox" mapping="ppn_taxtype_id"  maxlength="10" style="width: 400px" data-options="multiline: false , disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">PPN Value</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_ppn_value" class="easyui-numberbox" mapping="ppn_value" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"></div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-chk_ppn_isinclude" class="easyui-checkbox c1" mapping="recv_iscommit" data-options="label: 'PPN isInclude', labelPosition: 'after', checked: false , disabled: true">
				</div>
			</div>


			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">PPH Taxtype</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_pph_taxtype_id" class="easyui-textbox" mapping="pph_taxtype_id"  maxlength="10" style="width: 400px" data-options="multiline: false , disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">PPH Value</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_pph_value" class="easyui-numberbox" mapping="pph_value" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , disabled: true">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"></div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-chk_pph_isinclude" class="easyui-checkbox c1" mapping="recv_iscommit" data-options="label: 'PPH isInclude', labelPosition: 'after', checked: false , disabled: true">
				</div>
			</div>




			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Recv Value Nett</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_recvitem_totalvaluenett" class="easyui-numberbox" mapping="recvitem_totalvaluenett" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , disabled: true">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Recv Value PPN</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_recvitem_totalvalueppn" class="easyui-numberbox" mapping="recvitem_totalvalueppn" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , disabled: true">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Recv Value PPH</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_recvitem_totalvaluepph" class="easyui-numberbox" mapping="recvitem_totalvaluepph" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , disabled: true">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Recv IDR Nett</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_recvitem_totalidrnett" class="easyui-numberbox" mapping="recvitem_totalidrnett" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , disabled: true">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Recv IDR PPN</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_recvitem_totalidrppn" class="easyui-numberbox" mapping="recvitem_totalidrppn" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , disabled: true">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Recv IDR PPH</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_recvitem_totalidrpph" class="easyui-numberbox" mapping="recvitem_totalidrpph" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , disabled: true">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>






			
			<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Doc Version</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_recv_version" class="easyui-numberbox" mapping="recv_version" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

		</div>




		<?=$this->Section('Status', true, true)?>
		<div class="fgta_section_collapsible" style="display: none">


			<div class="form_row" >
				<div class="form_label_col"></div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-chk_recv_iscommit" class="easyui-checkbox c1" mapping="recv_iscommit" data-options="label: 'Commit', labelPosition: 'after', checked: false , disabled: true">
				</div>
			</div>

			<div class="form_row" style="display: none">
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">CommitBy</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_recv_commitby" class="easyui-textbox" mapping="recv_commitby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" style="display: none">
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">CommitDate</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_recv_commitdate" class="easyui-textbox" mapping="recv_commitdate"   style="width: 400px" data-options="multiline: false , disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"></div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-chk_recv_isrecv" class="easyui-checkbox c1" mapping="recv_isrecv" data-options="label: 'Received', labelPosition: 'after', checked: false , disabled: true">
				</div>
			</div>

			<div class="form_row" style="display: none">
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ReceivedBy</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_recv_recvby" class="easyui-textbox" mapping="recv_recvby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" style="display: none">
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ReceivedDate</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_recv_recvdate" class="easyui-textbox" mapping="recv_recvdate"   style="width: 400px" data-options="multiline: false , disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" >
				<div class="form_label_col"></div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-chk_recv_ispost" class="easyui-checkbox c1" mapping="recv_ispost" data-options="label: 'Post', labelPosition: 'after', checked: false , disabled: true">
				</div>
			</div>

			<div class="form_row" style="display: none">
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">PostBy</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_recv_postby" class="easyui-textbox" mapping="recv_postby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

			<div class="form_row" style="display: none">
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">PostDate</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_recv_postdate" class="easyui-textbox" mapping="recv_postdate"   style="width: 400px" data-options="multiline: false , disabled: true ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

		</div>	

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col detilbox" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_edititemsgrid')">
					<div id="pnl_edit-txt_items_title" class="detilgrid-text">Items</div>
					<div id="pnl_edit-txt_items_value" class="detilgrid-value">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editregistergrid')">
					<div id="pnl_edit-txt_register_title" class="detilgrid-text">Registration</div>
					<div id="pnl_edit-txt_register_value" class="detilgrid-value">&nbsp;</div>
				</div>
				<!--//
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editmultiadd')">
					<div id="pnl_edit-txt_multiadd_title" class="detilgrid-text">Multi Add</div>
					<div id="pnl_edit-txt_multiadd_value" class="detilgrid-value">&nbsp;</div>
				</div>
				//-->
			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
			<a id="pnl_edit-btn_print" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'icon-print'">print</a>
			<a id="pnl_edit-btn_commit" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'fgta-icon-commit'">Commit</a>			
			<a id="pnl_edit-btn_uncommit" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'fgta-icon-uncommit'">UnCommit</a>
			<a id="pnl_edit-btn_post" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'fgta-icon-post'">Post</a>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

