-- SET FOREIGN_KEY_CHECKS=0;

-- drop table if exists `trn_inquiry`;
-- drop table if exists `trn_inquirydetil`;
-- drop table if exists `trn_inquiryfiles`;
-- drop table if exists `trn_inquiryappr`;


CREATE TABLE `trn_inquiry` (
	`inquiry_id` varchar(30) NOT NULL , 
	`inquirytype_id` varchar(14) NOT NULL , 
	`inquiry_descr` varchar(255)  , 
	`inquiry_dtstart` date NOT NULL , 
	`inquiry_dtend` date NOT NULL , 
	`user_dept_id` varchar(30) NOT NULL , 
	`empl_id` varchar(30)  , 
	`inquiry_isadvance` tinyint(1) NOT NULL DEFAULT 0, 
	`project_id` varchar(30) NOT NULL , 
	`projecttask_id` varchar(14)  , 
	`projbudget_id` varchar(30)  , 
	`projbudgettask_id` varchar(14)  , 
	`inquiry_isunbudgetted` tinyint(1) NOT NULL DEFAULT 0, 
	`site_id` varchar(30) NOT NULL , 
	`deliver_siteaddress` varchar(250)  , 
	`deliver_city` varchar(60)  , 
	`deliver_upname` varchar(60)  , 
	`deliver_uptelp` varchar(60)  , 
	`inquirymodel_id` varchar(1) NOT NULL , 
	`inquiryselect_id` varchar(1) NOT NULL , 
	`related_dept_id` varchar(30) NOT NULL , 
	`owner_dept_id` varchar(30) NOT NULL , 
	`request_doc_id` varchar(30) NOT NULL , 
	`orderout_dept_id` varchar(30) NOT NULL , 
	`orderout_doc_id` varchar(30) NOT NULL , 
	`trxmodel_id` varchar(30) NOT NULL , 
	`itemmanage_id` varchar(2) NOT NULL , 
	`inquiry_rejectnotes` varchar(255)  , 
	`doc_id` varchar(30) NOT NULL , 
	`inquiry_selectfield` varchar(6) NOT NULL DEFAULT 000000, 
	`inquiry_version` int(4) NOT NULL DEFAULT 0, 
	`inquiry_maxadvancevalue` decimal(12, 0) NOT NULL DEFAULT 0, 
	`inquiry_isallowadvance` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_isdateinterval` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_iscommit` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_commitby` varchar(14)  , 
	`inquiry_commitdate` datetime  , 
	`inquiry_isapprovalprogress` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_isapproved` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_approveby` varchar(14)  , 
	`inquiry_approvedate` datetime  , 
	`inquiry_isdeclined` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_declineby` varchar(14)  , 
	`inquiry_declinedate` datetime  , 
	`inquiry_ispreparing` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_isprepared` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_preparedby` varchar(14)  , 
	`inquiry_prepareddate` datetime  , 
	`inquiry_isreject` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_rejectby` varchar(14)  , 
	`inquiry_rejectdate` datetime  , 
	`inquiry_iscomplete` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_isclose` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_closeby` varchar(14)  , 
	`inquiry_closedate` datetime  , 
	`inquiry_isautogenerated` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_isitemdeptuser` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_isitemdeptowner` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_istoberequest` tinyint(1) NOT NULL DEFAULT 0, 
	`_createby` varchar(13) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(13)  , 
	`_modifydate` datetime  , 
	PRIMARY KEY (`inquiry_id`)
) 
ENGINE=InnoDB
COMMENT='Inquiry item';

ALTER TABLE `trn_inquiry` ADD KEY `inquirytype_id` (`inquirytype_id`);
ALTER TABLE `trn_inquiry` ADD KEY `user_dept_id` (`user_dept_id`);
ALTER TABLE `trn_inquiry` ADD KEY `empl_id` (`empl_id`);
ALTER TABLE `trn_inquiry` ADD KEY `project_id` (`project_id`);
ALTER TABLE `trn_inquiry` ADD KEY `projecttask_id` (`projecttask_id`);
ALTER TABLE `trn_inquiry` ADD KEY `projbudget_id` (`projbudget_id`);
ALTER TABLE `trn_inquiry` ADD KEY `projbudgettask_id` (`projbudgettask_id`);
ALTER TABLE `trn_inquiry` ADD KEY `site_id` (`site_id`);
ALTER TABLE `trn_inquiry` ADD KEY `inquirymodel_id` (`inquirymodel_id`);
ALTER TABLE `trn_inquiry` ADD KEY `inquiryselect_id` (`inquiryselect_id`);
ALTER TABLE `trn_inquiry` ADD KEY `related_dept_id` (`related_dept_id`);
ALTER TABLE `trn_inquiry` ADD KEY `owner_dept_id` (`owner_dept_id`);
ALTER TABLE `trn_inquiry` ADD KEY `request_doc_id` (`request_doc_id`);
ALTER TABLE `trn_inquiry` ADD KEY `orderout_dept_id` (`orderout_dept_id`);
ALTER TABLE `trn_inquiry` ADD KEY `orderout_doc_id` (`orderout_doc_id`);
ALTER TABLE `trn_inquiry` ADD KEY `trxmodel_id` (`trxmodel_id`);
ALTER TABLE `trn_inquiry` ADD KEY `itemmanage_id` (`itemmanage_id`);
ALTER TABLE `trn_inquiry` ADD KEY `doc_id` (`doc_id`);

ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_inquirytype` FOREIGN KEY (`inquirytype_id`) REFERENCES `mst_inquirytype` (`inquirytype_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_dept` FOREIGN KEY (`user_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_empl` FOREIGN KEY (`empl_id`) REFERENCES `mst_empl` (`empl_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_project` FOREIGN KEY (`project_id`) REFERENCES `mst_project` (`project_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_projecttask` FOREIGN KEY (`projecttask_id`) REFERENCES `mst_projecttask` (`projecttask_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_projbudget` FOREIGN KEY (`projbudget_id`) REFERENCES `mst_projbudget` (`projbudget_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_projbudgettask` FOREIGN KEY (`projbudgettask_id`) REFERENCES `mst_projbudgettask` (`projbudgettask_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_site` FOREIGN KEY (`site_id`) REFERENCES `mst_site` (`site_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_inquirymodel` FOREIGN KEY (`inquirymodel_id`) REFERENCES `mst_inquirymodel` (`inquirymodel_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_inquiryselect` FOREIGN KEY (`inquiryselect_id`) REFERENCES `mst_inquiryselect` (`inquiryselect_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_dept_2` FOREIGN KEY (`related_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_dept_3` FOREIGN KEY (`owner_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_doc` FOREIGN KEY (`request_doc_id`) REFERENCES `mst_doc` (`doc_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_dept_4` FOREIGN KEY (`orderout_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_doc_2` FOREIGN KEY (`orderout_doc_id`) REFERENCES `mst_doc` (`doc_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_trxmodel` FOREIGN KEY (`trxmodel_id`) REFERENCES `mst_trxmodel` (`trxmodel_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_itemmanage` FOREIGN KEY (`itemmanage_id`) REFERENCES `mst_itemmanage` (`itemmanage_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_doc_3` FOREIGN KEY (`doc_id`) REFERENCES `mst_doc` (`doc_id`);





CREATE TABLE `trn_inquirydetil` (
	`inquirydetil_id` varchar(14) NOT NULL , 
	`itemasset_id` varchar(14)  , 
	`item_id` varchar(14)  , 
	`itemstock_id` varchar(14)  , 
	`partner_id` varchar(30)  , 
	`itemclass_id` varchar(14) NOT NULL , 
	`inquirydetil_descr` varchar(255)  , 
	`inquirydetil_qty` int(4) NOT NULL DEFAULT 0, 
	`inquirydetil_days` int(4) NOT NULL DEFAULT 0, 
	`inquirydetil_task` int(4) NOT NULL DEFAULT 0, 
	`inquirydetil_estrate` decimal(12, 0) NOT NULL DEFAULT 0, 
	`inquirydetil_estvalue` int(14) NOT NULL DEFAULT 0, 
	`projbudgetdet_id` varchar(30)  , 
	`inquirydetil_isunbudget` tinyint(1) NOT NULL DEFAULT 0, 
	`inquirydetil_isallowoverbudget` tinyint(1) NOT NULL DEFAULT 0, 
	`inquirydetil_qtyavailable` int(4) NOT NULL DEFAULT 0, 
	`accbudget_id` varchar(20)  , 
	`coa_id` varchar(17)  , 
	`inquiry_id` varchar(14) NOT NULL , 
	`_createby` varchar(13) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(13)  , 
	`_modifydate` datetime  , 
	PRIMARY KEY (`inquirydetil_id`)
) 
ENGINE=InnoDB
COMMENT='Itemclass yang akan di-inquiry';

ALTER TABLE `trn_inquirydetil` ADD KEY `itemasset_id` (`itemasset_id`);
ALTER TABLE `trn_inquirydetil` ADD KEY `item_id` (`item_id`);
ALTER TABLE `trn_inquirydetil` ADD KEY `itemstock_id` (`itemstock_id`);
ALTER TABLE `trn_inquirydetil` ADD KEY `partner_id` (`partner_id`);
ALTER TABLE `trn_inquirydetil` ADD KEY `itemclass_id` (`itemclass_id`);
ALTER TABLE `trn_inquirydetil` ADD KEY `projbudgetdet_id` (`projbudgetdet_id`);
ALTER TABLE `trn_inquirydetil` ADD KEY `accbudget_id` (`accbudget_id`);
ALTER TABLE `trn_inquirydetil` ADD KEY `coa_id` (`coa_id`);
ALTER TABLE `trn_inquirydetil` ADD KEY `inquiry_id` (`inquiry_id`);

ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_mst_itemasset` FOREIGN KEY (`itemasset_id`) REFERENCES `mst_itemasset` (`itemasset_id`);
ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_mst_item` FOREIGN KEY (`item_id`) REFERENCES `mst_item` (`item_id`);
ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_mst_itemstock` FOREIGN KEY (`itemstock_id`) REFERENCES `mst_itemstock` (`itemstock_id`);
ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_mst_partner` FOREIGN KEY (`partner_id`) REFERENCES `mst_partner` (`partner_id`);
ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_mst_itemclass` FOREIGN KEY (`itemclass_id`) REFERENCES `mst_itemclass` (`itemclass_id`);
ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_mst_projbudgetdet` FOREIGN KEY (`projbudgetdet_id`) REFERENCES `mst_projbudgetdet` (`projbudgetdet_id`);
ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_mst_accbudget` FOREIGN KEY (`accbudget_id`) REFERENCES `mst_accbudget` (`accbudget_id`);
ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_mst_coa` FOREIGN KEY (`coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_trn_inquiry` FOREIGN KEY (`inquiry_id`) REFERENCES `trn_inquiry` (`inquiry_id`);





CREATE TABLE `trn_inquiryfiles` (
	`inquiryfiles_id` varchar(14) NOT NULL , 
	`doctype_id` varchar(10) NOT NULL , 
	`inquiryfiles_descr` varchar(90) NOT NULL , 
	`inquiryfiles_order` int(4) NOT NULL DEFAULT 0, 
	`inquiryfiles_file` varchar(90)  , 
	`inquiry_id` varchar(14) NOT NULL , 
	`_createby` varchar(13) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(13)  , 
	`_modifydate` datetime  , 
	UNIQUE KEY `inquiryfiles_doc` (`inquiry_id`, `doctype_id`),
	PRIMARY KEY (`inquiryfiles_id`)
) 
ENGINE=InnoDB
COMMENT='Daftar FIle Inquiry';

ALTER TABLE `trn_inquiryfiles` ADD KEY `doctype_id` (`doctype_id`);
ALTER TABLE `trn_inquiryfiles` ADD KEY `inquiry_id` (`inquiry_id`);

ALTER TABLE `trn_inquiryfiles` ADD CONSTRAINT `fk_trn_inquiryfiles_mst_doctype` FOREIGN KEY (`doctype_id`) REFERENCES `mst_doctype` (`doctype_id`);
ALTER TABLE `trn_inquiryfiles` ADD CONSTRAINT `fk_trn_inquiryfiles_trn_inquiry` FOREIGN KEY (`inquiry_id`) REFERENCES `trn_inquiry` (`inquiry_id`);





CREATE TABLE `trn_inquiryappr` (
	`inquiryappr_id` varchar(14) NOT NULL , 
	`inquiryappr_isapproved` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiryappr_by` varchar(14)  , 
	`inquiryappr_date` datetime  , 
	`inquiry_version` int(4) NOT NULL DEFAULT 0, 
	`inquiryappr_isdeclined` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiryappr_declinedby` varchar(14)  , 
	`inquiryappr_declineddate` datetime  , 
	`inquiryappr_notes` varchar(255)  , 
	`inquiry_id` varchar(30) NOT NULL , 
	`docauth_descr` varchar(90)  , 
	`docauth_order` int(4) NOT NULL DEFAULT 0, 
	`docauth_value` int(4) NOT NULL DEFAULT 100, 
	`docauth_min` int(4) NOT NULL DEFAULT 0, 
	`authlevel_id` varchar(10) NOT NULL , 
	`authlevel_name` varchar(60) NOT NULL , 
	`auth_id` varchar(10)  , 
	`auth_name` varchar(60) NOT NULL , 
	`_createby` varchar(13) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(13)  , 
	`_modifydate` datetime  , 
	UNIQUE KEY `inquiry_auth_id` (`inquiry_id`, `auth_id`),
	PRIMARY KEY (`inquiryappr_id`)
) 
ENGINE=InnoDB
COMMENT='Approval undefined';

ALTER TABLE `trn_inquiryappr` ADD KEY `inquiry_id` (`inquiry_id`);

ALTER TABLE `trn_inquiryappr` ADD CONSTRAINT `fk_trn_inquiryappr_trn_inquiry` FOREIGN KEY (`inquiry_id`) REFERENCES `trn_inquiry` (`inquiry_id`);





