<?php require_once dirname(__FILE__).'/ofrecv-list.phtml' ?>
<?php require_once dirname(__FILE__).'/ofrecv-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/ofrecv-detilgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/ofrecv-detilform.phtml' ?>
<?php require_once dirname(__FILE__).'/ofrecv-recvgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/ofrecv-recvform.phtml' ?>
<?php require_once dirname(__FILE__).'/ofrecv-referencegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/ofrecv-referenceform.phtml' ?>
<?php require_once dirname(__FILE__).'/ofrecv-responsegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/ofrecv-responseform.phtml' ?>



<div id="pnl_edit_record_custom" style="display: none">
	<div class="form_row">
		<div class="form_label_col">Commit By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Commit Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitdate"></span>
		</div>
	</div> 
</div>		
		
