<tfoot>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-foot rowcheck" style="width: 30px; text-align: center">&nbsp;</td>
		<td class="fgtable-foot desktop-only" style="width: 100px;">&nbsp;</td>
		<td class="fgtable-foot mobile-only">TOTAL</td>
		<td class="fgtable-foot desktop-only">TOTAL</td>
		<td class="fgtable-foot detil_totalvalue" style="width: 100px; text-align: right;"></td>
	</tr>	
</tfoot>