<div class="form_row pnl_editdetilform_row">
	<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">&nbsp;</div>
	<div class="form_input_col" style="border: 0px solid black">
		<a id="pnl_editdetilform-btn_link_payable" class="easyui-linkbutton" href="javascript:void(0)">Link From Payable</a>
		<a id="pnl_editdetilform-btn_link_receivable" class="easyui-linkbutton" href="javascript:void(0)">Link From Receivable</a>
	</div>
</div>
