<div class="status-row" style="font-weight: 900">
Status
</div>
<div class="status-row">
	<div class="status-button unbalance">ub</div> <b>UnBalance</b>
</div>	
<div class="status-row">
	<div class="status-button emptyrows">er</div> <b>Empty Rows</b>
</div>
<div class="status-row">
	<div class="status-button commit">c</div> <b>Commit</b>
</div>
<div class="status-row">
	<div class="status-button posted">P</div> <b>Posted</b>
</div>

<div class="status-row">
	<div class="status-button linked">L</div> <b>Linked</b>
</div>

<div class="status-row">
	<div class="status-button responded">R</div> <b>Responded</b>
</div>

<div class="status-row">
	<div class="status-button closed">x</div> <b>Closed</b>
</div>
