<?php require_once dirname(__FILE__).'/itemasset-list.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-specgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-specform.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-filesgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-filesform.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-depregrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-depreform.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-bookinggrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-bookingform.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-movinggrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-movingform.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-maintenancegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-maintenanceform.phtml' ?>



