<?php require_once dirname(__FILE__).'/budgetdeptrev-list.phtml' ?>
<?php require_once dirname(__FILE__).'/budgetdeptrev-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/budgetdeptrev-itemsgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/budgetdeptrev-itemsform.phtml' ?>



<?php
$customrecordstatus = __DIR__.'/budgetdeptrev-customrecordstatus.phtml'; 
if (is_file($customrecordstatus)) {
	include $customrecordstatus;
} else { ?>

<div id="pnl_edit_record_custom" style="display: none">
	<div class="form_row">
		<div class="form_label_col">Commit By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Commit Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitdate"></span>
		</div>
	</div> 
</div>		
		
<?php } ?>
