<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Properties Type</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row txt_itemproptype_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemproptype_id" class="easyui-textbox" mapping="itemproptype_id" uppercase="true" maxlength="20" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'ID harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_itemproptype_name" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Nama</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemproptype_name" class="easyui-textbox" mapping="itemproptype_name"  maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Nama Tipe Properti harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_itemproptype_group" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Group</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemproptype_group" class="easyui-textbox" mapping="itemproptype_group"  maxlength="20" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_itemproptype_descr" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemproptype_descr" class="easyui-textbox" mapping="itemproptype_descr"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_itemproptype_order" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Order</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemproptype_order" class="easyui-numberbox" mapping="itemproptype_order" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemproptype_isitem" >
			<div class="form_label_col">Available at</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemproptype_isitem" class="easyui-checkbox c1" mapping="itemproptype_isitem" data-options="label: 'Item', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemproptype_isitemstock" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemproptype_isitemstock" class="easyui-checkbox c1" mapping="itemproptype_isitemstock" data-options="label: 'Item Stock', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemproptype_isitemasset" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemproptype_isitemasset" class="easyui-checkbox c1" mapping="itemproptype_isitemasset" data-options="label: 'Item Asset', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemproptype_ispropitemdisabled" >
			<div class="form_label_col">Editor</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemproptype_ispropitemdisabled" class="easyui-checkbox c1" mapping="itemproptype_ispropitemdisabled" data-options="label: 'Disabled in Item', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemproptype_ispropitemstockdisabled" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemproptype_ispropitemstockdisabled" class="easyui-checkbox c1" mapping="itemproptype_ispropitemstockdisabled" data-options="label: 'Disabled in Stock', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemproptype_ispropitemassetdisabled" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemproptype_ispropitemassetdisabled" class="easyui-checkbox c1" mapping="itemproptype_ispropitemassetdisabled" data-options="label: 'Disabled in Asset', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
			
			
			
			
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

