<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
	<div class="list-search-item" style="width: 50px;">Cari</div>

	<div class="list-search-item" style="width: 120px; margin-right: 3px">
		<input id="pnl_list-cbo_search_dept" class="easyui-combo" style="width: 100%">
	</div>

	<div class="list-search-item" style="width: 120px; margin-right: 3px">
		<input id="pnl_list-cbo_search_itemgroup" class="easyui-combo" style="width: 100%">
	</div>

	<div class="list-search-item">
		<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
	</div>
	<div class="list-search-item" style="width: 45px">
		<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
	</div>
</div>