<div id="pnl_editmovinggrid">
	<div class="fgta-page-title">Daftar Moving</div>
	<div id="pnl_editmovinggrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_editmovinggrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_editmovinggrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_editmovinggrid-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_editmovinggrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<?php
				$customview = __DIR__.'/itemstock-movinggrid-customview.phtml'; 
				if (is_file($customview)) {
					include $customview;
				} else { ?>
				<tr>
<th type="check">chk</th>					
					<th mapping="itemstockmoving_id">itemstockmoving_id</th>
					<th mapping="periodemo_id">periodemo_id</th>
					<th mapping="unit_id">unit_id</th>
					<th mapping="itemmvmodel_id">itemmvmodel_id</th>
					<th mapping="itemstockmoving_date">itemstockmoving_date</th>
					<th mapping="site_id">site_id</th>
					<th mapping="dept_id">dept_id</th>
					<th mapping="brand_id">brand_id</th>
					<th mapping="unitmeasurement_id">unitmeasurement_id</th>
					<th mapping="itemstockmoving_qty" style="text-align: right" formatter="row_format_number">itemstockmoving_qty</th>
					<th mapping="itemstockmoving_value" style="text-align: right" formatter="row_format_number">itemstockmoving_value</th>

					<th mapping=""></th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
<td class="fgtable-head" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Periode</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Unit</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Model</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Last Recv Date</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Site</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Dept</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Brand</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Unit Measurement</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Qty</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Value</td>

					<td class="fgtable-head" style="border-bottom: 1px solid #000000; text-align: center">&nbsp;</td>
				</tr>
				<?php } ?>
			</thead>
		</table>
	</div>



	<div class="pnl_editmovinggrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_editmovinggrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_editmovinggrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>


</div>	
