<div id="pnl_editmovingform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Moving</div>
		<a id="pnl_editmovingform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editmovingform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editmovingform-form">

		<div class="form_row pnl_editmovingform_row txt_itemstockmoving_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmovingform-txt_itemstockmoving_id" class="easyui-textbox" mapping="itemstockmoving_id"  maxlength="15"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editmovingform_row txt_periodemo_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Periode</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmovingform-txt_periodemo_id" class="easyui-textbox" mapping="periodemo_id"  maxlength="6"  style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editmovingform_row txt_unit_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Unit</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmovingform-txt_unit_id" class="easyui-textbox" mapping="unit_id"  maxlength="30"  style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editmovingform_row txt_itemmvmodel_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Model</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmovingform-txt_itemmvmodel_id" class="easyui-textbox" mapping="itemmvmodel_id"  maxlength="10"  style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editmovingform_row txt_itemstockmoving_date" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Last Recv Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmovingform-txt_itemstockmoving_date" class="easyui-textbox" mapping="itemstockmoving_date"   style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editmovingform_row txt_site_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Site</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmovingform-txt_site_id" class="easyui-textbox" mapping="site_id"  maxlength="30"  style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editmovingform_row txt_dept_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmovingform-txt_dept_id" class="easyui-textbox" mapping="dept_id"  maxlength="30"  style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editmovingform_row txt_brand_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Brand</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmovingform-txt_brand_id" class="easyui-textbox" mapping="brand_id"  maxlength="14"  style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editmovingform_row txt_unitmeasurement_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Unit Measurement</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmovingform-txt_unitmeasurement_id" class="easyui-textbox" mapping="unitmeasurement_id"  maxlength="10"  style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editmovingform_row txt_itemstock_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ItemStock ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmovingform-txt_itemstock_id" class="easyui-textbox" mapping="itemstock_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editmovingform_row txt_itemstockmoving_qty" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Qty</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmovingform-txt_itemstockmoving_qty" class="easyui-numberbox" mapping="itemstockmoving_qty" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editmovingform_row txt_itemstockmoving_value" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Value</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editmovingform-txt_itemstockmoving_value" class="easyui-numberbox" mapping="itemstockmoving_value" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editmovingform-autoadd" type="checkbox"><label for="pnl_editmovingform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editmovingform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editmovingform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editmovingform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editmovingform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editmovingform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
