<div id="pnl_editcompoundform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editcompoundform-caption">{{STATE_BEG}}Compound{{STATE_END}}</div>
		<a id="pnl_editcompoundform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editcompoundform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editcompoundform-form">

		<div class="form_row pnl_editcompoundform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcompoundform-txt_itemstockcompound_id" class="easyui-textbox" mapping="itemstockcompound_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editcompoundform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Item</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcompoundform-cbo_itemstock_compound" class="easyui-combo" style="width: 400px" mapping="itemstock_compound" display="itemstock_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editcompoundform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Value</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcompoundform-txt_itemstockcompound_value" class="easyui-numberbox" mapping="itemstockcompound_value" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editcompoundform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Unit of Measurement</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcompoundform-cbo_unitmeasurement_id" class="easyui-combo" style="width: 400px" mapping="unitmeasurement_id" display="unitmeasurement_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editcompoundform_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcompoundform-chk_itemstock_ismode1" class="easyui-checkbox c1" mapping="itemstock_ismode1" data-options="label: 'Mode 1', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_editcompoundform_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcompoundform-chk_itemstock_ismode2" class="easyui-checkbox c1" mapping="itemstock_ismode2" data-options="label: 'Mode 2', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_editcompoundform_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcompoundform-chk_itemstock_ismode3" class="easyui-checkbox c1" mapping="itemstock_ismode3" data-options="label: 'Mode 3', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_editcompoundform_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcompoundform-chk_itemstock_ismode4" class="easyui-checkbox c1" mapping="itemstock_ismode4" data-options="label: 'Mode 4', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_editcompoundform_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcompoundform-chk_itemstock_ismode5" class="easyui-checkbox c1" mapping="itemstock_ismode5" data-options="label: 'Mode 5', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_editcompoundform_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcompoundform-chk_itemstock_ismode6" class="easyui-checkbox c1" mapping="itemstock_ismode6" data-options="label: 'Mode 6', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_editcompoundform_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcompoundform-chk_itemstock_ismode7" class="easyui-checkbox c1" mapping="itemstock_ismode7" data-options="label: 'Mode 7', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_editcompoundform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ItemStock ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcompoundform-txt_itemstock_id" class="easyui-textbox" mapping="itemstock_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editcompoundform-autoadd" type="checkbox"><label for="pnl_editcompoundform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editcompoundform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/itemstock-compoundform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_editcompoundform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_editcompoundform-buttonbar-left">
			<a id="pnl_editcompoundform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editcompoundform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_editcompoundform-buttonbar-middle">
			<a id="pnl_editcompoundform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_editcompoundform-buttonbar-right">
			<a id="pnl_editcompoundform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
