<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_edit-caption">{{STATE_BEG}}Item Stock{{STATE_END}}</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_id" class="easyui-textbox" mapping="itemstock_id"  maxlength="14" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'ID harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Group</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_itemgroup_id" class="easyui-combo" style="width: 400px" mapping="itemgroup_id" display="itemgroup_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Uniq Code</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_code" class="easyui-textbox" mapping="itemstock_code"  maxlength="150" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Code Uniq (bydept) harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Nama Item</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_name" class="easyui-textbox" mapping="itemstock_name"  maxlength="150" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Nama item harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Nama Pendek</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_nameshort" class="easyui-textbox" mapping="itemstock_nameshort"  maxlength="150" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Nama item harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_descr" class="easyui-textbox" mapping="itemstock_descr"  maxlength="2500" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">CouchDb.Id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_couchdbid" class="easyui-textbox" mapping="itemstock_couchdbid"  maxlength="255" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>


		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Picture</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-fl_itemstock_picture" class="easyui-filebox" mapping="itemstock_picture" style="width: 400px" data-options="multiline: false , accept: 'image/*' ">
				<div style="display: flex;">
					<a class="filedownloadlink" id="pnl_edit-fl_itemstock_picture_link" style="cursor:pointer; margin-right: 10px; display: none">Download File</a>	
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
				<img id="pnl_edit-fl_itemstock_picture_img" style="width: 200px; width: 200px; border: 1px solid: #ccc; display:none">				
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Unit of Measurement</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_unitmeasurement_id" class="easyui-combo" style="width: 400px" mapping="unitmeasurement_id" display="unitmeasurement_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Owner Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_dept_id" class="easyui-combo" style="width: 400px" mapping="dept_id" display="dept_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Dept harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_dept_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;">Owner Dept yang akan manage item ini</div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Class</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_itemclass_id" class="easyui-combo" style="width: 400px" mapping="itemclass_id" display="itemclass_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Class harus diisi'"   validType="requiredcombo['pnl_edit-cbo_itemclass_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Unit</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_unit_id" class="easyui-combo" style="width: 400px" mapping="unit_id" display="unit_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Unit harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_unit_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemstock_isdisabled" class="easyui-checkbox c1" mapping="itemstock_isdisabled" data-options="label: 'Disabled', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemstock_ishascompound" class="easyui-checkbox c1" mapping="itemstock_ishascompound" data-options="label: 'Has Compound', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemstock_issellable" class="easyui-checkbox c1" mapping="itemstock_issellable" data-options="label: 'Sellable', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<?=$this->SectionBegin('Basic Pricing & Values', true, true, '')?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Original Price</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_priceori" class="easyui-numberbox" mapping="itemstock_priceori" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Adjustment</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_priceadj" class="easyui-numberbox" mapping="itemstock_priceadj" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Adjustment Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_priceadjdate" class="easyui-textbox" mapping="itemstock_priceadjdate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Gross Price</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_grossprice" class="easyui-numberbox" mapping="itemstock_grossprice" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemstock_isdiscvalue" class="easyui-checkbox c1" mapping="itemstock_isdiscvalue" data-options="label: 'Discount Using Value', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Disc (%)</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_disc" class="easyui-numberbox" mapping="itemstock_disc" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Disc Value</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_discval" class="easyui-numberbox" mapping="itemstock_discval" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Sell Price</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_sellprice" class="easyui-numberbox" mapping="itemstock_sellprice" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Estimated Cost</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_estcost" class="easyui-numberbox" mapping="itemstock_estcost" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		</div>			
		<?=$this->SectionEnd('')?>
					
		<?=$this->SectionBegin('Weight & Dimension', true, true, '')?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Weight (Kg)</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_weight" class="easyui-numberbox" mapping="itemstock_weight" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Length (cm)</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_length" class="easyui-numberbox" mapping="itemstock_length" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Width (cm)</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_width" class="easyui-numberbox" mapping="itemstock_width" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Height (cm)</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_height" class="easyui-numberbox" mapping="itemstock_height" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		</div>			
		<?=$this->SectionEnd('')?>
					
		<?=$this->SectionBegin('Inventory', true, true, '')?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">LastQty</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_lastqty" class="easyui-numberbox" mapping="itemstock_lastqty" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">LastValue</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_lastvalue" class="easyui-numberbox" mapping="itemstock_lastvalue" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Last Qty UpDate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_lastqtyupdate" class="easyui-textbox" mapping="itemstock_lastqtyupdate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemstock_isupdating" class="easyui-checkbox c1" mapping="itemstock_isupdating" data-options="label: 'Updating', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Last Batch Update</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_updatebatch" class="easyui-textbox" mapping="itemstock_updatebatch"  maxlength="30" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		</div>			
		<?=$this->SectionEnd('')?>
					
		<?=$this->SectionBegin('Last Receiving', true, true, '')?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Last Recv Id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_lastrecvid" class="easyui-textbox" mapping="itemstock_lastrecvid"  maxlength="90" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Last Recv Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_lastrecvdate" class="easyui-textbox" mapping="itemstock_lastrecvdate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Last Recv Qty</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_lastrecvqty" class="easyui-numberbox" mapping="itemstock_lastrecvqty" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Last Cost</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_lastcost" class="easyui-numberbox" mapping="itemstock_lastcost" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Last Cost Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_lastcostdate" class="easyui-textbox" mapping="itemstock_lastcostdate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		</div>			
		<?=$this->SectionEnd('')?>
					
		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Ref</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_ref" class="easyui-textbox" mapping="itemstock_ref"  maxlength="90" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">RefName</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_refname" class="easyui-textbox" mapping="itemstock_refname"  maxlength="200" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">UploadBatch</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemstock_uploadbatchcode" class="easyui-textbox" mapping="itemstock_uploadbatchcode"  maxlength="32" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col detilbox" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editbarcodegrid')">
					<div id="pnl_edit-txt_barcode_title" class="detilgrid-text">Barcode</div>
					<div id="pnl_edit-txt_barcode_value" class="detilgrid-value barcode_totalvalue">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editpropgrid')">
					<div id="pnl_edit-txt_prop_title" class="detilgrid-text">Properties</div>
					<div id="pnl_edit-txt_prop_value" class="detilgrid-value prop_totalvalue">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editpositiongrid')">
					<div id="pnl_edit-txt_position_title" class="detilgrid-text">Stock Position</div>
					<div id="pnl_edit-txt_position_value" class="detilgrid-value position_totalvalue">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editcompoundgrid')">
					<div id="pnl_edit-txt_compound_title" class="detilgrid-text">Compound</div>
					<div id="pnl_edit-txt_compound_value" class="detilgrid-value compound_totalvalue">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editconversiongrid')">
					<div id="pnl_edit-txt_conversion_title" class="detilgrid-text">Conversion</div>
					<div id="pnl_edit-txt_conversion_value" class="detilgrid-value conversion_totalvalue">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editpicturegrid')">
					<div id="pnl_edit-txt_picture_title" class="detilgrid-text">Picture</div>
					<div id="pnl_edit-txt_picture_value" class="detilgrid-value picture_totalvalue">&nbsp;</div>
				</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol-tombol xtion disini -->
			<?php
			$customheaderxtion = __DIR__.'/itemstock-edit-customxtion.phtml'; 
			if (is_file($customheaderxtion)) {
				include $customheaderxtion;
			} else { ?>
			
			
			
			
			<?php } ?>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5 fgta-button-delete" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

