<div id="pnl_editpositionform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editpositionform-caption">{{STATE_BEG}}Stock Position{{STATE_END}}</div>
		<a id="pnl_editpositionform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editpositionform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editpositionform-form">

		<div class="form_row pnl_editpositionform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpositionform-txt_itemstockposition_id" class="easyui-textbox" mapping="itemstockposition_id"  maxlength="15"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpositionform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Saldo Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpositionform-txt_itemstockposition_date" class="easyui-textbox" mapping="itemstockposition_date"   style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpositionform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Unit</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpositionform-txt_unit_id" class="easyui-textbox" mapping="unit_id"  maxlength="30"  style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpositionform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Site</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpositionform-txt_site_id" class="easyui-textbox" mapping="site_id"  maxlength="30"  style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpositionform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpositionform-txt_dept_id" class="easyui-textbox" mapping="dept_id"  maxlength="30"  style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpositionform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Brand</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpositionform-txt_brand_id" class="easyui-textbox" mapping="brand_id"  maxlength="14"  style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpositionform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Unit Measurement</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpositionform-txt_unitmeasurement_id" class="easyui-textbox" mapping="unitmeasurement_id"  maxlength="10"  style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpositionform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Qty</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpositionform-txt_itemstocksaldo_qty" class="easyui-numberbox" mapping="itemstocksaldo_qty" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpositionform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Value</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpositionform-txt_itemstocksaldo_value" class="easyui-numberbox" mapping="itemstocksaldo_value" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpositionform_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpositionform-chk_itemstockposition_isupdating" class="easyui-checkbox c1" mapping="itemstockposition_isupdating" data-options="label: 'Updating', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_editpositionform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Last Batch Update</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpositionform-txt_itemstockposition_updatebatch" class="easyui-textbox" mapping="itemstockposition_updatebatch"  maxlength="30"  style="width: 400px" data-options="multiline:false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editpositionform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ItemStock ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editpositionform-txt_itemstock_id" class="easyui-textbox" mapping="itemstock_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editpositionform-autoadd" type="checkbox"><label for="pnl_editpositionform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editpositionform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/itemstock-positionform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_editpositionform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_editpositionform-buttonbar-left">
			<a id="pnl_editpositionform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editpositionform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_editpositionform-buttonbar-middle">
			<a id="pnl_editpositionform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_editpositionform-buttonbar-right">
			<a id="pnl_editpositionform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
