<?php require_once dirname(__FILE__).'/itemstock-list.phtml' ?>
<?php require_once dirname(__FILE__).'/itemstock-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/itemstock-barcodegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemstock-barcodeform.phtml' ?>
<?php require_once dirname(__FILE__).'/itemstock-propgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemstock-propform.phtml' ?>
<?php require_once dirname(__FILE__).'/itemstock-positiongrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemstock-positionform.phtml' ?>
<?php require_once dirname(__FILE__).'/itemstock-compoundgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemstock-compoundform.phtml' ?>
<?php require_once dirname(__FILE__).'/itemstock-conversiongrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemstock-conversionform.phtml' ?>
<?php require_once dirname(__FILE__).'/itemstock-picturegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemstock-pictureform.phtml' ?>



<?php
$customrecordstatus = __DIR__.'/itemstock-customrecordstatus.phtml'; 
if (is_file($customrecordstatus)) {
	include $customrecordstatus;
} else { ?>

<?php } ?>
