<thead>
	<tr>
		<th type="check">chk</th>
		<th mapping="coa_name" class="desktop-only">coa_name</th>
		<th mapping="jurnaldetil_descr-mobile" class="mobile-only">jurnal_descr-mobile</th>
		<th mapping="jurnaldetil_descr" class="desktop-only">jurnaldetil_descr</th>
		<th mapping="jurnaldetil_validr" style="text-align: right" formatter="row_format_number">jurnaldetil_validr</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head rowcheck" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
		<td class="fgtable-head desktop-only" style="width: 100px; border-bottom: 1px solid #000000">Account</td>
		<td class="fgtable-head mobile-only" style="border-bottom: 1px solid #000000">Descr</td>
		<td class="fgtable-head desktop-only" style="border-bottom: 1px solid #000000">Descr</td>
		<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">IDR</td>
	</tr>
</thead>