
<thead>
	<tr>
		<th mapping="jurnal_descr-mobile" class="mobile-only">jurnal_descr-mobile</th>
		<th mapping="jurnal_id" class="desktop-only">jurnal_id</th>
		<th mapping="jurnal_status-desktop" class="desktop-only">jurnal-status-desktop</th>
		<th mapping="jurnal_descr" class="desktop-only grd-lst-desc">jurnal_descr</th>
		<th mapping="periodemo_name" class="desktop-only">periodemo_name</th>
		<th mapping="jurnal_date" class="desktop-only">jurnal_date</th>
		<th mapping="jurnal_validr" style="text-align: right"  formatter="row_format_number">jurnal_validr</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head mobile-only" style="border-bottom: 1px solid #000000">Descr</td>
		<td class="fgtable-head desktop-only" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head desktop-only" style="width: 92px; border-bottom: 1px solid #000000; text-align: center">Status</td>
		<td class="fgtable-head desktop-only" style="border-bottom: 1px solid #000000">Descr</td>
		<td class="fgtable-head desktop-only" style="width: 100px; border-bottom: 1px solid #000000">Periode</td>
		<td class="fgtable-head desktop-only" style="width: 100px; border-bottom: 1px solid #000000">Date</td>
		<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">IDR</td>
	</tr>
</thead>