<div id="pnl_editdetilform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
	<div id="pnl_editdetilform-buttonbar-left">
		<a id="pnl_editdetilform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
		<a id="pnl_editdetilform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
	</div>

	<div id="pnl_editdetilform-buttonbar-middle">
		<a id="pnl_editdetilform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		<a id="pnl_editdetilform-btn_link" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px;">Link</a>
		<a id="pnl_editdetilform-btn_unlink" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px;">UnLink</a>
	</div>

	<div id="pnl_editdetilform-buttonbar-right">
		<a id="pnl_editdetilform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
	</div>
</div>