<tr>
	<th type="check">chk</th>					
	<th mapping="partner_name">partner_name</th>
	<th mapping="jurnaldetil_descr">jurnaldetil_descr</th>
	<th mapping="jurnaldetil_validr" style="text-align: right" formatter="row_format_number">jurnaldetil_validr</th>
	<th mapping="coa_name">coa_name</th>
	<th mapping="dept_name">dept_name</th>
</tr>
<tr style="background-color: #cccccc; height: 30px">
	<td class="fgtable-head" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
	<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Partner</td>
	<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Descr</td>
	<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">IDR</td>
	<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Account</td>
	<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Dept</td>
</tr>