<tr>
	<th mapping="jurnal_id">jurnal_id</th>
	<th mapping="periodemo_name">periodemo_name</th>
	<th mapping="jurnal_date">jurnal_date</th>
	<th mapping="jurnal_descr">jurnal_descr</th>
	<th mapping="jurnal_validr" style="text-align: right"  formatter="row_format_number">jurnal_validr</th>

</tr>
<tr style="background-color: #cccccc; height: 30px">
	<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
	<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Periode</td>
	<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date</td>
	<td class="fgtable-head" style="border-bottom: 1px solid #000000">Descr</td>
	<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">IDR</td>
</tr>