<?php require_once dirname(__FILE__).'/coareport-list.phtml' ?>
<?php require_once dirname(__FILE__).'/coareport-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/coareport-columngrid.phtml' ?>
<?php require_once dirname(__FILE__).'/coareport-columnform.phtml' ?>



<?php
$customrecordstatus = __DIR__.'/coareport-customrecordstatus.phtml'; 
if (is_file($customrecordstatus)) {
	include $customrecordstatus;
} else { ?>

<?php } ?>
