<thead>
	<tr>
		<th mapping="inquirymodel_id">inquirymodel_id</th>
		<th mapping="inquirymodel_name">inquirymodel_name</th>
		<th mapping="inquirymodel_isqtybreakdown" type="checkbox">inquirymodel_isqtybreakdown</th>
		<th mapping="inquirymodel_isdateinterval" type="checkbox">inquirymodel_isdateinterval</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Model</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Quantity Breakdown</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Date Interval</td>
	</tr>
</thead>