<?php require_once dirname(__FILE__).'/inquiry-list.phtml' ?>
<?php require_once dirname(__FILE__).'/inquiry-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/inquiry-itemgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/inquiry-itemform.phtml' ?>
<?php require_once dirname(__FILE__).'/inquiry-filesgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/inquiry-filesform.phtml' ?>
<?php require_once dirname(__FILE__).'/inquiry-approvalgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/inquiry-approvalform.phtml' ?>



<div id="pnl_edit_record_custom" style="display: none">
	<div class="form_row">
		<div class="form_label_col">Commit By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Commit Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitdate"></span>
		</div>
	</div> 

	<div class="form_row" style="margin-top: 30px;">
		<div class="form_label_col">Approve By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-approveby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Approve Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-approvedate"></span>
		</div>
	</div>	

	<div class="form_row" style="margin-top: 30px;">
		<div class="form_label_col">Decline By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-declineby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Decline Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-declinedate"></span>
		</div>
	</div>	

</div>	
			
