var this_page_id;
var this_page_options;

import {fgta4slideselect} from  '../../../../../index.php/asset/fgta/framework/fgta4libs/fgta4slideselect.mjs'
import * as hnd from  './inquiry-edit-hnd.mjs'


const btn_edit = $('#pnl_edit-btn_edit')
const btn_save = $('#pnl_edit-btn_save')
const btn_delete = $('#pnl_edit-btn_delete')
const btn_print = $('#pnl_edit-btn_print');

const btn_commit = $('#pnl_edit-btn_commit')
const btn_uncommit = $('#pnl_edit-btn_uncommit')
const btn_approve = $('#pnl_edit-btn_approve')
const btn_decline = $('#pnl_edit-btn_decline')			
const btn_genreq = $('#pnl_edit-btn_genrequest')


const comp_advance = $('.advance');
const comp_viabank = $('.viabank')
const comp_budget = $('.budget');
const comp_project = $('.project')


const pnl_formitems = $('.pnl_edit-editpanel')
const pnl_inquirytype_id = $('#pnl_edit-inquirytype_id')
const pnl_form = $('#pnl_edit-form')
const obj = {
	txt_inquiry_id: $('#pnl_edit-txt_inquiry_id'),
	cbo_inquirytype_id: $('#pnl_edit-cbo_inquirytype_id'),
	txt_inquiry_descr: $('#pnl_edit-txt_inquiry_descr'),
	dt_inquiry_dtstart: $('#pnl_edit-dt_inquiry_dtstart'),
	dt_inquiry_dtend: $('#pnl_edit-dt_inquiry_dtend'),
	cbo_user_dept_id: $('#pnl_edit-cbo_user_dept_id'),
	cbo_empl_id: $('#pnl_edit-cbo_empl_id'),
	chk_inquiry_isadvance: $('#pnl_edit-chk_inquiry_isadvance'),

	chk_inquiry_isemplaspartner: $('#pnl_edit-chk_inquiry_isemplaspartner'),

	cbo_partner_id: $('#pnl_edit-cbo_partner_id'),
	cbo_paymtype_id: $('#pnl_edit-cbo_paymtype_id'),
	cbo_partnerbank_id: $('#pnl_edit-cbo_partnerbank_id'),
	txt_paymto_bankacc: $('#pnl_edit-txt_paymto_bankacc'),
	txt_paymto_bankaccname: $('#pnl_edit-txt_paymto_bankaccname'),
	txt_paymto_bankname: $('#pnl_edit-txt_paymto_bankname'),

	cbo_partnercontact_id: $('#pnl_edit-cbo_partnercontact_id'),
	txt_paymto_upname: $('#pnl_edit-txt_paymto_upname'),
	txt_paymto_upposition: $('#pnl_edit-txt_paymto_upposition'),
	txt_paymto_upphone: $('#pnl_edit-txt_paymto_upphone'),

	
	cbo_projbudget_id: $('#pnl_edit-cbo_projbudget_id'),
	cbo_projbudgettask_id: $('#pnl_edit-cbo_projbudgettask_id'),
	chk_inquiry_isunbudgetted: $('#pnl_edit-chk_inquiry_isunbudgetted'),
	cbo_site_id: $('#pnl_edit-cbo_site_id'),
	txt_deliver_siteaddress: $('#pnl_edit-txt_deliver_siteaddress'),
	txt_deliver_city: $('#pnl_edit-txt_deliver_city'),
	txt_deliver_upname: $('#pnl_edit-txt_deliver_upname'),
	txt_deliver_uptelp: $('#pnl_edit-txt_deliver_uptelp'),
	txt_inquirymodel_id: $('#pnl_edit-txt_inquirymodel_id'),
	txt_inquiryselect_id: $('#pnl_edit-txt_inquiryselect_id'),
	txt_request_dept_id: $('#pnl_edit-txt_request_dept_id'),
	txt_owner_dept_id: $('#pnl_edit-txt_owner_dept_id'),
	txt_request_doc_id: $('#pnl_edit-txt_request_doc_id'),
	txt_orderout_dept_id: $('#pnl_edit-txt_orderout_dept_id'),
	txt_orderout_doc_id: $('#pnl_edit-txt_orderout_doc_id'),
	txt_trxmodel_id: $('#pnl_edit-txt_trxmodel_id'),
	txt_itemmanage_id: $('#pnl_edit-txt_itemmanage_id'),
	txt_inquiry_rejectnotes: $('#pnl_edit-txt_inquiry_rejectnotes'),
	cbo_doc_id: $('#pnl_edit-cbo_doc_id'),
	txt_inquiry_selectfield: $('#pnl_edit-txt_inquiry_selectfield'),
	txt_inquiry_version: $('#pnl_edit-txt_inquiry_version'),
	txt_inquiry_maxadvancevalue: $('#pnl_edit-txt_inquiry_maxadvancevalue'),
	chk_inquiry_isallowadvance: $('#pnl_edit-chk_inquiry_isallowadvance'),
	chk_inquiry_isallowoverbudget: $('#pnl_edit-chk_inquiry_isallowoverbudget'),
	chk_inquiry_isdateinterval: $('#pnl_edit-chk_inquiry_isdateinterval'),
	chk_inquiry_iscommit: $('#pnl_edit-chk_inquiry_iscommit'),
	txt_inquiry_commitby: $('#pnl_edit-txt_inquiry_commitby'),
	txt_inquiry_commitdate: $('#pnl_edit-txt_inquiry_commitdate'),
	chk_inquiry_isapprovalprogress: $('#pnl_edit-chk_inquiry_isapprovalprogress'),
	chk_inquiry_isapproved: $('#pnl_edit-chk_inquiry_isapproved'),
	txt_inquiry_approveby: $('#pnl_edit-txt_inquiry_approveby'),
	txt_inquiry_approvedate: $('#pnl_edit-txt_inquiry_approvedate'),
	chk_inquiry_isdeclined: $('#pnl_edit-chk_inquiry_isdeclined'),
	txt_inquiry_declineby: $('#pnl_edit-txt_inquiry_declineby'),
	txt_inquiry_declinedate: $('#pnl_edit-txt_inquiry_declinedate'),
	chk_inquiry_ispreparing: $('#pnl_edit-chk_inquiry_ispreparing'),
	chk_inquiry_isprepared: $('#pnl_edit-chk_inquiry_isprepared'),
	txt_inquiry_preparedby: $('#pnl_edit-txt_inquiry_preparedby'),
	txt_inquiry_prepareddate: $('#pnl_edit-txt_inquiry_prepareddate'),
	chk_inquiry_isreject: $('#pnl_edit-chk_inquiry_isreject'),
	txt_inquiry_rejectby: $('#pnl_edit-txt_inquiry_rejectby'),
	txt_inquiry_rejectdate: $('#pnl_edit-txt_inquiry_rejectdate'),
	chk_inquiry_iscomplete: $('#pnl_edit-chk_inquiry_iscomplete'),
	chk_inquiry_isclose: $('#pnl_edit-chk_inquiry_isclose'),
	txt_inquiry_closeby: $('#pnl_edit-txt_inquiry_closeby'),
	txt_inquiry_closedate: $('#pnl_edit-txt_inquiry_closedate'),
	chk_inquiry_isautogenerated: $('#pnl_edit-chk_inquiry_isautogenerated'),
	chk_inquiry_isitemdeptuser: $('#pnl_edit-chk_inquiry_isitemdeptuser'),
	chk_inquiry_isitemdeptowner: $('#pnl_edit-chk_inquiry_isitemdeptowner'),
	chk_inquiry_istoberequest: $('#pnl_edit-chk_inquiry_istoberequest'),

	cbo_project_id: $('#pnl_edit-cbo_project_id'),
	cbo_projecttask_id: $('#pnl_edit-cbo_projecttask_id'),

}


const rec_commitby = $('#pnl_edit_record-commitby');
const rec_commitdate = $('#pnl_edit_record-commitdate');		
		
const rec_approveby = $('#pnl_edit_record-approveby');
const rec_approvedate = $('#pnl_edit_record-approvedate');			
const rec_declineby = $('#pnl_edit_record-declineby');
const rec_declinedate = $('#pnl_edit_record-declinedate');			
			



let form;

export async function init(opt) {
	this_page_id = opt.id;
	this_page_options = opt;


	var disableedit = false;
	// switch (this_page_options.variancename) {
	// 	case 'commit' :
	//		disableedit = true;
	//		btn_edit.linkbutton('disable');
	//		btn_save.linkbutton('disable');
	//		btn_delete.linkbutton('disable');
	//		break;
	// }


	form = new global.fgta4form(pnl_form, {
		primary: obj.txt_inquiry_id,
		autoid: true,
		logview: 'trn_inquiry',
		btn_edit: disableedit==true? $('<a>edit</a>') : btn_edit,
		btn_save: disableedit==true? $('<a>save</a>') : btn_save,
		btn_delete: disableedit==true? $('<a>delete</a>') : btn_delete,		
		objects : obj,
		OnDataSaving: async (data, options) => { await form_datasaving(data, options) },
		OnDataSaveError: async (data, options) => { await form_datasaveerror(data, options) },
		OnDataSaved: async (result, options) => {  await form_datasaved(result, options) },
		OnDataDeleting: async (data, options) => { await form_deleting(data, options) },
		OnDataDeleted: async (result, options) => { await form_deleted(result, options) },
		OnIdSetup : (options) => { form_idsetup(options) },
		OnViewModeChanged : (viewonly) => { form_viewmodechanged(viewonly) },
		OnRecordStatusCreated: () => {
			
		$('#pnl_edit_record_custom').detach().appendTo("#pnl_edit_record");
		$('#pnl_edit_record_custom').show();		
					
		}		
	})



	btn_print.linkbutton({ onClick: () => { btn_print_click(); 	} });	
	btn_commit.linkbutton({ onClick: () => { btn_action_click({ action: 'commit' }); } });
	btn_uncommit.linkbutton({ onClick: () => { btn_action_click({ action: 'uncommit' }); } });			
	btn_genreq.linkbutton({ onClick: () => { btn_action_click({ action: 'generaterequest' }); } });					
	btn_approve.linkbutton({ onClick: () => { btn_action_click({ action: 'approve' }); } });
	btn_decline.linkbutton({ onClick: () => {
		var id = 'pnl_edit-reason_' + Date.now().toString();
		$ui.ShowMessage(`
			<div style="display: block;  margin-bottom: 10px">
				<div style="font-weight: bold; margin-bottom: 10px">Reason</div>
				<div">
					<input id="${id}" class="easyui-textbox" style="width: 300px; height: 60px;" data-options="multiline: true">
				</div>
			</div>
		`, {
			'Decline': () => {
				var reason = $(`#${id}`).textbox('getValue');
				btn_action_click({ action: 'decline', reason: reason }); 
			},
			'Cancel': () => {
			} 
		}, ()=>{
			var obj_reason = $(`#${id}`);
			var txt = obj_reason.textbox('textbox');
			txt[0].maxLength = 255;
			txt[0].classList.add('declinereasonbox');
			txt[0].addEventListener('keyup', (ev)=>{
				if (ev.key=='Enter') {
					ev.stopPropagation();
				}
			});
			txt.css('text-align', 'center');
			txt.focus();
		})
	}});				
				



	obj.chk_inquiry_isdateinterval.checkbox({ onChange: (checked) => { chk_inquiry_isdateinterval_changed(checked) }});
	obj.chk_inquiry_isadvance.checkbox({ onChange: (checked) => { chk_inquiry_isadvance_changed(checked) }});
	obj.chk_inquiry_isunbudgetted.checkbox({ onChange: (checked) => { chk_inquiry_isunbudgetted_changed(checked) }});


	new fgta4slideselect(obj.cbo_inquirytype_id, {
		title: 'Pilih Type Inquiry',
		returnpage: this_page_id,
		api: $ui.apis.load_inquirytype_id,
		fieldValue: 'inquirytype_id',
		fieldValueMap: 'inquirytype_id',
		fieldDisplay: 'inquirytype_name',
		fields: [
			{mapping: 'inquirytype_id', text: 'ID'},
			{mapping: 'inquirytype_name', text: 'Type'},
			{mapping: 'related_dept_name', text: 'Destination'},
			{mapping: 'owner_dept_name', text: 'Owner'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
				
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {
				console.log(record);	
				form.setValue(obj.txt_inquirymodel_id, record.inquirymodel_id);
				form.setValue(obj.txt_inquiryselect_id, record.inquiryselect_id);
				form.setValue(obj.txt_owner_dept_id, record.owner_dept_id);
				form.setValue(obj.txt_request_dept_id, record.related_dept_id);
				form.setValue(obj.txt_request_doc_id, record.request_doc_id);
				form.setValue(obj.txt_orderout_dept_id, record.orderout_dept_id);
				form.setValue(obj.txt_orderout_doc_id, record.orderout_doc_id);
				form.setValue(obj.txt_trxmodel_id, record.trxmodel_id);
				form.setValue(obj.txt_itemmanage_id, record.itemmanage_id);
				form.setValue(obj.chk_inquiry_isdateinterval, record.inquirytype_isdateinterval=='1'?true:false);
				form.setValue(obj.chk_inquiry_isitemdeptuser, record.inquirytype_isdeptuser=='1'?true:false);
				form.setValue(obj.chk_inquiry_isitemdeptowner, record.inquirytype_isdeptowner=='1'?true:false);
				form.setValue(obj.chk_inquiry_istoberequest, record.inquirytype_istoberequest=='1'?true:false);
				form.setValue(obj.txt_inquiry_maxadvancevalue, record.inquirytype_maxadvancevalue);
				form.setValue(obj.chk_inquiry_isallowadvance, record.inquirytype_isallowadvance=='1'?true:false);
				form.setValue(obj.chk_inquiry_isemplaspartner, record.inquirytype_isemplaspartner=='1'?true:false);
				form.setValue(obj.chk_inquiry_isallowoverbudget, record.inquirytype_isallowoverbudget=='1'?true:false);
				form.setValue(obj.txt_inquiry_selectfield, record.inquiry_selectfield);

				chk_inquiry_isdateinterval_changed(record.inquirytype_isdateinterval=='1'?true:false);
				chk_inquiry_isallowadvance_changed(record.inquirytype_isallowadvance=='1'?true:false);
				chk_inquiry_isallowoverbudget_changed(record.inquirytype_isallowoverbudget=='1'?true:false);
				
				pnl_formitems.show();
				form.setDisable(obj.cbo_inquirytype_id, true)

			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_user_dept_id, {
		title: 'Pilih user_dept_id',
		returnpage: this_page_id,
		api: $ui.apis.load_user_dept_id,
		fieldValue: 'user_dept_id',
		fieldValueMap: 'dept_id',
		fieldDisplay: 'dept_name',
		fields: [
			{mapping: 'dept_id', text: 'dept_id'},
			{mapping: 'dept_name', text: 'dept_name'},
		],
		OnDataLoading: (criteria, options) => {
			criteria.isparent = 0;
			criteria.isdisabled = 0;
		},
		OnDataLoaded : (result, options) => {
				
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {
				obj.cbo_empl_id.reset();
				obj.cbo_partner_id.reset();
				obj.cbo_project_id.reset();
				obj.cbo_projecttask_id.reset();
				obj.cbo_projbudget_id.reset();
				obj.cbo_projbudgettask_id.reset();
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_empl_id, {
		title: 'Pilih empl_id',
		returnpage: this_page_id,
		api: $ui.apis.load_empl_id,
		fieldValue: 'empl_id',
		fieldValueMap: 'empl_id',
		fieldDisplay: 'empl_name',
		fields: [
			{mapping: 'empl_id', text: 'empl_id'},
			{mapping: 'empl_name', text: 'empl_name'},
		],
		OnDataLoading: (criteria, options) => {
			var inquiry_isemplaspartner = form.getValue(obj.chk_inquiry_isemplaspartner);
			if (inquiry_isemplaspartner) {
				options.api = $ui.apis.load_empl_id_partner
			} 
			criteria.dept_id = form.getValue(obj.cbo_user_dept_id)
			criteria.isdisabled = 0
		},
		OnDataLoaded : (result, options) => {
			// result.records.unshift({empl_id:'--NULL--', empl_name:'NONE'});	
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {		
				var inquiry_isemplaspartner = form.getValue(obj.chk_inquiry_isemplaspartner);
				if (inquiry_isemplaspartner) {
					// console.log(record.partner_id, record.partner_name);
					form.setValue(obj.cbo_partner_id, record.partner_id, record.partner_name)
				} 
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_project_id, {
		title: 'Pilih project_id',
		returnpage: this_page_id,
		api: $ui.apis.load_project_id,
		fieldValue: 'project_id',
		fieldValueMap: 'project_id',
		fieldDisplay: 'project_name',
		fields: [
			{mapping: 'project_id', text: 'project_id'},
			{mapping: 'project_name', text: 'project_name'},
		],
		OnDataLoading: (criteria) => {
			criteria.dept_id = form.getValue(obj.cbo_user_dept_id)
			criteria.isdisabled = 0;
		},
		OnDataLoaded : (result, options) => {
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_projecttask_id, {
		title: 'Pilih projecttask_id',
		returnpage: this_page_id,
		api: $ui.apis.load_projecttask_id,
		fieldValue: 'projecttask_id',
		fieldValueMap: 'projecttask_id',
		fieldDisplay: 'projecttask_name',
		fields: [
			{mapping: 'projecttask_id', text: 'projecttask_id'},
			{mapping: 'projecttask_name', text: 'projecttask_name'},
		],
		OnDataLoading: (criteria) => {
			criteria.project_id = form.getValue(obj.cbo_project_id)
		},
		OnDataLoaded : (result, options) => {
			result.records.unshift({projecttask_id:'--NULL--', projecttask_name:'NONE'});	
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_projbudget_id, {
		title: 'Pilih projbudget_id',
		returnpage: this_page_id,
		api: $ui.apis.load_projbudget_id,
		fieldValue: 'projbudget_id',
		fieldValueMap: 'projbudget_id',
		fieldDisplay: 'projbudget_name',
		fields: [
			{mapping: 'projbudget_id', text: 'ID'},
			{mapping: 'projbudget_name', text: 'Budget'},
			{mapping: 'project_name', text: 'Project'},
			{mapping: 'dept_name', text: 'Owner'},
		],
		OnDataLoading: (criteria) => {
			criteria.dept_id = form.getValue(obj.cbo_user_dept_id)
		},
		OnDataLoaded : (result, options) => {
				
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {	
				// cbo_projbudget_id_selected(value, display, record, args);	
				form.setValue(obj.cbo_project_id, record.project_id, record.project_name);		
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_projbudgettask_id, {
		title: 'Pilih projbudgettask_id',
		returnpage: this_page_id,
		api: $ui.apis.load_projbudgettask_id,
		fieldValue: 'projbudgettask_id',
		fieldValueMap: 'projbudgettask_id',
		fieldDisplay: 'projbudgettask_name',
		fields: [
			{mapping: 'projbudgettask_id', text: 'ID'},
			{mapping: 'projbudgettask_name', text: 'Task'},
		],
		OnDataLoading: (criteria) => {
			var projbudget_id = form.getValue(obj.cbo_projbudget_id);
			criteria.projbudget_id = projbudget_id;
		},
		OnDataLoaded : (result, options) => {
			result.records.unshift({projbudgettask_id:'--NULL--', projbudgettask_name:'NONE'});	
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {
				form.setValue(obj.cbo_projecttask_id, record.projecttask_id, record.projbudgettask_name);			
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_site_id, {
		title: 'Pilih site_id',
		returnpage: this_page_id,
		api: $ui.apis.load_site_id,
		fieldValue: 'site_id',
		fieldValueMap: 'site_id',
		fieldDisplay: 'site_name',
		fields: [
			{mapping: 'site_id', text: 'site_id'},
			{mapping: 'site_name', text: 'site_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
				
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {	
				form.setValue(obj.txt_deliver_siteaddress, record.site_address);
				form.setValue(obj.txt_deliver_city, record.city_name);
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_doc_id, {
		title: 'Pilih doc_id',
		returnpage: this_page_id,
		api: $ui.apis.load_doc_id,
		fieldValue: 'doc_id',
		fieldValueMap: 'doc_id',
		fieldDisplay: 'doc_name',
		fields: [
			{mapping: 'doc_id', text: 'doc_id'},
			{mapping: 'doc_name', text: 'doc_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
				
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				

	
	new fgta4slideselect(obj.cbo_partner_id, {
		title: 'Pilih Partner',
		returnpage: this_page_id,
		api: $ui.apis.load_partner_id,
		fieldValue: 'partner_id',
		fieldValueMap: 'partner_id',
		fieldDisplay: 'partner_name',
		fields: [
			{mapping: 'partner_id', text: 'ID'},
			{mapping: 'partner_name', text: 'Nama'},
			{mapping: 'partnertype_name', text: 'Type'},
		],
		OnDataLoading: (criteria) => {
		},
		OnDataLoaded : (result, options) => {
			if (!obj.cbo_partner_id.combo('options').required) {
				result.records.unshift({partner_id:'--NULL--', partner_name:'NONE'});	
			}
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {	
				
			}
		}
	})


	new fgta4slideselect(obj.cbo_paymtype_id, {
		title: 'Pilih Tipe Pembayaran',
		returnpage: this_page_id,
		api: $ui.apis.load_paymtype_id,
		fieldValue: 'paymtype_id',
		fieldValueMap: 'paymtype_id',
		fieldDisplay: 'paymtype_name',
		fields: [
			{mapping: 'paymtype_id', text: 'ID'},
			{mapping: 'paymtype_name', text: 'Nama'},
		],
		OnDataLoading: (criteria) => {
		},
		OnDataLoaded : (result, options) => {
			if (!obj.cbo_paymtype_id.combo('options').required) {
				result.records.unshift({paymtype_id:'--NULL--', paymtype_name:'NONE'});	
			}
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {	
				cbo_paymtype_id_selected(value)				
			}
		}
	})


	new fgta4slideselect(obj.cbo_partnerbank_id, {
		title: 'Pilih Account Bank',
		returnpage: this_page_id,
		api: $ui.apis.load_partnerbank_id,
		fieldValue: 'partnerbank_id',
		fieldValueMap: 'partnerbank_id',
		fieldDisplay: 'partnerbank_accnum',
		fields: [
			{mapping: 'partnerbank_id', text: 'ID'},
			{mapping: 'partnerbank_accnum', text: 'Nama'},
		],
		OnDataLoading: (criteria) => {
			criteria.id = form.getValue(obj.cbo_partner_id);
		},
		OnDataLoaded : (result, options) => {
			if (!obj.cbo_partnerbank_id.combo('options').required) {
				result.records.unshift({partnerbank_id:'--NULL--', partnerbank_accnum:'NONE'});	
			}
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {
				form.setValue(obj.txt_paymto_bankacc, record.partnerbank_accnum)
				form.setValue(obj.txt_paymto_bankaccname, record.partnerbank_accname)
				form.setValue(obj.txt_paymto_bankname, record.bank_name)
			}
		}
	})

	new fgta4slideselect(obj.cbo_partnercontact_id, {
		title: 'Pilih Contact Partner',
		returnpage: this_page_id,
		api: $ui.apis.load_partnercontact_id,
		fieldValue: 'partnercontact_id',
		fieldValueMap: 'partnercontact_id',
		fieldDisplay: 'partnercontact_name',
		fields: [
			{mapping: 'partnercontact_id', text: 'ID'},
			{mapping: 'partnercontact_name', text: 'Nama'},
			{mapping: 'partnercontact_position', text: 'Position'},
		],
		OnDataLoading: (criteria) => {
			criteria.id = form.getValue(obj.cbo_partner_id);
		},
		OnDataLoaded : (result, options) => {
				
		},
		OnSelected: (value, display, record) => {
			form.setValue(obj.txt_paymto_upname, record.partnercontact_name)
			form.setValue(obj.txt_paymto_upposition, record.partnercontact_position)
			form.setValue(obj.txt_paymto_upphone, record.partnercontact_mobilephone)
		}
	})


	document.addEventListener('keydown', (ev)=>{
		if ($ui.getPages().getCurrentPage()==this_page_id) {
			if (ev.code=='KeyS' && ev.ctrlKey==true) {
				if (!form.isInViewMode()) {
					form.btn_save_click();
				}
				ev.stopPropagation()
				ev.preventDefault()
			}
		}
	}, true)
	
	document.addEventListener('OnSizeRecalculated', (ev) => {
		OnSizeRecalculated(ev.detail.width, ev.detail.height)
	})	

	document.addEventListener('OnButtonBack', (ev) => {
		if ($ui.getPages().getCurrentPage()==this_page_id) {
			ev.detail.cancel = true;
			if (form.isDataChanged()) {
				form.canceledit(()=>{
					$ui.getPages().show('pnl_list', ()=>{
						form.setViewMode()
						$ui.getPages().ITEMS['pnl_list'].handler.scrolllast()
					})
				})
			} else {
				$ui.getPages().show('pnl_list', ()=>{
					form.setViewMode()
					$ui.getPages().ITEMS['pnl_list'].handler.scrolllast()
				})
			}
		
		}
	})

	document.addEventListener('OnButtonHome', (ev) => {
		if ($ui.getPages().getCurrentPage()==this_page_id) {
			if (form.isDataChanged()) {
				ev.detail.cancel = true;
				$ui.ShowMessage('Anda masih dalam mode edit dengan pending data, silakan matikan mode edit untuk kembali ke halaman utama.')
			}
		}
	})

	if (typeof hnd.init==='function') {
		hnd.init({
			form: form,
			obj: obj,
			opt: opt,
		})
	}

}

export function OnSizeRecalculated(width, height) {
}

export function getForm() {
	return form
}


export function open(data, rowid, viewmode=true, fn_callback) {

	var pMdt = form.getDefaultPrompt(true)
	var pOpt = form.getDefaultPrompt(false)


	var fn_dataopening = async (options) => {
		options.criteria[form.primary.mapping] = data[form.primary.mapping]
	}

	var fn_dataopened = async (result, options) => {
		var record = result.record;

		updatefilebox(record);
		// if (record.empl_id==null) { record.empl_id=pOpt.value; record.empl_name=pOpt.text; }
		// if (record.projecttask_id==null) { record.projecttask_id=pOpt.value; record.projecttask_name=pOpt.text; }
		// if (record.projbudgettask_id==null) { record.projbudgettask_id=pOpt.value; record.projbudgettask_name=pOpt.text; }
		// if (record.partnercontact_id==null) { record.partnercontact_id=pOpt.value; record.partnercontact_name=pOpt.text; }
		// if (record.partnerbank_id==null) { record.partnerbank_id=pOpt.value; record.partnerbank_accnum=pOpt.text; }
		// if (record.projbudget_id==null) { record.projbudget_id=pOpt.value; record.projbudget_name=pOpt.text; }
		// if (record.partner_id==null) { record.partner_id=pOpt.value; record.partner_name=pOpt.text; }
		// if (record.paymtype_id==null) { record.paymtype_id=pOpt.value; record.paymtype_name=pOpt.text; }
		for (var objid in obj) {
			let o = obj[objid]
			if (o.isCombo() && !o.isRequired()) {
				var value =  result.record[o.getFieldValueName()];
				if (value==null ) {
					record[o.getFieldValueName()] = pOpt.value;
					record[o.getFieldDisplayName()] = pOpt.text;
				}
			}
		}
  		updaterecordstatus(record)

		form.SuspendEvent(true);
		form
			.fill(record)
			.setValue(obj.cbo_inquirytype_id, record.inquirytype_id, record.inquirytype_name)
			.setValue(obj.cbo_user_dept_id, record.user_dept_id, record.user_dept_name)
			.setValue(obj.cbo_empl_id, record.empl_id, record.empl_name)
			.setValue(obj.cbo_project_id, record.project_id, record.project_name)
			.setValue(obj.cbo_projecttask_id, record.projecttask_id, record.projecttask_name)
			.setValue(obj.cbo_projbudget_id, record.projbudget_id, record.projbudget_name)
			.setValue(obj.cbo_projbudgettask_id, record.projbudgettask_id, record.projbudgettask_name)
			.setValue(obj.cbo_site_id, record.site_id, record.site_name)
			.setValue(obj.cbo_doc_id, record.doc_id, record.doc_name)
			.setValue(obj.cbo_partner_id, record.partner_id, record.partner_name)
			.setValue(obj.cbo_partnerbank_id, record.partnerbank_id, record.partnerbank_accnum)
			.setValue(obj.cbo_partnercontact_id, record.partnercontact_id, record.partnercontact_name)
			.setValue(obj.cbo_paymtype_id, record.paymtype_id, record.paymtype_name)
			.setViewMode(viewmode)
			.lock(false)
			.rowid = rowid

		
		chk_inquiry_isadvance_changed(record.inquiry_isadvance=='1' ? true : false)
		chk_inquiry_isdateinterval_changed(record.inquiry_isdateinterval=='1' ? true : false);
		chk_inquiry_isunbudgetted_changed(record.inquiry_isunbudgetted=='1' ? true : false);
		chk_inquiry_isallowadvance_changed(record.inquiry_isallowadvance=='1'?true:false);
		chk_inquiry_isallowoverbudget_changed(record.inquiry_isallowoverbudget=='1'?true:false) ;

		pnl_formitems.show();
		pnl_inquirytype_id.show();
		form.setDisable(obj.cbo_inquirytype_id, true);


		form.commit()
		form.SuspendEvent(false);
		updatebuttonstate(record)

		// tampilkan form untuk data editor
		fn_callback()
	}

	var fn_dataopenerror = (err) => {
		$ui.ShowMessage('[ERROR]'+err.errormessage);
	}

	form.dataload(fn_dataopening, fn_dataopened, fn_dataopenerror)
	
}


export function createnew() {

	var promptMandatory = form.getDefaultPrompt(true)
	var promptOptional = form.getDefaultPrompt(false)


	form.createnew(async (data, options)=>{
		// console.log(data)
		// console.log(options)
		form.rowid = null

		// set nilai-nilai default untuk form
		data.inquiry_dtstart = global.now()
		data.inquiry_dtend = global.now()
		data.inquiry_isadvance = '0'
		data.inquiry_isunbudgetted = '0'
		data.inquiry_version = 0
		data.inquiry_maxadvancevalue = 0
		data.inquiry_isallowadvance = '0'
		data.inquiry_isdateinterval = '0'
		data.inquiry_iscommit = '0'
		data.inquiry_isapprovalprogress = '0'
		data.inquiry_isapproved = '0'
		data.inquiry_isdeclined = '0'
		data.inquiry_ispreparing = '0'
		data.inquiry_isprepared = '0'
		data.inquiry_isreject = '0'
		data.inquiry_iscomplete = '0'
		data.inquiry_isclose = '0'
		data.inquiry_isautogenerated = '0'
		data.inquiry_isitemdeptuser = '0'
		data.inquiry_isitemdeptowner = '0'
		data.inquiry_istoberequest = '0'

		data.inquirytype_id = '0'
		data.inquirytype_name = '-- PILIH --'
		data.user_dept_id = global.setup.dept_id
		data.user_dept_name = global.setup.dept_name
		data.empl_id = global.setup.empl_id
		data.empl_name = global.setup.empl_name
		data.project_id = '0'
		data.project_name = '-- PILIH --'
		data.projecttask_id = '--NULL--'
		data.projecttask_name = 'NONE'
		data.projbudget_id = '0'
		data.projbudget_name = '-- PILIH --'
		data.projbudgettask_id = '--NULL--'
		data.projbudgettask_name = 'NONE'
		data.site_id = '0'
		data.site_name = '-- PILIH --'
		data.doc_id = global.setup.doc_id
		data.doc_name = global.setup.doc_id
		data.partner_id = global.setup.partner_id
		data.partner_name = global.setup.partner_name
		data.paymtype_id = promptOptional.value
		data.paymtype_name = promptOptional.text
		data.partnercontact_id = promptOptional.value
		data.partnercontact_name = promptOptional.text
		data.partnerbank_id = promptOptional.value
		data.partnerbank_name = promptOptional.text
		



		rec_commitby.html('');
		rec_commitdate.html('');
		
		rec_approveby.html('');
		rec_approvedate.html('');
		rec_declineby.html('');
		rec_declinedate.html('');
		

		chk_inquiry_isdateinterval_changed(data.inquiry_isdateinterval=='1'?true:false)
		chk_inquiry_isadvance_changed(data.inquiry_isadvance=='1'?true:false)
		chk_inquiry_isunbudgetted_changed(data.inquiry_isunbudgetted=='1' ? true : false)
		cbo_paymtype_id_selected(data.paymtype_id);


		var button_commit_on = true;
		var button_uncommit_on = false;
		var button_approve_on = false;
		var button_decline_on = false;
		btn_commit.linkbutton(button_commit_on ? 'enable' : 'disable');
		btn_uncommit.linkbutton(button_uncommit_on ? 'enable' : 'disable');
		btn_approve.linkbutton(button_approve_on ? 'enable' : 'disable');
		btn_decline.linkbutton(button_decline_on ? 'enable' : 'disable');
			

		pnl_formitems.hide();
		pnl_inquirytype_id.show();
		form.setDisable(obj.cbo_inquirytype_id, false);

		options.OnCanceled = () => {
			$ui.getPages().show('pnl_list')
		}

		$ui.getPages().ITEMS['pnl_edititemgrid'].handler.createnew(data, options)
		$ui.getPages().ITEMS['pnl_editapprovalgrid'].handler.createnew(data, options)


	})
}


export function detil_open(pnlname) {
	if (form.isDataChanged()) {
		$ui.ShowMessage('Simpan dulu perubahan datanya.')
		return;
	}

	//$ui.getPages().show(pnlname)
	$ui.getPages().show(pnlname, () => {
		var partner_name = obj.cbo_partner_id.combo('getText');
		var empl_name = obj.cbo_empl_id.combo('getText');
		
		var header_data = form.getData();
		header_data.partner_name = partner_name;
		header_data.empl_name = empl_name;
		
		$ui.getPages().ITEMS[pnlname].handler.OpenDetil(header_data)
	})	
}


function updatefilebox(record) {
	// apabila ada keperluan untuk menampilkan data dari object storage

}

function updaterecordstatus(record) {
	// apabila ada keperluan untuk update status record di sini

		rec_commitby.html(record.inquiry_commitby);
		rec_commitdate.html(record.inquiry_commitdate);
		
		rec_approveby.html(record.inquiry_approveby);
		rec_approvedate.html(record.inquiry_approvedate);
		rec_declineby.html(record.inquiry_declineby);
		rec_declinedate.html(record.inquiry_declinedate);
			
}

function updatebuttonstate(record) {
	// apabila ada keperluan untuk update state action button di sini

		/* action button */
		var button_commit_on = false;
		var button_uncommit_on = false;
		var button_approve_on = false;
		var button_decline_on = false;

		
		if (record.inquiry_isfirm=="1") {
			button_commit_on = false;
			button_uncommit_on = false;
			button_approve_on = false;
			button_decline_on = false;
			form.lock(true);	
		} else if (record.inquiry_isdeclined=="1" || record.inquiry_isuseralreadydeclined=="1") {
			button_commit_on = false;
			button_uncommit_on = true;
			button_approve_on = true;
			button_decline_on = false;
			form.lock(true);	
		} else if (record.inquiry_isapproved=="1" || record.inquiry_isuseralreadyapproved=="1") {
			button_commit_on = false;
			button_uncommit_on = false;
			button_approve_on = false;
			button_decline_on = true;	
			form.lock(true);	
		} else if (record.inquiry_isapprovalprogress=="1") {
			button_commit_on = false;
			button_uncommit_on = false;
			button_approve_on = true;
			button_decline_on = true;
			form.lock(true);	
		} else if (record.inquiry_iscommit=="1") {
			button_commit_on = false;
			button_uncommit_on = true;
			button_approve_on = true;
			button_decline_on = true;
			form.lock(true);		
		} else {
			button_commit_on = true;
			button_uncommit_on = false;
			button_approve_on = false;
			button_decline_on = false;
			form.lock(false);
		} 
	
		btn_commit.linkbutton(button_commit_on ? 'enable' : 'disable');
		btn_uncommit.linkbutton(button_uncommit_on ? 'enable' : 'disable');
		btn_approve.linkbutton(button_approve_on ? 'enable' : 'disable');
		btn_decline.linkbutton(button_decline_on ? 'enable' : 'disable');		
				
}

function updategridstate(record) {
	// apabila ada keperluan untuk update state grid list di sini



	var updategriddata = {}

	var col_commit = 'inquiry_iscommit';
	updategriddata[col_commit] = record.inquiry_iscommit;	
	
	var col_approveprogress = 'inquiry_isapprovalprogress';
	var col_approve = 'inquiry_isapprove'
	var col_decline = "inquiry_isdeclined"
	updategriddata[col_approveprogress] = record.inquiry_isapprovalprogress;
	updategriddata[col_approve] = record.inquiry_isapproved;
	updategriddata[col_decline] = record.inquiry_isdeclined;				
			
	$ui.getPages().ITEMS['pnl_list'].handler.updategrid(updategriddata, form.rowid);
			
}

function form_viewmodechanged(viewmode) {
	var OnViewModeChangedEvent = new CustomEvent('OnViewModeChanged', {detail: {}})
	$ui.triggerevent(OnViewModeChangedEvent, {
		viewmode: viewmode
	})
}

function form_idsetup(options) {
	var objid = obj.txt_inquiry_id
	switch (options.action) {
		case 'fill' :
			objid.textbox('disable') 
			break;

		case 'createnew' :
			// console.log('new')
			if (form.autoid) {
				objid.textbox('disable') 
				objid.textbox('setText', '[AUTO]') 
			} else {
				objid.textbox('enable') 
			}
			break;
			
		case 'save' :
			objid.textbox('disable') 
			break;	
	}
}


async function form_datasaving(data, options) {


	// cek dulu data yang akan disimpan,
	// apabila belum sesuai dengan yang diharuskan, batalkan penyimpanan
	//    options.cancel = true

	// Modifikasi object data, apabila ingin menambahkan variabel yang akan dikirim ke server
	options.skipmappingresponse = [];
	for (var objid in obj) {
		var o = obj[objid]
		if (o.isCombo() && !o.isRequired()) {
			var id = o.getFieldValueName()
			options.skipmappingresponse.push(id)
		}
	}
}

async function form_datasaveerror(err, options) {
	// apabila mau olah error messagenya
	// $ui.ShowMessage(err.errormessage)
	console.log(err)
}


async function form_datasaved(result, options) {
	var pOpt = form.getDefaultPrompt(false)

	var data = {}
	Object.assign(data, form.getData(), result.dataresponse)
	for (var objid in obj) {
		var o = obj[objid]
		if (o.isCombo() && !o.isRequired()) {
			var value =  result.dataresponse[o.getFieldValueName()];
			var text = result.dataresponse[o.getFieldDisplayName()];
			if (value==null ) {
				value = pOpt.value;
				text = pOpt.text;
			}
			form.setValue(o, value, text);
		}
	}
	form.rowid = $ui.getPages().ITEMS['pnl_list'].handler.updategrid(data, form.rowid)
}



async function form_deleting(data) {
}

async function form_deleted(result, options) {
	$ui.getPages().show('pnl_list')
	$ui.getPages().ITEMS['pnl_list'].handler.removerow(form.rowid)

}



function btn_print_click() {

	if (form.isDataChanged() || !form.isInViewMode()) {
		$ui.ShowMessage('Simpan dulu perubahan datanya.');
		return;
	}

	var id = obj.txt_inquiry_id.textbox('getValue');
	var printurl = 'index.php/printout/' + window.global.modulefullname + '/inquiry.xprint?id=' + id;

	var print_to_new_window = global.setup.print_to_new_window;
	var debug = false;
	var debug = false;
	if (debug || print_to_new_window) {
		var w = window.open(printurl);
		w.onload = () => {
			window.onreadytoprint(() => {
				iframe.contentWindow.print();
			});
		}
	} else {
		$ui.mask('wait...');
		var iframe_id = 'fgta_printelement';
		var iframe = document.getElementById(iframe_id);
		if (iframe) {
			iframe.parentNode.removeChild(iframe);
			iframe = null;
		}

		if (!iframe) {
			iframe = document.createElement('iframe');
			iframe.id = iframe_id;
			iframe.style.visibility = 'hidden';
			iframe.style.height = '10px';
			iframe.style.widows = '10px';
			document.body.appendChild(iframe);

			iframe.onload = () => {
				$ui.unmask();
				iframe.contentWindow.OnPrintCommand(() => {
					console.log('start print');
					iframe.contentWindow.print();
				});
				iframe.contentWindow.preparemodule();
			}
		}
		iframe.src = printurl + '&iframe=1';

	}

}	






async function btn_action_click(args) {
	if (form.isDataChanged() || !form.isInViewMode()) {
		$ui.ShowMessage('[WARNING]Simpan dulu perubahan data, dan tidak sedang dalam mode edit.');
		return;
	}


	var docname = 'Inquiry'
	var txt_version = obj.txt_inquiry_version;
	var chk_iscommit = obj.chk_inquiry_iscommit;
	
	var chk_isapprovalprogress = obj.chk_inquiry_isapprovalprogress;	
	var chk_isapprove = obj.chk_inquiry_isapproved;
	var chk_isdeclined = obj.chk_inquiry_isdeclined;
		
	
	var id = form.getCurrentId();

	Object.assign(args, {
		id: id,
		act_url: null,
		act_msg_quest: null,
		act_msg_result: null,
		act_do: null,
		use_otp: false,
		otp_message: `Berikut adalah code yang harus anda masukkan untuk melakukan ${args.action} ${docname} dengan no id ${id}`,
	});

	switch (args.action) {
		case 'commit' :
			args.act_url = `${global.modulefullname}/xtion-${args.action}`;
			args.act_msg_quest = `Apakah anda yakin akan <b>${args.action}</b> ${docname} no ${args.id} ?`;
			args.act_msg_result = `${docname} no ${args.id} telah di ${args.action}.`;
			args.act_do = (result) => {
				chk_iscommit.checkbox('check');
				
			chk_isapprove.checkbox('uncheck');
		
				form.commit();
			}
			break;

		case 'uncommit' :
			args.act_url = `${global.modulefullname}/xtion-${args.action}`;
			args.act_msg_quest = `Apakah anda yakin akan <b>${args.action}</b> ${docname} no ${args.id} ?`;
			args.act_msg_result = `${docname} no ${args.id} telah di ${args.action}.`;
			args.act_do = (result) => {
				chk_iscommit.checkbox('uncheck');
				
			chk_isapprove.checkbox('uncheck');
			chk_isdeclined.checkbox('uncheck');
		
				form.setValue(txt_version, result.version);
				form.commit();
			}
			break;

		
		case 'approve' :
			args.act_url = `${global.modulefullname}/xtion-approve`;
			args.act_msg_quest = `Apakah anda yakin akan <b>${args.action}</b> ${docname} no ${args.id} ?`;
			args.act_msg_result = `${docname} no ${args.id} telah di ${args.action}.`;
			args.use_otp = true;
			args.otp_title = 'Approval Code';
			args.param = {
				approve: true,
				approval_note: ''
			}
			args.act_do = (result) => {
				chk_iscommit.checkbox('check');
				chk_isapprovalprogress.checkbox('check');
				chk_isapprove.checkbox(result.isfinalapproval ? "check" : "uncheck");
				chk_isdeclined.checkbox('uncheck');
				form.commit();
			}
			break;

		case 'decline' :
			args.act_url = `${global.modulefullname}/xtion-approve`;
			args.act_msg_quest = '', //`Apakah anda yakin akan <b>${args.action}</b> ${docname} no ${args.id} ?`;
			args.act_msg_result = `${docname} no ${args.id} telah di ${args.action}.`;
			args.use_otp = true;
			args.otp_title = 'Decline Code';
			args.param = {
				approve: false,
				approval_note: args.reason
			}
			args.act_do = (result) => {
				chk_iscommit.checkbox('check');
				chk_isapprove.checkbox('uncheck');
				chk_isdeclined.checkbox('check');
				form.commit();
			}
			break;

		case 'generaterequest':
			args.act_url = `${global.modulefullname}/xtion-${args.action}`;
			args.act_msg_quest = `Apakah anda yakin akan <b>${args.action}</b> ${docname} no ${args.id} ?`;
			args.act_msg_result = `${docname} no ${args.id} telah di ${args.action}.`;
			args.act_do = (result) => {};
			break;
			
	}


	try {
		$ui.mask('wait..');
		var { doAction } = await import('../../../../../index.php/asset/fgta/framework/fgta4libs/fgta4xtion.mjs');
		await doAction(args, (err, result) => {
			if (err) {
				$ui.ShowMessage('[WARNING]' + err.message);	
			} else {
				updaterecordstatus(result.dataresponse);
				args.act_do(result);
				updatebuttonstate(result.dataresponse);
				updategridstate(result.dataresponse);
				if (args.act_msg_result!=='') $ui.ShowMessage('[INFO]' + args.act_msg_result);	
			}
		});
	} catch (err) {
		console.error(err);
		$ui.ShowMessage('[ERROR]' + err.message);
	} finally {
		$ui.unmask();
	}
}	
	

function chk_inquiry_isdateinterval_changed(checked) {
	if (checked) {
		$('#pnl_edit-inquiry_dtstart .form_label_col').html('Date Start');
		$('#pnl_edit-inquiry_dtend').show();
		$('#pnl_edititemform-inquirydetil_days').show();
		$('#pnl_edititemform-inquirydetil_task').show();
	} else {
		$('#pnl_edit-inquiry_dtstart .form_label_col').html('Date');
		$('#pnl_edit-inquiry_dtend').hide();
		$('#pnl_edititemform-inquirydetil_days').hide();
		$('#pnl_edititemform-inquirydetil_task').hide();
	}
}


function chk_inquiry_isunbudgetted_changed(checked) {
	var promptMandatory = form.getDefaultPrompt(true)
	var promptOptional = form.getDefaultPrompt(false)

	if (checked) {
		//budget boleh tidak diisi
		comp_budget.addClass('hidden')
		comp_project.removeClass('hidden')

		obj.cbo_projbudget_id.revalidate({
			required: false, invalidMessage: null, prompt: form.getDefaultPrompt(false).text,
			validType: null,
		});	

		if (!form.isEventSuspended()) {
			form.setValue(obj.cbo_projbudget_id, promptOptional.value, promptOptional.text);
		};
	} else {
		// budget wajib diisi
		comp_budget.removeClass('hidden')
		comp_project.addClass('hidden')

		obj.cbo_projbudget_id.revalidate({
			required: true, invalidMessage:  'Budget harus diisi', prompt: form.getDefaultPrompt(true).text,
			validType: "requiredcombo['pnl_edit-cbo_projbudget_id']",
		});

		if (!form.isEventSuspended()) {
			form.setValue(obj.cbo_projbudget_id, promptMandatory.value, promptMandatory.text);
		}
	}
}

function chk_inquiry_isadvance_changed(checked) {

	if (checked) {
		comp_advance.removeClass('hide_advance')

		// partner wajib
		obj.cbo_partner_id.revalidate({
			required: true, invalidMessage:  'Partner harus diisi', prompt: form.getDefaultPrompt(true).text,
			validType: "requiredcombo['pnl_edit-cbo_partner_id']",
		});

		// paymtype wajib
		obj.cbo_paymtype_id.revalidate({
			required: true, invalidMessage:  'Payment Type harus diisi', prompt: form.getDefaultPrompt(true).text,
			validType: "requiredcombo['pnl_edit-cbo_paymtype_id']",
		});


		// partner contact wajib
		obj.cbo_partnercontact_id.revalidate({
			required: true, invalidMessage:  'Contact Type harus diisi', prompt: form.getDefaultPrompt(true).text,
			validType: "requiredcombo['pnl_edit-cbo_partnercontact_id']",
		});		

	} else {

		comp_advance.addClass('hide_advance')

		// partner boleh nggak diisi
		obj.cbo_partner_id.revalidate({
			required: false, invalidMessage: null, prompt: form.getDefaultPrompt(false).text,
			validType: null,
		});		

		// partner boleh nggak diisi
		obj.cbo_paymtype_id.revalidate({
			required: false, invalidMessage: null, prompt: form.getDefaultPrompt(false).text,
			validType: null,
		});	


		// partner  boleh nggak diisi
		obj.cbo_partnercontact_id.revalidate({
			required: false, invalidMessage: null, prompt: form.getDefaultPrompt(false).text,
			validType: null,
		});	

	}

	var paymtype_id = form.getValue(obj.cbo_paymtype_id);
	cbo_paymtype_id_selected(paymtype_id);

	// var partner_id = form.getValue(obj.cbo_partner_id);
	// if (!obj.cbo_partner_id.combo('isValid')) {
	// 	console.log('tidak valid')
	// } else {
	// 	console.log('valid')
	// }

}


function chk_inquiry_isallowadvance_changed(checked) {
	if (checked) {
		form.setDisable(obj.chk_inquiry_isadvance, false)
	} else {
		form.setDisable(obj.chk_inquiry_isadvance, true)
	}
}

function chk_inquiry_isallowoverbudget_changed(checked) {

}


function cbo_paymtype_id_selected(value, display, record, args) {
	
	// CA, GI, TR
	if (value=='GI' || value=='TR') {
		comp_viabank.removeClass('hide_viabank')

		// partner bank wajib
		obj.cbo_partnerbank_id.revalidate({
			required: true, invalidMessage:  'Bank Account harus diisi', prompt: form.getDefaultPrompt(true).text,
			validType: "requiredcombo['pnl_edit-cbo_partnerbank_id']",
		});	

	} else {
		
		comp_viabank.addClass('hide_viabank')

		// partner bank boleh gak diisi
		obj.cbo_partnerbank_id.revalidate({
			required: false, invalidMessage: null, prompt: form.getDefaultPrompt(false).text,
			validType: null,
		});
	}
}

