<?php require_once dirname(__FILE__).'/inquiryprocess-list.phtml' ?>
<?php require_once dirname(__FILE__).'/inquiryprocess-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/inquiryprocess-itemgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/inquiryprocess-itemform.phtml' ?>
<?php require_once dirname(__FILE__).'/inquiryprocess-filesgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/inquiryprocess-filesform.phtml' ?>



