var this_page_id;
var this_page_options;

import {fgta4slideselect} from  '../../../../../index.php/asset/fgta/framework/fgta4libs/fgta4slideselect.mjs'
import * as hnd from  './orderout-edit-hnd.mjs'

const txt_caption = $('#pnl_edit-caption')


const btn_edit = $('#pnl_edit-btn_edit')
const btn_save = $('#pnl_edit-btn_save')
const btn_delete = $('#pnl_edit-btn_delete')
const btn_print = $('#pnl_edit-btn_print');

const btn_commit = $('#pnl_edit-btn_commit')
const btn_uncommit = $('#pnl_edit-btn_uncommit')
			

const btn_approve = $('#pnl_edit-btn_approve')
const btn_decline = $('#pnl_edit-btn_decline')			
				



const pnl_form = $('#pnl_edit-form')
const obj = {
	txt_orderout_id: $('#pnl_edit-txt_orderout_id'),
	cbo_unit_id: $('#pnl_edit-cbo_unit_id'),
	cbo_request_id: $('#pnl_edit-cbo_request_id'),
	chk_orderout_isunref: $('#pnl_edit-chk_orderout_isunref'),
	cbo_inquirytype_id: $('#pnl_edit-cbo_inquirytype_id'),
	cbo_trxmodel_id: $('#pnl_edit-cbo_trxmodel_id'),
	cbo_request_dept_id: $('#pnl_edit-cbo_request_dept_id'),
	txt_orderout_descr: $('#pnl_edit-txt_orderout_descr'),
	dt_orderout_dtstart: $('#pnl_edit-dt_orderout_dtstart'),
	dt_orderout_dtend: $('#pnl_edit-dt_orderout_dtend'),
	cbo_curr_id: $('#pnl_edit-cbo_curr_id'),
	txt_curr_rate: $('#pnl_edit-txt_curr_rate'),
	cbo_ppn_taxtype_id: $('#pnl_edit-cbo_ppn_taxtype_id'),
	cbo_pph_taxtype_id: $('#pnl_edit-cbo_pph_taxtype_id'),
	cbo_partner_id: $('#pnl_edit-cbo_partner_id'),
	cbo_ordercontract_id: $('#pnl_edit-cbo_ordercontract_id'),
	txt_orderout_quot: $('#pnl_edit-txt_orderout_quot'),
	cbo_paymtype_id: $('#pnl_edit-cbo_paymtype_id'),
	cbo_partnerbank_id: $('#pnl_edit-cbo_partnerbank_id'),
	txt_partnerbank_name: $('#pnl_edit-txt_partnerbank_name'),
	txt_partnerbank_bankacc: $('#pnl_edit-txt_partnerbank_bankacc'),
	txt_partnerbank_bankaccname: $('#pnl_edit-txt_partnerbank_bankaccname'),
	txt_partnerbank_bankname: $('#pnl_edit-txt_partnerbank_bankname'),
	cbo_partnercontact_id: $('#pnl_edit-cbo_partnercontact_id'),
	txt_partnercontact_upname: $('#pnl_edit-txt_partnercontact_upname'),
	txt_partnercontact_position: $('#pnl_edit-txt_partnercontact_position'),
	txt_partnercontact_upphone: $('#pnl_edit-txt_partnercontact_upphone'),
	txt_partnercontact_email: $('#pnl_edit-txt_partnercontact_email'),
	cbo_project_id: $('#pnl_edit-cbo_project_id'),
	cbo_projecttask_id: $('#pnl_edit-cbo_projecttask_id'),
	cbo_projbudget_id: $('#pnl_edit-cbo_projbudget_id'),
	cbo_projbudgettask_id: $('#pnl_edit-cbo_projbudgettask_id'),
	chk_orderout_isunbudgetted: $('#pnl_edit-chk_orderout_isunbudgetted'),
	cbo_site_id: $('#pnl_edit-cbo_site_id'),
	cbo_user_dept_id: $('#pnl_edit-cbo_user_dept_id'),
	cbo_recv_dept_id: $('#pnl_edit-cbo_recv_dept_id'),
	txt_deliver_siteaddress: $('#pnl_edit-txt_deliver_siteaddress'),
	txt_deliver_city: $('#pnl_edit-txt_deliver_city'),
	txt_deliver_upname: $('#pnl_edit-txt_deliver_upname'),
	txt_deliver_uptelp: $('#pnl_edit-txt_deliver_uptelp'),
	cbo_inquiry_id: $('#pnl_edit-cbo_inquiry_id'),
	chk_orderout_ismultirequest: $('#pnl_edit-chk_orderout_ismultirequest'),
	txt_inquirymodel_id: $('#pnl_edit-txt_inquirymodel_id'),
	txt_inquiryselect_id: $('#pnl_edit-txt_inquiryselect_id'),
	txt_itemmanage_id: $('#pnl_edit-txt_itemmanage_id'),
	txt_owner_dept_id: $('#pnl_edit-txt_owner_dept_id'),
	txt_orderout_dept_id: $('#pnl_edit-txt_orderout_dept_id'),
	cbo_doc_id: $('#pnl_edit-cbo_doc_id'),
	cbo_ordermodel_id: $('#pnl_edit-cbo_ordermodel_id'),
	txt_orderout_version: $('#pnl_edit-txt_orderout_version'),
	chk_orderout_isdateinterval: $('#pnl_edit-chk_orderout_isdateinterval'),
	chk_orderout_iscommit: $('#pnl_edit-chk_orderout_iscommit'),
	txt_orderout_commitby: $('#pnl_edit-txt_orderout_commitby'),
	txt_orderout_commitdate: $('#pnl_edit-txt_orderout_commitdate'),
	chk_orderout_isapprovalprogress: $('#pnl_edit-chk_orderout_isapprovalprogress'),
	chk_orderout_isapproved: $('#pnl_edit-chk_orderout_isapproved'),
	txt_orderout_approveby: $('#pnl_edit-txt_orderout_approveby'),
	txt_orderout_approvedate: $('#pnl_edit-txt_orderout_approvedate'),
	chk_orderout_isdeclined: $('#pnl_edit-chk_orderout_isdeclined'),
	txt_orderout_declineby: $('#pnl_edit-txt_orderout_declineby'),
	txt_orderout_declinedate: $('#pnl_edit-txt_orderout_declinedate'),
	chk_orderout_isclose: $('#pnl_edit-chk_orderout_isclose'),
	txt_orderout_closeby: $('#pnl_edit-txt_orderout_closeby'),
	txt_orderout_closedate: $('#pnl_edit-txt_orderout_closedate'),
	chk_orderout_isadvance: $('#pnl_edit-chk_orderout_isadvance'),
	chk_orderout_isautogenerated: $('#pnl_edit-chk_orderout_isautogenerated'),
	chk_orderout_isitemdeptuser: $('#pnl_edit-chk_orderout_isitemdeptuser'),
	chk_orderout_isitemdeptowner: $('#pnl_edit-chk_orderout_isitemdeptowner')
}


const rec_commitby = $('#pnl_edit_record-commitby');
const rec_commitdate = $('#pnl_edit_record-commitdate');		
		
const rec_approveby = $('#pnl_edit_record-approveby');
const rec_approvedate = $('#pnl_edit_record-approvedate');			
const rec_declineby = $('#pnl_edit_record-declineby');
const rec_declinedate = $('#pnl_edit_record-declinedate');			
			


let form;
let rowdata;

export async function init(opt) {
	this_page_id = opt.id;
	this_page_options = opt;

	txt_caption.template = txt_caption.html();
	var disableedit = false;


	form = new global.fgta4form(pnl_form, {
		primary: obj.txt_orderout_id,
		autoid: true,
		logview: 'trn_orderout',
		btn_edit: disableedit==true? $('<a>edit</a>') : btn_edit,
		btn_save: disableedit==true? $('<a>save</a>') : btn_save,
		btn_delete: disableedit==true? $('<a>delete</a>') : btn_delete,		
		objects : obj,
		OnDataSaving: async (data, options) => { await form_datasaving(data, options) },
		OnDataSaveError: async (data, options) => { await form_datasaveerror(data, options) },
		OnDataSaved: async (result, options) => {  await form_datasaved(result, options) },
		OnDataDeleting: async (data, options) => { await form_deleting(data, options) },
		OnDataDeleted: async (result, options) => { await form_deleted(result, options) },
		OnIdSetup : (options) => { form_idsetup(options) },
		OnViewModeChanged : (viewonly) => { form_viewmodechanged(viewonly) },
		OnRecordStatusCreated: () => {
			
		$('#pnl_edit_record_custom').detach().appendTo("#pnl_edit_record");
		$('#pnl_edit_record_custom').show();		
					
		}		
	});
	form.getHeaderData = () => {
		return getHeaderData();
	}


	btn_print.linkbutton({ onClick: () => { btn_print_click(); } });	
	


	btn_commit.linkbutton({ onClick: async () => { 
		var args = { action: 'commit', cancel: false, options: {}};
		if (typeof hnd.action_starting === 'function') {
			await hnd.action_starting(args);
		}
		if (args.cancel) {
			if (typeof args.cancelShowMessage === 'function') { args.cancelShowMessage(); }
			return;
		}
		btn_action_click({ action: args.action, options: args.options }); 
	} });

	btn_uncommit.linkbutton({ onClick: async () => { 
		var args = { action: 'uncommit', cancel: false, options: {}};
		if (typeof hnd.action_starting === 'function') {
			await hnd.action_starting(args);
		}
		if (args.cancel) {
			if (typeof args.cancelShowMessage === 'function') { args.cancelShowMessage(); }
			return;
		}
		btn_action_click({ action: args.action, options: args.options }); 
	} });

			


	btn_approve.linkbutton({ onClick: async () => { 
		var args = { action: 'approve', cancel: false, options: {}};
		if (typeof hnd.action_starting === 'function') {
			await hnd.action_starting(args);
		}
		if (args.cancel) {
			if (typeof args.cancelShowMessage === 'function') { args.cancelShowMessage(); }
			return;
		}
		btn_action_click({ action: args.action, options: args.options }); 
	} });

	btn_decline.linkbutton({ onClick: async () => {
		var args = { action: 'decline', cancel: false, options: {}};
		if (typeof hnd.action_starting === 'function') {
			await hnd.action_starting(args);
		}
		if (args.cancel) {
			if (typeof args.cancelShowMessage === 'function') { args.cancelShowMessage(); }
			return;
		}
		var id = 'pnl_edit-reason_' + Date.now().toString();
		$ui.ShowMessage(`
			<div style="display: block;  margin-bottom: 10px">
				<div style="font-weight: bold; margin-bottom: 10px">Reason</div>
				<div">
					<input id="${id}" class="easyui-textbox" style="width: 300px; height: 60px;" data-options="multiline: true">
				</div>
			</div>
		`, {
			'Decline': () => {
				var txt = window.parent.document.getElementById(id);
				var reason = txt.value;
				btn_action_click({ action: args.action, options: args.options, reason: reason }); 
			},
			'Cancel': () => {
			} 
		}, ()=>{
			var txt = window.parent.document.getElementById(id);
			txt.placeholder = 'type your decline reason';
			txt.maxLength = 255;
			txt.classList.add('declinereasonbox');
			txt.addEventListener('keyup', (ev)=>{
				if (ev.key=='Enter') {
					ev.stopPropagation();
				}
			});
			txt.focus();
		})
	}});				
				
	// Generator: Xtion Handler not exist
	// Generator: Object Handler not exist

	// Generator: Upload Handler not exist


	obj.cbo_unit_id.name = 'pnl_edit-cbo_unit_id'		
	new fgta4slideselect(obj.cbo_unit_id, {
		title: 'Pilih Unit',
		returnpage: this_page_id,
		api: $ui.apis.load_unit_id,
		fieldValue: 'unit_id',
		fieldDisplay: 'unit_name',
		fields: [
			{mapping: 'unit_id', text: 'unit_id'},
			{mapping: 'unit_name', text: 'unit_name'}
		],

	})				
				
	obj.cbo_request_id.name = 'pnl_edit-cbo_request_id'		
	new fgta4slideselect(obj.cbo_request_id, {
		title: 'Pilih request_id',
		returnpage: this_page_id,
		api: $ui.apis.load_request_id,
		fieldValue: 'request_id',
		fieldDisplay: 'request_descr',
		fields: [
			{mapping: 'request_id', text: 'request_id'},
			{mapping: 'request_descr', text: 'request_descr'}
		],

	})				
				
	obj.cbo_inquirytype_id.name = 'pnl_edit-cbo_inquirytype_id'		
	new fgta4slideselect(obj.cbo_inquirytype_id, {
		title: 'Pilih inquirytype_id',
		returnpage: this_page_id,
		api: $ui.apis.load_inquirytype_id,
		fieldValue: 'inquirytype_id',
		fieldDisplay: 'inquirytype_name',
		fields: [
			{mapping: 'inquirytype_id', text: 'inquirytype_id'},
			{mapping: 'inquirytype_name', text: 'inquirytype_name'}
		],

	})				
				
	obj.cbo_trxmodel_id.name = 'pnl_edit-cbo_trxmodel_id'		
	new fgta4slideselect(obj.cbo_trxmodel_id, {
		title: 'Pilih trxmodel_id',
		returnpage: this_page_id,
		api: $ui.apis.load_trxmodel_id,
		fieldValue: 'trxmodel_id',
		fieldDisplay: 'trxmodel_name',
		fields: [
			{mapping: 'trxmodel_id', text: 'trxmodel_id'},
			{mapping: 'trxmodel_name', text: 'trxmodel_name'}
		],

	})				
				
	obj.cbo_request_dept_id.name = 'pnl_edit-cbo_request_dept_id'		
	new fgta4slideselect(obj.cbo_request_dept_id, {
		title: 'Pilih request_dept_id',
		returnpage: this_page_id,
		api: $ui.apis.load_request_dept_id,
		fieldValue: 'request_dept_id',
		fieldDisplay: 'request_dept_name',
		fieldValueMap: 'dept_id',
		fieldDisplayMap: 'dept_name',
		fields: [
			{mapping: 'dept_id', text: 'dept_id'},
			{mapping: 'dept_name', text: 'dept_name'}
		],

	})				
				
	obj.cbo_curr_id.name = 'pnl_edit-cbo_curr_id'		
	new fgta4slideselect(obj.cbo_curr_id, {
		title: 'Pilih curr_id',
		returnpage: this_page_id,
		api: $ui.apis.load_curr_id,
		fieldValue: 'curr_id',
		fieldDisplay: 'curr_name',
		fields: [
			{mapping: 'curr_id', text: 'curr_id'},
			{mapping: 'curr_name', text: 'curr_name'}
		],

	})				
				
	obj.cbo_ppn_taxtype_id.name = 'pnl_edit-cbo_ppn_taxtype_id'		
	new fgta4slideselect(obj.cbo_ppn_taxtype_id, {
		title: 'Pilih ppn_taxtype_id',
		returnpage: this_page_id,
		api: $ui.apis.load_ppn_taxtype_id,
		fieldValue: 'ppn_taxtype_id',
		fieldDisplay: 'ppn_taxtype_name',
		fieldValueMap: 'taxtype_id',
		fieldDisplayMap: 'taxtype_name',
		fields: [
			{mapping: 'taxtype_id', text: 'taxtype_id'},
			{mapping: 'taxtype_name', text: 'taxtype_name'}
		],

	})				
				
	obj.cbo_pph_taxtype_id.name = 'pnl_edit-cbo_pph_taxtype_id'		
	new fgta4slideselect(obj.cbo_pph_taxtype_id, {
		title: 'Pilih pph_taxtype_id',
		returnpage: this_page_id,
		api: $ui.apis.load_pph_taxtype_id,
		fieldValue: 'pph_taxtype_id',
		fieldDisplay: 'pph_taxtype_name',
		fieldValueMap: 'taxtype_id',
		fieldDisplayMap: 'taxtype_name',
		fields: [
			{mapping: 'taxtype_id', text: 'taxtype_id'},
			{mapping: 'taxtype_name', text: 'taxtype_name'}
		],

	})				
				
	obj.cbo_partner_id.name = 'pnl_edit-cbo_partner_id'		
	new fgta4slideselect(obj.cbo_partner_id, {
		title: 'Pilih partner_id',
		returnpage: this_page_id,
		api: $ui.apis.load_partner_id,
		fieldValue: 'partner_id',
		fieldDisplay: 'partner_name',
		fields: [
			{mapping: 'partner_id', text: 'partner_id'},
			{mapping: 'partner_name', text: 'partner_name'}
		],

	})				
				
	obj.cbo_ordercontract_id.name = 'pnl_edit-cbo_ordercontract_id'		
	new fgta4slideselect(obj.cbo_ordercontract_id, {
		title: 'Pilih ordercontract_id',
		returnpage: this_page_id,
		api: $ui.apis.load_ordercontract_id,
		fieldValue: 'ordercontract_id',
		fieldDisplay: 'ordercontract_descr',
		fields: [
			{mapping: 'ordercontract_id', text: 'ordercontract_id'},
			{mapping: 'ordercontract_descr', text: 'ordercontract_descr'}
		],

	})				
				
	obj.cbo_paymtype_id.name = 'pnl_edit-cbo_paymtype_id'		
	new fgta4slideselect(obj.cbo_paymtype_id, {
		title: 'Pilih paymtype_id',
		returnpage: this_page_id,
		api: $ui.apis.load_paymtype_id,
		fieldValue: 'paymtype_id',
		fieldDisplay: 'paymtype_name',
		fields: [
			{mapping: 'paymtype_id', text: 'paymtype_id'},
			{mapping: 'paymtype_name', text: 'paymtype_name'}
		],

	})				
				
	obj.cbo_partnerbank_id.name = 'pnl_edit-cbo_partnerbank_id'		
	new fgta4slideselect(obj.cbo_partnerbank_id, {
		title: 'Pilih partnerbank_id',
		returnpage: this_page_id,
		api: $ui.apis.load_partnerbank_id,
		fieldValue: 'partnerbank_id',
		fieldDisplay: 'partnerbank_accnum',
		fields: [
			{mapping: 'partnerbank_id', text: 'partnerbank_id'},
			{mapping: 'partnerbank_accnum', text: 'partnerbank_accnum'}
		],

	})				
				
	obj.cbo_partnercontact_id.name = 'pnl_edit-cbo_partnercontact_id'		
	new fgta4slideselect(obj.cbo_partnercontact_id, {
		title: 'Pilih partnercontact_id',
		returnpage: this_page_id,
		api: $ui.apis.load_partnercontact_id,
		fieldValue: 'partnercontact_id',
		fieldDisplay: 'partnercontact_name',
		fields: [
			{mapping: 'partnercontact_id', text: 'partnercontact_id'},
			{mapping: 'partnercontact_name', text: 'partnercontact_name'}
		],

	})				
				
	obj.cbo_project_id.name = 'pnl_edit-cbo_project_id'		
	new fgta4slideselect(obj.cbo_project_id, {
		title: 'Pilih project_id',
		returnpage: this_page_id,
		api: $ui.apis.load_project_id,
		fieldValue: 'project_id',
		fieldDisplay: 'project_name',
		fields: [
			{mapping: 'project_id', text: 'project_id'},
			{mapping: 'project_name', text: 'project_name'}
		],

	})				
				
	obj.cbo_projecttask_id.name = 'pnl_edit-cbo_projecttask_id'		
	new fgta4slideselect(obj.cbo_projecttask_id, {
		title: 'Pilih projecttask_id',
		returnpage: this_page_id,
		api: $ui.apis.load_projecttask_id,
		fieldValue: 'projecttask_id',
		fieldDisplay: 'projecttask_name',
		fields: [
			{mapping: 'projecttask_id', text: 'projecttask_id'},
			{mapping: 'projecttask_name', text: 'projecttask_name'}
		],

	})				
				
	obj.cbo_projbudget_id.name = 'pnl_edit-cbo_projbudget_id'		
	new fgta4slideselect(obj.cbo_projbudget_id, {
		title: 'Pilih projbudget_id',
		returnpage: this_page_id,
		api: $ui.apis.load_projbudget_id,
		fieldValue: 'projbudget_id',
		fieldDisplay: 'projbudget_name',
		fields: [
			{mapping: 'projbudget_id', text: 'projbudget_id'},
			{mapping: 'projbudget_name', text: 'projbudget_name'}
		],

	})				
				
	obj.cbo_projbudgettask_id.name = 'pnl_edit-cbo_projbudgettask_id'		
	new fgta4slideselect(obj.cbo_projbudgettask_id, {
		title: 'Pilih projbudgettask_id',
		returnpage: this_page_id,
		api: $ui.apis.load_projbudgettask_id,
		fieldValue: 'projbudgettask_id',
		fieldDisplay: 'projecttask_name',
		fields: [
			{mapping: 'projbudgettask_id', text: 'projbudgettask_id'},
			{mapping: 'projecttask_name', text: 'projecttask_name'}
		],

	})				
				
	obj.cbo_site_id.name = 'pnl_edit-cbo_site_id'		
	new fgta4slideselect(obj.cbo_site_id, {
		title: 'Pilih site_id',
		returnpage: this_page_id,
		api: $ui.apis.load_site_id,
		fieldValue: 'site_id',
		fieldDisplay: 'site_name',
		fields: [
			{mapping: 'site_id', text: 'site_id'},
			{mapping: 'site_name', text: 'site_name'}
		],

	})				
				
	obj.cbo_user_dept_id.name = 'pnl_edit-cbo_user_dept_id'		
	new fgta4slideselect(obj.cbo_user_dept_id, {
		title: 'Pilih user_dept_id',
		returnpage: this_page_id,
		api: $ui.apis.load_user_dept_id,
		fieldValue: 'user_dept_id',
		fieldDisplay: 'user_dept_name',
		fieldValueMap: 'dept_id',
		fieldDisplayMap: 'dept_name',
		fields: [
			{mapping: 'dept_id', text: 'dept_id'},
			{mapping: 'dept_name', text: 'dept_name'}
		],

	})				
				
	obj.cbo_recv_dept_id.name = 'pnl_edit-cbo_recv_dept_id'		
	new fgta4slideselect(obj.cbo_recv_dept_id, {
		title: 'Pilih recv_dept_id',
		returnpage: this_page_id,
		api: $ui.apis.load_recv_dept_id,
		fieldValue: 'recv_dept_id',
		fieldDisplay: 'recv_dept_name',
		fieldValueMap: 'dept_id',
		fieldDisplayMap: 'dept_name',
		fields: [
			{mapping: 'dept_id', text: 'dept_id'},
			{mapping: 'dept_name', text: 'dept_name'}
		],

	})				
				
	obj.cbo_inquiry_id.name = 'pnl_edit-cbo_inquiry_id'		
	new fgta4slideselect(obj.cbo_inquiry_id, {
		title: 'Pilih inquiry_id',
		returnpage: this_page_id,
		api: $ui.apis.load_inquiry_id,
		fieldValue: 'inquiry_id',
		fieldDisplay: 'inquiry_descr',
		fields: [
			{mapping: 'inquiry_id', text: 'inquiry_id'},
			{mapping: 'inquiry_descr', text: 'inquiry_descr'}
		],

	})				
				
	obj.cbo_doc_id.name = 'pnl_edit-cbo_doc_id'		
	new fgta4slideselect(obj.cbo_doc_id, {
		title: 'Pilih doc_id',
		returnpage: this_page_id,
		api: $ui.apis.load_doc_id,
		fieldValue: 'doc_id',
		fieldDisplay: 'doc_name',
		fields: [
			{mapping: 'doc_id', text: 'doc_id'},
			{mapping: 'doc_name', text: 'doc_name'}
		],

	})				
				
	obj.cbo_ordermodel_id.name = 'pnl_edit-cbo_ordermodel_id'		
	new fgta4slideselect(obj.cbo_ordermodel_id, {
		title: 'Pilih ordermodel_id',
		returnpage: this_page_id,
		api: $ui.apis.load_ordermodel_id,
		fieldValue: 'ordermodel_id',
		fieldDisplay: 'ordermodel_name',
		fields: [
			{mapping: 'ordermodel_id', text: 'ordermodel_id'},
			{mapping: 'ordermodel_name', text: 'ordermodel_name'}
		],

	})				
				




	document.addEventListener('keydown', (ev)=>{
		if ($ui.getPages().getCurrentPage()==this_page_id) {
			if (ev.code=='KeyS' && ev.ctrlKey==true) {
				if (!form.isInViewMode()) {
					form.btn_save_click();
				}
				ev.stopPropagation()
				ev.preventDefault()
			}
		}
	}, true)
	
	document.addEventListener('OnSizeRecalculated', (ev) => {
		OnSizeRecalculated(ev.detail.width, ev.detail.height)
	})	

	document.addEventListener('OnButtonBack', (ev) => {
		var element = document.activeElement;
		element.blur();
		if ($ui.getPages().getCurrentPage()==this_page_id) {
			ev.detail.cancel = true;
			if (form.isDataChanged()) {
				form.canceledit(()=>{
					$ui.getPages().show('pnl_list', ()=>{
						form.setViewMode()
						$ui.getPages().ITEMS['pnl_list'].handler.scrolllast()
					})
				})
			} else {
				$ui.getPages().show('pnl_list', ()=>{
					form.setViewMode()
					$ui.getPages().ITEMS['pnl_list'].handler.scrolllast()
				})
			}
		
		}
	})

	document.addEventListener('OnButtonHome', (ev) => {
		if ($ui.getPages().getCurrentPage()==this_page_id) {
			if (form.isDataChanged()) {
				ev.detail.cancel = true;
				$ui.ShowMessage('Anda masih dalam mode edit dengan pending data, silakan matikan mode edit untuk kembali ke halaman utama.')
			}
		}
	})

	//button state
	if (typeof hnd.init==='function') {
		hnd.init({
			form: form,
			obj: obj,
			opt: opt,
			btn_action_click: (actionargs) => {
				if (typeof btn_action_click == 'function') {
					btn_action_click(actionargs);
				}
			}
		})
	}

}

export function OnSizeRecalculated(width, height) {
}

export function getForm() {
	return form
}

export function getCurrentRowdata() {
	return rowdata;
}

export function open(data, rowid, viewmode=true, fn_callback) {

	var caption = txt_caption.template;
	caption = caption.replace('{{STATE_BEG}}', '');
	caption = caption.replace('{{STATE_END}}', ' View');
	txt_caption.html(caption);


	rowdata = {
		data: data,
		rowid: rowid
	}

	var pOpt = form.getDefaultPrompt(false)
	var fn_dataopening = async (options) => {
		options.criteria[form.primary.mapping] = data[form.primary.mapping]
	}

	var fn_dataopened = async (result, options) => {
		var record = result.record;
		updatefilebox(record);

		/*
		if (result.record.unit_id==null) { result.record.unit_id='--NULL--'; result.record.unit_name='NONE'; }
		if (result.record.request_id==null) { result.record.request_id='--NULL--'; result.record.request_descr='NONE'; }
		if (result.record.ppn_taxtype_id==null) { result.record.ppn_taxtype_id='--NULL--'; result.record.ppn_taxtype_name='NONE'; }
		if (result.record.pph_taxtype_id==null) { result.record.pph_taxtype_id='--NULL--'; result.record.pph_taxtype_name='NONE'; }
		if (result.record.ordercontract_id==null) { result.record.ordercontract_id='--NULL--'; result.record.ordercontract_descr='NONE'; }
		if (result.record.partnerbank_id==null) { result.record.partnerbank_id='--NULL--'; result.record.partnerbank_accnum='NONE'; }
		if (result.record.partnercontact_id==null) { result.record.partnercontact_id='--NULL--'; result.record.partnercontact_name='NONE'; }
		if (result.record.project_id==null) { result.record.project_id='--NULL--'; result.record.project_name='NONE'; }
		if (result.record.projecttask_id==null) { result.record.projecttask_id='--NULL--'; result.record.projecttask_name='NONE'; }
		if (result.record.projbudget_id==null) { result.record.projbudget_id='--NULL--'; result.record.projbudget_name='NONE'; }
		if (result.record.projbudgettask_id==null) { result.record.projbudgettask_id='--NULL--'; result.record.projecttask_name='NONE'; }
		if (result.record.user_dept_id==null) { result.record.user_dept_id='--NULL--'; result.record.user_dept_name='NONE'; }
		if (result.record.inquiry_id==null) { result.record.inquiry_id='--NULL--'; result.record.inquiry_descr='NONE'; }

		*/
		for (var objid in obj) {
			let o = obj[objid]
			if (o.isCombo() && !o.isRequired()) {
				var value =  result.record[o.getFieldValueName()];
				if (value==null ) {
					record[o.getFieldValueName()] = pOpt.value;
					record[o.getFieldDisplayName()] = pOpt.text;
				}
			}
		}
  		updaterecordstatus(record)

		/* handle data saat opening data */   
		if (typeof hnd.form_dataopening == 'function') {
			hnd.form_dataopening(result, options);
		}


		form.SuspendEvent(true);
		form
			.fill(record)
			.setValue(obj.cbo_unit_id, record.unit_id, record.unit_name)
			.setValue(obj.cbo_request_id, record.request_id, record.request_descr)
			.setValue(obj.cbo_inquirytype_id, record.inquirytype_id, record.inquirytype_name)
			.setValue(obj.cbo_trxmodel_id, record.trxmodel_id, record.trxmodel_name)
			.setValue(obj.cbo_request_dept_id, record.request_dept_id, record.request_dept_name)
			.setValue(obj.cbo_curr_id, record.curr_id, record.curr_name)
			.setValue(obj.cbo_ppn_taxtype_id, record.ppn_taxtype_id, record.ppn_taxtype_name)
			.setValue(obj.cbo_pph_taxtype_id, record.pph_taxtype_id, record.pph_taxtype_name)
			.setValue(obj.cbo_partner_id, record.partner_id, record.partner_name)
			.setValue(obj.cbo_ordercontract_id, record.ordercontract_id, record.ordercontract_descr)
			.setValue(obj.cbo_paymtype_id, record.paymtype_id, record.paymtype_name)
			.setValue(obj.cbo_partnerbank_id, record.partnerbank_id, record.partnerbank_accnum)
			.setValue(obj.cbo_partnercontact_id, record.partnercontact_id, record.partnercontact_name)
			.setValue(obj.cbo_project_id, record.project_id, record.project_name)
			.setValue(obj.cbo_projecttask_id, record.projecttask_id, record.projecttask_name)
			.setValue(obj.cbo_projbudget_id, record.projbudget_id, record.projbudget_name)
			.setValue(obj.cbo_projbudgettask_id, record.projbudgettask_id, record.projecttask_name)
			.setValue(obj.cbo_site_id, record.site_id, record.site_name)
			.setValue(obj.cbo_user_dept_id, record.user_dept_id, record.user_dept_name)
			.setValue(obj.cbo_recv_dept_id, record.recv_dept_id, record.recv_dept_name)
			.setValue(obj.cbo_inquiry_id, record.inquiry_id, record.inquiry_descr)
			.setValue(obj.cbo_doc_id, record.doc_id, record.doc_name)
			.setValue(obj.cbo_ordermodel_id, record.ordermodel_id, record.ordermodel_name)
			.setViewMode(viewmode)
			.lock(false)
			.rowid = rowid


		/* tambahkan event atau behaviour saat form dibuka
		   apabila ada rutin mengubah form dan tidak mau dijalankan pada saat opening,
		   cek dengan form.isEventSuspended()
		*/   
		if (typeof hnd.form_dataopened == 'function') {
			hnd.form_dataopened(result, options);
		}


		/* commit form */
		form.commit()
		form.SuspendEvent(false); 
		updatebuttonstate(record)


		/* update rowdata */
		for (var nv in rowdata.data) {
			if (record[nv]!=undefined) {
				rowdata.data[nv] = record[nv];
			}
		}

		// tampilkan form untuk data editor
		if (typeof fn_callback==='function') {
			fn_callback(null, rowdata.data);
		}
		
	}

	var fn_dataopenerror = (err) => {
		$ui.ShowMessage('[ERROR]'+err.errormessage);
	}

	form.dataload(fn_dataopening, fn_dataopened, fn_dataopenerror)
	
}


export function createnew() {

	var caption = txt_caption.template;
	caption = caption.replace('{{STATE_BEG}}', 'Create New ');
	caption = caption.replace('{{STATE_END}}', '');
	txt_caption.html(caption);


	form.createnew(async (data, options)=>{
		// console.log(data)
		// console.log(options)
		form.rowid = null

		// set nilai-nilai default untuk form
		data.orderout_isunref = '0'
		data.orderout_dtstart = global.now()
		data.orderout_dtend = global.now()
		data.curr_rate = 0
		data.orderout_isunbudgetted = '0'
		data.orderout_ismultirequest = '0'
		data.orderout_version = 0
		data.orderout_isdateinterval = '0'
		data.orderout_iscommit = '0'
		data.orderout_isapprovalprogress = '0'
		data.orderout_isapproved = '0'
		data.orderout_isdeclined = '0'
		data.orderout_isclose = '0'
		data.orderout_isadvance = '0'
		data.orderout_isautogenerated = '0'
		data.orderout_isitemdeptuser = '0'
		data.orderout_isitemdeptowner = '0'

		data.unit_id = '--NULL--'
		data.unit_name = 'NONE'
		data.request_id = '--NULL--'
		data.request_descr = 'NONE'
		data.inquirytype_id = '0'
		data.inquirytype_name = '-- PILIH --'
		data.trxmodel_id = '0'
		data.trxmodel_name = '-- PILIH --'
		data.request_dept_id = '0'
		data.request_dept_name = '-- PILIH --'
		data.curr_id = '0'
		data.curr_name = '-- PILIH --'
		data.ppn_taxtype_id = '--NULL--'
		data.ppn_taxtype_name = 'NONE'
		data.pph_taxtype_id = '--NULL--'
		data.pph_taxtype_name = 'NONE'
		data.partner_id = '0'
		data.partner_name = '-- PILIH --'
		data.ordercontract_id = '--NULL--'
		data.ordercontract_descr = 'NONE'
		data.paymtype_id = '0'
		data.paymtype_name = '-- PILIH --'
		data.partnerbank_id = '--NULL--'
		data.partnerbank_accnum = 'NONE'
		data.partnercontact_id = '--NULL--'
		data.partnercontact_name = 'NONE'
		data.project_id = '--NULL--'
		data.project_name = 'NONE'
		data.projecttask_id = '--NULL--'
		data.projecttask_name = 'NONE'
		data.projbudget_id = '--NULL--'
		data.projbudget_name = 'NONE'
		data.projbudgettask_id = '--NULL--'
		data.projecttask_name = 'NONE'
		data.site_id = '0'
		data.site_name = '-- PILIH --'
		data.user_dept_id = '--NULL--'
		data.user_dept_name = 'NONE'
		data.recv_dept_id = '0'
		data.recv_dept_name = '-- PILIH --'
		data.inquiry_id = '--NULL--'
		data.inquiry_descr = 'NONE'
		data.doc_id = global.setup.doc_id
		data.doc_name = global.setup.doc_id
		data.ordermodel_id = '0'
		data.ordermodel_name = '-- PILIH --'

		if (typeof hnd.form_newdata == 'function') {
			// untuk mengambil nilai ui component,
			// di dalam handler form_newdata, gunakan perintah:
			// options.OnNewData = () => {
			// 		...
			// }		
			hnd.form_newdata(data, options);
		}

		rec_commitby.html('');
		rec_commitdate.html('');
		
		rec_approveby.html('');
		rec_approvedate.html('');
		rec_declineby.html('');
		rec_declinedate.html('');
		


		var button_commit_on = true;
		var button_uncommit_on = false;
		var button_approve_on = false;
		var button_decline_on = false;
		btn_commit.linkbutton(button_commit_on ? 'enable' : 'disable');
		btn_uncommit.linkbutton(button_uncommit_on ? 'enable' : 'disable');
		btn_approve.linkbutton(button_approve_on ? 'enable' : 'disable');
		btn_decline.linkbutton(button_decline_on ? 'enable' : 'disable');
			

		options.OnCanceled = () => {
			$ui.getPages().show('pnl_list')
		}

		$ui.getPages().ITEMS['pnl_edititemsgrid'].handler.createnew(data, options)
		$ui.getPages().ITEMS['pnl_editfilesgrid'].handler.createnew(data, options)
		$ui.getPages().ITEMS['pnl_editapprovalgrid'].handler.createnew(data, options)


	})
}


export function getHeaderData() {
	var header_data = form.getData();
	if (typeof hnd.form_getHeaderData == 'function') {
		hnd.form_getHeaderData(header_data);
	}
	return header_data;
}

export function detil_open(pnlname) {
	if (form.isDataChanged()) {
		$ui.ShowMessage('Simpan dulu perubahan datanya.')
		return;
	}

	//$ui.getPages().show(pnlname)
	let header_data = getHeaderData();
	if (typeof hnd.form_detil_opening == 'function') {
		hnd.form_detil_opening(pnlname, (cancel)=>{
			if (cancel===true) {
				return;
			}
			$ui.getPages().show(pnlname, () => {
				$ui.getPages().ITEMS[pnlname].handler.OpenDetil(header_data)
			})
		});
	} else {
		$ui.getPages().show(pnlname, () => {
			$ui.getPages().ITEMS[pnlname].handler.OpenDetil(header_data)
		})
	}

	
}


function updatefilebox(record) {
	// apabila ada keperluan untuk menampilkan data dari object storage


	if (typeof hnd.form_updatefilebox == 'function') {
		hnd.form_updatefilebox(record);
	}
}

function updaterecordstatus(record) {
	// apabila ada keperluan untuk update status record di sini

	rec_commitby.html(record.orderout_commitby);
	rec_commitdate.html(record.orderout_commitdate);
		
	rec_approveby.html(record.orderout_approveby);
	rec_approvedate.html(record.orderout_approvedate);
	rec_declineby.html(record.orderout_declineby);
	rec_declinedate.html(record.orderout_declinedate);
			

	if (typeof hnd.form_updaterecordstatus == 'function') {
		hnd.form_updaterecordstatus(record);
	}
}

function updatebuttonstate(record) {
	// apabila ada keperluan untuk update state action button di sini

	/* action button */
	var button_commit_on = false;
	var button_uncommit_on = false;
	var button_approve_on = false;
	var button_decline_on = false;

	
	if (record.orderout_isfirm=="1") {
		button_commit_on = false;
		button_uncommit_on = false;
		button_approve_on = false;
		button_decline_on = false;
		form.lock(true);	
	} else if (record.orderout_isdeclined=="1" || record.orderout_isuseralreadydeclined=="1") {
		button_commit_on = false;
		button_uncommit_on = true;
		button_approve_on = true;
		button_decline_on = false;
		form.lock(true);	
	} else if (record.orderout_isapproved=="1" || record.orderout_isuseralreadyapproved=="1") {
		button_commit_on = false;
		button_uncommit_on = false;
		button_approve_on = false;
		button_decline_on = true;	
		form.lock(true);	
	} else if (record.orderout_isapprovalprogress=="1") {
		button_commit_on = false;
		button_uncommit_on = false;
		button_approve_on = true;
		button_decline_on = true;
		form.lock(true);	
	} else if (record.orderout_iscommit=="1") {
		button_commit_on = false;
		button_uncommit_on = true;
		button_approve_on = true;
		button_decline_on = true;
		form.lock(true);		
	} else {
		button_commit_on = true;
		button_uncommit_on = false;
		button_approve_on = false;
		button_decline_on = false;
		form.lock(false);
	} 

	btn_commit.linkbutton(button_commit_on ? 'enable' : 'disable');
	btn_uncommit.linkbutton(button_uncommit_on ? 'enable' : 'disable');
	btn_approve.linkbutton(button_approve_on ? 'enable' : 'disable');
	btn_decline.linkbutton(button_decline_on ? 'enable' : 'disable');		
			

	if (typeof hnd.form_updatebuttonstate == 'function') {
		hnd.form_updatebuttonstate(record);
	}
}

function updategridstate(record) {
	var updategriddata = {}

	// apabila ada keperluan untuk update state grid list di sini

	var col_commit = 'orderout_iscommit';
	updategriddata[col_commit] = record.orderout_iscommit;	
	
	var col_approveprogress = 'orderout_isapprovalprogress';
	var col_approve = 'orderout_isapprove'
	var col_decline = "orderout_isdeclined"
	updategriddata[col_approveprogress] = record.orderout_isapprovalprogress;
	updategriddata[col_approve] = record.orderout_isapproved;
	updategriddata[col_decline] = record.orderout_isdeclined;				
			

	if (typeof hnd.form_updategridstate == 'function') {
		hnd.form_updategridstate(updategriddata, record);
	}

	$ui.getPages().ITEMS['pnl_list'].handler.updategrid(updategriddata, form.rowid);

}

function form_viewmodechanged(viewmode) {

	var caption = txt_caption.template;
	if (viewmode) {
		caption = caption.replace('{{STATE_BEG}}', '');
		caption = caption.replace('{{STATE_END}}', ' View');
	} else {
		caption = caption.replace('{{STATE_BEG}}', '');
		caption = caption.replace('{{STATE_END}}', ' Edit');
	}
	txt_caption.html(caption);


	var OnViewModeChangedEvent = new CustomEvent('OnViewModeChanged', {detail: {}})
	$ui.triggerevent(OnViewModeChangedEvent, {
		viewmode: viewmode
	})
}

function form_idsetup(options) {
	var objid = obj.txt_orderout_id
	switch (options.action) {
		case 'fill' :
			objid.textbox('disable') 
			break;

		case 'createnew' :
			// console.log('new')
			if (form.autoid) {
				objid.textbox('disable') 
				objid.textbox('setText', '[AUTO]') 
			} else {
				objid.textbox('enable') 
			}
			break;
			
		case 'save' :
			objid.textbox('disable') 
			break;	
	}
}


async function form_datasaving(data, options) {
	// cek dulu data yang akan disimpan,
	// apabila belum sesuai dengan yang diharuskan, batalkan penyimpanan
	//    options.cancel = true

	// Modifikasi object data, apabila ingin menambahkan variabel yang akan dikirim ke server
	// options.skipmappingresponse = ['unit_id', 'request_id', 'ppn_taxtype_id', 'pph_taxtype_id', 'ordercontract_id', 'partnerbank_id', 'partnercontact_id', 'project_id', 'projecttask_id', 'projbudget_id', 'projbudgettask_id', 'user_dept_id', 'inquiry_id', ];
	options.skipmappingresponse = [];
	for (var objid in obj) {
		var o = obj[objid]
		if (o.isCombo() && !o.isRequired()) {
			var id = o.getFieldValueName()
			options.skipmappingresponse.push(id)
			// console.log(id)
		}
	}

	if (typeof hnd.form_datasaving == 'function') {
		hnd.form_datasaving(data, options);
	}

}

async function form_datasaveerror(err, options) {
	// apabila mau olah error messagenya
	// $ui.ShowMessage(err.errormessage)
	console.error(err)
	if (typeof hnd.form_datasaveerror == 'function') {
		hnd.form_datasaveerror(err, options);
	}
	if (options.supress_error_dialog!=true) {
		$ui.ShowMessage('[ERROR]'+err.message);
	}

}


async function form_datasaved(result, options) {
	// Apabila tidak mau munculkan dialog
	// options.suppressdialog = true

	// Apabila ingin mengganti message Data Tersimpan
	// options.savedmessage = 'Data sudah disimpan cuy!'

	// if (form.isNewData()) {
	// 	console.log('masukan ke grid')
	// 	$ui.getPages().ITEMS['pnl_list'].handler.updategrid(form.getData())
	// } else {
	// 	console.log('update grid')
	// }


	var data = {}
	Object.assign(data, form.getData(), result.dataresponse)
	/*
	form.setValue(obj.cbo_unit_id, result.dataresponse.unit_name!=='--NULL--' ? result.dataresponse.unit_id : '--NULL--', result.dataresponse.unit_name!=='--NULL--'?result.dataresponse.unit_name:'NONE')
	form.setValue(obj.cbo_request_id, result.dataresponse.request_descr!=='--NULL--' ? result.dataresponse.request_id : '--NULL--', result.dataresponse.request_descr!=='--NULL--'?result.dataresponse.request_descr:'NONE')
	form.setValue(obj.cbo_ppn_taxtype_id, result.dataresponse.ppn_taxtype_name!=='--NULL--' ? result.dataresponse.ppn_taxtype_id : '--NULL--', result.dataresponse.ppn_taxtype_name!=='--NULL--'?result.dataresponse.ppn_taxtype_name:'NONE')
	form.setValue(obj.cbo_pph_taxtype_id, result.dataresponse.pph_taxtype_name!=='--NULL--' ? result.dataresponse.pph_taxtype_id : '--NULL--', result.dataresponse.pph_taxtype_name!=='--NULL--'?result.dataresponse.pph_taxtype_name:'NONE')
	form.setValue(obj.cbo_ordercontract_id, result.dataresponse.ordercontract_descr!=='--NULL--' ? result.dataresponse.ordercontract_id : '--NULL--', result.dataresponse.ordercontract_descr!=='--NULL--'?result.dataresponse.ordercontract_descr:'NONE')
	form.setValue(obj.cbo_partnerbank_id, result.dataresponse.partnerbank_accnum!=='--NULL--' ? result.dataresponse.partnerbank_id : '--NULL--', result.dataresponse.partnerbank_accnum!=='--NULL--'?result.dataresponse.partnerbank_accnum:'NONE')
	form.setValue(obj.cbo_partnercontact_id, result.dataresponse.partnercontact_name!=='--NULL--' ? result.dataresponse.partnercontact_id : '--NULL--', result.dataresponse.partnercontact_name!=='--NULL--'?result.dataresponse.partnercontact_name:'NONE')
	form.setValue(obj.cbo_project_id, result.dataresponse.project_name!=='--NULL--' ? result.dataresponse.project_id : '--NULL--', result.dataresponse.project_name!=='--NULL--'?result.dataresponse.project_name:'NONE')
	form.setValue(obj.cbo_projecttask_id, result.dataresponse.projecttask_name!=='--NULL--' ? result.dataresponse.projecttask_id : '--NULL--', result.dataresponse.projecttask_name!=='--NULL--'?result.dataresponse.projecttask_name:'NONE')
	form.setValue(obj.cbo_projbudget_id, result.dataresponse.projbudget_name!=='--NULL--' ? result.dataresponse.projbudget_id : '--NULL--', result.dataresponse.projbudget_name!=='--NULL--'?result.dataresponse.projbudget_name:'NONE')
	form.setValue(obj.cbo_projbudgettask_id, result.dataresponse.projecttask_name!=='--NULL--' ? result.dataresponse.projbudgettask_id : '--NULL--', result.dataresponse.projecttask_name!=='--NULL--'?result.dataresponse.projecttask_name:'NONE')
	form.setValue(obj.cbo_user_dept_id, result.dataresponse.user_dept_name!=='--NULL--' ? result.dataresponse.user_dept_id : '--NULL--', result.dataresponse.user_dept_name!=='--NULL--'?result.dataresponse.user_dept_name:'NONE')
	form.setValue(obj.cbo_inquiry_id, result.dataresponse.inquiry_descr!=='--NULL--' ? result.dataresponse.inquiry_id : '--NULL--', result.dataresponse.inquiry_descr!=='--NULL--'?result.dataresponse.inquiry_descr:'NONE')

	*/

	var pOpt = form.getDefaultPrompt(false)
	for (var objid in obj) {
		var o = obj[objid]
		if (o.isCombo() && !o.isRequired()) {
			var value =  result.dataresponse[o.getFieldValueName()];
			var text = result.dataresponse[o.getFieldDisplayName()];
			if (value==null ) {
				value = pOpt.value;
				text = pOpt.text;
			}
			form.setValue(o, value, text);
		}
	}
	form.rowid = $ui.getPages().ITEMS['pnl_list'].handler.updategrid(data, form.rowid)
	var rowdata = {
		data: data,
		rowid: form.rowid
	}

	if (typeof hnd.form_datasaved == 'function') {
		hnd.form_datasaved(result, rowdata, options);
	}
}



async function form_deleting(data, options) {
	if (typeof hnd.form_deleting == 'function') {
		hnd.form_deleting(data, options);
	}
}

async function form_deleted(result, options) {
	$ui.getPages().show('pnl_list')
	$ui.getPages().ITEMS['pnl_list'].handler.removerow(form.rowid)

	if (typeof hnd.form_deleted == 'function') {
		hnd.form_deleted(result, options);
	}
}



function btn_print_click() {

	if (form.isDataChanged() || !form.isInViewMode()) {
		$ui.ShowMessage('Simpan dulu perubahan datanya.');
		return;
	}

	var module = window.global.modulefullname;
	var renderto = 'formtemplate-standard.phtml';
	var format = 'format-01-a4-potrait';

	var args = {
		id: form.getCurrentId(),
		variancename: this_page_options.variancename,
		reportmodule: `${module}/orderout.xprint?renderto=${renderto}&format=${format}`,
		handled: false
	}

	if (typeof hnd.form_printing == 'function') {
		hnd.form_printing(args);
	}


	if (!args.handled) {
		$ui.getPages().show('pnl_editpreview', ()=>{
			// console.log('Preview Showed');
			$ui.getPages().ITEMS['pnl_editpreview'].handler.PreviewForm({
				id: args.id, 
				variancename: args.variancename,
				reportmodule: args.reportmodule
			});
		});
	}
}	





async function btn_action_click(args) {
	if (form.isDataChanged() || !form.isInViewMode()) {
		$ui.ShowMessage('[WARNING]Simpan dulu perubahan data, dan tidak sedang dalam mode edit.');
		return;
	}


	var docname = 'Purchase Order'
	var txt_version = obj.txt_orderout_version;
	var chk_iscommit = obj.chk_orderout_iscommit;
	
	var chk_isapprovalprogress = obj.chk_orderout_isapprovalprogress;	
	var chk_isapprove = obj.chk_orderout_isapproved;
	var chk_isdeclined = obj.chk_orderout_isdeclined;
		
	
	var id = form.getCurrentId();

	Object.assign(args, {
		id: id,
		act_url: null,
		act_msg_quest: null,
		act_msg_result: null,
		act_do: null,
		use_otp: false,
		otp_message: `Berikut adalah code yang harus anda masukkan untuk melakukan ${args.action} ${docname} dengan no id ${id}`,
	});

	switch (args.action) {
		
		case 'commit' :
			args.xtion_version = '1.1';
			args.act_url = `${global.modulefullname}/xtion-commit`;
			args.act_msg_quest = `Apakah anda yakin akan <b>${args.action}</b> ${docname} no ${args.id} ?`;
			args.act_msg_result = `${docname} no ${args.id} telah di ${args.action}.`;
			args.act_do = (result) => {
				chk_iscommit.checkbox('check');
				
				form.commit();
			}
			break;

		case 'uncommit' :
			args.xtion_version = '1.1';
			args.act_url = `${global.modulefullname}/xtion-uncommit`;
			args.act_msg_quest = `Apakah anda yakin akan <b>${args.action}</b> ${docname} no ${args.id} ?`;
			args.act_msg_result = `${docname} no ${args.id} telah di ${args.action}.`;
			args.act_do = (result) => {
				chk_iscommit.checkbox('uncheck');
				
				form.setValue(txt_version, result.version);
				form.commit();
			}
			break;		
			
		
		case 'approve' :
			args.xtion_version = '1.1';
			args.act_url = `${global.modulefullname}/xtion-approve`;
			args.act_msg_quest = `Apakah anda yakin akan <b>${args.action}</b> ${docname} no ${args.id} ?`;
			args.act_msg_result = `${docname} no ${args.id} telah di ${args.action}.`;
			args.use_otp = true;
			args.otp_title = 'Approval Code';
			args.param = {
				approve: true,
				approval_note: ''
			}
			args.act_do = (result) => {
				chk_iscommit.checkbox('check');
				chk_isapprovalprogress.checkbox('check');
				chk_isapprove.checkbox(result.isfinalapproval ? "check" : "uncheck");
				chk_isdeclined.checkbox('uncheck');
				form.commit();
			}
			break;

		case 'decline' :
			args.xtion_version = '1.1';
			args.act_url = `${global.modulefullname}/xtion-approve`;
			args.act_msg_quest = '', //`Apakah anda yakin akan <b>${args.action}</b> ${docname} no ${args.id} ?`;
			args.act_msg_result = `${docname} no ${args.id} telah di ${args.action}.`;
			args.use_otp = true;
			args.otp_title = 'Decline Code';
			args.param = {
				approve: false,
				approval_note: args.reason
			}
			args.act_do = (result) => {
				chk_iscommit.checkbox('check');
				chk_isapprove.checkbox('uncheck');
				chk_isdeclined.checkbox('check');
				form.commit();
			}
			break;		
		
	
		default:
			if (typeof hnd.do_other_action == 'function') {
				hnd.do_other_action(args);
			}
	}

	
	if (args.cancel) { return } // batalkan xtion

	try {
		$ui.mask('wait..');
		var { doAction } = await import('../../../../../index.php/asset/fgta/framework/fgta4libs/fgta4xtion.mjs');
		await doAction(args, (err, result) => {
			if (err) {
				$ui.ShowMessage('[WARNING]' + err.message);	
			} else {
				if (result.dataresponse!=undefined) { updaterecordstatus(result.dataresponse) };
				args.act_do(result);

				if (result.dataresponse!=undefined) {
					updatebuttonstate(result.dataresponse);
					updategridstate(result.dataresponse);
				}

				if (typeof hnd.action_done == 'function') {
					hnd.action_done(result, args);
				}

				if (args.act_msg_result!=='') $ui.ShowMessage('[INFO]' + args.act_msg_result);	
			}
		});
	} catch (err) {
		console.error(err);
		$ui.ShowMessage('[ERROR]' + err.message);
	} finally {
		$ui.unmask();
	}
}	
	
	