-- SET FOREIGN_KEY_CHECKS=0;

-- drop table if exists `trn_orderout`;
-- drop table if exists `trn_orderoutitem`;
-- drop table if exists `trn_orderoutfiles`;
-- drop table if exists `trn_orderoutappr`;


CREATE TABLE IF NOT EXISTS `trn_orderout` (
	`orderout_id` varchar(30) NOT NULL , 
	`unit_id` varchar(30)  , 
	`request_id` varchar(30)  , 
	`orderout_isunref` tinyint(1) NOT NULL DEFAULT 0, 
	`inquirytype_id` varchar(30)  , 
	`trxmodel_id` varchar(10)  , 
	`request_dept_id` varchar(30)  , 
	`orderout_descr` varchar(1000)  , 
	`orderout_dtstart` date  , 
	`orderout_dtend` date  , 
	`curr_id` varchar(10)  , 
	`curr_rate` decimal(12, 0) NOT NULL DEFAULT 1, 
	`ppn_taxtype_id` varchar(10)  , 
	`pph_taxtype_id` varchar(10)  , 
	`partner_id` varchar(30)  , 
	`ordercontract_id` varchar(14)  , 
	`orderout_quot` varchar(90)  , 
	`paymtype_id` varchar(6)  , 
	`partnerbank_id` varchar(14)  , 
	`partnerbank_name` varchar(90)  , 
	`partnerbank_bankacc` varchar(90)  , 
	`partnerbank_bankaccname` varchar(90)  , 
	`partnerbank_bankname` varchar(90)  , 
	`partnercontact_id` varchar(14)  , 
	`partnercontact_upname` varchar(90)  , 
	`partnercontact_position` varchar(90)  , 
	`partnercontact_upphone` varchar(90)  , 
	`partnercontact_email` varchar(90)  , 
	`project_id` varchar(30)  , 
	`projecttask_id` varchar(14)  , 
	`projbudget_id` varchar(30)  , 
	`projbudgettask_id` varchar(14)  , 
	`orderout_isunbudgetted` tinyint(1) NOT NULL DEFAULT 0, 
	`site_id` varchar(30)  , 
	`user_dept_id` varchar(30)  , 
	`recv_dept_id` varchar(30)  , 
	`deliver_siteaddress` varchar(250)  , 
	`deliver_city` varchar(60)  , 
	`deliver_upname` varchar(60)  , 
	`deliver_uptelp` varchar(60)  , 
	`inquiry_id` varchar(30)  , 
	`orderout_ismultirequest` tinyint(1) NOT NULL DEFAULT 0, 
	`inquirymodel_id` varchar(1)  , 
	`inquiryselect_id` varchar(1)  , 
	`itemmanage_id` varchar(2)  , 
	`owner_dept_id` varchar(30)  , 
	`orderout_dept_id` varchar(30)  , 
	`doc_id` varchar(30)  , 
	`ordermodel_id` varchar(5)  , 
	`orderout_version` int(4) NOT NULL DEFAULT 0, 
	`orderout_isdateinterval` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_iscommit` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_commitby` varchar(14)  , 
	`orderout_commitdate` datetime  , 
	`orderout_isapprovalprogress` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_isapproved` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_approveby` varchar(14)  , 
	`orderout_approvedate` datetime  , 
	`orderout_isdeclined` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_declineby` varchar(14)  , 
	`orderout_declinedate` datetime  , 
	`orderout_isclose` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_closeby` varchar(14)  , 
	`orderout_closedate` datetime  , 
	`orderout_isadvance` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_isautogenerated` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_isitemdeptuser` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_isitemdeptowner` tinyint(1) NOT NULL DEFAULT 0, 
	`_createby` varchar(14) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(14)  , 
	`_modifydate` datetime  , 
	PRIMARY KEY (`orderout_id`)
) 
ENGINE=InnoDB
COMMENT='Daftar Order Pembelian, Sewa, Service, Talent, dll';


ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `unit_id` varchar(30)   AFTER `orderout_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `request_id` varchar(30)   AFTER `unit_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_isunref` tinyint(1) NOT NULL DEFAULT 0 AFTER `request_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `inquirytype_id` varchar(30)   AFTER `orderout_isunref`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `trxmodel_id` varchar(10)   AFTER `inquirytype_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `request_dept_id` varchar(30)   AFTER `trxmodel_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_descr` varchar(1000)   AFTER `request_dept_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_dtstart` date   AFTER `orderout_descr`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_dtend` date   AFTER `orderout_dtstart`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `curr_id` varchar(10)   AFTER `orderout_dtend`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `curr_rate` decimal(12, 0) NOT NULL DEFAULT 1 AFTER `curr_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `ppn_taxtype_id` varchar(10)   AFTER `curr_rate`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `pph_taxtype_id` varchar(10)   AFTER `ppn_taxtype_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `partner_id` varchar(30)   AFTER `pph_taxtype_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `ordercontract_id` varchar(14)   AFTER `partner_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_quot` varchar(90)   AFTER `ordercontract_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `paymtype_id` varchar(6)   AFTER `orderout_quot`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `partnerbank_id` varchar(14)   AFTER `paymtype_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `partnerbank_name` varchar(90)   AFTER `partnerbank_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `partnerbank_bankacc` varchar(90)   AFTER `partnerbank_name`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `partnerbank_bankaccname` varchar(90)   AFTER `partnerbank_bankacc`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `partnerbank_bankname` varchar(90)   AFTER `partnerbank_bankaccname`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `partnercontact_id` varchar(14)   AFTER `partnerbank_bankname`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `partnercontact_upname` varchar(90)   AFTER `partnercontact_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `partnercontact_position` varchar(90)   AFTER `partnercontact_upname`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `partnercontact_upphone` varchar(90)   AFTER `partnercontact_position`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `partnercontact_email` varchar(90)   AFTER `partnercontact_upphone`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `project_id` varchar(30)   AFTER `partnercontact_email`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `projecttask_id` varchar(14)   AFTER `project_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `projbudget_id` varchar(30)   AFTER `projecttask_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `projbudgettask_id` varchar(14)   AFTER `projbudget_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_isunbudgetted` tinyint(1) NOT NULL DEFAULT 0 AFTER `projbudgettask_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `site_id` varchar(30)   AFTER `orderout_isunbudgetted`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `user_dept_id` varchar(30)   AFTER `site_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `recv_dept_id` varchar(30)   AFTER `user_dept_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `deliver_siteaddress` varchar(250)   AFTER `recv_dept_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `deliver_city` varchar(60)   AFTER `deliver_siteaddress`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `deliver_upname` varchar(60)   AFTER `deliver_city`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `deliver_uptelp` varchar(60)   AFTER `deliver_upname`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `inquiry_id` varchar(30)   AFTER `deliver_uptelp`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_ismultirequest` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `inquirymodel_id` varchar(1)   AFTER `orderout_ismultirequest`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `inquiryselect_id` varchar(1)   AFTER `inquirymodel_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `itemmanage_id` varchar(2)   AFTER `inquiryselect_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `owner_dept_id` varchar(30)   AFTER `itemmanage_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_dept_id` varchar(30)   AFTER `owner_dept_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `doc_id` varchar(30)   AFTER `orderout_dept_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `ordermodel_id` varchar(5)   AFTER `doc_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_version` int(4) NOT NULL DEFAULT 0 AFTER `ordermodel_id`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_isdateinterval` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderout_version`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_iscommit` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderout_isdateinterval`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_commitby` varchar(14)   AFTER `orderout_iscommit`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_commitdate` datetime   AFTER `orderout_commitby`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_isapprovalprogress` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderout_commitdate`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_isapproved` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderout_isapprovalprogress`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_approveby` varchar(14)   AFTER `orderout_isapproved`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_approvedate` datetime   AFTER `orderout_approveby`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_isdeclined` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderout_approvedate`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_declineby` varchar(14)   AFTER `orderout_isdeclined`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_declinedate` datetime   AFTER `orderout_declineby`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_isclose` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderout_declinedate`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_closeby` varchar(14)   AFTER `orderout_isclose`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_closedate` datetime   AFTER `orderout_closeby`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_isadvance` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderout_closedate`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_isautogenerated` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderout_isadvance`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_isitemdeptuser` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderout_isautogenerated`;
ALTER TABLE `trn_orderout` ADD COLUMN IF NOT EXISTS  `orderout_isitemdeptowner` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderout_isitemdeptuser`;


ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `unit_id` varchar(30)    AFTER `orderout_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `request_id` varchar(30)    AFTER `unit_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_isunref` tinyint(1) NOT NULL DEFAULT 0  AFTER `request_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `inquirytype_id` varchar(30)    AFTER `orderout_isunref`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `trxmodel_id` varchar(10)    AFTER `inquirytype_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `request_dept_id` varchar(30)    AFTER `trxmodel_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_descr` varchar(1000)    AFTER `request_dept_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_dtstart` date    AFTER `orderout_descr`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_dtend` date    AFTER `orderout_dtstart`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `curr_id` varchar(10)    AFTER `orderout_dtend`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `curr_rate` decimal(12, 0) NOT NULL DEFAULT 1  AFTER `curr_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `ppn_taxtype_id` varchar(10)    AFTER `curr_rate`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `pph_taxtype_id` varchar(10)    AFTER `ppn_taxtype_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `partner_id` varchar(30)    AFTER `pph_taxtype_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `ordercontract_id` varchar(14)    AFTER `partner_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_quot` varchar(90)    AFTER `ordercontract_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `paymtype_id` varchar(6)    AFTER `orderout_quot`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `partnerbank_id` varchar(14)    AFTER `paymtype_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `partnerbank_name` varchar(90)    AFTER `partnerbank_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `partnerbank_bankacc` varchar(90)    AFTER `partnerbank_name`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `partnerbank_bankaccname` varchar(90)    AFTER `partnerbank_bankacc`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `partnerbank_bankname` varchar(90)    AFTER `partnerbank_bankaccname`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `partnercontact_id` varchar(14)    AFTER `partnerbank_bankname`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `partnercontact_upname` varchar(90)    AFTER `partnercontact_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `partnercontact_position` varchar(90)    AFTER `partnercontact_upname`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `partnercontact_upphone` varchar(90)    AFTER `partnercontact_position`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `partnercontact_email` varchar(90)    AFTER `partnercontact_upphone`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `project_id` varchar(30)    AFTER `partnercontact_email`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `projecttask_id` varchar(14)    AFTER `project_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `projbudget_id` varchar(30)    AFTER `projecttask_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `projbudgettask_id` varchar(14)    AFTER `projbudget_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_isunbudgetted` tinyint(1) NOT NULL DEFAULT 0  AFTER `projbudgettask_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `site_id` varchar(30)    AFTER `orderout_isunbudgetted`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `user_dept_id` varchar(30)    AFTER `site_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `recv_dept_id` varchar(30)    AFTER `user_dept_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `deliver_siteaddress` varchar(250)    AFTER `recv_dept_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `deliver_city` varchar(60)    AFTER `deliver_siteaddress`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `deliver_upname` varchar(60)    AFTER `deliver_city`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `deliver_uptelp` varchar(60)    AFTER `deliver_upname`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `inquiry_id` varchar(30)    AFTER `deliver_uptelp`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_ismultirequest` tinyint(1) NOT NULL DEFAULT 0  AFTER `inquiry_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `inquirymodel_id` varchar(1)    AFTER `orderout_ismultirequest`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `inquiryselect_id` varchar(1)    AFTER `inquirymodel_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `itemmanage_id` varchar(2)    AFTER `inquiryselect_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `owner_dept_id` varchar(30)    AFTER `itemmanage_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_dept_id` varchar(30)    AFTER `owner_dept_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `doc_id` varchar(30)    AFTER `orderout_dept_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `ordermodel_id` varchar(5)    AFTER `doc_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_version` int(4) NOT NULL DEFAULT 0  AFTER `ordermodel_id`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_isdateinterval` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderout_version`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_iscommit` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderout_isdateinterval`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_commitby` varchar(14)    AFTER `orderout_iscommit`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_commitdate` datetime    AFTER `orderout_commitby`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_isapprovalprogress` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderout_commitdate`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_isapproved` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderout_isapprovalprogress`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_approveby` varchar(14)    AFTER `orderout_isapproved`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_approvedate` datetime    AFTER `orderout_approveby`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_isdeclined` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderout_approvedate`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_declineby` varchar(14)    AFTER `orderout_isdeclined`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_declinedate` datetime    AFTER `orderout_declineby`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_isclose` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderout_declinedate`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_closeby` varchar(14)    AFTER `orderout_isclose`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_closedate` datetime    AFTER `orderout_closeby`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_isadvance` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderout_closedate`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_isautogenerated` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderout_isadvance`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_isitemdeptuser` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderout_isautogenerated`;
ALTER TABLE `trn_orderout` MODIFY COLUMN IF EXISTS  `orderout_isitemdeptowner` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderout_isitemdeptuser`;



ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `unit_id` (`unit_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `request_id` (`request_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `inquirytype_id` (`inquirytype_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `trxmodel_id` (`trxmodel_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `request_dept_id` (`request_dept_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `curr_id` (`curr_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `ppn_taxtype_id` (`ppn_taxtype_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `pph_taxtype_id` (`pph_taxtype_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `partner_id` (`partner_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `ordercontract_id` (`ordercontract_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `paymtype_id` (`paymtype_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `partnerbank_id` (`partnerbank_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `partnercontact_id` (`partnercontact_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `project_id` (`project_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `projecttask_id` (`projecttask_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `projbudget_id` (`projbudget_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `projbudgettask_id` (`projbudgettask_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `site_id` (`site_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `user_dept_id` (`user_dept_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `recv_dept_id` (`recv_dept_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `inquiry_id` (`inquiry_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS  `inquirymodel_id` (`inquirymodel_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS  `inquiryselect_id` (`inquiryselect_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS  `itemmanage_id` (`itemmanage_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS  `owner_dept_id` (`owner_dept_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS  `orderout_dept_id` (`orderout_dept_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `doc_id` (`doc_id`);
ALTER TABLE `trn_orderout` ADD KEY IF NOT EXISTS `ordermodel_id` (`ordermodel_id`);

ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_unit` FOREIGN KEY IF NOT EXISTS  (`unit_id`) REFERENCES `mst_unit` (`unit_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_trn_request` FOREIGN KEY IF NOT EXISTS  (`request_id`) REFERENCES `trn_request` (`request_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_inquirytype` FOREIGN KEY IF NOT EXISTS  (`inquirytype_id`) REFERENCES `mst_inquirytype` (`inquirytype_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_trxmodel` FOREIGN KEY IF NOT EXISTS  (`trxmodel_id`) REFERENCES `mst_trxmodel` (`trxmodel_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_dept` FOREIGN KEY IF NOT EXISTS  (`request_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_curr` FOREIGN KEY IF NOT EXISTS  (`curr_id`) REFERENCES `mst_curr` (`curr_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_taxtype` FOREIGN KEY IF NOT EXISTS  (`ppn_taxtype_id`) REFERENCES `mst_taxtype` (`taxtype_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_taxtype_2` FOREIGN KEY IF NOT EXISTS  (`pph_taxtype_id`) REFERENCES `mst_taxtype` (`taxtype_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_partner` FOREIGN KEY IF NOT EXISTS  (`partner_id`) REFERENCES `mst_partner` (`partner_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_trn_ordercontract` FOREIGN KEY IF NOT EXISTS  (`ordercontract_id`) REFERENCES `trn_ordercontract` (`ordercontract_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_paymtype` FOREIGN KEY IF NOT EXISTS  (`paymtype_id`) REFERENCES `mst_paymtype` (`paymtype_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_partnerbank` FOREIGN KEY IF NOT EXISTS  (`partnerbank_id`) REFERENCES `mst_partnerbank` (`partnerbank_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_partnercontact` FOREIGN KEY IF NOT EXISTS  (`partnercontact_id`) REFERENCES `mst_partnercontact` (`partnercontact_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_project` FOREIGN KEY IF NOT EXISTS  (`project_id`) REFERENCES `mst_project` (`project_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_projecttask` FOREIGN KEY IF NOT EXISTS  (`projecttask_id`) REFERENCES `mst_projecttask` (`projecttask_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_projbudget` FOREIGN KEY IF NOT EXISTS  (`projbudget_id`) REFERENCES `mst_projbudget` (`projbudget_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_projbudgettask` FOREIGN KEY IF NOT EXISTS  (`projbudgettask_id`) REFERENCES `mst_projbudgettask` (`projbudgettask_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_site` FOREIGN KEY IF NOT EXISTS  (`site_id`) REFERENCES `mst_site` (`site_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_dept_2` FOREIGN KEY IF NOT EXISTS  (`user_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_dept_3` FOREIGN KEY IF NOT EXISTS  (`recv_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_trn_inquiry` FOREIGN KEY IF NOT EXISTS  (`inquiry_id`) REFERENCES `trn_inquiry` (`inquiry_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_inquirymodel` FOREIGN KEY IF NOT EXISTS (`inquirymodel_id`) REFERENCES `mst_inquirymodel` (`inquirymodel_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_inquiryselect` FOREIGN KEY IF NOT EXISTS (`inquiryselect_id`) REFERENCES `mst_inquiryselect` (`inquiryselect_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_itemmanage` FOREIGN KEY IF NOT EXISTS (`itemmanage_id`) REFERENCES `mst_itemmanage` (`itemmanage_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_dept_4` FOREIGN KEY IF NOT EXISTS (`owner_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_dept_5` FOREIGN KEY IF NOT EXISTS (`orderout_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_doc` FOREIGN KEY IF NOT EXISTS  (`doc_id`) REFERENCES `mst_doc` (`doc_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_ordermodel` FOREIGN KEY IF NOT EXISTS  (`ordermodel_id`) REFERENCES `mst_ordermodel` (`ordermodel_id`);





CREATE TABLE IF NOT EXISTS `trn_orderoutitem` (
	`orderoutitem_id` varchar(14) NOT NULL , 
	`itemasset_id` varchar(14)  , 
	`item_id` varchar(14)  , 
	`itemstock_id` varchar(14)  , 
	`partner_id` varchar(30)  , 
	`itemclass_id` varchar(14) NOT NULL , 
	`orderoutitem_ref` varchar(255)  , 
	`orderoutitem_descr` varchar(255)  , 
	`orderoutitem_qty` int(4) NOT NULL DEFAULT 0, 
	`orderoutitem_days` int(4) NOT NULL DEFAULT 0, 
	`orderoutitem_task` int(4) NOT NULL DEFAULT 0, 
	`orderoutitem_rate` decimal(12, 2) NOT NULL DEFAULT 0, 
	`orderoutitem_value` decimal(14, 2) NOT NULL DEFAULT 0, 
	`curr_id` varchar(10) NOT NULL , 
	`curr_rate` decimal(12, 0) NOT NULL DEFAULT 0, 
	`orderoutitem_idr` decimal(14, 2) NOT NULL DEFAULT 0, 
	`projbudgetdet_id` varchar(30)  , 
	`orderoutitem_isoverbudget` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_isunbudget` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_budgetavailable` decimal(14, 0) NOT NULL DEFAULT 0, 
	`orderoutitem_budgetqtyavailable` int(16) NOT NULL DEFAULT 0, 
	`orderoutitem_budgetdaysavailable` int(16) NOT NULL DEFAULT 0, 
	`orderoutitem_budgettaskavailable` int(16) NOT NULL DEFAULT 0, 
	`orderoutitem_isuseqty` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_isusedays` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_isusetask` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_islimitqty` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_islimitdays` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_islimittask` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_islimitvalue` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_isallowoverbudget` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_isallowunbudget` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_qtyavailable` int(4) NOT NULL DEFAULT 0, 
	`accbudget_id` varchar(20)  , 
	`coa_id` varchar(17)  , 
	`request_id` varchar(30)  , 
	`requestitem_id` varchar(14)  , 
	`inquiry_id` varchar(30)  , 
	`inquiryitem_id` varchar(14)  , 
	`orderout_id` varchar(30) NOT NULL , 
	`_createby` varchar(14) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(14)  , 
	`_modifydate` datetime  , 
	PRIMARY KEY (`orderoutitem_id`)
) 
ENGINE=InnoDB
COMMENT='Item yang di request';


ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `itemasset_id` varchar(14)   AFTER `orderoutitem_id`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `item_id` varchar(14)   AFTER `itemasset_id`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `itemstock_id` varchar(14)   AFTER `item_id`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `partner_id` varchar(30)   AFTER `itemstock_id`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `itemclass_id` varchar(14) NOT NULL  AFTER `partner_id`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_ref` varchar(255)   AFTER `itemclass_id`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_descr` varchar(255)   AFTER `orderoutitem_ref`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_qty` int(4) NOT NULL DEFAULT 0 AFTER `orderoutitem_descr`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_days` int(4) NOT NULL DEFAULT 0 AFTER `orderoutitem_qty`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_task` int(4) NOT NULL DEFAULT 0 AFTER `orderoutitem_days`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_rate` decimal(12, 2) NOT NULL DEFAULT 0 AFTER `orderoutitem_task`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_value` decimal(14, 2) NOT NULL DEFAULT 0 AFTER `orderoutitem_rate`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `curr_id` varchar(10) NOT NULL  AFTER `orderoutitem_value`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `curr_rate` decimal(12, 0) NOT NULL DEFAULT 0 AFTER `curr_id`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_idr` decimal(14, 2) NOT NULL DEFAULT 0 AFTER `curr_rate`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `projbudgetdet_id` varchar(30)   AFTER `orderoutitem_idr`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_isoverbudget` tinyint(1) NOT NULL DEFAULT 0 AFTER `projbudgetdet_id`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_isunbudget` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderoutitem_isoverbudget`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_budgetavailable` decimal(14, 0) NOT NULL DEFAULT 0 AFTER `orderoutitem_isunbudget`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_budgetqtyavailable` int(16) NOT NULL DEFAULT 0 AFTER `orderoutitem_budgetavailable`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_budgetdaysavailable` int(16) NOT NULL DEFAULT 0 AFTER `orderoutitem_budgetqtyavailable`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_budgettaskavailable` int(16) NOT NULL DEFAULT 0 AFTER `orderoutitem_budgetdaysavailable`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_isuseqty` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderoutitem_budgettaskavailable`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_isusedays` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderoutitem_isuseqty`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_isusetask` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderoutitem_isusedays`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_islimitqty` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderoutitem_isusetask`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_islimitdays` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderoutitem_islimitqty`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_islimittask` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderoutitem_islimitdays`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_islimitvalue` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderoutitem_islimittask`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_isallowoverbudget` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderoutitem_islimitvalue`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_isallowunbudget` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderoutitem_isallowoverbudget`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderoutitem_qtyavailable` int(4) NOT NULL DEFAULT 0 AFTER `orderoutitem_isallowunbudget`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `accbudget_id` varchar(20)   AFTER `orderoutitem_qtyavailable`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `coa_id` varchar(17)   AFTER `accbudget_id`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `request_id` varchar(30)   AFTER `coa_id`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `requestitem_id` varchar(14)   AFTER `request_id`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `inquiry_id` varchar(30)   AFTER `requestitem_id`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `inquiryitem_id` varchar(14)   AFTER `inquiry_id`;
ALTER TABLE `trn_orderoutitem` ADD COLUMN IF NOT EXISTS  `orderout_id` varchar(30) NOT NULL  AFTER `inquiryitem_id`;


ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `itemasset_id` varchar(14)    AFTER `orderoutitem_id`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `item_id` varchar(14)    AFTER `itemasset_id`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `itemstock_id` varchar(14)    AFTER `item_id`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `partner_id` varchar(30)    AFTER `itemstock_id`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `itemclass_id` varchar(14) NOT NULL   AFTER `partner_id`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_ref` varchar(255)    AFTER `itemclass_id`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_descr` varchar(255)    AFTER `orderoutitem_ref`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_qty` int(4) NOT NULL DEFAULT 0  AFTER `orderoutitem_descr`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_days` int(4) NOT NULL DEFAULT 0  AFTER `orderoutitem_qty`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_task` int(4) NOT NULL DEFAULT 0  AFTER `orderoutitem_days`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_rate` decimal(12, 2) NOT NULL DEFAULT 0  AFTER `orderoutitem_task`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_value` decimal(14, 2) NOT NULL DEFAULT 0  AFTER `orderoutitem_rate`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `curr_id` varchar(10) NOT NULL   AFTER `orderoutitem_value`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `curr_rate` decimal(12, 0) NOT NULL DEFAULT 0  AFTER `curr_id`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_idr` decimal(14, 2) NOT NULL DEFAULT 0  AFTER `curr_rate`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `projbudgetdet_id` varchar(30)    AFTER `orderoutitem_idr`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_isoverbudget` tinyint(1) NOT NULL DEFAULT 0  AFTER `projbudgetdet_id`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_isunbudget` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderoutitem_isoverbudget`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_budgetavailable` decimal(14, 0) NOT NULL DEFAULT 0  AFTER `orderoutitem_isunbudget`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_budgetqtyavailable` int(16) NOT NULL DEFAULT 0  AFTER `orderoutitem_budgetavailable`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_budgetdaysavailable` int(16) NOT NULL DEFAULT 0  AFTER `orderoutitem_budgetqtyavailable`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_budgettaskavailable` int(16) NOT NULL DEFAULT 0  AFTER `orderoutitem_budgetdaysavailable`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_isuseqty` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderoutitem_budgettaskavailable`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_isusedays` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderoutitem_isuseqty`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_isusetask` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderoutitem_isusedays`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_islimitqty` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderoutitem_isusetask`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_islimitdays` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderoutitem_islimitqty`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_islimittask` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderoutitem_islimitdays`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_islimitvalue` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderoutitem_islimittask`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_isallowoverbudget` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderoutitem_islimitvalue`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_isallowunbudget` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderoutitem_isallowoverbudget`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderoutitem_qtyavailable` int(4) NOT NULL DEFAULT 0  AFTER `orderoutitem_isallowunbudget`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `accbudget_id` varchar(20)    AFTER `orderoutitem_qtyavailable`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `coa_id` varchar(17)    AFTER `accbudget_id`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `request_id` varchar(30)    AFTER `coa_id`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `requestitem_id` varchar(14)    AFTER `request_id`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `inquiry_id` varchar(30)    AFTER `requestitem_id`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `inquiryitem_id` varchar(14)    AFTER `inquiry_id`;
ALTER TABLE `trn_orderoutitem` MODIFY COLUMN IF EXISTS  `orderout_id` varchar(30) NOT NULL   AFTER `inquiryitem_id`;



ALTER TABLE `trn_orderoutitem` ADD KEY IF NOT EXISTS `itemasset_id` (`itemasset_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY IF NOT EXISTS `item_id` (`item_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY IF NOT EXISTS `itemstock_id` (`itemstock_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY IF NOT EXISTS `partner_id` (`partner_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY IF NOT EXISTS `itemclass_id` (`itemclass_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY IF NOT EXISTS `curr_id` (`curr_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY IF NOT EXISTS `projbudgetdet_id` (`projbudgetdet_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY IF NOT EXISTS  `accbudget_id` (`accbudget_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY IF NOT EXISTS  `coa_id` (`coa_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY IF NOT EXISTS  `request_id` (`request_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY IF NOT EXISTS  `requestitem_id` (`requestitem_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY IF NOT EXISTS  `inquiry_id` (`inquiry_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY IF NOT EXISTS  `inquiryitem_id` (`inquiryitem_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY IF NOT EXISTS `orderout_id` (`orderout_id`);

ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_itemasset` FOREIGN KEY IF NOT EXISTS  (`itemasset_id`) REFERENCES `mst_itemasset` (`itemasset_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_item` FOREIGN KEY IF NOT EXISTS  (`item_id`) REFERENCES `mst_item` (`item_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_itemstock` FOREIGN KEY IF NOT EXISTS  (`itemstock_id`) REFERENCES `mst_itemstock` (`itemstock_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_partner` FOREIGN KEY IF NOT EXISTS  (`partner_id`) REFERENCES `mst_partner` (`partner_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_itemclass` FOREIGN KEY IF NOT EXISTS  (`itemclass_id`) REFERENCES `mst_itemclass` (`itemclass_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_curr` FOREIGN KEY IF NOT EXISTS  (`curr_id`) REFERENCES `mst_curr` (`curr_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_projbudgetdet` FOREIGN KEY IF NOT EXISTS  (`projbudgetdet_id`) REFERENCES `mst_projbudgetdet` (`projbudgetdet_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_accbudget` FOREIGN KEY IF NOT EXISTS (`accbudget_id`) REFERENCES `mst_accbudget` (`accbudget_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_coa` FOREIGN KEY IF NOT EXISTS (`coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_trn_request` FOREIGN KEY IF NOT EXISTS (`request_id`) REFERENCES `trn_request` (`request_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_trn_requestdetil` FOREIGN KEY IF NOT EXISTS (`requestitem_id`) REFERENCES `trn_requestdetil` (`requestitem_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_trn_inquiry` FOREIGN KEY IF NOT EXISTS (`inquiry_id`) REFERENCES `trn_inquiry` (`inquiry_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_trn_inquirydetil` FOREIGN KEY IF NOT EXISTS (`inquiryitem_id`) REFERENCES `trn_inquirydetil` (`inquirydetil_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_trn_orderout` FOREIGN KEY IF NOT EXISTS (`orderout_id`) REFERENCES `trn_orderout` (`orderout_id`);





CREATE TABLE IF NOT EXISTS `trn_orderoutfiles` (
	`orderoutfiles_id` varchar(14) NOT NULL , 
	`doctype_id` varchar(10) NOT NULL , 
	`orderoutfiles_descr` varchar(90) NOT NULL , 
	`orderoutfiles_order` int(4) NOT NULL DEFAULT 0, 
	`orderoutfiles_file` varchar(90)  , 
	`orderout_id` varchar(30) NOT NULL , 
	`_createby` varchar(14) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(14)  , 
	`_modifydate` datetime  , 
	UNIQUE KEY `orderout_doc` (`orderout_id`, `doctype_id`),
	PRIMARY KEY (`orderoutfiles_id`)
) 
ENGINE=InnoDB
COMMENT='Daftar File Inquiry';


ALTER TABLE `trn_orderoutfiles` ADD COLUMN IF NOT EXISTS  `doctype_id` varchar(10) NOT NULL  AFTER `orderoutfiles_id`;
ALTER TABLE `trn_orderoutfiles` ADD COLUMN IF NOT EXISTS  `orderoutfiles_descr` varchar(90) NOT NULL  AFTER `doctype_id`;
ALTER TABLE `trn_orderoutfiles` ADD COLUMN IF NOT EXISTS  `orderoutfiles_order` int(4) NOT NULL DEFAULT 0 AFTER `orderoutfiles_descr`;
ALTER TABLE `trn_orderoutfiles` ADD COLUMN IF NOT EXISTS  `orderoutfiles_file` varchar(90)   AFTER `orderoutfiles_order`;
ALTER TABLE `trn_orderoutfiles` ADD COLUMN IF NOT EXISTS  `orderout_id` varchar(30) NOT NULL  AFTER `orderoutfiles_file`;


ALTER TABLE `trn_orderoutfiles` MODIFY COLUMN IF EXISTS  `doctype_id` varchar(10) NOT NULL   AFTER `orderoutfiles_id`;
ALTER TABLE `trn_orderoutfiles` MODIFY COLUMN IF EXISTS  `orderoutfiles_descr` varchar(90) NOT NULL   AFTER `doctype_id`;
ALTER TABLE `trn_orderoutfiles` MODIFY COLUMN IF EXISTS  `orderoutfiles_order` int(4) NOT NULL DEFAULT 0  AFTER `orderoutfiles_descr`;
ALTER TABLE `trn_orderoutfiles` MODIFY COLUMN IF EXISTS  `orderoutfiles_file` varchar(90)    AFTER `orderoutfiles_order`;
ALTER TABLE `trn_orderoutfiles` MODIFY COLUMN IF EXISTS  `orderout_id` varchar(30) NOT NULL   AFTER `orderoutfiles_file`;


ALTER TABLE `trn_orderoutfiles` ADD CONSTRAINT `orderout_doc` UNIQUE IF NOT EXISTS  (`orderout_id`, `doctype_id`);

ALTER TABLE `trn_orderoutfiles` ADD KEY IF NOT EXISTS `doctype_id` (`doctype_id`);
ALTER TABLE `trn_orderoutfiles` ADD KEY IF NOT EXISTS `orderout_id` (`orderout_id`);

ALTER TABLE `trn_orderoutfiles` ADD CONSTRAINT `fk_trn_orderoutfiles_mst_doctype` FOREIGN KEY IF NOT EXISTS  (`doctype_id`) REFERENCES `mst_doctype` (`doctype_id`);
ALTER TABLE `trn_orderoutfiles` ADD CONSTRAINT `fk_trn_orderoutfiles_trn_orderout` FOREIGN KEY IF NOT EXISTS (`orderout_id`) REFERENCES `trn_orderout` (`orderout_id`);





CREATE TABLE IF NOT EXISTS `trn_orderoutappr` (
	`orderoutappr_id` varchar(14) NOT NULL , 
	`orderoutappr_isapproved` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutappr_by` varchar(14)  , 
	`orderoutappr_date` datetime  , 
	`orderout_version` int(4) NOT NULL DEFAULT 0, 
	`orderoutappr_isdeclined` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutappr_declinedby` varchar(14)  , 
	`orderoutappr_declineddate` datetime  , 
	`orderoutappr_notes` varchar(255)  , 
	`orderout_id` varchar(30) NOT NULL , 
	`docauth_descr` varchar(90)  , 
	`docauth_order` int(4) NOT NULL DEFAULT 0, 
	`docauth_value` int(4) NOT NULL DEFAULT 100, 
	`docauth_min` int(4) NOT NULL DEFAULT 0, 
	`authlevel_id` varchar(10) NOT NULL , 
	`authlevel_name` varchar(60) NOT NULL , 
	`auth_id` varchar(10)  , 
	`auth_name` varchar(60) NOT NULL , 
	`_createby` varchar(14) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(14)  , 
	`_modifydate` datetime  , 
	UNIQUE KEY `orderout_auth_id` (`orderout_id`, `auth_id`),
	PRIMARY KEY (`orderoutappr_id`)
) 
ENGINE=InnoDB
COMMENT='Approval Purchase Order';


ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `orderoutappr_isapproved` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderoutappr_id`;
ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `orderoutappr_by` varchar(14)   AFTER `orderoutappr_isapproved`;
ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `orderoutappr_date` datetime   AFTER `orderoutappr_by`;
ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `orderout_version` int(4) NOT NULL DEFAULT 0 AFTER `orderoutappr_date`;
ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `orderoutappr_isdeclined` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderout_version`;
ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `orderoutappr_declinedby` varchar(14)   AFTER `orderoutappr_isdeclined`;
ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `orderoutappr_declineddate` datetime   AFTER `orderoutappr_declinedby`;
ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `orderoutappr_notes` varchar(255)   AFTER `orderoutappr_declineddate`;
ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `orderout_id` varchar(30) NOT NULL  AFTER `orderoutappr_notes`;
ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `docauth_descr` varchar(90)   AFTER `orderout_id`;
ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `docauth_order` int(4) NOT NULL DEFAULT 0 AFTER `docauth_descr`;
ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `docauth_value` int(4) NOT NULL DEFAULT 100 AFTER `docauth_order`;
ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `docauth_min` int(4) NOT NULL DEFAULT 0 AFTER `docauth_value`;
ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `authlevel_id` varchar(10) NOT NULL  AFTER `docauth_min`;
ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `authlevel_name` varchar(60) NOT NULL  AFTER `authlevel_id`;
ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `auth_id` varchar(10)   AFTER `authlevel_name`;
ALTER TABLE `trn_orderoutappr` ADD COLUMN IF NOT EXISTS  `auth_name` varchar(60) NOT NULL  AFTER `auth_id`;


ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `orderoutappr_isapproved` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderoutappr_id`;
ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `orderoutappr_by` varchar(14)    AFTER `orderoutappr_isapproved`;
ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `orderoutappr_date` datetime    AFTER `orderoutappr_by`;
ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `orderout_version` int(4) NOT NULL DEFAULT 0  AFTER `orderoutappr_date`;
ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `orderoutappr_isdeclined` tinyint(1) NOT NULL DEFAULT 0  AFTER `orderout_version`;
ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `orderoutappr_declinedby` varchar(14)    AFTER `orderoutappr_isdeclined`;
ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `orderoutappr_declineddate` datetime    AFTER `orderoutappr_declinedby`;
ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `orderoutappr_notes` varchar(255)    AFTER `orderoutappr_declineddate`;
ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `orderout_id` varchar(30) NOT NULL   AFTER `orderoutappr_notes`;
ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `docauth_descr` varchar(90)    AFTER `orderout_id`;
ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `docauth_order` int(4) NOT NULL DEFAULT 0  AFTER `docauth_descr`;
ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `docauth_value` int(4) NOT NULL DEFAULT 100  AFTER `docauth_order`;
ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `docauth_min` int(4) NOT NULL DEFAULT 0  AFTER `docauth_value`;
ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `authlevel_id` varchar(10) NOT NULL   AFTER `docauth_min`;
ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `authlevel_name` varchar(60) NOT NULL   AFTER `authlevel_id`;
ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `auth_id` varchar(10)    AFTER `authlevel_name`;
ALTER TABLE `trn_orderoutappr` MODIFY COLUMN IF EXISTS  `auth_name` varchar(60) NOT NULL   AFTER `auth_id`;


ALTER TABLE `trn_orderoutappr` ADD CONSTRAINT `orderout_auth_id` UNIQUE IF NOT EXISTS  (`orderout_id`, `auth_id`);

ALTER TABLE `trn_orderoutappr` ADD KEY IF NOT EXISTS `orderout_id` (`orderout_id`);

ALTER TABLE `trn_orderoutappr` ADD CONSTRAINT `fk_trn_orderoutappr_trn_orderout` FOREIGN KEY IF NOT EXISTS (`orderout_id`) REFERENCES `trn_orderout` (`orderout_id`);





