-- SET FOREIGN_KEY_CHECKS=0;

-- drop table if exists `trn_inquiry`;
-- drop table if exists `trn_inquiryitem`;
-- drop table if exists `trn_inquirydetil`;
-- drop table if exists `trn_inquiryfiles`;
-- drop table if exists `trn_inquiryappr`;


CREATE TABLE IF NOT EXISTS `trn_inquiry` (
	`inquiry_id` varchar(30) NOT NULL , 
	`inquirytype_id` varchar(14) NOT NULL , 
	`inquiry_descr` varchar(255)  , 
	`inquiry_dtstart` date NOT NULL , 
	`inquiry_dtend` date NOT NULL , 
	`user_dept_id` varchar(30) NOT NULL , 
	`empl_id` varchar(30)  , 
	`inquiry_isadvance` tinyint(1) NOT NULL DEFAULT 0, 
	`project_id` varchar(30) NOT NULL , 
	`projecttask_id` varchar(14)  , 
	`projbudget_id` varchar(30)  , 
	`projbudgettask_id` varchar(14)  , 
	`inquiry_isunbudgetted` tinyint(1) NOT NULL DEFAULT 0, 
	`site_id` varchar(30) NOT NULL , 
	`deliver_siteaddress` varchar(250)  , 
	`deliver_city` varchar(60)  , 
	`deliver_upname` varchar(60)  , 
	`deliver_uptelp` varchar(60)  , 
	`inquirymodel_id` varchar(1) NOT NULL , 
	`inquiryselect_id` varchar(1) NOT NULL , 
	`request_dept_id` varchar(30) NOT NULL , 
	`owner_dept_id` varchar(30) NOT NULL , 
	`request_doc_id` varchar(30) NOT NULL , 
	`orderout_dept_id` varchar(30) NOT NULL , 
	`orderout_doc_id` varchar(30) NOT NULL , 
	`trxmodel_id` varchar(30) NOT NULL , 
	`itemmanage_id` varchar(2) NOT NULL , 
	`inquiry_rejectnotes` varchar(255)  , 
	`doc_id` varchar(30) NOT NULL , 
	`inquiry_selectfield` varchar(6) NOT NULL DEFAULT 000000, 
	`inquiry_version` int(4) NOT NULL DEFAULT 0, 
	`inquiry_isdateinterval` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_maxadvancevalue` decimal(12, 0) NOT NULL DEFAULT 0, 
	`inquiry_isallowadvance` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_iscommit` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_commitby` varchar(14)  , 
	`inquiry_commitdate` datetime  , 
	`inquiry_isapprovalprogress` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_isapproved` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_approveby` varchar(14)  , 
	`inquiry_approvedate` datetime  , 
	`inquiry_isdeclined` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_declineby` varchar(14)  , 
	`inquiry_declinedate` datetime  , 
	`inquiry_ispreparing` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_isprepared` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_preparedby` varchar(14)  , 
	`inquiry_prepareddate` datetime  , 
	`inquiry_isreject` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_rejectby` varchar(14)  , 
	`inquiry_rejectdate` datetime  , 
	`inquiry_iscomplete` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_isclose` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_closeby` varchar(14)  , 
	`inquiry_closedate` datetime  , 
	`inquiry_isautogenerated` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_isitemdeptuser` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_isitemdeptowner` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiry_istoberequest` tinyint(1) NOT NULL DEFAULT 0, 
	`_createby` varchar(13) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(13)  , 
	`_modifydate` datetime  , 
	PRIMARY KEY (`inquiry_id`)
) 
ENGINE=InnoDB
COMMENT='Inquiry item';


ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquirytype_id` varchar(14) NOT NULL  AFTER `inquiry_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_descr` varchar(255)   AFTER `inquirytype_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_dtstart` date NOT NULL  AFTER `inquiry_descr`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_dtend` date NOT NULL  AFTER `inquiry_dtstart`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `user_dept_id` varchar(30) NOT NULL  AFTER `inquiry_dtend`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `empl_id` varchar(30)   AFTER `user_dept_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_isadvance` tinyint(1) NOT NULL DEFAULT 0 AFTER `empl_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `project_id` varchar(30) NOT NULL  AFTER `inquiry_isadvance`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `projecttask_id` varchar(14)   AFTER `project_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `projbudget_id` varchar(30)   AFTER `projecttask_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `projbudgettask_id` varchar(14)   AFTER `projbudget_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_isunbudgetted` tinyint(1) NOT NULL DEFAULT 0 AFTER `projbudgettask_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `site_id` varchar(30) NOT NULL  AFTER `inquiry_isunbudgetted`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `deliver_siteaddress` varchar(250)   AFTER `site_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `deliver_city` varchar(60)   AFTER `deliver_siteaddress`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `deliver_upname` varchar(60)   AFTER `deliver_city`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `deliver_uptelp` varchar(60)   AFTER `deliver_upname`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquirymodel_id` varchar(1) NOT NULL  AFTER `deliver_uptelp`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiryselect_id` varchar(1) NOT NULL  AFTER `inquirymodel_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `request_dept_id` varchar(30) NOT NULL  AFTER `inquiryselect_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `owner_dept_id` varchar(30) NOT NULL  AFTER `request_dept_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `request_doc_id` varchar(30) NOT NULL  AFTER `owner_dept_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `orderout_dept_id` varchar(30) NOT NULL  AFTER `request_doc_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `orderout_doc_id` varchar(30) NOT NULL  AFTER `orderout_dept_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `trxmodel_id` varchar(30) NOT NULL  AFTER `orderout_doc_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `itemmanage_id` varchar(2) NOT NULL  AFTER `trxmodel_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_rejectnotes` varchar(255)   AFTER `itemmanage_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `doc_id` varchar(30) NOT NULL  AFTER `inquiry_rejectnotes`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_selectfield` varchar(6) NOT NULL DEFAULT 000000 AFTER `doc_id`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_version` int(4) NOT NULL DEFAULT 0 AFTER `inquiry_selectfield`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_isdateinterval` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_version`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_maxadvancevalue` decimal(12, 0) NOT NULL DEFAULT 0 AFTER `inquiry_isdateinterval`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_isallowadvance` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_maxadvancevalue`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_iscommit` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_isallowadvance`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_commitby` varchar(14)   AFTER `inquiry_iscommit`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_commitdate` datetime   AFTER `inquiry_commitby`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_isapprovalprogress` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_commitdate`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_isapproved` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_isapprovalprogress`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_approveby` varchar(14)   AFTER `inquiry_isapproved`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_approvedate` datetime   AFTER `inquiry_approveby`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_isdeclined` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_approvedate`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_declineby` varchar(14)   AFTER `inquiry_isdeclined`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_declinedate` datetime   AFTER `inquiry_declineby`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_ispreparing` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_declinedate`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_isprepared` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_ispreparing`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_preparedby` varchar(14)   AFTER `inquiry_isprepared`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_prepareddate` datetime   AFTER `inquiry_preparedby`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_isreject` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_prepareddate`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_rejectby` varchar(14)   AFTER `inquiry_isreject`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_rejectdate` datetime   AFTER `inquiry_rejectby`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_iscomplete` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_rejectdate`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_isclose` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_iscomplete`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_closeby` varchar(14)   AFTER `inquiry_isclose`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_closedate` datetime   AFTER `inquiry_closeby`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_isautogenerated` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_closedate`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_isitemdeptuser` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_isautogenerated`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_isitemdeptowner` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_isitemdeptuser`;
ALTER TABLE `trn_inquiry` ADD COLUMN IF NOT EXISTS  `inquiry_istoberequest` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_isitemdeptowner`;


ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquirytype_id` varchar(14) NOT NULL  AFTER `inquiry_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_descr` varchar(255)   AFTER `inquirytype_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_dtstart` date NOT NULL  AFTER `inquiry_descr`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_dtend` date NOT NULL  AFTER `inquiry_dtstart`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `user_dept_id` varchar(30) NOT NULL  AFTER `inquiry_dtend`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `empl_id` varchar(30)   AFTER `user_dept_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_isadvance` tinyint(1) NOT NULL DEFAULT 0 AFTER `empl_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `project_id` varchar(30) NOT NULL  AFTER `inquiry_isadvance`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `projecttask_id` varchar(14)   AFTER `project_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `projbudget_id` varchar(30)   AFTER `projecttask_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `projbudgettask_id` varchar(14)   AFTER `projbudget_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_isunbudgetted` tinyint(1) NOT NULL DEFAULT 0 AFTER `projbudgettask_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `site_id` varchar(30) NOT NULL  AFTER `inquiry_isunbudgetted`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `deliver_siteaddress` varchar(250)   AFTER `site_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `deliver_city` varchar(60)   AFTER `deliver_siteaddress`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `deliver_upname` varchar(60)   AFTER `deliver_city`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `deliver_uptelp` varchar(60)   AFTER `deliver_upname`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquirymodel_id` varchar(1) NOT NULL  AFTER `deliver_uptelp`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiryselect_id` varchar(1) NOT NULL  AFTER `inquirymodel_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `request_dept_id` varchar(30) NOT NULL  AFTER `inquiryselect_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `owner_dept_id` varchar(30) NOT NULL  AFTER `request_dept_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `request_doc_id` varchar(30) NOT NULL  AFTER `owner_dept_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `orderout_dept_id` varchar(30) NOT NULL  AFTER `request_doc_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `orderout_doc_id` varchar(30) NOT NULL  AFTER `orderout_dept_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `trxmodel_id` varchar(30) NOT NULL  AFTER `orderout_doc_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `itemmanage_id` varchar(2) NOT NULL  AFTER `trxmodel_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_rejectnotes` varchar(255)   AFTER `itemmanage_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `doc_id` varchar(30) NOT NULL  AFTER `inquiry_rejectnotes`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_selectfield` varchar(6) NOT NULL DEFAULT 000000 AFTER `doc_id`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_version` int(4) NOT NULL DEFAULT 0 AFTER `inquiry_selectfield`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_isdateinterval` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_version`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_maxadvancevalue` decimal(12, 0) NOT NULL DEFAULT 0 AFTER `inquiry_isdateinterval`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_isallowadvance` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_maxadvancevalue`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_iscommit` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_isallowadvance`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_commitby` varchar(14)   AFTER `inquiry_iscommit`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_commitdate` datetime   AFTER `inquiry_commitby`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_isapprovalprogress` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_commitdate`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_isapproved` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_isapprovalprogress`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_approveby` varchar(14)   AFTER `inquiry_isapproved`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_approvedate` datetime   AFTER `inquiry_approveby`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_isdeclined` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_approvedate`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_declineby` varchar(14)   AFTER `inquiry_isdeclined`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_declinedate` datetime   AFTER `inquiry_declineby`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_ispreparing` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_declinedate`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_isprepared` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_ispreparing`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_preparedby` varchar(14)   AFTER `inquiry_isprepared`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_prepareddate` datetime   AFTER `inquiry_preparedby`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_isreject` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_prepareddate`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_rejectby` varchar(14)   AFTER `inquiry_isreject`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_rejectdate` datetime   AFTER `inquiry_rejectby`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_iscomplete` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_rejectdate`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_isclose` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_iscomplete`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_closeby` varchar(14)   AFTER `inquiry_isclose`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_closedate` datetime   AFTER `inquiry_closeby`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_isautogenerated` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_closedate`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_isitemdeptuser` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_isautogenerated`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_isitemdeptowner` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_isitemdeptuser`;
ALTER TABLE `trn_inquiry` MODIFY COLUMN IF EXISTS  `inquiry_istoberequest` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_isitemdeptowner`;



ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS `inquirytype_id` (`inquirytype_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS `user_dept_id` (`user_dept_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS `empl_id` (`empl_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS `project_id` (`project_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS `projecttask_id` (`projecttask_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS `projbudget_id` (`projbudget_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS `projbudgettask_id` (`projbudgettask_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS `site_id` (`site_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS  `inquirymodel_id` (`inquirymodel_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS  `inquiryselect_id` (`inquiryselect_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS  `request_dept_id` (`request_dept_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS  `owner_dept_id` (`owner_dept_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS  `request_doc_id` (`request_doc_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS  `orderout_dept_id` (`orderout_dept_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS  `orderout_doc_id` (`orderout_doc_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS  `trxmodel_id` (`trxmodel_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS  `itemmanage_id` (`itemmanage_id`);
ALTER TABLE `trn_inquiry` ADD KEY IF NOT EXISTS `doc_id` (`doc_id`);

ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_inquirytype` FOREIGN KEY IF NOT EXISTS  (`inquirytype_id`) REFERENCES `mst_inquirytype` (`inquirytype_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_dept` FOREIGN KEY IF NOT EXISTS  (`user_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_empl` FOREIGN KEY IF NOT EXISTS  (`empl_id`) REFERENCES `mst_empl` (`empl_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_project` FOREIGN KEY IF NOT EXISTS  (`project_id`) REFERENCES `mst_project` (`project_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_projecttask` FOREIGN KEY IF NOT EXISTS  (`projecttask_id`) REFERENCES `mst_projecttask` (`projecttask_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_projbudget` FOREIGN KEY IF NOT EXISTS  (`projbudget_id`) REFERENCES `mst_projbudget` (`projbudget_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_projbudgettask` FOREIGN KEY IF NOT EXISTS  (`projbudgettask_id`) REFERENCES `mst_projbudgettask` (`projbudgettask_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_site` FOREIGN KEY IF NOT EXISTS  (`site_id`) REFERENCES `mst_site` (`site_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_inquirymodel` FOREIGN KEY IF NOT EXISTS (`inquirymodel_id`) REFERENCES `mst_inquirymodel` (`inquirymodel_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_inquiryselect` FOREIGN KEY IF NOT EXISTS (`inquiryselect_id`) REFERENCES `mst_inquiryselect` (`inquiryselect_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_dept_2` FOREIGN KEY IF NOT EXISTS (`request_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_dept_3` FOREIGN KEY IF NOT EXISTS (`owner_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_doc` FOREIGN KEY IF NOT EXISTS (`request_doc_id`) REFERENCES `mst_doc` (`doc_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_dept_4` FOREIGN KEY IF NOT EXISTS (`orderout_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_doc_2` FOREIGN KEY IF NOT EXISTS (`orderout_doc_id`) REFERENCES `mst_doc` (`doc_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_trxmodel` FOREIGN KEY IF NOT EXISTS (`trxmodel_id`) REFERENCES `mst_trxmodel` (`trxmodel_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_itemmanage` FOREIGN KEY IF NOT EXISTS (`itemmanage_id`) REFERENCES `mst_itemmanage` (`itemmanage_id`);
ALTER TABLE `trn_inquiry` ADD CONSTRAINT `fk_trn_inquiry_mst_doc_3` FOREIGN KEY IF NOT EXISTS  (`doc_id`) REFERENCES `mst_doc` (`doc_id`);





CREATE TABLE IF NOT EXISTS `trn_inquiryitem` (
	`inquiryitem_id` varchar(14) NOT NULL , 
	`itemasset_id` varchar(14)  , 
	`item_id` varchar(14)  , 
	`itemstock_id` varchar(14)  , 
	`partner_id` varchar(30)  , 
	`itemclass_id` varchar(14) NOT NULL , 
	`inquirydetil_descr` varchar(255)  , 
	`inquirydetil_qty` int(4) NOT NULL DEFAULT 0, 
	`inquirydetil_days` int(4) NOT NULL DEFAULT 0, 
	`inquirydetil_task` int(4) NOT NULL DEFAULT 0, 
	`inquirydetil_qty_proc` int(4) NOT NULL DEFAULT 0, 
	`proc_trxmodel_id` varchar(10) NOT NULL , 
	`inquirydetil_qty_outstd` int(4) NOT NULL DEFAULT 0, 
	`outstd_trxmodel_id` varchar(10) NOT NULL , 
	`inquirydetil_estrate` decimal(12, 0) NOT NULL DEFAULT 0, 
	`inquirydetil_estvalue` int(14) NOT NULL DEFAULT 0, 
	`inquiryitem_isconfirm` tinyint(1) NOT NULL DEFAULT 0, 
	`projbudgetdet_id` varchar(30)  , 
	`inquirydetil_isunbudget` tinyint(1) NOT NULL DEFAULT 0, 
	`inquirydetil_isallowoverbudget` tinyint(1) NOT NULL DEFAULT 0, 
	`accbudget_id` varchar(20)  , 
	`coa_id` varchar(17)  , 
	`inquirydetil_id` varchar(14) NOT NULL , 
	`inquiry_id` varchar(14) NOT NULL , 
	`_createby` varchar(13) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(13)  , 
	`_modifydate` datetime  , 
	PRIMARY KEY (`inquiryitem_id`)
) 
ENGINE=InnoDB
COMMENT='Breakdown Item yang diinquiry';


ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `itemasset_id` varchar(14)   AFTER `inquiryitem_id`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `item_id` varchar(14)   AFTER `itemasset_id`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `itemstock_id` varchar(14)   AFTER `item_id`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `partner_id` varchar(30)   AFTER `itemstock_id`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `itemclass_id` varchar(14) NOT NULL  AFTER `partner_id`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `inquirydetil_descr` varchar(255)   AFTER `itemclass_id`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `inquirydetil_qty` int(4) NOT NULL DEFAULT 0 AFTER `inquirydetil_descr`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `inquirydetil_days` int(4) NOT NULL DEFAULT 0 AFTER `inquirydetil_qty`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `inquirydetil_task` int(4) NOT NULL DEFAULT 0 AFTER `inquirydetil_days`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `inquirydetil_qty_proc` int(4) NOT NULL DEFAULT 0 AFTER `inquirydetil_task`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `proc_trxmodel_id` varchar(10) NOT NULL  AFTER `inquirydetil_qty_proc`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `inquirydetil_qty_outstd` int(4) NOT NULL DEFAULT 0 AFTER `proc_trxmodel_id`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `outstd_trxmodel_id` varchar(10) NOT NULL  AFTER `inquirydetil_qty_outstd`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `inquirydetil_estrate` decimal(12, 0) NOT NULL DEFAULT 0 AFTER `outstd_trxmodel_id`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `inquirydetil_estvalue` int(14) NOT NULL DEFAULT 0 AFTER `inquirydetil_estrate`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `inquiryitem_isconfirm` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquirydetil_estvalue`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `projbudgetdet_id` varchar(30)   AFTER `inquiryitem_isconfirm`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `inquirydetil_isunbudget` tinyint(1) NOT NULL DEFAULT 0 AFTER `projbudgetdet_id`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `inquirydetil_isallowoverbudget` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquirydetil_isunbudget`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `accbudget_id` varchar(20)   AFTER `inquirydetil_isallowoverbudget`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `coa_id` varchar(17)   AFTER `accbudget_id`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `inquirydetil_id` varchar(14) NOT NULL  AFTER `coa_id`;
ALTER TABLE `trn_inquiryitem` ADD COLUMN IF NOT EXISTS  `inquiry_id` varchar(14) NOT NULL  AFTER `inquirydetil_id`;


ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `itemasset_id` varchar(14)   AFTER `inquiryitem_id`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `item_id` varchar(14)   AFTER `itemasset_id`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `itemstock_id` varchar(14)   AFTER `item_id`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `partner_id` varchar(30)   AFTER `itemstock_id`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `itemclass_id` varchar(14) NOT NULL  AFTER `partner_id`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `inquirydetil_descr` varchar(255)   AFTER `itemclass_id`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `inquirydetil_qty` int(4) NOT NULL DEFAULT 0 AFTER `inquirydetil_descr`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `inquirydetil_days` int(4) NOT NULL DEFAULT 0 AFTER `inquirydetil_qty`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `inquirydetil_task` int(4) NOT NULL DEFAULT 0 AFTER `inquirydetil_days`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `inquirydetil_qty_proc` int(4) NOT NULL DEFAULT 0 AFTER `inquirydetil_task`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `proc_trxmodel_id` varchar(10) NOT NULL  AFTER `inquirydetil_qty_proc`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `inquirydetil_qty_outstd` int(4) NOT NULL DEFAULT 0 AFTER `proc_trxmodel_id`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `outstd_trxmodel_id` varchar(10) NOT NULL  AFTER `inquirydetil_qty_outstd`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `inquirydetil_estrate` decimal(12, 0) NOT NULL DEFAULT 0 AFTER `outstd_trxmodel_id`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `inquirydetil_estvalue` int(14) NOT NULL DEFAULT 0 AFTER `inquirydetil_estrate`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `inquiryitem_isconfirm` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquirydetil_estvalue`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `projbudgetdet_id` varchar(30)   AFTER `inquiryitem_isconfirm`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `inquirydetil_isunbudget` tinyint(1) NOT NULL DEFAULT 0 AFTER `projbudgetdet_id`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `inquirydetil_isallowoverbudget` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquirydetil_isunbudget`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `accbudget_id` varchar(20)   AFTER `inquirydetil_isallowoverbudget`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `coa_id` varchar(17)   AFTER `accbudget_id`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `inquirydetil_id` varchar(14) NOT NULL  AFTER `coa_id`;
ALTER TABLE `trn_inquiryitem` MODIFY COLUMN IF EXISTS  `inquiry_id` varchar(14) NOT NULL  AFTER `inquirydetil_id`;



ALTER TABLE `trn_inquiryitem` ADD KEY IF NOT EXISTS `itemasset_id` (`itemasset_id`);
ALTER TABLE `trn_inquiryitem` ADD KEY IF NOT EXISTS `item_id` (`item_id`);
ALTER TABLE `trn_inquiryitem` ADD KEY IF NOT EXISTS `itemstock_id` (`itemstock_id`);
ALTER TABLE `trn_inquiryitem` ADD KEY IF NOT EXISTS `partner_id` (`partner_id`);
ALTER TABLE `trn_inquiryitem` ADD KEY IF NOT EXISTS `itemclass_id` (`itemclass_id`);
ALTER TABLE `trn_inquiryitem` ADD KEY IF NOT EXISTS `proc_trxmodel_id` (`proc_trxmodel_id`);
ALTER TABLE `trn_inquiryitem` ADD KEY IF NOT EXISTS `outstd_trxmodel_id` (`outstd_trxmodel_id`);
ALTER TABLE `trn_inquiryitem` ADD KEY IF NOT EXISTS `projbudgetdet_id` (`projbudgetdet_id`);
ALTER TABLE `trn_inquiryitem` ADD KEY IF NOT EXISTS  `accbudget_id` (`accbudget_id`);
ALTER TABLE `trn_inquiryitem` ADD KEY IF NOT EXISTS  `coa_id` (`coa_id`);
ALTER TABLE `trn_inquiryitem` ADD KEY IF NOT EXISTS  `inquirydetil_id` (`inquirydetil_id`);
ALTER TABLE `trn_inquiryitem` ADD KEY IF NOT EXISTS `inquiry_id` (`inquiry_id`);

ALTER TABLE `trn_inquiryitem` ADD CONSTRAINT `fk_trn_inquiryitem_mst_itemasset` FOREIGN KEY IF NOT EXISTS  (`itemasset_id`) REFERENCES `mst_itemasset` (`itemasset_id`);
ALTER TABLE `trn_inquiryitem` ADD CONSTRAINT `fk_trn_inquiryitem_mst_item` FOREIGN KEY IF NOT EXISTS  (`item_id`) REFERENCES `mst_item` (`item_id`);
ALTER TABLE `trn_inquiryitem` ADD CONSTRAINT `fk_trn_inquiryitem_mst_itemstock` FOREIGN KEY IF NOT EXISTS  (`itemstock_id`) REFERENCES `mst_itemstock` (`itemstock_id`);
ALTER TABLE `trn_inquiryitem` ADD CONSTRAINT `fk_trn_inquiryitem_mst_partner` FOREIGN KEY IF NOT EXISTS  (`partner_id`) REFERENCES `mst_partner` (`partner_id`);
ALTER TABLE `trn_inquiryitem` ADD CONSTRAINT `fk_trn_inquiryitem_mst_itemclass` FOREIGN KEY IF NOT EXISTS  (`itemclass_id`) REFERENCES `mst_itemclass` (`itemclass_id`);
ALTER TABLE `trn_inquiryitem` ADD CONSTRAINT `fk_trn_inquiryitem_mst_trxmodel` FOREIGN KEY IF NOT EXISTS  (`proc_trxmodel_id`) REFERENCES `mst_trxmodel` (`trxmodel_id`);
ALTER TABLE `trn_inquiryitem` ADD CONSTRAINT `fk_trn_inquiryitem_mst_trxmodel_2` FOREIGN KEY IF NOT EXISTS  (`outstd_trxmodel_id`) REFERENCES `mst_trxmodel` (`trxmodel_id`);
ALTER TABLE `trn_inquiryitem` ADD CONSTRAINT `fk_trn_inquiryitem_mst_projbudgetdet` FOREIGN KEY IF NOT EXISTS  (`projbudgetdet_id`) REFERENCES `mst_projbudgetdet` (`projbudgetdet_id`);
ALTER TABLE `trn_inquiryitem` ADD CONSTRAINT `fk_trn_inquiryitem_mst_accbudget` FOREIGN KEY IF NOT EXISTS (`accbudget_id`) REFERENCES `mst_accbudget` (`accbudget_id`);
ALTER TABLE `trn_inquiryitem` ADD CONSTRAINT `fk_trn_inquiryitem_mst_coa` FOREIGN KEY IF NOT EXISTS (`coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_inquiryitem` ADD CONSTRAINT `fk_trn_inquiryitem_trn_inquirydetil` FOREIGN KEY IF NOT EXISTS (`inquirydetil_id`) REFERENCES `trn_inquirydetil` (`inquirydetil_id`);
ALTER TABLE `trn_inquiryitem` ADD CONSTRAINT `fk_trn_inquiryitem_trn_inquiry` FOREIGN KEY IF NOT EXISTS (`inquiry_id`) REFERENCES `trn_inquiry` (`inquiry_id`);





CREATE TABLE IF NOT EXISTS `trn_inquirydetil` (
	`inquirydetil_id` varchar(14) NOT NULL , 
	`itemasset_id` varchar(14)  , 
	`item_id` varchar(14)  , 
	`itemstock_id` varchar(14)  , 
	`partner_id` varchar(30)  , 
	`itemclass_id` varchar(14) NOT NULL , 
	`inquirydetil_descr` varchar(255)  , 
	`inquirydetil_qty` int(4) NOT NULL DEFAULT 0, 
	`inquirydetil_days` int(4) NOT NULL DEFAULT 0, 
	`inquirydetil_task` int(4) NOT NULL DEFAULT 0, 
	`inquirydetil_estrate` decimal(12, 0) NOT NULL DEFAULT 0, 
	`inquirydetil_estvalue` int(14) NOT NULL DEFAULT 0, 
	`projbudgetdet_id` varchar(30)  , 
	`inquirydetil_isunbudget` tinyint(1) NOT NULL DEFAULT 0, 
	`inquirydetil_isallowoverbudget` tinyint(1) NOT NULL DEFAULT 0, 
	`inquirydetil_qtyavailable` int(4) NOT NULL DEFAULT 0, 
	`accbudget_id` varchar(20)  , 
	`coa_id` varchar(17)  , 
	`inquiry_id` varchar(14) NOT NULL , 
	`_createby` varchar(13) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(13)  , 
	`_modifydate` datetime  , 
	PRIMARY KEY (`inquirydetil_id`)
) 
ENGINE=InnoDB
COMMENT='Itemclass yang akan di-inquiry';


ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `itemasset_id` varchar(14)   AFTER `inquirydetil_id`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `item_id` varchar(14)   AFTER `itemasset_id`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `itemstock_id` varchar(14)   AFTER `item_id`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `partner_id` varchar(30)   AFTER `itemstock_id`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `itemclass_id` varchar(14) NOT NULL  AFTER `partner_id`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `inquirydetil_descr` varchar(255)   AFTER `itemclass_id`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `inquirydetil_qty` int(4) NOT NULL DEFAULT 0 AFTER `inquirydetil_descr`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `inquirydetil_days` int(4) NOT NULL DEFAULT 0 AFTER `inquirydetil_qty`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `inquirydetil_task` int(4) NOT NULL DEFAULT 0 AFTER `inquirydetil_days`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `inquirydetil_estrate` decimal(12, 0) NOT NULL DEFAULT 0 AFTER `inquirydetil_task`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `inquirydetil_estvalue` int(14) NOT NULL DEFAULT 0 AFTER `inquirydetil_estrate`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `projbudgetdet_id` varchar(30)   AFTER `inquirydetil_estvalue`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `inquirydetil_isunbudget` tinyint(1) NOT NULL DEFAULT 0 AFTER `projbudgetdet_id`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `inquirydetil_isallowoverbudget` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquirydetil_isunbudget`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `inquirydetil_qtyavailable` int(4) NOT NULL DEFAULT 0 AFTER `inquirydetil_isallowoverbudget`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `accbudget_id` varchar(20)   AFTER `inquirydetil_qtyavailable`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `coa_id` varchar(17)   AFTER `accbudget_id`;
ALTER TABLE `trn_inquirydetil` ADD COLUMN IF NOT EXISTS  `inquiry_id` varchar(14) NOT NULL  AFTER `coa_id`;


ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `itemasset_id` varchar(14)   AFTER `inquirydetil_id`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `item_id` varchar(14)   AFTER `itemasset_id`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `itemstock_id` varchar(14)   AFTER `item_id`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `partner_id` varchar(30)   AFTER `itemstock_id`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `itemclass_id` varchar(14) NOT NULL  AFTER `partner_id`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `inquirydetil_descr` varchar(255)   AFTER `itemclass_id`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `inquirydetil_qty` int(4) NOT NULL DEFAULT 0 AFTER `inquirydetil_descr`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `inquirydetil_days` int(4) NOT NULL DEFAULT 0 AFTER `inquirydetil_qty`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `inquirydetil_task` int(4) NOT NULL DEFAULT 0 AFTER `inquirydetil_days`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `inquirydetil_estrate` decimal(12, 0) NOT NULL DEFAULT 0 AFTER `inquirydetil_task`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `inquirydetil_estvalue` int(14) NOT NULL DEFAULT 0 AFTER `inquirydetil_estrate`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `projbudgetdet_id` varchar(30)   AFTER `inquirydetil_estvalue`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `inquirydetil_isunbudget` tinyint(1) NOT NULL DEFAULT 0 AFTER `projbudgetdet_id`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `inquirydetil_isallowoverbudget` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquirydetil_isunbudget`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `inquirydetil_qtyavailable` int(4) NOT NULL DEFAULT 0 AFTER `inquirydetil_isallowoverbudget`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `accbudget_id` varchar(20)   AFTER `inquirydetil_qtyavailable`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `coa_id` varchar(17)   AFTER `accbudget_id`;
ALTER TABLE `trn_inquirydetil` MODIFY COLUMN IF EXISTS  `inquiry_id` varchar(14) NOT NULL  AFTER `coa_id`;



ALTER TABLE `trn_inquirydetil` ADD KEY IF NOT EXISTS `itemasset_id` (`itemasset_id`);
ALTER TABLE `trn_inquirydetil` ADD KEY IF NOT EXISTS `item_id` (`item_id`);
ALTER TABLE `trn_inquirydetil` ADD KEY IF NOT EXISTS `itemstock_id` (`itemstock_id`);
ALTER TABLE `trn_inquirydetil` ADD KEY IF NOT EXISTS `partner_id` (`partner_id`);
ALTER TABLE `trn_inquirydetil` ADD KEY IF NOT EXISTS `itemclass_id` (`itemclass_id`);
ALTER TABLE `trn_inquirydetil` ADD KEY IF NOT EXISTS `projbudgetdet_id` (`projbudgetdet_id`);
ALTER TABLE `trn_inquirydetil` ADD KEY IF NOT EXISTS  `accbudget_id` (`accbudget_id`);
ALTER TABLE `trn_inquirydetil` ADD KEY IF NOT EXISTS  `coa_id` (`coa_id`);
ALTER TABLE `trn_inquirydetil` ADD KEY IF NOT EXISTS `inquiry_id` (`inquiry_id`);

ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_mst_itemasset` FOREIGN KEY IF NOT EXISTS  (`itemasset_id`) REFERENCES `mst_itemasset` (`itemasset_id`);
ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_mst_item` FOREIGN KEY IF NOT EXISTS  (`item_id`) REFERENCES `mst_item` (`item_id`);
ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_mst_itemstock` FOREIGN KEY IF NOT EXISTS  (`itemstock_id`) REFERENCES `mst_itemstock` (`itemstock_id`);
ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_mst_partner` FOREIGN KEY IF NOT EXISTS  (`partner_id`) REFERENCES `mst_partner` (`partner_id`);
ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_mst_itemclass` FOREIGN KEY IF NOT EXISTS  (`itemclass_id`) REFERENCES `mst_itemclass` (`itemclass_id`);
ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_mst_projbudgetdet` FOREIGN KEY IF NOT EXISTS  (`projbudgetdet_id`) REFERENCES `mst_projbudgetdet` (`projbudgetdet_id`);
ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_mst_accbudget` FOREIGN KEY IF NOT EXISTS (`accbudget_id`) REFERENCES `mst_accbudget` (`accbudget_id`);
ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_mst_coa` FOREIGN KEY IF NOT EXISTS (`coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_inquirydetil` ADD CONSTRAINT `fk_trn_inquirydetil_trn_inquiry` FOREIGN KEY IF NOT EXISTS (`inquiry_id`) REFERENCES `trn_inquiry` (`inquiry_id`);





CREATE TABLE IF NOT EXISTS `trn_inquiryfiles` (
	`inquiryfiles_id` varchar(14) NOT NULL , 
	`doctype_id` varchar(10) NOT NULL , 
	`inquiryfiles_descr` varchar(90) NOT NULL , 
	`inquiryfiles_order` int(4) NOT NULL DEFAULT 0, 
	`inquiryfiles_file` varchar(90)  , 
	`inquiry_id` varchar(14) NOT NULL , 
	`_createby` varchar(13) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(13)  , 
	`_modifydate` datetime  , 
	UNIQUE KEY `inquiryfiles_doc` (`inquiry_id`, `doctype_id`),
	PRIMARY KEY (`inquiryfiles_id`)
) 
ENGINE=InnoDB
COMMENT='Daftar FIle Inquiry';


ALTER TABLE `trn_inquiryfiles` ADD COLUMN IF NOT EXISTS  `doctype_id` varchar(10) NOT NULL  AFTER `inquiryfiles_id`;
ALTER TABLE `trn_inquiryfiles` ADD COLUMN IF NOT EXISTS  `inquiryfiles_descr` varchar(90) NOT NULL  AFTER `doctype_id`;
ALTER TABLE `trn_inquiryfiles` ADD COLUMN IF NOT EXISTS  `inquiryfiles_order` int(4) NOT NULL DEFAULT 0 AFTER `inquiryfiles_descr`;
ALTER TABLE `trn_inquiryfiles` ADD COLUMN IF NOT EXISTS  `inquiryfiles_file` varchar(90)   AFTER `inquiryfiles_order`;
ALTER TABLE `trn_inquiryfiles` ADD COLUMN IF NOT EXISTS  `inquiry_id` varchar(14) NOT NULL  AFTER `inquiryfiles_file`;


ALTER TABLE `trn_inquiryfiles` MODIFY COLUMN IF EXISTS  `doctype_id` varchar(10) NOT NULL  AFTER `inquiryfiles_id`;
ALTER TABLE `trn_inquiryfiles` MODIFY COLUMN IF EXISTS  `inquiryfiles_descr` varchar(90) NOT NULL  AFTER `doctype_id`;
ALTER TABLE `trn_inquiryfiles` MODIFY COLUMN IF EXISTS  `inquiryfiles_order` int(4) NOT NULL DEFAULT 0 AFTER `inquiryfiles_descr`;
ALTER TABLE `trn_inquiryfiles` MODIFY COLUMN IF EXISTS  `inquiryfiles_file` varchar(90)   AFTER `inquiryfiles_order`;
ALTER TABLE `trn_inquiryfiles` MODIFY COLUMN IF EXISTS  `inquiry_id` varchar(14) NOT NULL  AFTER `inquiryfiles_file`;


ALTER TABLE `trn_inquiryfiles` ADD CONSTRAINT `inquiryfiles_doc` UNIQUE IF NOT EXISTS  (`inquiry_id`, `doctype_id`);

ALTER TABLE `trn_inquiryfiles` ADD KEY IF NOT EXISTS `doctype_id` (`doctype_id`);
ALTER TABLE `trn_inquiryfiles` ADD KEY IF NOT EXISTS `inquiry_id` (`inquiry_id`);

ALTER TABLE `trn_inquiryfiles` ADD CONSTRAINT `fk_trn_inquiryfiles_mst_doctype` FOREIGN KEY IF NOT EXISTS  (`doctype_id`) REFERENCES `mst_doctype` (`doctype_id`);
ALTER TABLE `trn_inquiryfiles` ADD CONSTRAINT `fk_trn_inquiryfiles_trn_inquiry` FOREIGN KEY IF NOT EXISTS (`inquiry_id`) REFERENCES `trn_inquiry` (`inquiry_id`);





CREATE TABLE IF NOT EXISTS `trn_inquiryappr` (
	`inquiryappr_id` varchar(14) NOT NULL , 
	`inquiryappr_isapproved` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiryappr_by` varchar(14)  , 
	`inquiryappr_date` datetime  , 
	`inquiry_version` int(4) NOT NULL DEFAULT 0, 
	`inquiryappr_isdeclined` tinyint(1) NOT NULL DEFAULT 0, 
	`inquiryappr_declinedby` varchar(14)  , 
	`inquiryappr_declineddate` datetime  , 
	`inquiryappr_notes` varchar(255)  , 
	`inquiry_id` varchar(30) NOT NULL , 
	`docauth_descr` varchar(90)  , 
	`docauth_order` int(4) NOT NULL DEFAULT 0, 
	`docauth_value` int(4) NOT NULL DEFAULT 100, 
	`docauth_min` int(4) NOT NULL DEFAULT 0, 
	`authlevel_id` varchar(10) NOT NULL , 
	`authlevel_name` varchar(60) NOT NULL , 
	`auth_id` varchar(10)  , 
	`auth_name` varchar(60) NOT NULL , 
	`_createby` varchar(13) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(13)  , 
	`_modifydate` datetime  , 
	UNIQUE KEY `inquiry_auth_id` (`inquiry_id`, `auth_id`),
	PRIMARY KEY (`inquiryappr_id`)
) 
ENGINE=InnoDB
COMMENT='Approval undefined';


ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `inquiryappr_isapproved` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiryappr_id`;
ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `inquiryappr_by` varchar(14)   AFTER `inquiryappr_isapproved`;
ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `inquiryappr_date` datetime   AFTER `inquiryappr_by`;
ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `inquiry_version` int(4) NOT NULL DEFAULT 0 AFTER `inquiryappr_date`;
ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `inquiryappr_isdeclined` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_version`;
ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `inquiryappr_declinedby` varchar(14)   AFTER `inquiryappr_isdeclined`;
ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `inquiryappr_declineddate` datetime   AFTER `inquiryappr_declinedby`;
ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `inquiryappr_notes` varchar(255)   AFTER `inquiryappr_declineddate`;
ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `inquiry_id` varchar(30) NOT NULL  AFTER `inquiryappr_notes`;
ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `docauth_descr` varchar(90)   AFTER `inquiry_id`;
ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `docauth_order` int(4) NOT NULL DEFAULT 0 AFTER `docauth_descr`;
ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `docauth_value` int(4) NOT NULL DEFAULT 100 AFTER `docauth_order`;
ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `docauth_min` int(4) NOT NULL DEFAULT 0 AFTER `docauth_value`;
ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `authlevel_id` varchar(10) NOT NULL  AFTER `docauth_min`;
ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `authlevel_name` varchar(60) NOT NULL  AFTER `authlevel_id`;
ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `auth_id` varchar(10)   AFTER `authlevel_name`;
ALTER TABLE `trn_inquiryappr` ADD COLUMN IF NOT EXISTS  `auth_name` varchar(60) NOT NULL  AFTER `auth_id`;


ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `inquiryappr_isapproved` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiryappr_id`;
ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `inquiryappr_by` varchar(14)   AFTER `inquiryappr_isapproved`;
ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `inquiryappr_date` datetime   AFTER `inquiryappr_by`;
ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `inquiry_version` int(4) NOT NULL DEFAULT 0 AFTER `inquiryappr_date`;
ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `inquiryappr_isdeclined` tinyint(1) NOT NULL DEFAULT 0 AFTER `inquiry_version`;
ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `inquiryappr_declinedby` varchar(14)   AFTER `inquiryappr_isdeclined`;
ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `inquiryappr_declineddate` datetime   AFTER `inquiryappr_declinedby`;
ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `inquiryappr_notes` varchar(255)   AFTER `inquiryappr_declineddate`;
ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `inquiry_id` varchar(30) NOT NULL  AFTER `inquiryappr_notes`;
ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `docauth_descr` varchar(90)   AFTER `inquiry_id`;
ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `docauth_order` int(4) NOT NULL DEFAULT 0 AFTER `docauth_descr`;
ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `docauth_value` int(4) NOT NULL DEFAULT 100 AFTER `docauth_order`;
ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `docauth_min` int(4) NOT NULL DEFAULT 0 AFTER `docauth_value`;
ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `authlevel_id` varchar(10) NOT NULL  AFTER `docauth_min`;
ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `authlevel_name` varchar(60) NOT NULL  AFTER `authlevel_id`;
ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `auth_id` varchar(10)   AFTER `authlevel_name`;
ALTER TABLE `trn_inquiryappr` MODIFY COLUMN IF EXISTS  `auth_name` varchar(60) NOT NULL  AFTER `auth_id`;


ALTER TABLE `trn_inquiryappr` ADD CONSTRAINT `inquiry_auth_id` UNIQUE IF NOT EXISTS  (`inquiry_id`, `auth_id`);

ALTER TABLE `trn_inquiryappr` ADD KEY IF NOT EXISTS `inquiry_id` (`inquiry_id`);

ALTER TABLE `trn_inquiryappr` ADD CONSTRAINT `fk_trn_inquiryappr_trn_inquiry` FOREIGN KEY IF NOT EXISTS (`inquiry_id`) REFERENCES `trn_inquiry` (`inquiry_id`);





