<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit AsetMove Type</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row txt_itemassetmovetype_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemassetmovetype_id" class="easyui-textbox" mapping="itemassetmovetype_id" uppercase="true" maxlength="14" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'ID harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_itemassetmovetype_name" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Asset Move Type</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemassetmovetype_name" class="easyui-textbox" mapping="itemassetmovetype_name" uppercase="true" maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Nama Tipe Asset Move harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_itemassetmovetype_descr" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemassetmovetype_descr" class="easyui-textbox" mapping="itemassetmovetype_descr"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_itemassetmovemodel_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Asset Move Model</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_itemassetmovemodel_id" class="easyui-combo" style="width: 400px" mapping="itemassetmovemodel_id" display="itemassetmovemodel_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Model Asset Move harus diisi'"   validType="requiredcombo['pnl_edit-cbo_itemassetmovemodel_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_trxmodel_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Transaction</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_trxmodel_id" class="easyui-combo" style="width: 400px" mapping="trxmodel_id" display="trxmodel_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Model Transaksi harus diisi'"   validType="requiredcombo['pnl_edit-cbo_trxmodel_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemassetmovetype_isdateinterval" >
			<div class="form_label_col">Range</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemassetmovetype_isdateinterval" class="easyui-checkbox c1" mapping="itemassetmovetype_isdateinterval" data-options="label: 'Date Interval', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemassetmovetype_isdept" >
			<div class="form_label_col">Mandatory</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemassetmovetype_isdept" class="easyui-checkbox c1" mapping="itemassetmovetype_isdept" data-options="label: 'Dept', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemassetmovetype_isemployee" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemassetmovetype_isemployee" class="easyui-checkbox c1" mapping="itemassetmovetype_isemployee" data-options="label: 'Employee', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemassetmovetype_issite" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemassetmovetype_issite" class="easyui-checkbox c1" mapping="itemassetmovetype_issite" data-options="label: 'Site', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemassetmovetype_isroom" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemassetmovetype_isroom" class="easyui-checkbox c1" mapping="itemassetmovetype_isroom" data-options="label: 'Room', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
			
			
			
			
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

