<div id="pnl_edititemgrid">
	<div class="fgta-page-title">Daftar Budget Items</div>
	<div id="pnl_edititemgrid-title" class="fgta-page-subtitle">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_edititemgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_edititemgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_edititemgrid-btn_load" class="easyui-linkbutton c8 fgta-button-listload" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->


	<?php
	$customheadpanel = __DIR__.'/budgetdeptprop-itemgrid-customheadpanel.phtml';
	if (is_file($customheadpanel)) {
		include $customheadpanel;
	} 
	?>

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_edititemgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<?php
			$customview = __DIR__.'/budgetdeptprop-itemgrid-customview.phtml'; 
			if (is_file($customview)) {
				include $customview;
			} else { ?>
			<thead>

				<tr>
<th type="check">chk</th>					
					<th mapping="budgetdeptpropitem_id">budgetdeptpropitem_id</th>
					<th mapping="coabudget_dept_name">coabudget_dept_name</th>
					<th mapping="dept_name">dept_name</th>
					<th mapping="budgetdeptpropitem_descr">budgetdeptpropitem_descr</th>
					<th mapping="budgetdeptmonth_01" style="text-align: right" formatter="row_format_number">budgetdeptmonth_01</th>
					<th mapping="budgetdeptmonth_02" style="text-align: right" formatter="row_format_number">budgetdeptmonth_02</th>
					<th mapping="budgetdeptmonth_03" style="text-align: right" formatter="row_format_number">budgetdeptmonth_03</th>
					<th mapping="budgetdeptmonth_04" style="text-align: right" formatter="row_format_number">budgetdeptmonth_04</th>
					<th mapping="budgetdeptmonth_05" style="text-align: right" formatter="row_format_number">budgetdeptmonth_05</th>
					<th mapping="budgetdeptmonth_06" style="text-align: right" formatter="row_format_number">budgetdeptmonth_06</th>
					<th mapping="budgetdeptmonth_07" style="text-align: right" formatter="row_format_number">budgetdeptmonth_07</th>
					<th mapping="budgetdeptmonth_08" style="text-align: right" formatter="row_format_number">budgetdeptmonth_08</th>
					<th mapping="budgetdeptmonth_09" style="text-align: right" formatter="row_format_number">budgetdeptmonth_09</th>
					<th mapping="budgetdeptmonth_10" style="text-align: right" formatter="row_format_number">budgetdeptmonth_10</th>
					<th mapping="budgetdeptmonth_11" style="text-align: right" formatter="row_format_number">budgetdeptmonth_11</th>
					<th mapping="budgetdeptmonth_12" style="text-align: right" formatter="row_format_number">budgetdeptmonth_12</th>

					<th mapping=""></th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
<td class="fgtable-head rowcheck" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Budget</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Dept</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Descr</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Jan</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Feb</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Mar</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Apr</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">May</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Jun</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Jul</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Ags</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Sep</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Oct</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Nov</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Des</td>

					<td class="fgtable-head" style="border-bottom: 1px solid #000000; text-align: center">&nbsp;</td>
				</tr>
			</thead>
			<?php } ?>
			
			<?php
			$tablefooter = __DIR__.'/budgetdeptprop-itemgrid-tablefooter.phtml';
			if (is_file($tablefooter)) {
				include $tablefooter;
			} 
			?>
			
		</table>
	</div>



	<div class="pnl_edititemgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_edititemgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8 fgta-button-rowdel">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_edititemgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8 fgta-button-rowadd">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>



	<?php
	$customfootpanel = __DIR__.'/budgetdeptprop-itemgrid-customfootpanel.phtml';
	if (is_file($customfootpanel)) {
		include $customfootpanel;
	} 
	?>

</div>	
