<div  style="display: flex; justify-content: space-between">
	<div style="display: flex">
		<div id="pnl_list-obj_pastebox" class="pastebox head-editable-toggle" contenteditable placeholder="Paste template disini..." oninput="if(this.innerHTML.trim()==='<br>')this.innerHTML=''" ></div>
	</div>
	<div>
		<a id="pnl_list-btn_download" href="javascript:void(0)" class="easyui-linkbutton head-editable-toggle">Download Template</a>
	</div>
</div>