<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_edit-caption">{{STATE_BEG}}Item Class{{STATE_END}}</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemclass_id" class="easyui-textbox" mapping="itemclass_id"  maxlength="14" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Model</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_itemmodel_id" class="easyui-combo" style="width: 400px" mapping="itemmodel_id" display="itemmodel_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Model harus diisi'"   validType="requiredcombo['pnl_edit-cbo_itemmodel_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Manage As</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_itemmanage_id" class="easyui-combo" style="width: 400px" mapping="itemmanage_id" display="itemmanage_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Order Doc harus diisi'"   validType="requiredcombo['pnl_edit-cbo_itemmanage_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Item Class Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemclass_name" class="easyui-textbox" mapping="itemclass_name" uppercase="true" maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Nama Klasifikasi item harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemclass_isdisabled" class="easyui-checkbox c1" mapping="itemclass_isdisabled" data-options="label: 'Disabled', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemclass_isadvproces" class="easyui-checkbox c1" mapping="itemclass_isadvproces" data-options="label: 'Process as Advance', labelPosition: 'after', checked: false , labelWidth: '200px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemclass_descr" class="easyui-textbox" mapping="itemclass_descr"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Class Group</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_itemclassgroup_id" class="easyui-combo" style="width: 400px" mapping="itemclassgroup_id" display="itemclassgroup_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Default Unit</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_owner_unit_id" class="easyui-combo" style="width: 400px" mapping="owner_unit_id" display="owner_unit_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;">apabila dikosongkan, saat transaksi, unit akan diisi sesuai data unit pada transaksi</div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Default Owner Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_owner_dept_id" class="easyui-combo" style="width: 400px" mapping="owner_dept_id" display="owner_dept_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;">apabila dikosongkan, saat transaksi, dept akan diisi sesuai data dept pada transaksi</div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Maintainer</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_maintainer_dept_id" class="easyui-combo" style="width: 400px" mapping="maintainer_dept_id" display="maintainer_dept_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;">Maintainer Dept yang akan manage distribusi tipe item ini</div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Unit of Measurement</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_unitmeasurement_id" class="easyui-combo" style="width: 400px" mapping="unitmeasurement_id" display="unitmeasurement_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Unit Measurement harus diisi'"   validType="requiredcombo['pnl_edit-cbo_unitmeasurement_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row assetpanel assetpanel-hide" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">If Value More Than</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemclass_minassetvalue" class="easyui-numberbox" mapping="itemclass_minassetvalue" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Inquiry Budget</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_inquiry_accbudget_id" class="easyui-combo" style="width: 400px" mapping="inquiry_accbudget_id" display="inquiry_accbudget_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Account BS</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_nr_coa_id" class="easyui-combo" style="width: 400px" mapping="nr_coa_id" display="settl_coa_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;">Ivnentory / Persediaan, Asset</div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Account IS</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_lr_coa_id" class="easyui-combo" style="width: 400px" mapping="lr_coa_id" display="cost_coa_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;">Account Cost / Amortisasi / Depresiasi (asset)</div>
			</div>
		</div>

		<div class="form_row pnl_edit_row assetpanel assetpanel-hide" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Depresiasi</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_depremodel_id" class="easyui-combo" style="width: 400px" mapping="depremodel_id" display="depremodel_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row assetpanel assetpanel-hide" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Depre Age</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemclass_depreage" class="easyui-numberbox" mapping="itemclass_depreage" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row assetpanel assetpanel-hide" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Depre Residu</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemclass_depreresidu" class="easyui-numberbox" mapping="itemclass_depreresidu" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col">Budget Restriction</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemclass_isallowoverqty" class="easyui-checkbox c1" mapping="itemclass_isallowoverqty" data-options="label: 'Allow over qty from Budget', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemclass_isallowoverdays" class="easyui-checkbox c1" mapping="itemclass_isallowoverdays" data-options="label: 'Allow over days from Budget', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemclass_isallowovertask" class="easyui-checkbox c1" mapping="itemclass_isallowovertask" data-options="label: 'Allow over task from Budget', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemclass_isallowovervalue" class="easyui-checkbox c1" mapping="itemclass_isallowovervalue" data-options="label: 'Allow over value from Budgett', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemclass_isallowunbudget" class="easyui-checkbox c1" mapping="itemclass_isallowunbudget" data-options="label: 'Allow Request UnBudgeted', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<?=$this->SectionBegin('Item Settings', true, true, '')?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edit_row" >
			<div class="form_label_col">Current Setting</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemclass_isindependentsetting" class="easyui-checkbox c1" mapping="itemclass_isindependentsetting" data-options="label: 'Independent', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemmodel_isintangible" class="easyui-checkbox c1" mapping="itemmodel_isintangible" data-options="label: 'Intangiable', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemmodel_issellable" class="easyui-checkbox c1" mapping="itemmodel_issellable" data-options="label: 'Sellable', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemmodel_isnonitem" class="easyui-checkbox c1" mapping="itemmodel_isnonitem" data-options="label: 'Non Item', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemmodel_ishasmainteinerdept" class="easyui-checkbox c1" mapping="itemmodel_ishasmainteinerdept" data-options="label: 'Has Maintainer Dept', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemmanage_isasset" class="easyui-checkbox c1" mapping="itemmanage_isasset" data-options="label: 'Manage As Asset ', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_depremodel_isautocalc" class="easyui-checkbox c1" mapping="depremodel_isautocalc" data-options="label: 'Auto Calculate Depre', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col">Dept Filter</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemmanage_isbyassetowner" class="easyui-checkbox c1" mapping="itemmanage_isbyassetowner" data-options="label: 'By Asset Owner', labelPosition: 'after', checked: false , labelWidth: '300px', disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemmanage_isbystockowner" class="easyui-checkbox c1" mapping="itemmanage_isbystockowner" data-options="label: 'By Stock Owner', labelPosition: 'after', checked: false , labelWidth: '300px', disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemmanage_isbynonitemowner" class="easyui-checkbox c1" mapping="itemmanage_isbynonitemowner" data-options="label: 'By Non Item Owner', labelPosition: 'after', checked: false , labelWidth: '300px', disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemmanage_isbypartnerselect" class="easyui-checkbox c1" mapping="itemmanage_isbypartnerselect" data-options="label: 'By Partner Selector', labelPosition: 'after', checked: false , labelWidth: '300px', disabled: true">
			</div>
		</div>

		</div>			
		<?=$this->SectionEnd('')?>
					
	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col detilbox" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editaccountgrid')">
					<div id="pnl_edit-txt_account_title" class="detilgrid-text">Account Ovveride by Project Type</div>
					<div id="pnl_edit-txt_account_value" class="detilgrid-value account_totalvalue">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editfilesgrid')">
					<div id="pnl_edit-txt_files_title" class="detilgrid-text">Files</div>
					<div id="pnl_edit-txt_files_value" class="detilgrid-value files_totalvalue">&nbsp;</div>
				</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol-tombol xtion disini -->
			<?php
			$customheaderxtion = __DIR__.'/itemclass-edit-customxtion.phtml'; 
			if (is_file($customheaderxtion)) {
				include $customheaderxtion;
			} else { ?>
			
			
			
			
			<?php } ?>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5 fgta-button-delete" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

