<div id="pnl_editaccountform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Account Ovveride by Project Type</div>
		<a id="pnl_editaccountform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editaccountform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editaccountform-form">

		<div class="form_row pnl_editaccountform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editaccountform-txt_itemclassaccbudget_id" class="easyui-textbox" mapping="itemclassaccbudget_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editaccountform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Project Model</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editaccountform-cbo_projectmodel_id" class="easyui-combo" style="width: 400px" mapping="projectmodel_id" display="projectmodel_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'ID harus diisi', prompt: '-- PILIH --'"  validType="requiredcombo['pnl_editaccountform-cbo_projectmodel_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editaccountform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Inquiry Budget Account</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editaccountform-cbo_inquiry_accbudget_id" class="easyui-combo" style="width: 400px" mapping="inquiry_accbudget_id" display="accbudget_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Account Budget harus diisi', prompt: '-- PILIH --'"  validType="requiredcombo['pnl_editaccountform-cbo_inquiry_accbudget_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editaccountform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Account BS</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editaccountform-cbo_nr_coa_id" class="easyui-combo" style="width: 400px" mapping="nr_coa_id" display="coa_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;">Ivnentory / Persediaan, Asset</div>
			</div>
		</div>

		<div class="form_row pnl_editaccountform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Account IS</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editaccountform-cbo_lr_coa_id" class="easyui-combo" style="width: 400px" mapping="lr_coa_id" display="coa_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;">Account Cost / Amortisasi / Depresiasi (asset)</div>
			</div>
		</div>

		<div class="form_row pnl_editaccountform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Item</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editaccountform-txt_itemclass_id" class="easyui-textbox" mapping="itemclass_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editaccountform-autoadd" type="checkbox"><label for="pnl_editaccountform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editaccountform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editaccountform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editaccountform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editaccountform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editaccountform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
