<thead>
	<tr>
		<th mapping="itemclass_name">itemclass_name</th>
		<th mapping="itemclass_isdisabled" type="checkbox">itemclass_isdisabled</th>

	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Item Class</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Disabled</td>

	</tr>
</thead>