<div id="pnl_editdetilgrid">
	<div class="fgta-page-title">Daftar Detil</div>
	<div id="pnl_editdetilgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_editdetilgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_editdetilgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_editdetilgrid-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_editdetilgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<?php
				$customview = __DIR__.'/itemmove-detilgrid-customview.phtml'; 
				if (is_file($customview)) {
					include $customview;
				} else { ?>
				<tr>
<th type="check">chk</th>					
					<th mapping="itemmovedetil_id">itemmovedetil_id</th>
					<th mapping="item_id">item_id</th>
					<th mapping="item_name">item_name</th>
					<th mapping="itemmovedetil_qtyprop" style="text-align: right" formatter="row_format_number">itemmovedetil_qtyprop</th>
					<th mapping="itemmovedetil_qtysend" style="text-align: right" formatter="row_format_number">itemmovedetil_qtysend</th>
					<th mapping="itemmovedetil_qtyrecv" style="text-align: right" formatter="row_format_number">itemmovedetil_qtyrecv</th>

					<th mapping=""></th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
<td class="fgtable-head" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Item ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Item Name</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Qty Prop</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Qty Send</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Qty Recv</td>

					<td class="fgtable-head" style="border-bottom: 1px solid #000000; text-align: center">&nbsp;</td>
				</tr>
				<?php } ?>
			</thead>
		</table>
	</div>



	<div class="pnl_editdetilgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_editdetilgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_editdetilgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>


</div>	
