<div id="pnl_editdetilgrid">
	<div class="fgta-page-title">Daftar Detil</div>
	<div id="pnl_editdetilgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_editdetilgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_editdetilgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_editdetilgrid-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_editdetilgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<tr>
					<th mapping="coa_id">coa_id</th>
					<th mapping="accbudget_id">accbudget_id</th>
					<th mapping="budget_id">budget_id</th>
					<th mapping="billindetil_descr">billindetil_descr</th>
					<th mapping="billindetil_validr" style="text-align: right" formatter="row_format_number">billindetil_validr</th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">

					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Coa</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Account Budget</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Budget</td>
					<td class="fgtable-head" style="border-bottom: 1px solid #000000">Descr</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">IDR</td>
				</tr>
			</thead>
		</table>
	</div>

	<div id="pnl_editdetilgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_editdetilgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_editdetilgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>
	</div>


	<div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">COA (Kredit)</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilgrid-cbo_coa_id" class="easyui-combo" style="width: 400px" mapping="coa_id" display="coa_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'COA harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_editdetilgrid-cbo_coa_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</div>


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
			<a id="pnl_editdetilgrid-btn_verify" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;">Verify</a>
		</div>
		<div>
		</div>
	</div>


</div>	
