<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Permintaan Pembayaran</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_billin_id" class="easyui-textbox" mapping="billin_id"  maxlength="14" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'ID harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" id="pnl_edit-billtype_id">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Type</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_billtype_id" class="easyui-combo" style="width: 400px" mapping="billtype_id" display="billtype_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Type Bill', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_billtype_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>


		<div id="pnl_edit-entry">		


		<div class="form_row" id="pnl_edit-billin_ref" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Ref</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_billin_ref" class="easyui-textbox" mapping="billin_ref"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>



		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_dept_id" class="easyui-combo" style="width: 400px" mapping="dept_id" display="dept_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Departemen harus diisi'"   validType="requiredcombo['pnl_edit-cbo_dept_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" id="pnl_edit-orderout_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Order</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_orderout_id" class="easyui-combo" style="width: 400px" mapping="orderout_id" display="orderout_descr" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" id="pnl_edit-recv_id">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Receive</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_recv_id" class="easyui-combo" style="width: 400px" mapping="recv_id" display="recv_descr" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>




		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Project</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_project_id" class="easyui-combo" style="width: 400px" mapping="project_id" display="project_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Project harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_project_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Project Task</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_projecttask_id" class="easyui-combo" style="width: 400px" mapping="projecttask_id" display="projecttask_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>


		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Deskripsi</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_billin_descr" class="easyui-textbox" mapping="billin_descr"  maxlength="255" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Descr harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" id="pnl_edit-trxmodel_id">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Model Transaksi</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_trxmodel_id" class="easyui-combo" style="width: 250px" mapping="trxmodel_id" display="trxmodel_name"  data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Model transaksi harus diisi'"   validType="requiredcombo['pnl_edit-cbo_trxmodel_id']"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Periode</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_periodemo_id" class="easyui-combo" style="width: 200px" mapping="periodemo_id" display="periodemo_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Periode harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_periodemo_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_billin_date" class="easyui-datebox" style="width: 150px" mapping="billin_date" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Due Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_billin_datedue" class="easyui-datebox" style="width: 150px" mapping="billin_datedue" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>



		<div class="form_row" id="pnl_edit-billin_taxcode" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">No Faktur Pajak</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_billin_taxcode" class="easyui-textbox" mapping="billin_taxcode"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>



		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Budget</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_projbudget_id" class="easyui-combo" style="width: 400px" mapping="projbudget_id" display="projbudget_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Budget harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_projbudget_id']"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Budget Task</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_projbudgettask_id" class="easyui-combo" style="width: 400px" mapping="projbudgettask_id" display="projecttask_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Partner</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partner_id" class="easyui-combo" style="width: 400px" mapping="partner_id" display="partner_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Partner harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_partner_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Dibayar Kepada</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_paymto_name" class="easyui-textbox" mapping="paymto_name"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Partner Contact</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partnercontact_id" class="easyui-combo" style="width: 400px" mapping="partnercontact_id" display="partnercontact_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Contact partner harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_partnercontact_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>



		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">UP</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_paymto_upname" class="easyui-textbox" mapping="paymto_upname"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Jabatan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_paymto_upposition" class="easyui-textbox" mapping="paymto_upposition"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Phone</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_paymto_upphone" class="easyui-textbox" mapping="paymto_upphone"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>



		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Tipe Pembayaran</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_paymtype_id" class="easyui-combo" style="width: 200px" mapping="paymtype_id" display="paymtype_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Tipe Pembayaran harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_paymtype_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>




		<div id="pnl_edit-banktransfer">
		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Partner Bank</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partnerbank_id" class="easyui-combo" style="width: 400px" mapping="partnerbank_id" display="partnerbank_accnum" data-options="editable:false, valueField:'id', textField:'text' , required: false, prompt: 'NONE'" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Account</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_paymto_bankacc" class="easyui-textbox" mapping="paymto_bankacc"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Nama Account</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_paymto_bankaccname" class="easyui-textbox" mapping="paymto_bankaccname"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Nama Bank</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_paymto_bankname" class="easyui-textbox" mapping="paymto_bankname"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>
		</div>




		<div class="form_row" id="pnl_edit-curr_id">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Currency</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_curr_id" class="easyui-combo" style="width: 100px" mapping="curr_id" display="curr_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Currency harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_curr_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" id="pnl_edit-billin_valfrgrate" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Rate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_billin_valfrgrate" class="easyui-numberbox" mapping="billin_valfrgrate" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total Value</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_billin_valfrg" class="easyui-numberbox" mapping="billin_valfrg" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Total in IDR</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_billin_validr" class="easyui-numberbox" mapping="billin_validr" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row"  style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Notes</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_billin_notes" class="easyui-textbox" mapping="billin_notes"  maxlength="255" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Version</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_billin_version" class="easyui-numberbox" mapping="billin_version" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Order Doc</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_doc_id" class="easyui-combo" style="width: 400px" mapping="doc_id" display="doc_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'ID harus diisi', disabled: true"   validType="requiredcombo['pnl_edit-cbo_doc_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Process</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_process_dept_id" class="easyui-combo" style="width: 400px" mapping="process_dept_id" display="process_dept_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Process Departemen harus diisi', disabled: true"   validType="requiredcombo['pnl_edit-cbo_process_dept_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>


		<div class="form_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_billin_iscommit" class="easyui-checkbox c1" mapping="billin_iscommit" data-options="label: 'Commit', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">CommitBy</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_billin_commitby" class="easyui-textbox" mapping="billin_commitby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">CommitDate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_billin_commitdate" class="easyui-textbox" mapping="billin_commitdate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_billin_isapprovalprogress" class="easyui-checkbox c1" mapping="billin_isapprovalprogress" data-options="label: 'Progress', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_billin_isapproved" class="easyui-checkbox c1" mapping="billin_isapproved" data-options="label: 'Approved', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Approve By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_billin_approveby" class="easyui-textbox" mapping="billin_approveby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Approve Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_billin_approvedate" class="easyui-textbox" mapping="billin_approvedate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_billin_isdeclined" class="easyui-checkbox c1" mapping="billin_isdeclined" data-options="label: 'Declined', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Decline By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_billin_declineby" class="easyui-textbox" mapping="billin_declineby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Decline Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_billin_declinedate" class="easyui-textbox" mapping="billin_declinedate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>


		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col detilbox" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editdetilgrid')">
					<div id="pnl_edit-txt_detil_title" class="detilgrid-text">Detil</div>
					<div id="pnl_edit-txt_detil_value" class="detilgrid-value">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editpaymgrid')">
					<div id="pnl_edit-txt_paym_title" class="detilgrid-text">Jadwal Pembayaran</div>
					<div id="pnl_edit-txt_paym_value" class="detilgrid-value">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editapprovalgrid')">
					<div id="pnl_edit-txt_approval_title" class="detilgrid-text">Approval</div>
					<div id="pnl_edit-txt_approval_value" class="detilgrid-value">&nbsp;</div>
				</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		<a id="pnl_edit-btn_print" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'icon-print'">print</a>
		
			<a id="pnl_edit-btn_commit" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'fgta-icon-commit'">Commit</a>			
			<a id="pnl_edit-btn_uncommit" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'fgta-icon-uncommit'">UnCommit</a>
			
		
				<a id="pnl_edit-btn_approve" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="plain:true,iconCls:'fgta-icon-posting'">Approve</a>
				<a id="pnl_edit-btn_decline" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="plain:true,iconCls:'fgta-icon-unposting'">Decline</a>
				
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

