<div id="pnl_editdetilform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Detil</div>
		<a id="pnl_editdetilform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editdetilform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editdetilform-form">

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_billoutdetil_id" class="easyui-textbox" mapping="billoutdetil_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Row Type</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-cbo_billrowtype_id" class="easyui-combo" style="width: 400px" mapping="billrowtype_id" display="billrowtype_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Row Type', disabled: true"  validType="requiredcombo['pnl_editdetilform-cbo_billrowtype_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Tax</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-cbo_taxtype_id" class="easyui-combo" style="width: 400px" mapping="taxtype_id" display="taxtype_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE', disabled: true" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_billoutdetil_descr" class="easyui-textbox" mapping="billoutdetil_descr" uppercase="true" maxlength="255"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Descr harus diisi' , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>



		<?=$this->Section('Tagihan Awal', true, true)?>
		<div class="fgta_section_collapsible defbottomborder" style="display: none">	

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Currency</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-cbo_curr_id" class="easyui-combo" style="width: 400px" mapping="curr_id" display="curr_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Currency harus diisi', prompt: '-- PILIH --', disabled: true"  validType="requiredcombo['pnl_editdetilform-cbo_curr_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Valas</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_billoutdetil_valfrg" class="easyui-numberbox" mapping="billoutdetil_valfrg" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , required: true, disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Rate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_billoutdetil_valfrgrate" class="easyui-numberbox" mapping="billoutdetil_valfrgrate" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true, disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">IDR</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_billoutdetil_validr" class="easyui-numberbox" mapping="billoutdetil_validr" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , required: true, disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Class</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-cbo_itemclass_id" class="easyui-combo" style="width: 400px" mapping="itemclass_id" display="itemclass_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Class harus diisi', disabled: true"  validType="requiredcombo['pnl_editdetilform-cbo_itemclass_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Akun Pembayaran</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-cbo_coa_id" class="easyui-combo" style="width: 400px" mapping="coa_id" display="coa_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE', disabled: true" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>


		</div>




		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Nilai Tagihan Awal</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_billoutdetil_validr_ori" class="easyui-numberbox" mapping="billoutdetil_validr_ori" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , required: true, disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Nilai Tagihan Baru</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_billoutdetil_validr_rev" class="easyui-numberbox" mapping="billoutdetil_validr_rev" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , required: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Variance</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_billoutdetil_validr_var" class="easyui-numberbox" mapping="billoutdetil_validr_var" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  , required: true, disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Keterangan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_billoutdetil_rev_descr" class="easyui-textbox" mapping="billoutdetil_rev_descr"  maxlength="255"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Descr harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Coa Variance</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-cbo_rev_coa_id" class="easyui-combo" style="width: 400px" mapping="rev_coa_id" display="rev_coa_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, nvalidMessage: 'COA Variance harus diisi', prompt: '--PILiH--'" validType="requiredcombo['pnl_editdetilform-cbo_rev_coa_id']">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Periode Buku</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-cbo_periodemo_id" class="easyui-combo" style="width: 400px" mapping="periodemo_id" display="periodemo_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Periode harus diisi', prompt: '-- PILIH --'"  validType="requiredcombo['pnl_editdetilform-cbo_periodemo_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">BookDate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-dt_billoutdetil_bookdate" class="easyui-datebox" style="width: 400px" mapping="billoutdetil_bookdate" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Bill ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdetilform-txt_billout_id" class="easyui-textbox" mapping="billout_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editdetilform-autoadd" type="checkbox"><label for="pnl_editdetilform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editdetilform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editdetilform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editdetilform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editdetilform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editdetilform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
