<div id="pnl_editdeptform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editdeptform-caption">{{STATE_BEG}}Dept{{STATE_END}}</div>
		<a id="pnl_editdeptform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editdeptform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editdeptform-form">

		<div class="form_row pnl_editdeptform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdeptform-txt_coabudgetdept_id" class="easyui-textbox" mapping="coabudgetdept_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editdeptform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdeptform-cbo_dept_id" class="easyui-combo" style="width: 400px" mapping="dept_id" display="dept_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Dept harus diisi', prompt: '-- PILIH --'"  validType="requiredcombo['pnl_editdeptform-cbo_dept_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editdeptform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Acccount Budget</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdeptform-txt_coabudget_id" class="easyui-textbox" mapping="coabudget_id" uppercase="true" maxlength="20"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editdeptform-autoadd" type="checkbox"><label for="pnl_editdeptform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editdeptform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/coabudget-deptform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_editdeptform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_editdeptform-buttonbar-left">
			<a id="pnl_editdeptform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editdeptform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_editdeptform-buttonbar-middle">
			<a id="pnl_editdeptform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_editdeptform-buttonbar-right">
			<a id="pnl_editdeptform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
