-- SET FOREIGN_KEY_CHECKS=0;

-- drop table if exists `trn_orderindelv`;
-- drop table if exists `trn_orderindelvitem`;


CREATE TABLE IF NOT EXISTS `trn_orderindelv` (
	`orderindelv_id` varchar(30) NOT NULL , 
	`unit_id` varchar(10)  , 
	`dept_id` varchar(30) NOT NULL , 
	`partner_id` varchar(30)  , 
	`orderin_id` varchar(30)  , 
	`orderindelv_descr` varchar(255)  , 
	`orderindelv_dt` date NOT NULL , 
	`site_id` varchar(30)  , 
	`orderintype_id` varchar(10)  , 
	`ae_empl_id` varchar(14)  , 
	`owner_dept_id` varchar(30)  , 
	`trxmodel_id` varchar(10)  , 
	`project_id` varchar(30)  , 
	`ppn_taxtype_id` varchar(10)  , 
	`ppn_taxvalue` decimal(4, 2) NOT NULL DEFAULT 0, 
	`ppn_include` tinyint(1) NOT NULL DEFAULT 0, 
	`pph_taxtype_id` varchar(10)  , 
	`pph_taxvalue` decimal(4, 2) NOT NULL DEFAULT 0, 
	`arunbill_coa_id` varchar(17) NOT NULL , 
	`ar_coa_id` varchar(17) NOT NULL , 
	`dp_coa_id` varchar(17) NOT NULL , 
	`sales_coa_id` varchar(10) NOT NULL , 
	`salesdisc_coa_id` varchar(10)  , 
	`ppn_coa_id` varchar(10)  , 
	`ppnsubsidi_coa_id` varchar(10)  , 
	`pph_coa_id` varchar(10)  , 
	`orderindelv_totalitem` int(5) NOT NULL DEFAULT 0, 
	`orderindevl_totalqty` int(5) NOT NULL DEFAULT 0, 
	`orderindelv_salesgross` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderindelv_discount` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderindelv_subtotal` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderindelv_pph` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderindelv_nett` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderindelv_ppn` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderindelv_total` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderindelv_totaladdcost` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderindelv_payment` decimal(16, 0) NOT NULL DEFAULT 0, 
	`orderindelv_version` int(4) NOT NULL DEFAULT 0, 
	`orderindelv_iscommit` tinyint(1) NOT NULL DEFAULT 0, 
	`orderindelv_commitby` varchar(14)  , 
	`orderindelv_commitdate` datetime  , 
	`orderindelev_isautogenerated` tinyint(1) NOT NULL DEFAULT 0, 
	`_createby` varchar(13) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(13)  , 
	`_modifydate` datetime  , 
	PRIMARY KEY (`orderindelv_id`)
) 
ENGINE=InnoDB
COMMENT='Daftar pemenuhan orderin (delivery ke customer, dan yang semacamnya)';


ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `unit_id` varchar(10)   AFTER `orderindelv_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `dept_id` varchar(30) NOT NULL  AFTER `unit_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `partner_id` varchar(30)   AFTER `dept_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderin_id` varchar(30)   AFTER `partner_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelv_descr` varchar(255)   AFTER `orderin_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelv_dt` date NOT NULL  AFTER `orderindelv_descr`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `site_id` varchar(30)   AFTER `orderindelv_dt`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderintype_id` varchar(10)   AFTER `site_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `ae_empl_id` varchar(14)   AFTER `orderintype_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `owner_dept_id` varchar(30)   AFTER `ae_empl_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `trxmodel_id` varchar(10)   AFTER `owner_dept_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `project_id` varchar(30)   AFTER `trxmodel_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `ppn_taxtype_id` varchar(10)   AFTER `project_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `ppn_taxvalue` decimal(4, 2) NOT NULL DEFAULT 0 AFTER `ppn_taxtype_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `ppn_include` tinyint(1) NOT NULL DEFAULT 0 AFTER `ppn_taxvalue`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `pph_taxtype_id` varchar(10)   AFTER `ppn_include`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `pph_taxvalue` decimal(4, 2) NOT NULL DEFAULT 0 AFTER `pph_taxtype_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `arunbill_coa_id` varchar(17) NOT NULL  AFTER `pph_taxvalue`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `ar_coa_id` varchar(17) NOT NULL  AFTER `arunbill_coa_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `dp_coa_id` varchar(17) NOT NULL  AFTER `ar_coa_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `sales_coa_id` varchar(10) NOT NULL  AFTER `dp_coa_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `salesdisc_coa_id` varchar(10)   AFTER `sales_coa_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `ppn_coa_id` varchar(10)   AFTER `salesdisc_coa_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `ppnsubsidi_coa_id` varchar(10)   AFTER `ppn_coa_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `pph_coa_id` varchar(10)   AFTER `ppnsubsidi_coa_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelv_totalitem` int(5) NOT NULL DEFAULT 0 AFTER `pph_coa_id`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindevl_totalqty` int(5) NOT NULL DEFAULT 0 AFTER `orderindelv_totalitem`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelv_salesgross` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindevl_totalqty`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelv_discount` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindelv_salesgross`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelv_subtotal` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindelv_discount`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelv_pph` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindelv_subtotal`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelv_nett` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindelv_pph`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelv_ppn` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindelv_nett`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelv_total` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindelv_ppn`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelv_totaladdcost` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindelv_total`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelv_payment` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindelv_totaladdcost`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelv_version` int(4) NOT NULL DEFAULT 0 AFTER `orderindelv_payment`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelv_iscommit` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderindelv_version`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelv_commitby` varchar(14)   AFTER `orderindelv_iscommit`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelv_commitdate` datetime   AFTER `orderindelv_commitby`;
ALTER TABLE `trn_orderindelv` ADD COLUMN IF NOT EXISTS  `orderindelev_isautogenerated` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderindelv_commitdate`;


ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `unit_id` varchar(10)   AFTER `orderindelv_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `dept_id` varchar(30) NOT NULL  AFTER `unit_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `partner_id` varchar(30)   AFTER `dept_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderin_id` varchar(30)   AFTER `partner_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelv_descr` varchar(255)   AFTER `orderin_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelv_dt` date NOT NULL  AFTER `orderindelv_descr`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `site_id` varchar(30)   AFTER `orderindelv_dt`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderintype_id` varchar(10)   AFTER `site_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `ae_empl_id` varchar(14)   AFTER `orderintype_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `owner_dept_id` varchar(30)   AFTER `ae_empl_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `trxmodel_id` varchar(10)   AFTER `owner_dept_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `project_id` varchar(30)   AFTER `trxmodel_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `ppn_taxtype_id` varchar(10)   AFTER `project_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `ppn_taxvalue` decimal(4, 2) NOT NULL DEFAULT 0 AFTER `ppn_taxtype_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `ppn_include` tinyint(1) NOT NULL DEFAULT 0 AFTER `ppn_taxvalue`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `pph_taxtype_id` varchar(10)   AFTER `ppn_include`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `pph_taxvalue` decimal(4, 2) NOT NULL DEFAULT 0 AFTER `pph_taxtype_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `arunbill_coa_id` varchar(17) NOT NULL  AFTER `pph_taxvalue`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `ar_coa_id` varchar(17) NOT NULL  AFTER `arunbill_coa_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `dp_coa_id` varchar(17) NOT NULL  AFTER `ar_coa_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `sales_coa_id` varchar(10) NOT NULL  AFTER `dp_coa_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `salesdisc_coa_id` varchar(10)   AFTER `sales_coa_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `ppn_coa_id` varchar(10)   AFTER `salesdisc_coa_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `ppnsubsidi_coa_id` varchar(10)   AFTER `ppn_coa_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `pph_coa_id` varchar(10)   AFTER `ppnsubsidi_coa_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelv_totalitem` int(5) NOT NULL DEFAULT 0 AFTER `pph_coa_id`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindevl_totalqty` int(5) NOT NULL DEFAULT 0 AFTER `orderindelv_totalitem`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelv_salesgross` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindevl_totalqty`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelv_discount` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindelv_salesgross`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelv_subtotal` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindelv_discount`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelv_pph` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindelv_subtotal`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelv_nett` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindelv_pph`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelv_ppn` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindelv_nett`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelv_total` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindelv_ppn`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelv_totaladdcost` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindelv_total`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelv_payment` decimal(16, 0) NOT NULL DEFAULT 0 AFTER `orderindelv_totaladdcost`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelv_version` int(4) NOT NULL DEFAULT 0 AFTER `orderindelv_payment`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelv_iscommit` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderindelv_version`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelv_commitby` varchar(14)   AFTER `orderindelv_iscommit`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelv_commitdate` datetime   AFTER `orderindelv_commitby`;
ALTER TABLE `trn_orderindelv` MODIFY COLUMN IF EXISTS  `orderindelev_isautogenerated` tinyint(1) NOT NULL DEFAULT 0 AFTER `orderindelv_commitdate`;



ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `unit_id` (`unit_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `dept_id` (`dept_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `partner_id` (`partner_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `orderin_id` (`orderin_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `site_id` (`site_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `orderintype_id` (`orderintype_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `ae_empl_id` (`ae_empl_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `owner_dept_id` (`owner_dept_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `trxmodel_id` (`trxmodel_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `project_id` (`project_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `ppn_taxtype_id` (`ppn_taxtype_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `pph_taxtype_id` (`pph_taxtype_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `arunbill_coa_id` (`arunbill_coa_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `ar_coa_id` (`ar_coa_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `dp_coa_id` (`dp_coa_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `sales_coa_id` (`sales_coa_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `salesdisc_coa_id` (`salesdisc_coa_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `ppn_coa_id` (`ppn_coa_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `ppnsubsidi_coa_id` (`ppnsubsidi_coa_id`);
ALTER TABLE `trn_orderindelv` ADD KEY IF NOT EXISTS `pph_coa_id` (`pph_coa_id`);

ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_unit` FOREIGN KEY IF NOT EXISTS  (`unit_id`) REFERENCES `mst_unit` (`unit_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_dept` FOREIGN KEY IF NOT EXISTS  (`dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_partner` FOREIGN KEY IF NOT EXISTS  (`partner_id`) REFERENCES `mst_partner` (`partner_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_trn_orderin` FOREIGN KEY IF NOT EXISTS  (`orderin_id`) REFERENCES `trn_orderin` (`orderin_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_site` FOREIGN KEY IF NOT EXISTS  (`site_id`) REFERENCES `mst_site` (`site_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_orderintype` FOREIGN KEY IF NOT EXISTS  (`orderintype_id`) REFERENCES `mst_orderintype` (`orderintype_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_empl` FOREIGN KEY IF NOT EXISTS  (`ae_empl_id`) REFERENCES `mst_empl` (`empl_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_dept_2` FOREIGN KEY IF NOT EXISTS  (`owner_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_trxmodel` FOREIGN KEY IF NOT EXISTS  (`trxmodel_id`) REFERENCES `mst_trxmodel` (`trxmodel_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_project` FOREIGN KEY IF NOT EXISTS  (`project_id`) REFERENCES `mst_project` (`project_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_taxtype` FOREIGN KEY IF NOT EXISTS  (`ppn_taxtype_id`) REFERENCES `mst_taxtype` (`taxtype_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_taxtype_2` FOREIGN KEY IF NOT EXISTS  (`pph_taxtype_id`) REFERENCES `mst_taxtype` (`taxtype_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_coa` FOREIGN KEY IF NOT EXISTS  (`arunbill_coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_coa_2` FOREIGN KEY IF NOT EXISTS  (`ar_coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_coa_3` FOREIGN KEY IF NOT EXISTS  (`dp_coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_coa_4` FOREIGN KEY IF NOT EXISTS  (`sales_coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_coa_5` FOREIGN KEY IF NOT EXISTS  (`salesdisc_coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_coa_6` FOREIGN KEY IF NOT EXISTS  (`ppn_coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_coa_7` FOREIGN KEY IF NOT EXISTS  (`ppnsubsidi_coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_orderindelv` ADD CONSTRAINT `fk_trn_orderindelv_mst_coa_8` FOREIGN KEY IF NOT EXISTS  (`pph_coa_id`) REFERENCES `mst_coa` (`coa_id`);





CREATE TABLE IF NOT EXISTS `trn_orderindelvitem` (
	`orderindelvitem_id` varchar(14) NOT NULL , 
	`itemclass_id` varchar(14) NOT NULL , 
	`orderinitem_descr` varchar(90) NOT NULL , 
	`orderinitem_qty` int(4) NOT NULL DEFAULT 0, 
	`orderinitem_price` decimal(12, 0) NOT NULL DEFAULT 0, 
	`orderinitem_pricediscpercent` decimal(12, 0) NOT NULL DEFAULT 0, 
	`orderinitem_pricediscvalue` decimal(12, 0) NOT NULL DEFAULT 0, 
	`orderinitem_subtotal` decimal(14, 0) NOT NULL DEFAULT 0, 
	`accbudget_id` varchar(20)  , 
	`coa_id` varchar(17)  , 
	`orderindelv_id` varchar(30) NOT NULL , 
	`_createby` varchar(13) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(13)  , 
	`_modifydate` datetime  , 
	PRIMARY KEY (`orderindelvitem_id`)
) 
ENGINE=InnoDB
COMMENT='Item yang di request';


ALTER TABLE `trn_orderindelvitem` ADD COLUMN IF NOT EXISTS  `itemclass_id` varchar(14) NOT NULL  AFTER `orderindelvitem_id`;
ALTER TABLE `trn_orderindelvitem` ADD COLUMN IF NOT EXISTS  `orderinitem_descr` varchar(90) NOT NULL  AFTER `itemclass_id`;
ALTER TABLE `trn_orderindelvitem` ADD COLUMN IF NOT EXISTS  `orderinitem_qty` int(4) NOT NULL DEFAULT 0 AFTER `orderinitem_descr`;
ALTER TABLE `trn_orderindelvitem` ADD COLUMN IF NOT EXISTS  `orderinitem_price` decimal(12, 0) NOT NULL DEFAULT 0 AFTER `orderinitem_qty`;
ALTER TABLE `trn_orderindelvitem` ADD COLUMN IF NOT EXISTS  `orderinitem_pricediscpercent` decimal(12, 0) NOT NULL DEFAULT 0 AFTER `orderinitem_price`;
ALTER TABLE `trn_orderindelvitem` ADD COLUMN IF NOT EXISTS  `orderinitem_pricediscvalue` decimal(12, 0) NOT NULL DEFAULT 0 AFTER `orderinitem_pricediscpercent`;
ALTER TABLE `trn_orderindelvitem` ADD COLUMN IF NOT EXISTS  `orderinitem_subtotal` decimal(14, 0) NOT NULL DEFAULT 0 AFTER `orderinitem_pricediscvalue`;
ALTER TABLE `trn_orderindelvitem` ADD COLUMN IF NOT EXISTS  `accbudget_id` varchar(20)   AFTER `orderinitem_subtotal`;
ALTER TABLE `trn_orderindelvitem` ADD COLUMN IF NOT EXISTS  `coa_id` varchar(17)   AFTER `accbudget_id`;
ALTER TABLE `trn_orderindelvitem` ADD COLUMN IF NOT EXISTS  `orderindelv_id` varchar(30) NOT NULL  AFTER `coa_id`;


ALTER TABLE `trn_orderindelvitem` MODIFY COLUMN IF EXISTS  `itemclass_id` varchar(14) NOT NULL  AFTER `orderindelvitem_id`;
ALTER TABLE `trn_orderindelvitem` MODIFY COLUMN IF EXISTS  `orderinitem_descr` varchar(90) NOT NULL  AFTER `itemclass_id`;
ALTER TABLE `trn_orderindelvitem` MODIFY COLUMN IF EXISTS  `orderinitem_qty` int(4) NOT NULL DEFAULT 0 AFTER `orderinitem_descr`;
ALTER TABLE `trn_orderindelvitem` MODIFY COLUMN IF EXISTS  `orderinitem_price` decimal(12, 0) NOT NULL DEFAULT 0 AFTER `orderinitem_qty`;
ALTER TABLE `trn_orderindelvitem` MODIFY COLUMN IF EXISTS  `orderinitem_pricediscpercent` decimal(12, 0) NOT NULL DEFAULT 0 AFTER `orderinitem_price`;
ALTER TABLE `trn_orderindelvitem` MODIFY COLUMN IF EXISTS  `orderinitem_pricediscvalue` decimal(12, 0) NOT NULL DEFAULT 0 AFTER `orderinitem_pricediscpercent`;
ALTER TABLE `trn_orderindelvitem` MODIFY COLUMN IF EXISTS  `orderinitem_subtotal` decimal(14, 0) NOT NULL DEFAULT 0 AFTER `orderinitem_pricediscvalue`;
ALTER TABLE `trn_orderindelvitem` MODIFY COLUMN IF EXISTS  `accbudget_id` varchar(20)   AFTER `orderinitem_subtotal`;
ALTER TABLE `trn_orderindelvitem` MODIFY COLUMN IF EXISTS  `coa_id` varchar(17)   AFTER `accbudget_id`;
ALTER TABLE `trn_orderindelvitem` MODIFY COLUMN IF EXISTS  `orderindelv_id` varchar(30) NOT NULL  AFTER `coa_id`;



ALTER TABLE `trn_orderindelvitem` ADD KEY IF NOT EXISTS `itemclass_id` (`itemclass_id`);
ALTER TABLE `trn_orderindelvitem` ADD KEY IF NOT EXISTS `accbudget_id` (`accbudget_id`);
ALTER TABLE `trn_orderindelvitem` ADD KEY IF NOT EXISTS `coa_id` (`coa_id`);
ALTER TABLE `trn_orderindelvitem` ADD KEY IF NOT EXISTS `orderindelv_id` (`orderindelv_id`);

ALTER TABLE `trn_orderindelvitem` ADD CONSTRAINT `fk_trn_orderindelvitem_mst_itemclass` FOREIGN KEY IF NOT EXISTS  (`itemclass_id`) REFERENCES `mst_itemclass` (`itemclass_id`);
ALTER TABLE `trn_orderindelvitem` ADD CONSTRAINT `fk_trn_orderindelvitem_mst_accbudget` FOREIGN KEY IF NOT EXISTS  (`accbudget_id`) REFERENCES `mst_accbudget` (`accbudget_id`);
ALTER TABLE `trn_orderindelvitem` ADD CONSTRAINT `fk_trn_orderindelvitem_mst_coa` FOREIGN KEY IF NOT EXISTS  (`coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_orderindelvitem` ADD CONSTRAINT `fk_trn_orderindelvitem_trn_orderindelv` FOREIGN KEY IF NOT EXISTS (`orderindelv_id`) REFERENCES `trn_orderindelv` (`orderindelv_id`);





