-- SET FOREIGN_KEY_CHECKS=0;

-- drop table if exists `trn_orderout`;
-- drop table if exists `trn_orderoutitem`;
-- drop table if exists `trn_orderoutfiles`;
-- drop table if exists `trn_orderoutappr`;


CREATE TABLE `trn_orderout` (
	`orderout_id` varchar(30) NOT NULL , 
	`unit_id` varchar(30)  , 
	`request_id` varchar(30)  , 
	`orderout_isunref` tinyint(1) NOT NULL DEFAULT 0, 
	`inquirytype_id` varchar(30) NOT NULL , 
	`trxmodel_id` varchar(10) NOT NULL , 
	`request_dept_id` varchar(30) NOT NULL , 
	`orderout_descr` varchar(90) NOT NULL , 
	`orderout_dtstart` date NOT NULL , 
	`orderout_dtend` date NOT NULL , 
	`curr_id` varchar(10) NOT NULL , 
	`curr_rate` decimal(12, 0) NOT NULL DEFAULT 0, 
	`ppn_taxtype_id` varchar(10)  , 
	`pph_taxtype_id` varchar(10)  , 
	`partner_id` varchar(30)  , 
	`ordercontract_id` varchar(14)  , 
	`orderout_quot` varchar(90) NOT NULL , 
	`paymtype_id` varchar(6) NOT NULL , 
	`partnerbank_id` varchar(14)  , 
	`partnerbank_name` varchar(90) NOT NULL , 
	`partnerbank_bankacc` varchar(90) NOT NULL , 
	`partnerbank_bankaccname` varchar(90) NOT NULL , 
	`partnerbank_bankname` varchar(90) NOT NULL , 
	`partnercontact_id` varchar(14)  , 
	`partnercontact_upname` varchar(90) NOT NULL , 
	`partnercontact_position` varchar(90) NOT NULL , 
	`partnercontact_upphone` varchar(90) NOT NULL , 
	`partnercontact_email` varchar(90) NOT NULL , 
	`project_id` varchar(30)  , 
	`projecttask_id` varchar(14)  , 
	`projbudget_id` varchar(30)  , 
	`projbudgettask_id` varchar(14)  , 
	`orderout_isunbudgetted` tinyint(1) NOT NULL DEFAULT 0, 
	`site_id` varchar(30)  , 
	`user_dept_id` varchar(30)  , 
	`recv_dept_id` varchar(30) NOT NULL , 
	`deliver_siteaddress` varchar(250)  , 
	`deliver_city` varchar(60)  , 
	`deliver_upname` varchar(60)  , 
	`deliver_uptelp` varchar(60)  , 
	`inquiry_id` varchar(30)  , 
	`orderout_ismultirequest` tinyint(1) NOT NULL DEFAULT 0, 
	`inquirymodel_id` varchar(1) NOT NULL , 
	`inquiryselect_id` varchar(1) NOT NULL , 
	`itemmanage_id` varchar(2) NOT NULL , 
	`owner_dept_id` varchar(30) NOT NULL , 
	`orderout_dept_id` varchar(30) NOT NULL , 
	`doc_id` varchar(30) NOT NULL , 
	`orderout_version` int(4) NOT NULL DEFAULT 0, 
	`orderout_isdateinterval` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_iscommit` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_commitby` varchar(14)  , 
	`orderout_commitdate` datetime  , 
	`orderout_isapprovalprogress` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_isapproved` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_approveby` varchar(14)  , 
	`orderout_approvedate` datetime  , 
	`orderout_isdeclined` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_declineby` varchar(14)  , 
	`orderout_declinedate` datetime  , 
	`orderout_isclose` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_closeby` varchar(14)  , 
	`orderout_closedate` datetime  , 
	`orderout_isadvance` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_isautogenerated` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_isitemdeptuser` tinyint(1) NOT NULL DEFAULT 0, 
	`orderout_isitemdeptowner` tinyint(1) NOT NULL DEFAULT 0, 
	`_createby` varchar(13) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(13)  , 
	`_modifydate` datetime  , 
	PRIMARY KEY (`orderout_id`)
) 
ENGINE=InnoDB
COMMENT='Daftar Order Pembelian, Sewa, Service, Talent, dll';

ALTER TABLE `trn_orderout` ADD KEY `unit_id` (`unit_id`);
ALTER TABLE `trn_orderout` ADD KEY `request_id` (`request_id`);
ALTER TABLE `trn_orderout` ADD KEY `inquirytype_id` (`inquirytype_id`);
ALTER TABLE `trn_orderout` ADD KEY `trxmodel_id` (`trxmodel_id`);
ALTER TABLE `trn_orderout` ADD KEY `request_dept_id` (`request_dept_id`);
ALTER TABLE `trn_orderout` ADD KEY `curr_id` (`curr_id`);
ALTER TABLE `trn_orderout` ADD KEY `ppn_taxtype_id` (`ppn_taxtype_id`);
ALTER TABLE `trn_orderout` ADD KEY `pph_taxtype_id` (`pph_taxtype_id`);
ALTER TABLE `trn_orderout` ADD KEY `partner_id` (`partner_id`);
ALTER TABLE `trn_orderout` ADD KEY `ordercontract_id` (`ordercontract_id`);
ALTER TABLE `trn_orderout` ADD KEY `paymtype_id` (`paymtype_id`);
ALTER TABLE `trn_orderout` ADD KEY `partnerbank_id` (`partnerbank_id`);
ALTER TABLE `trn_orderout` ADD KEY `partnercontact_id` (`partnercontact_id`);
ALTER TABLE `trn_orderout` ADD KEY `project_id` (`project_id`);
ALTER TABLE `trn_orderout` ADD KEY `projecttask_id` (`projecttask_id`);
ALTER TABLE `trn_orderout` ADD KEY `projbudget_id` (`projbudget_id`);
ALTER TABLE `trn_orderout` ADD KEY `projbudgettask_id` (`projbudgettask_id`);
ALTER TABLE `trn_orderout` ADD KEY `site_id` (`site_id`);
ALTER TABLE `trn_orderout` ADD KEY `user_dept_id` (`user_dept_id`);
ALTER TABLE `trn_orderout` ADD KEY `recv_dept_id` (`recv_dept_id`);
ALTER TABLE `trn_orderout` ADD KEY `inquiry_id` (`inquiry_id`);
ALTER TABLE `trn_orderout` ADD KEY `inquirymodel_id` (`inquirymodel_id`);
ALTER TABLE `trn_orderout` ADD KEY `inquiryselect_id` (`inquiryselect_id`);
ALTER TABLE `trn_orderout` ADD KEY `itemmanage_id` (`itemmanage_id`);
ALTER TABLE `trn_orderout` ADD KEY `owner_dept_id` (`owner_dept_id`);
ALTER TABLE `trn_orderout` ADD KEY `orderout_dept_id` (`orderout_dept_id`);
ALTER TABLE `trn_orderout` ADD KEY `doc_id` (`doc_id`);

ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_unit` FOREIGN KEY (`unit_id`) REFERENCES `mst_unit` (`unit_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_trn_request` FOREIGN KEY (`request_id`) REFERENCES `trn_request` (`request_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_inquirytype` FOREIGN KEY (`inquirytype_id`) REFERENCES `mst_inquirytype` (`inquirytype_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_trxmodel` FOREIGN KEY (`trxmodel_id`) REFERENCES `mst_trxmodel` (`trxmodel_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_dept` FOREIGN KEY (`request_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_curr` FOREIGN KEY (`curr_id`) REFERENCES `mst_curr` (`curr_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_taxtype` FOREIGN KEY (`ppn_taxtype_id`) REFERENCES `mst_taxtype` (`taxtype_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_taxtype_2` FOREIGN KEY (`pph_taxtype_id`) REFERENCES `mst_taxtype` (`taxtype_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_partner` FOREIGN KEY (`partner_id`) REFERENCES `mst_partner` (`partner_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_trn_ordercontract` FOREIGN KEY (`ordercontract_id`) REFERENCES `trn_ordercontract` (`ordercontract_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_paymtype` FOREIGN KEY (`paymtype_id`) REFERENCES `mst_paymtype` (`paymtype_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_partnerbank` FOREIGN KEY (`partnerbank_id`) REFERENCES `mst_partnerbank` (`partnerbank_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_partnercontact` FOREIGN KEY (`partnercontact_id`) REFERENCES `mst_partnercontact` (`partnercontact_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_project` FOREIGN KEY (`project_id`) REFERENCES `mst_project` (`project_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_projecttask` FOREIGN KEY (`projecttask_id`) REFERENCES `mst_projecttask` (`projecttask_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_projbudget` FOREIGN KEY (`projbudget_id`) REFERENCES `mst_projbudget` (`projbudget_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_projbudgettask` FOREIGN KEY (`projbudgettask_id`) REFERENCES `mst_projbudgettask` (`projbudgettask_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_site` FOREIGN KEY (`site_id`) REFERENCES `mst_site` (`site_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_dept_2` FOREIGN KEY (`user_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_dept_3` FOREIGN KEY (`recv_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_trn_inquiry` FOREIGN KEY (`inquiry_id`) REFERENCES `trn_inquiry` (`inquiry_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_inquirymodel` FOREIGN KEY (`inquirymodel_id`) REFERENCES `mst_inquirymodel` (`inquirymodel_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_inquiryselect` FOREIGN KEY (`inquiryselect_id`) REFERENCES `mst_inquiryselect` (`inquiryselect_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_itemmanage` FOREIGN KEY (`itemmanage_id`) REFERENCES `mst_itemmanage` (`itemmanage_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_dept_4` FOREIGN KEY (`owner_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_dept_5` FOREIGN KEY (`orderout_dept_id`) REFERENCES `mst_dept` (`dept_id`);
ALTER TABLE `trn_orderout` ADD CONSTRAINT `fk_trn_orderout_mst_doc` FOREIGN KEY (`doc_id`) REFERENCES `mst_doc` (`doc_id`);





CREATE TABLE `trn_orderoutitem` (
	`orderoutitem_id` varchar(14) NOT NULL , 
	`itemasset_id` varchar(14)  , 
	`item_id` varchar(14)  , 
	`itemstock_id` varchar(14)  , 
	`partner_id` varchar(30)  , 
	`itemclass_id` varchar(14) NOT NULL , 
	`orderoutitem_descr` varchar(90) NOT NULL , 
	`orderoutitem_qty` int(4) NOT NULL DEFAULT 0, 
	`orderoutitem_days` int(4) NOT NULL DEFAULT 0, 
	`orderoutitem_task` int(4) NOT NULL DEFAULT 0, 
	`orderoutitem_rate` decimal(12, 2) NOT NULL DEFAULT 0, 
	`orderoutitem_value` decimal(14, 2) NOT NULL DEFAULT 0, 
	`curr_id` varchar(10) NOT NULL , 
	`curr_rate` decimal(12, 0) NOT NULL DEFAULT 0, 
	`orderoutitem_idr` decimal(14, 2) NOT NULL DEFAULT 0, 
	`projbudgetdet_id` varchar(30)  , 
	`orderoutitem_isoverbudget` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_isunbudget` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_budgetavailable` decimal(14, 0) NOT NULL DEFAULT 0, 
	`orderoutitem_budgetqtyavailable` int(16) NOT NULL DEFAULT 0, 
	`orderoutitem_budgetdaysavailable` int(16) NOT NULL DEFAULT 0, 
	`orderoutitem_budgettaskavailable` int(16) NOT NULL DEFAULT 0, 
	`orderoutitem_isuseqty` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_isusedays` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_isusetask` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_islimitqty` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_islimitdays` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_islimittask` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_islimitvalue` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_isallowoverbudget` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_isallowunbudget` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutitem_qtyavailable` int(4) NOT NULL DEFAULT 0, 
	`accbudget_id` varchar(20)  , 
	`coa_id` varchar(17)  , 
	`request_id` varchar(30)  , 
	`requestitem_id` varchar(14)  , 
	`inquiry_id` varchar(30)  , 
	`inquiryitem_id` varchar(14)  , 
	`orderout_id` varchar(30) NOT NULL , 
	`_createby` varchar(13) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(13)  , 
	`_modifydate` datetime  , 
	PRIMARY KEY (`orderoutitem_id`)
) 
ENGINE=InnoDB
COMMENT='Item yang di request';

ALTER TABLE `trn_orderoutitem` ADD KEY `itemasset_id` (`itemasset_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY `item_id` (`item_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY `itemstock_id` (`itemstock_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY `partner_id` (`partner_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY `itemclass_id` (`itemclass_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY `curr_id` (`curr_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY `projbudgetdet_id` (`projbudgetdet_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY `accbudget_id` (`accbudget_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY `coa_id` (`coa_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY `request_id` (`request_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY `requestitem_id` (`requestitem_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY `inquiry_id` (`inquiry_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY `inquiryitem_id` (`inquiryitem_id`);
ALTER TABLE `trn_orderoutitem` ADD KEY `orderout_id` (`orderout_id`);

ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_itemasset` FOREIGN KEY (`itemasset_id`) REFERENCES `mst_itemasset` (`itemasset_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_item` FOREIGN KEY (`item_id`) REFERENCES `mst_item` (`item_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_itemstock` FOREIGN KEY (`itemstock_id`) REFERENCES `mst_itemstock` (`itemstock_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_partner` FOREIGN KEY (`partner_id`) REFERENCES `mst_partner` (`partner_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_itemclass` FOREIGN KEY (`itemclass_id`) REFERENCES `mst_itemclass` (`itemclass_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_curr` FOREIGN KEY (`curr_id`) REFERENCES `mst_curr` (`curr_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_projbudgetdet` FOREIGN KEY (`projbudgetdet_id`) REFERENCES `mst_projbudgetdet` (`projbudgetdet_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_accbudget` FOREIGN KEY (`accbudget_id`) REFERENCES `mst_accbudget` (`accbudget_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_mst_coa` FOREIGN KEY (`coa_id`) REFERENCES `mst_coa` (`coa_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_trn_request` FOREIGN KEY (`request_id`) REFERENCES `trn_request` (`request_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_trn_requestitem` FOREIGN KEY (`requestitem_id`) REFERENCES `trn_requestitem` (`requestitem_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_trn_inquiry` FOREIGN KEY (`inquiry_id`) REFERENCES `trn_inquiry` (`inquiry_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_trn_inquirydetil` FOREIGN KEY (`inquiryitem_id`) REFERENCES `trn_inquirydetil` (`inquirydetil_id`);
ALTER TABLE `trn_orderoutitem` ADD CONSTRAINT `fk_trn_orderoutitem_trn_orderout` FOREIGN KEY (`orderout_id`) REFERENCES `trn_orderout` (`orderout_id`);





CREATE TABLE `trn_orderoutfiles` (
	`orderoutfiles_id` varchar(14) NOT NULL , 
	`doctype_id` varchar(10) NOT NULL , 
	`orderoutfiles_descr` varchar(90) NOT NULL , 
	`orderoutfiles_order` int(4) NOT NULL DEFAULT 0, 
	`orderoutfiles_file` varchar(90)  , 
	`orderout_id` varchar(14) NOT NULL , 
	`_createby` varchar(13) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(13)  , 
	`_modifydate` datetime  , 
	UNIQUE KEY `orderout_doc` (`orderout_id`, `doctype_id`),
	PRIMARY KEY (`orderoutfiles_id`)
) 
ENGINE=InnoDB
COMMENT='Daftar FIle Inquiry';

ALTER TABLE `trn_orderoutfiles` ADD KEY `doctype_id` (`doctype_id`);
ALTER TABLE `trn_orderoutfiles` ADD KEY `orderout_id` (`orderout_id`);

ALTER TABLE `trn_orderoutfiles` ADD CONSTRAINT `fk_trn_orderoutfiles_mst_doctype` FOREIGN KEY (`doctype_id`) REFERENCES `mst_doctype` (`doctype_id`);
ALTER TABLE `trn_orderoutfiles` ADD CONSTRAINT `fk_trn_orderoutfiles_trn_orderout` FOREIGN KEY (`orderout_id`) REFERENCES `trn_orderout` (`orderout_id`);





CREATE TABLE `trn_orderoutappr` (
	`orderoutappr_id` varchar(14) NOT NULL , 
	`orderoutappr_isapproved` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutappr_by` varchar(14)  , 
	`orderoutappr_date` datetime  , 
	`orderout_version` int(4) NOT NULL DEFAULT 0, 
	`orderoutappr_isdeclined` tinyint(1) NOT NULL DEFAULT 0, 
	`orderoutappr_declinedby` varchar(14)  , 
	`orderoutappr_declineddate` datetime  , 
	`orderoutappr_notes` varchar(255)  , 
	`orderout_id` varchar(30) NOT NULL , 
	`docauth_descr` varchar(90)  , 
	`docauth_order` int(4) NOT NULL DEFAULT 0, 
	`docauth_value` int(4) NOT NULL DEFAULT 100, 
	`docauth_min` int(4) NOT NULL DEFAULT 0, 
	`authlevel_id` varchar(10) NOT NULL , 
	`authlevel_name` varchar(60) NOT NULL , 
	`auth_id` varchar(10)  , 
	`auth_name` varchar(60) NOT NULL , 
	`_createby` varchar(13) NOT NULL , 
	`_createdate` datetime NOT NULL DEFAULT current_timestamp(), 
	`_modifyby` varchar(13)  , 
	`_modifydate` datetime  , 
	UNIQUE KEY `orderout_auth_id` (`orderout_id`, `auth_id`),
	PRIMARY KEY (`orderoutappr_id`)
) 
ENGINE=InnoDB
COMMENT='Approval undefined';

ALTER TABLE `trn_orderoutappr` ADD KEY `orderout_id` (`orderout_id`);

ALTER TABLE `trn_orderoutappr` ADD CONSTRAINT `fk_trn_orderoutappr_trn_orderout` FOREIGN KEY (`orderout_id`) REFERENCES `trn_orderout` (`orderout_id`);





