var this_page_id;
var this_page_options;

import {fgta4slideselect} from  '../../../../../index.php/asset/fgta/framework/fgta4libs/fgta4slideselect.mjs'

const btn_edit = $('#pnl_edit-btn_edit')
const btn_save = $('#pnl_edit-btn_save')
const btn_delete = $('#pnl_edit-btn_delete')
const btn_print = $('#pnl_edit-btn_print');

const btn_commit = $('#pnl_edit-btn_commit')
const btn_uncommit = $('#pnl_edit-btn_uncommit')
			

const btn_approve = $('#pnl_edit-btn_approve')
const btn_decline = $('#pnl_edit-btn_decline')			
				
const comp_select_asset = $('.inquiryselect.asset');
const comp_select_item = $('.inquiryselect.item');
const comp_select_stock = $('.inquiryselect.stock');
const comp_select_partner = $('.inquiryselect.partner');
const comp_select_class = $('.inquiryselect.class');

const pnl_form = $('#pnl_edit-form')
const obj = {
	txt_orderout_id: $('#pnl_edit-txt_orderout_id'),
	cbo_unit_id: $('#pnl_edit-cbo_unit_id'),
	cbo_request_id: $('#pnl_edit-cbo_request_id'),
	chk_orderout_isunref: $('#pnl_edit-chk_orderout_isunref'),
	cbo_inquirytype_id: $('#pnl_edit-cbo_inquirytype_id'),
	cbo_trxmodel_id: $('#pnl_edit-cbo_trxmodel_id'),
	cbo_request_dept_id: $('#pnl_edit-cbo_request_dept_id'),
	txt_orderout_descr: $('#pnl_edit-txt_orderout_descr'),
	dt_orderout_dtstart: $('#pnl_edit-dt_orderout_dtstart'),
	dt_orderout_dtend: $('#pnl_edit-dt_orderout_dtend'),
	cbo_curr_id: $('#pnl_edit-cbo_curr_id'),
	txt_curr_rate: $('#pnl_edit-txt_curr_rate'),
	cbo_ppn_taxtype_id: $('#pnl_edit-cbo_ppn_taxtype_id'),
	cbo_pph_taxtype_id: $('#pnl_edit-cbo_pph_taxtype_id'),
	cbo_partner_id: $('#pnl_edit-cbo_partner_id'),
	cbo_ordercontract_id: $('#pnl_edit-cbo_ordercontract_id'),
	txt_orderout_quot: $('#pnl_edit-txt_orderout_quot'),
	cbo_paymtype_id: $('#pnl_edit-cbo_paymtype_id'),
	cbo_partnerbank_id: $('#pnl_edit-cbo_partnerbank_id'),
	txt_partnerbank_name: $('#pnl_edit-txt_partnerbank_name'),
	txt_partnerbank_bankacc: $('#pnl_edit-txt_partnerbank_bankacc'),
	txt_partnerbank_bankaccname: $('#pnl_edit-txt_partnerbank_bankaccname'),
	txt_partnerbank_bankname: $('#pnl_edit-txt_partnerbank_bankname'),
	cbo_partnercontact_id: $('#pnl_edit-cbo_partnercontact_id'),
	txt_partnercontact_upname: $('#pnl_edit-txt_partnercontact_upname'),
	txt_partnercontact_position: $('#pnl_edit-txt_partnercontact_position'),
	txt_partnercontact_upphone: $('#pnl_edit-txt_partnercontact_upphone'),
	txt_partnercontact_email: $('#pnl_edit-txt_partnercontact_email'),
	cbo_project_id: $('#pnl_edit-cbo_project_id'),
	cbo_projecttask_id: $('#pnl_edit-cbo_projecttask_id'),
	cbo_projbudget_id: $('#pnl_edit-cbo_projbudget_id'),
	cbo_projbudgettask_id: $('#pnl_edit-cbo_projbudgettask_id'),
	chk_orderout_isunbudgetted: $('#pnl_edit-chk_orderout_isunbudgetted'),
	cbo_site_id: $('#pnl_edit-cbo_site_id'),
	cbo_user_dept_id: $('#pnl_edit-cbo_user_dept_id'),
	cbo_recv_dept_id: $('#pnl_edit-cbo_recv_dept_id'),
	txt_deliver_siteaddress: $('#pnl_edit-txt_deliver_siteaddress'),
	txt_deliver_city: $('#pnl_edit-txt_deliver_city'),
	txt_deliver_upname: $('#pnl_edit-txt_deliver_upname'),
	txt_deliver_uptelp: $('#pnl_edit-txt_deliver_uptelp'),
	cbo_inquiry_id: $('#pnl_edit-cbo_inquiry_id'),
	chk_orderout_ismultirequest: $('#pnl_edit-chk_orderout_ismultirequest'),
	txt_inquirymodel_id: $('#pnl_edit-txt_inquirymodel_id'),
	txt_inquiryselect_id: $('#pnl_edit-txt_inquiryselect_id'),
	txt_inquiry_selectfield: $('#pnl_edit-txt_inquiry_selectfield'),
	txt_itemmanage_id: $('#pnl_edit-txt_itemmanage_id'),
	txt_owner_dept_id: $('#pnl_edit-txt_owner_dept_id'),
	txt_orderout_dept_id: $('#pnl_edit-txt_orderout_dept_id'),
	cbo_doc_id: $('#pnl_edit-cbo_doc_id'),
	txt_orderout_version: $('#pnl_edit-txt_orderout_version'),
	chk_orderout_isdateinterval: $('#pnl_edit-chk_orderout_isdateinterval'),
	chk_orderout_iscommit: $('#pnl_edit-chk_orderout_iscommit'),
	txt_orderout_commitby: $('#pnl_edit-txt_orderout_commitby'),
	txt_orderout_commitdate: $('#pnl_edit-txt_orderout_commitdate'),
	chk_orderout_isapprovalprogress: $('#pnl_edit-chk_orderout_isapprovalprogress'),
	chk_orderout_isapproved: $('#pnl_edit-chk_orderout_isapproved'),
	txt_orderout_approveby: $('#pnl_edit-txt_orderout_approveby'),
	txt_orderout_approvedate: $('#pnl_edit-txt_orderout_approvedate'),
	chk_orderout_isdeclined: $('#pnl_edit-chk_orderout_isdeclined'),
	txt_orderout_declineby: $('#pnl_edit-txt_orderout_declineby'),
	txt_orderout_declinedate: $('#pnl_edit-txt_orderout_declinedate'),
	chk_orderout_isclose: $('#pnl_edit-chk_orderout_isclose'),
	txt_orderout_closeby: $('#pnl_edit-txt_orderout_closeby'),
	txt_orderout_closedate: $('#pnl_edit-txt_orderout_closedate'),
	chk_orderout_isadvance: $('#pnl_edit-chk_orderout_isadvance'),
	chk_orderout_isautogenerated: $('#pnl_edit-chk_orderout_isautogenerated'),
	chk_orderout_isitemdeptuser: $('#pnl_edit-chk_orderout_isitemdeptuser'),
	chk_orderout_isitemdeptowner: $('#pnl_edit-chk_orderout_isitemdeptowner')
}


const rec_commitby = $('#pnl_edit_record-commitby');
const rec_commitdate = $('#pnl_edit_record-commitdate');		
		
const rec_approveby = $('#pnl_edit_record-approveby');
const rec_approvedate = $('#pnl_edit_record-approvedate');			
const rec_declineby = $('#pnl_edit_record-declineby');
const rec_declinedate = $('#pnl_edit_record-declinedate');			
			


let form;

export async function init(opt) {
	this_page_id = opt.id;
	this_page_options = opt;


	var disableedit = false;
	// switch (this_page_options.variancename) {
	// 	case 'commit' :
	//		disableedit = true;
	//		btn_edit.linkbutton('disable');
	//		btn_save.linkbutton('disable');
	//		btn_delete.linkbutton('disable');
	//		break;
	// }


	form = new global.fgta4form(pnl_form, {
		primary: obj.txt_orderout_id,
		autoid: true,
		logview: 'trn_orderout',
		btn_edit: disableedit==true? $('<a>edit</a>') : btn_edit,
		btn_save: disableedit==true? $('<a>save</a>') : btn_save,
		btn_delete: disableedit==true? $('<a>delete</a>') : btn_delete,		
		objects : obj,
		OnDataSaving: async (data, options) => { await form_datasaving(data, options) },
		OnDataSaveError: async (data, options) => { await form_datasaveerror(data, options) },
		OnDataSaved: async (result, options) => {  await form_datasaved(result, options) },
		OnDataDeleting: async (data, options) => { await form_deleting(data, options) },
		OnDataDeleted: async (result, options) => { await form_deleted(result, options) },
		OnIdSetup : (options) => { form_idsetup(options) },
		OnViewModeChanged : (viewonly) => { form_viewmodechanged(viewonly) },
		OnRecordStatusCreated: () => {
			
		$('#pnl_edit_record_custom').detach().appendTo("#pnl_edit_record");
		$('#pnl_edit_record_custom').show();		
					
		}		
	})



	btn_print.linkbutton({
		onClick: () => {
			btn_print_click();
		}
	});	
	
	

	btn_commit.linkbutton({ onClick: () => { btn_action_click({ action: 'commit' }); } });
	btn_uncommit.linkbutton({ onClick: () => { btn_action_click({ action: 'uncommit' }); } });			
			

	btn_approve.linkbutton({ onClick: () => { btn_action_click({ action: 'approve' }); } });
	btn_decline.linkbutton({ onClick: () => {
		var id = 'pnl_edit-reason_' + Date.now().toString();
		$ui.ShowMessage(`
			<div style="display: block;  margin-bottom: 10px">
				<div style="font-weight: bold; margin-bottom: 10px">Reason</div>
				<div">
					<input id="${id}" class="easyui-textbox" style="width: 300px; height: 60px;" data-options="multiline: true">
				</div>
			</div>
		`, {
			'Decline': () => {
				var reason = $(`#${id}`).textbox('getValue');
				btn_action_click({ action: 'decline', reason: reason }); 
			},
			'Cancel': () => {
			} 
		}, ()=>{
			var obj_reason = $(`#${id}`);
			var txt = obj_reason.textbox('textbox');
			txt[0].maxLength = 255;
			txt[0].classList.add('declinereasonbox');
			txt[0].addEventListener('keyup', (ev)=>{
				if (ev.key=='Enter') {
					ev.stopPropagation();
				}
			});
			txt.css('text-align', 'center');
			txt.focus();
		})
	}});				
				

	obj.chk_orderout_isunref.checkbox({ onChange: (checked) => { chk_orderout_isunref_check(checked) }});



	new fgta4slideselect(obj.cbo_unit_id, {
		title: 'Pilih unit_id',
		returnpage: this_page_id,
		api: $ui.apis.load_unit_id,
		fieldValue: 'unit_id',
		fieldValueMap: 'unit_id',
		fieldDisplay: 'unit_name',
		fields: [
			{mapping: 'unit_id', text: 'unit_id'},
			{mapping: 'unit_name', text: 'unit_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
			result.records.unshift({unit_id:'--NULL--', unit_name:'NONE'});	
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_request_id, {
		title: 'Pilih request_id',
		returnpage: this_page_id,
		api: `${global.modulefullname}/get-request-outstanding`,
		fieldValue: 'request_id',
		fieldValueMap: 'request_id',
		fieldDisplay: 'request_descr',
		fields: [
			{mapping: 'request_id', text: 'request_id'},
			{mapping: 'request_descr', text: 'request_descr'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
			result.records.unshift({request_id:'--NULL--', request_descr:'NONE'});	
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {
				console.log(record);		

				if (record.projecttask_id==null || record.projecttask_id=='--NULL--') { record.projecttask_id='--NULL--'; record.projecttask_name='NONE'; }
				if (record.projbudget_id==null || record.projbudget_id=='--NULL--') { record.projbudget_id='--NULL--'; record.projbudget_name='NONE'; }
				if (record.projbudgettask_id==null || record.projbudgettask_id=='--NULL--') { record.projbudgettask_id='--NULL--'; record.projbudgettask_name='NONE'; }
				
				form.setValue(obj.cbo_inquiry_id, record.inquiry_id, record.inquiry_descr);
				form.setValue(obj.cbo_inquirytype_id, record.inquirytype_id, record.inquirytype_name);
				form.setValue(obj.cbo_user_dept_id, record.user_dept_id, record.user_dept_name);
				form.setValue(obj.txt_orderout_descr, record.inquiry_descr)
				form.setValue(obj.dt_orderout_dtstart, global.now(from_sql_date(record.request_dtstart)));
				form.setValue(obj.dt_orderout_dtend, global.now(from_sql_date(record.request_dtend)));
				form.setValue(obj.cbo_project_id, record.project_id, record.project_name);
				form.setValue(obj.cbo_projecttask_id, record.projecttask_id, record.projecttask_name);
				form.setValue(obj.cbo_projbudget_id, record.projbudget_id, record.projbudget_name);
				form.setValue(obj.cbo_projbudgettask_id, record.projbudgettask_id, record.projbudgettask_name);
				form.setValue(obj.cbo_trxmodel_id, record.trxmodel_id, record.trxmodel_name);
				form.setValue(obj.txt_inquirymodel_id, record.inquirymodel_id);
				form.setValue(obj.txt_inquiryselect_id, record.inquiryselect_id);
				form.setValue(obj.txt_inquiry_selectfield, record.inquiry_selectfield);
				form.setValue(obj.txt_owner_dept_id, record.owner_dept_id);
				form.setValue(obj.cbo_request_dept_id, record.request_dept_id, record.request_dept_name);
				form.setValue(obj.txt_orderout_dept_id, record.orderout_dept_id);
				form.setValue(obj.txt_itemmanage_id, record.itemmanage_id);
				form.setValue(obj.cbo_doc_id, record.orderout_doc_id, record.orderout_doc_name);
				form.setValue(obj.chk_orderout_isdateinterval, record.request_isdateinterval=='1'?true:false);
				form.setValue(obj.chk_orderout_isitemdeptuser, record.request_isitemdeptuser=='1'?true:false);
				form.setValue(obj.chk_orderout_isitemdeptowner, record.request_isitemdeptowner=='1'?true:false);
				form.setValue(obj.cbo_site_id, record.site_id, record.site_name);
				form.setValue(obj.txt_deliver_siteaddress, record.deliver_siteaddress);
				form.setValue(obj.txt_deliver_city, record.deliver_city);
				form.setValue(obj.txt_deliver_upname, record.deliver_upname);
				form.setValue(obj.txt_deliver_uptelp, record.deliver_uptelp);		
				form.setValue(obj.cbo_recv_dept_id, record.owner_dept_id,  record.owner_dept_name );						
									
				
				chk_orderout_isdateinterval_check(record.request_isdateinterval=='1'?true:false);
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_inquirytype_id, {
		title: 'Pilih inquirytype_id',
		returnpage: this_page_id,
		api: $ui.apis.load_inquirytype_id,
		fieldValue: 'inquirytype_id',
		fieldValueMap: 'inquirytype_id',
		fieldDisplay: 'inquirytype_name',
		fields: [
			{mapping: 'inquirytype_id', text: 'inquirytype_id'},
			{mapping: 'inquirytype_name', text: 'inquirytype_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
				
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {	
				form.setValue(obj.txt_inquirymodel_id, record.inquirymodel_id);
				form.setValue(obj.txt_inquiryselect_id, record.inquiryselect_id);
				form.setValue(obj.txt_inquiry_selectfield, record.inquiry_selectfield);
				form.setValue(obj.txt_owner_dept_id, record.owner_dept_id);
				form.setValue(obj.cbo_request_dept_id, record.related_dept_id, record.related_dept_name);
				form.setValue(obj.txt_orderout_dept_id, record.orderout_dept_id);
				form.setValue(obj.cbo_doc_id, record.orderout_doc_id, record.orderout_doc_name);
				form.setValue(obj.cbo_trxmodel_id, record.trxmodel_id, record.trxmodel_name);
				form.setValue(obj.txt_itemmanage_id, record.itemmanage_id);
				form.setValue(obj.chk_orderout_isdateinterval, record.inquirytype_isdateinterval=='1'?true:false);
				form.setValue(obj.chk_orderout_isitemdeptuser, record.inquirytype_isdeptuser=='1'?true:false);
				form.setValue(obj.chk_orderout_isitemdeptowner, record.inquirytype_isdeptowner=='1'?true:false);

				chk_orderout_isdateinterval_check(record.inquirytype_isdateinterval=='1'?true:false);
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_trxmodel_id, {
		title: 'Pilih trxmodel_id',
		returnpage: this_page_id,
		api: $ui.apis.load_trxmodel_id,
		fieldValue: 'trxmodel_id',
		fieldValueMap: 'trxmodel_id',
		fieldDisplay: 'trxmodel_name',
		fields: [
			{mapping: 'trxmodel_id', text: 'trxmodel_id'},
			{mapping: 'trxmodel_name', text: 'trxmodel_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
				
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_request_dept_id, {
		title: 'Pilih request_dept_id',
		returnpage: this_page_id,
		api: $ui.apis.load_request_dept_id,
		fieldValue: 'request_dept_id',
		fieldValueMap: 'dept_id',
		fieldDisplay: 'dept_name',
		fields: [
			{mapping: 'dept_id', text: 'dept_id'},
			{mapping: 'dept_name', text: 'dept_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
				
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_curr_id, {
		title: 'Pilih curr_id',
		returnpage: this_page_id,
		api: $ui.apis.load_curr_id,
		fieldValue: 'curr_id',
		fieldValueMap: 'curr_id',
		fieldDisplay: 'curr_name',
		fields: [
			{mapping: 'curr_id', text: 'curr_id'},
			{mapping: 'curr_name', text: 'curr_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
				
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {
				form.setValue(obj.txt_curr_rate, record.curr_rate)
										
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_ppn_taxtype_id, {
		title: 'Pilih ppn_taxtype_id',
		returnpage: this_page_id,
		api: $ui.apis.load_ppn_taxtype_id,
		fieldValue: 'ppn_taxtype_id',
		fieldValueMap: 'taxtype_id',
		fieldDisplay: 'taxtype_name',
		fields: [
			{mapping: 'taxtype_id', text: 'taxtype_id'},
			{mapping: 'taxtype_name', text: 'taxtype_name'},
		],
		OnDataLoading: (criteria) => {
			criteria.taxmodel_id = 'PPN'
		},
		OnDataLoaded : (result, options) => {
			result.records.unshift({taxtype_id:'--NULL--', taxtype_name:'NONE'});	
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {	
				console.log(record);			
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_pph_taxtype_id, {
		title: 'Pilih pph_taxtype_id',
		returnpage: this_page_id,
		api: $ui.apis.load_pph_taxtype_id,
		fieldValue: 'pph_taxtype_id',
		fieldValueMap: 'taxtype_id',
		fieldDisplay: 'taxtype_name',
		fields: [
			{mapping: 'taxtype_id', text: 'taxtype_id'},
			{mapping: 'taxtype_name', text: 'taxtype_name'},
		],
		OnDataLoading: (criteria) => {
			criteria.taxmodel_id = 'PPH'
		},
		OnDataLoaded : (result, options) => {
			result.records.unshift({taxtype_id:'--NULL--', taxtype_name:'NONE'});	
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {	
				console.log(record);			
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_partner_id, {
		title: 'Pilih partner_id',
		returnpage: this_page_id,
		api: $ui.apis.load_partner_id,
		fieldValue: 'partner_id',
		fieldValueMap: 'partner_id',
		fieldDisplay: 'partner_name',
		fields: [
			{mapping: 'partner_id', text: 'partner_id'},
			{mapping: 'partner_name', text: 'partner_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
				
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_ordercontract_id, {
		title: 'Pilih ordercontract_id',
		returnpage: this_page_id,
		api: $ui.apis.load_ordercontract_id,
		fieldValue: 'ordercontract_id',
		fieldValueMap: 'ordercontract_id',
		fieldDisplay: 'ordercontract_descr',
		fields: [
			{mapping: 'ordercontract_id', text: 'ordercontract_id'},
			{mapping: 'ordercontract_descr', text: 'ordercontract_descr'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
			result.records.unshift({ordercontract_id:'--NULL--', ordercontract_descr:'NONE'});	
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_paymtype_id, {
		title: 'Pilih paymtype_id',
		returnpage: this_page_id,
		api: $ui.apis.load_paymtype_id,
		fieldValue: 'paymtype_id',
		fieldValueMap: 'paymtype_id',
		fieldDisplay: 'paymtype_name',
		fields: [
			{mapping: 'paymtype_id', text: 'paymtype_id'},
			{mapping: 'paymtype_name', text: 'paymtype_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
				
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_partnerbank_id, {
		title: 'Pilih partnerbank_id',
		returnpage: this_page_id,
		api: $ui.apis.load_partnerbank_id,
		fieldValue: 'partnerbank_id',
		fieldValueMap: 'partnerbank_id',
		fieldDisplay: 'partnerbank_accnum',
		fields: [
			{mapping: 'partnerbank_id', text: 'partnerbank_id'},
			{mapping: 'partnerbank_accnum', text: 'partnerbank_accnum'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
			result.records.unshift({partnerbank_id:'--NULL--', partnerbank_accnum:'NONE'});	
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {
				form.setValue(obj.txt_partnerbank_name, record.partnerbank_accname)
				form.setValue(obj.txt_partnerbank_bankacc, record.partnerbank_accnum)
				form.setValue(obj.txt_partnerbank_bankaccname, record.partnerbank_accname)
				form.setValue(obj.txt_partnerbank_name, record.bank_name)
										
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_partnercontact_id, {
		title: 'Pilih partnercontact_id',
		returnpage: this_page_id,
		api: $ui.apis.load_partnercontact_id,
		fieldValue: 'partnercontact_id',
		fieldValueMap: 'partnercontact_id',
		fieldDisplay: 'partnercontact_name',
		fields: [
			{mapping: 'partnercontact_id', text: 'partnercontact_id'},
			{mapping: 'partnercontact_name', text: 'partnercontact_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
			result.records.unshift({partnercontact_id:'--NULL--', partnercontact_name:'NONE'});	
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {
				form.setValue(obj.txt_partnercontact_upname, record.partnercontact_name)
				form.setValue(obj.txt_partnercontact_position, record.partnercontact_position)
				form.setValue(obj.txt_partnercontact_upphone, record.partnercontact_mobilephone)
				form.setValue(obj.txt_partnercontact_email, record.partnercontact_email)		
										
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_project_id, {
		title: 'Pilih project_id',
		returnpage: this_page_id,
		api: $ui.apis.load_project_id,
		fieldValue: 'project_id',
		fieldValueMap: 'project_id',
		fieldDisplay: 'project_name',
		fields: [
			{mapping: 'project_id', text: 'project_id'},
			{mapping: 'project_name', text: 'project_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
			result.records.unshift({project_id:'--NULL--', project_name:'NONE'});	
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_projecttask_id, {
		title: 'Pilih projecttask_id',
		returnpage: this_page_id,
		api: $ui.apis.load_projecttask_id,
		fieldValue: 'projecttask_id',
		fieldValueMap: 'projecttask_id',
		fieldDisplay: 'projecttask_name',
		fields: [
			{mapping: 'projecttask_id', text: 'projecttask_id'},
			{mapping: 'projecttask_name', text: 'projecttask_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
			result.records.unshift({projecttask_id:'--NULL--', projecttask_name:'NONE'});	
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_projbudget_id, {
		title: 'Pilih projbudget_id',
		returnpage: this_page_id,
		api: $ui.apis.load_projbudget_id,
		fieldValue: 'projbudget_id',
		fieldValueMap: 'projbudget_id',
		fieldDisplay: 'projbudget_name',
		fields: [
			{mapping: 'projbudget_id', text: 'projbudget_id'},
			{mapping: 'projbudget_name', text: 'projbudget_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
			result.records.unshift({projbudget_id:'--NULL--', projbudget_name:'NONE'});	
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_projbudgettask_id, {
		title: 'Pilih projbudgettask_id',
		returnpage: this_page_id,
		api: $ui.apis.load_projbudgettask_id,
		fieldValue: 'projbudgettask_id',
		fieldValueMap: 'projbudgettask_id',
		fieldDisplay: 'projecttask_name',
		fields: [
			{mapping: 'projbudgettask_id', text: 'projbudgettask_id'},
			{mapping: 'projecttask_name', text: 'projecttask_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
			result.records.unshift({projbudgettask_id:'--NULL--', projecttask_name:'NONE'});	
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_site_id, {
		title: 'Pilih site_id',
		returnpage: this_page_id,
		api: $ui.apis.load_site_id,
		fieldValue: 'site_id',
		fieldValueMap: 'site_id',
		fieldDisplay: 'site_name',
		fields: [
			{mapping: 'site_id', text: 'site_id'},
			{mapping: 'site_name', text: 'site_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
				
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_user_dept_id, {
		title: 'Pilih user_dept_id',
		returnpage: this_page_id,
		api: $ui.apis.load_user_dept_id,
		fieldValue: 'user_dept_id',
		fieldValueMap: 'dept_id',
		fieldDisplay: 'dept_name',
		fields: [
			{mapping: 'dept_id', text: 'dept_id'},
			{mapping: 'dept_name', text: 'dept_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
			result.records.unshift({dept_id:'--NULL--', dept_name:'NONE'});	
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_recv_dept_id, {
		title: 'Pilih recv_dept_id',
		returnpage: this_page_id,
		api: $ui.apis.load_recv_dept_id,
		fieldValue: 'recv_dept_id',
		fieldValueMap: 'dept_id',
		fieldDisplay: 'dept_name',
		fields: [
			{mapping: 'dept_id', text: 'dept_id'},
			{mapping: 'dept_name', text: 'dept_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
				
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_inquiry_id, {
		title: 'Pilih inquiry_id',
		returnpage: this_page_id,
		api: $ui.apis.load_inquiry_id,
		fieldValue: 'inquiry_id',
		fieldValueMap: 'inquiry_id',
		fieldDisplay: 'inquiry_descr',
		fields: [
			{mapping: 'inquiry_id', text: 'inquiry_id'},
			{mapping: 'inquiry_descr', text: 'inquiry_descr'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
			result.records.unshift({inquiry_id:'--NULL--', inquiry_descr:'NONE'});	
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {
										
			}
		}
	})				
				
	new fgta4slideselect(obj.cbo_doc_id, {
		title: 'Pilih doc_id',
		returnpage: this_page_id,
		api: $ui.apis.load_doc_id,
		fieldValue: 'doc_id',
		fieldValueMap: 'doc_id',
		fieldDisplay: 'doc_name',
		fields: [
			{mapping: 'doc_id', text: 'doc_id'},
			{mapping: 'doc_name', text: 'doc_name'},
		],
		OnDataLoading: (criteria) => {},
		OnDataLoaded : (result, options) => {
				
		},
		OnSelected: (value, display, record, args) => {
			if (value!=args.PreviousValue ) {				
			}
		}
	})				
				

	document.addEventListener('keydown', (ev)=>{
		if ($ui.getPages().getCurrentPage()==this_page_id) {
			if (ev.code=='KeyS' && ev.ctrlKey==true) {
				if (!form.isInViewMode()) {
					form.btn_save_click();
				}
				ev.stopPropagation()
				ev.preventDefault()
			}
		}
	}, true)
	
	document.addEventListener('OnSizeRecalculated', (ev) => {
		OnSizeRecalculated(ev.detail.width, ev.detail.height)
	})	

	document.addEventListener('OnButtonBack', (ev) => {
		if ($ui.getPages().getCurrentPage()==this_page_id) {
			ev.detail.cancel = true;
			if (form.isDataChanged()) {
				form.canceledit(()=>{
					$ui.getPages().show('pnl_list', ()=>{
						form.setViewMode()
						$ui.getPages().ITEMS['pnl_list'].handler.scrolllast()
					})
				})
			} else {
				$ui.getPages().show('pnl_list', ()=>{
					form.setViewMode()
					$ui.getPages().ITEMS['pnl_list'].handler.scrolllast()
				})
			}
		
		}
	})

	document.addEventListener('OnButtonHome', (ev) => {
		if ($ui.getPages().getCurrentPage()==this_page_id) {
			if (form.isDataChanged()) {
				ev.detail.cancel = true;
				$ui.ShowMessage('Anda masih dalam mode edit dengan pending data, silakan matikan mode edit untuk kembali ke halaman utama.')
			}
		}
	})

	//button state

}

export function OnSizeRecalculated(width, height) {
}

export function getForm() {
	return form
}


export function open(data, rowid, viewmode=true, fn_callback) {

	var pOpt = form.getDefaultPrompt(false)
	var fn_dataopening = async (options) => {
		options.criteria[form.primary.mapping] = data[form.primary.mapping]
	}

	var fn_dataopened = async (result, options) => {
		var record = result.record;
		updatefilebox(record);


		console.log(result)

		for (var objid in obj) {
			let o = obj[objid]
			if (o.isCombo() && !o.isRequired()) {
				var value =  result.record[o.getFieldValueName()];
				if (value==null ) {
					record[o.getFieldValueName()] = pOpt.value;
					record[o.getFieldDisplayName()] = pOpt.text;
				}
			}
		}
  		updaterecordstatus(record)

		

		form.SuspendEvent(true);

		chk_orderout_isunref_check(record.orderout_isunref=='1'?true:false)

		form
			.fill(record)
			.setValue(obj.cbo_unit_id, record.unit_id, record.unit_name)
			.setValue(obj.cbo_request_id, record.request_id, record.request_descr)
			.setValue(obj.cbo_inquirytype_id, record.inquirytype_id, record.inquirytype_name)
			.setValue(obj.cbo_trxmodel_id, record.trxmodel_id, record.trxmodel_name)
			.setValue(obj.cbo_request_dept_id, record.request_dept_id, record.request_dept_name)
			.setValue(obj.cbo_curr_id, record.curr_id, record.curr_name)
			.setValue(obj.cbo_ppn_taxtype_id, record.ppn_taxtype_id, record.ppn_taxtype_name)
			.setValue(obj.cbo_pph_taxtype_id, record.pph_taxtype_id, record.pph_taxtype_name)
			.setValue(obj.cbo_partner_id, record.partner_id, record.partner_name)
			.setValue(obj.cbo_ordercontract_id, record.ordercontract_id, record.ordercontract_descr)
			.setValue(obj.cbo_paymtype_id, record.paymtype_id, record.paymtype_name)
			.setValue(obj.cbo_partnerbank_id, record.partnerbank_id, record.partnerbank_accnum)
			.setValue(obj.cbo_partnercontact_id, record.partnercontact_id, record.partnercontact_name)
			.setValue(obj.cbo_project_id, record.project_id, record.project_name)
			.setValue(obj.cbo_projecttask_id, record.projecttask_id, record.projecttask_name)
			.setValue(obj.cbo_projbudget_id, record.projbudget_id, record.projbudget_name)
			.setValue(obj.cbo_projbudgettask_id, record.projbudgettask_id, record.projecttask_name)
			.setValue(obj.cbo_site_id, record.site_id, record.site_name)
			.setValue(obj.cbo_user_dept_id, record.user_dept_id, record.user_dept_name)
			.setValue(obj.cbo_recv_dept_id, record.recv_dept_id, record.recv_dept_name)
			.setValue(obj.cbo_inquiry_id, record.inquiry_id, record.inquiry_descr)
			.setValue(obj.cbo_doc_id, record.doc_id, record.doc_name)
			.setViewMode(viewmode)
			.lock(false)
			.rowid = rowid


		/* tambahkan event atau behaviour saat form dibuka
		   apabila ada rutin mengubah form dan tidak mau dijalankan pada saat opening,
		   cek dengan form.isEventSuspended()
		*/   
		chk_orderout_isdateinterval_check(record.orderout_isdateinterval=='1'?true:false)

		/* commit form */
		form.commit()
		form.SuspendEvent(false); 
		updatebuttonstate(record)

		// tampilkan form untuk data editor
		fn_callback()
	}

	var fn_dataopenerror = (err) => {
		$ui.ShowMessage('[ERROR]'+err.errormessage);
	}

	form.dataload(fn_dataopening, fn_dataopened, fn_dataopenerror)
	
}


export function createnew() {
	form.createnew(async (data, options)=>{
		// console.log(data)
		// console.log(options)
		form.rowid = null

		// set nilai-nilai default untuk form
		data.orderout_isunref = '0'
		data.orderout_dtstart = global.now()
		data.orderout_dtend = global.now()
		data.curr_rate = global.setup.curr_rate
		data.orderout_isunbudgetted = '0'
		data.orderout_ismultirequest = '0'
		data.orderout_version = 0
		data.orderout_isdateinterval = '0'
		data.orderout_iscommit = '0'
		data.orderout_isapprovalprogress = '0'
		data.orderout_isapproved = '0'
		data.orderout_isdeclined = '0'
		data.orderout_isclose = '0'
		data.orderout_isadvance = '0'
		data.orderout_isautogenerated = '0'
		data.orderout_isitemdeptuser = '0'
		data.orderout_isitemdeptowner = '0'

		data.unit_id = '--NULL--'
		data.unit_name = 'NONE'
		data.request_id = '--NULL--'
		data.request_descr = 'NONE'
		data.inquirytype_id = '0'
		data.inquirytype_name = '-- PILIH --'
		data.trxmodel_id = '0'
		data.trxmodel_name = '-- PILIH --'
		data.request_dept_id = '0'
		data.request_dept_name = '-- PILIH --'
		data.curr_id = global.setup.curr_id;
		data.curr_name = global.setup.curr_name;
		data.ppn_taxtype_id = '--NULL--'
		data.ppn_taxtype_name = 'NONE'
		data.pph_taxtype_id = '--NULL--'
		data.pph_taxtype_name = 'NONE'
		data.partner_id = '0'
		data.partner_name = '-- PILIH --'
		data.ordercontract_id = '--NULL--'
		data.ordercontract_descr = 'NONE'
		data.paymtype_id = '0'
		data.paymtype_name = '-- PILIH --'
		data.partnerbank_id = '--NULL--'
		data.partnerbank_accnum = 'NONE'
		data.partnercontact_id = '--NULL--'
		data.partnercontact_name = 'NONE'
		data.project_id = '--NULL--'
		data.project_name = 'NONE'
		data.projecttask_id = '--NULL--'
		data.projecttask_name = 'NONE'
		data.projbudget_id = '--NULL--'
		data.projbudget_name = 'NONE'
		data.projbudgettask_id = '--NULL--'
		data.projecttask_name = 'NONE'
		data.site_id = '0'
		data.site_name = '-- PILIH --'
		data.user_dept_id = '--NULL--'
		data.user_dept_name = 'NONE'
		data.recv_dept_id = '0'
		data.recv_dept_name = '-- PILIH --'
		data.inquiry_id = '--NULL--'
		data.inquiry_descr = 'NONE'
		data.doc_id = global.setup.doc_id
		data.doc_name = global.setup.doc_id


		chk_orderout_isunref_check(data.orderout_isunref=='1'?true:false)
		chk_orderout_isdateinterval_check(data.orderout_isdateinterval=='1'?true:false)

		rec_commitby.html('');
		rec_commitdate.html('');
		
		rec_approveby.html('');
		rec_approvedate.html('');
		rec_declineby.html('');
		rec_declinedate.html('');
		




		var button_commit_on = true;
		var button_uncommit_on = false;
		var button_approve_on = false;
		var button_decline_on = false;
		btn_commit.linkbutton(button_commit_on ? 'enable' : 'disable');
		btn_uncommit.linkbutton(button_uncommit_on ? 'enable' : 'disable');
		btn_approve.linkbutton(button_approve_on ? 'enable' : 'disable');
		btn_decline.linkbutton(button_decline_on ? 'enable' : 'disable');
			



		options.OnCanceled = () => {
			$ui.getPages().show('pnl_list')
		}

		$ui.getPages().ITEMS['pnl_edititemsgrid'].handler.createnew(data, options)
		$ui.getPages().ITEMS['pnl_editfilesgrid'].handler.createnew(data, options)
		$ui.getPages().ITEMS['pnl_editapprovalgrid'].handler.createnew(data, options)


	})
}


export function detil_open(pnlname) {
	if (form.isDataChanged()) {
		$ui.ShowMessage('Simpan dulu perubahan datanya.')
		return;
	}

	//$ui.getPages().show(pnlname)
	$ui.getPages().show(pnlname, () => {
		$ui.getPages().ITEMS[pnlname].handler.OpenDetil(form.getData())
	})	
}


function updatefilebox(record) {
	// apabila ada keperluan untuk menampilkan data dari object storage

}

function updaterecordstatus(record) {
	// apabila ada keperluan untuk update status record di sini

		rec_commitby.html(record.orderout_commitby);
		rec_commitdate.html(record.orderout_commitdate);
		
		rec_approveby.html(record.orderout_approveby);
		rec_approvedate.html(record.orderout_approvedate);
		rec_declineby.html(record.orderout_declineby);
		rec_declinedate.html(record.orderout_declinedate);
			
}

function updatebuttonstate(record) {
	// apabila ada keperluan untuk update state action button di sini

		/* action button */
		var button_commit_on = false;
		var button_uncommit_on = false;
		var button_approve_on = false;
		var button_decline_on = false;

		
		if (record.orderout_isfirm=="1") {
			button_commit_on = false;
			button_uncommit_on = false;
			button_approve_on = false;
			button_decline_on = false;
			form.lock(true);	
		} else if (record.orderout_isdeclined=="1" || record.orderout_isuseralreadydeclined=="1") {
			button_commit_on = false;
			button_uncommit_on = true;
			button_approve_on = true;
			button_decline_on = false;
			form.lock(true);	
		} else if (record.orderout_isapproved=="1" || record.orderout_isuseralreadyapproved=="1") {
			button_commit_on = false;
			button_uncommit_on = false;
			button_approve_on = false;
			button_decline_on = true;	
			form.lock(true);	
		} else if (record.orderout_isapprovalprogress=="1") {
			button_commit_on = false;
			button_uncommit_on = false;
			button_approve_on = true;
			button_decline_on = true;
			form.lock(true);	
		} else if (record.orderout_iscommit=="1") {
			button_commit_on = false;
			button_uncommit_on = true;
			button_approve_on = true;
			button_decline_on = true;
			form.lock(true);		
		} else {
			button_commit_on = true;
			button_uncommit_on = false;
			button_approve_on = false;
			button_decline_on = false;
			form.lock(false);
		} 
	
		btn_commit.linkbutton(button_commit_on ? 'enable' : 'disable');
		btn_uncommit.linkbutton(button_uncommit_on ? 'enable' : 'disable');
		btn_approve.linkbutton(button_approve_on ? 'enable' : 'disable');
		btn_decline.linkbutton(button_decline_on ? 'enable' : 'disable');		
				
}

function updategridstate(record) {
	// apabila ada keperluan untuk update state grid list di sini



	var updategriddata = {}

	var col_commit = 'orderout_iscommit';
	updategriddata[col_commit] = record.orderout_iscommit;	
	
	var col_approveprogress = 'orderout_isapprovalprogress';
	var col_approve = 'orderout_isapprove'
	var col_decline = "orderout_isdeclined"
	updategriddata[col_approveprogress] = record.orderout_isapprovalprogress;
	updategriddata[col_approve] = record.orderout_isapproved;
	updategriddata[col_decline] = record.orderout_isdeclined;				
			
	$ui.getPages().ITEMS['pnl_list'].handler.updategrid(updategriddata, form.rowid);
			
}

function form_viewmodechanged(viewmode) {
	var OnViewModeChangedEvent = new CustomEvent('OnViewModeChanged', {detail: {}})
	$ui.triggerevent(OnViewModeChangedEvent, {
		viewmode: viewmode
	})
}

function form_idsetup(options) {
	var objid = obj.txt_orderout_id
	switch (options.action) {
		case 'fill' :
			objid.textbox('disable') 
			break;

		case 'createnew' :
			// console.log('new')
			if (form.autoid) {
				objid.textbox('disable') 
				objid.textbox('setText', '[AUTO]') 
			} else {
				objid.textbox('enable') 
			}
			break;
			
		case 'save' :
			objid.textbox('disable') 
			break;	
	}
}


async function form_datasaving(data, options) {
	// cek dulu data yang akan disimpan,
	// apabila belum sesuai dengan yang diharuskan, batalkan penyimpanan
	//    options.cancel = true

	// Modifikasi object data, apabila ingin menambahkan variabel yang akan dikirim ke server
	// options.skipmappingresponse = ['unit_id', 'request_id', 'ppn_taxtype_id', 'pph_taxtype_id', 'ordercontract_id', 'partnerbank_id', 'partnercontact_id', 'project_id', 'projecttask_id', 'projbudget_id', 'projbudgettask_id', 'user_dept_id', 'inquiry_id', ];
	options.skipmappingresponse = [];
	for (var objid in obj) {
		var o = obj[objid]
		if (o.isCombo() && !o.isRequired()) {
			var id = o.getFieldValueName()
			options.skipmappingresponse.push(id)
			console.log(id)
		}
	}

}

async function form_datasaveerror(err, options) {
	// apabila mau olah error messagenya
	// $ui.ShowMessage(err.errormessage)
	console.log(err)
}


async function form_datasaved(result, options) {
	// Apabila tidak mau munculkan dialog
	// options.suppressdialog = true

	// Apabila ingin mengganti message Data Tersimpan
	// options.savedmessage = 'Data sudah disimpan cuy!'

	// if (form.isNewData()) {
	// 	console.log('masukan ke grid')
	// 	$ui.getPages().ITEMS['pnl_list'].handler.updategrid(form.getData())
	// } else {
	// 	console.log('update grid')
	// }


	var data = {}
	Object.assign(data, form.getData(), result.dataresponse)
	var pOpt = form.getDefaultPrompt(false)
	for (var objid in obj) {
		var o = obj[objid]
		if (o.isCombo() && !o.isRequired()) {
			var value =  result.dataresponse[o.getFieldValueName()];
			var text = result.dataresponse[o.getFieldDisplayName()];
			if (value==null ) {
				value = pOpt.value;
				text = pOpt.text;
			}
			form.setValue(o, value, text);
		}
	}
	form.rowid = $ui.getPages().ITEMS['pnl_list'].handler.updategrid(data, form.rowid)
}



async function form_deleting(data) {
}

async function form_deleted(result, options) {
	$ui.getPages().show('pnl_list')
	$ui.getPages().ITEMS['pnl_list'].handler.removerow(form.rowid)

}



function btn_print_click() {

	if (form.isDataChanged() || !form.isInViewMode()) {
		$ui.ShowMessage('Simpan dulu perubahan datanya.');
		return;
	}

	var id = obj.txt_orderout_id.textbox('getValue');
	var printurl = 'index.php/printout/' + window.global.modulefullname + '/orderout.xprint?id=' + id;

	var print_to_new_window = global.setup.print_to_new_window;
	var debug = false;
	var debug = false;
	if (debug || print_to_new_window) {
		var w = window.open(printurl);
		w.onload = () => {
			window.onreadytoprint(() => {
				iframe.contentWindow.print();
			});
		}
	} else {
		$ui.mask('wait...');
		var iframe_id = 'fgta_printelement';
		var iframe = document.getElementById(iframe_id);
		if (iframe) {
			iframe.parentNode.removeChild(iframe);
			iframe = null;
		}

		if (!iframe) {
			iframe = document.createElement('iframe');
			iframe.id = iframe_id;
			iframe.style.visibility = 'hidden';
			iframe.style.height = '10px';
			iframe.style.widows = '10px';
			document.body.appendChild(iframe);

			iframe.onload = () => {
				$ui.unmask();
				iframe.contentWindow.OnPrintCommand(() => {
					console.log('start print');
					iframe.contentWindow.print();
				});
				iframe.contentWindow.preparemodule();
			}
		}
		iframe.src = printurl + '&iframe=1';

	}

}	






async function btn_action_click(args) {
	if (form.isDataChanged() || !form.isInViewMode()) {
		$ui.ShowMessage('[WARNING]Simpan dulu perubahan data, dan tidak sedang dalam mode edit.');
		return;
	}


	var docname = 'Orderout'
	var txt_version = obj.txt_orderout_version;
	var chk_iscommit = obj.chk_orderout_iscommit;
	
	var chk_isapprovalprogress = obj.chk_orderout_isapprovalprogress;	
	var chk_isapprove = obj.chk_orderout_isapproved;
	var chk_isdeclined = obj.chk_orderout_isdeclined;
		
	
	var id = form.getCurrentId();

	Object.assign(args, {
		id: id,
		act_url: null,
		act_msg_quest: null,
		act_msg_result: null,
		act_do: null,
		use_otp: false,
		otp_message: `Berikut adalah code yang harus anda masukkan untuk melakukan ${args.action} ${docname} dengan no id ${id}`,
	});

	switch (args.action) {
		case 'commit' :
			args.act_url = `${global.modulefullname}/xtion-${args.action}`;
			args.act_msg_quest = `Apakah anda yakin akan <b>${args.action}</b> ${docname} no ${args.id} ?`;
			args.act_msg_result = `${docname} no ${args.id} telah di ${args.action}.`;
			args.act_do = (result) => {
				chk_iscommit.checkbox('check');
				
			chk_isapprove.checkbox('uncheck');
		
				form.commit();
			}
			break;

		case 'uncommit' :
			args.act_url = `${global.modulefullname}/xtion-${args.action}`;
			args.act_msg_quest = `Apakah anda yakin akan <b>${args.action}</b> ${docname} no ${args.id} ?`;
			args.act_msg_result = `${docname} no ${args.id} telah di ${args.action}.`;
			args.act_do = (result) => {
				chk_iscommit.checkbox('uncheck');
				
			chk_isapprove.checkbox('uncheck');
			chk_isdeclined.checkbox('uncheck');
		
				form.setValue(txt_version, result.version);
				form.commit();
			}
			break;

		
		case 'approve' :
			args.act_url = `${global.modulefullname}/xtion-approve`;
			args.act_msg_quest = `Apakah anda yakin akan <b>${args.action}</b> ${docname} no ${args.id} ?`;
			args.act_msg_result = `${docname} no ${args.id} telah di ${args.action}.`;
			args.use_otp = true;
			args.otp_title = 'Approval Code';
			args.param = {
				approve: true,
				approval_note: ''
			}
			args.act_do = (result) => {
				chk_iscommit.checkbox('check');
				chk_isapprovalprogress.checkbox('check');
				chk_isapprove.checkbox(result.isfinalapproval ? "check" : "uncheck");
				chk_isdeclined.checkbox('uncheck');
				form.commit();
			}
			break;

		case 'decline' :
			args.act_url = `${global.modulefullname}/xtion-approve`;
			args.act_msg_quest = '', //`Apakah anda yakin akan <b>${args.action}</b> ${docname} no ${args.id} ?`;
			args.act_msg_result = `${docname} no ${args.id} telah di ${args.action}.`;
			args.use_otp = true;
			args.otp_title = 'Decline Code';
			args.param = {
				approve: false,
				approval_note: args.reason
			}
			args.act_do = (result) => {
				chk_iscommit.checkbox('check');
				chk_isapprove.checkbox('uncheck');
				chk_isdeclined.checkbox('check');
				form.commit();
			}
			break;		
			
	}


	try {
		$ui.mask('wait..');
		var { doAction } = await import('../../../../../index.php/asset/fgta/framework/fgta4libs/fgta4xtion.mjs');
		await doAction(args, (err, result) => {
			if (err) {
				$ui.ShowMessage('[WARNING]' + err.message);	
			} else {
				updaterecordstatus(result.dataresponse);
				args.act_do(result);
				updatebuttonstate(result.dataresponse);
				updategridstate(result.dataresponse);
				if (args.act_msg_result!=='') $ui.ShowMessage('[INFO]' + args.act_msg_result);	
			}
		});
	} catch (err) {
		console.error(err);
		$ui.ShowMessage('[ERROR]' + err.message);
	} finally {
		$ui.unmask();
	}
}	
	
	

function chk_orderout_isunref_check(checked) {
	if (checked) {
		// Tanpaperlu referensi dari request
		obj.cbo_request_id.revalidate({
			required: false, invalidMessage: null, prompt: form.getDefaultPrompt(false).text,
			validType: null,
		});
		form.setDisable(obj.cbo_request_id, true);
		form.setDisable(obj.cbo_inquirytype_id, false);

	} else {
		obj.cbo_request_id.revalidate({
			required: true, invalidMessage:  'Request harus diisi', prompt: form.getDefaultPrompt(true).text,
			validType: "requiredcombo['pnl_edit-cbo_request_id']",
		});	
		form.setDisable(obj.cbo_request_id, false);
		form.setDisable(obj.cbo_inquirytype_id, true);
	}

	obj.cbo_request_id.reset();
	obj.cbo_inquirytype_id.reset();

}


function chk_orderout_isdateinterval_check(checked) {
	if (checked) {
		$('#pnl_edit-request_dtstart .form_label_col').html('Date Start');
		$('#pnl_edit-request_dtend').show();
	} else {
		$('#pnl_edit-request_dtstart .form_label_col').html('Date');
		$('#pnl_edit-request_dtend').hide();
	}
}



function txt_inquiryselect_id_changed(inquiryselect_id) {

	switch (inquiryselect_id) {
		case 'A': // A	ASSET SELECTION
			comp_select_asset.removeClass('hidden');
			comp_select_item.addClass('hidden')
			comp_select_partner.addClass('hidden')
			comp_select_stock.addClass('hidden')

			comp_select_class.addClass('disabled')
			break;

		case 'C': // C	CLASS SELECTION
			comp_select_asset.addClass('hidden');
			comp_select_item.addClass('hidden')
			comp_select_partner.addClass('hidden')
			comp_select_stock.addClass('hidden')

			comp_select_class.removeClass('disabled')
			break;

		case 'I': // I	ITEM SELECTION
			comp_select_asset.addClass('hidden');
			comp_select_item.removeClass('hidden')
			comp_select_partner.addClass('hidden')
			comp_select_stock.addClass('hidden')

			comp_select_class.addClass('disabled')
			break;


		case 'P' : // P	PARTNER SELECTION
			comp_select_asset.addClass('hidden');
			comp_select_item.addClass('hidden')
			comp_select_partner.removeClass('hidden')
			comp_select_stock.addClass('hidden')

			comp_select_class.addClass('disabled')
			break;

		case 'S' : // S	STOCK SELECTION
			comp_select_asset.addClass('hidden');
			comp_select_item.addClass('hidden')
			comp_select_partner.addClass('hidden')
			comp_select_stock.removeClass('hidden')

			comp_select_class.addClass('disabled')
			break;
				
	}
}