<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Order</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_orderout_id" class="easyui-textbox" mapping="orderout_id"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Unit</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_unit_id" class="easyui-combo" style="width: 400px" mapping="unit_id" display="unit_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Request</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_request_id" class="easyui-combo" style="width: 400px" mapping="request_id" display="request_descr" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_orderout_isunref" class="easyui-checkbox c1" mapping="orderout_isunref" data-options="label: 'Un Requested', labelPosition: 'after', checked: false , labelWidth: '200px'">
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Inquiry Type</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_inquirytype_id" class="easyui-combo" style="width: 400px" mapping="inquirytype_id" display="inquirytype_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'type inquiry harus diisi'"   validType="requiredcombo['pnl_edit-cbo_inquirytype_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Model Trx</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_trxmodel_id" class="easyui-combo" style="width: 400px" mapping="trxmodel_id" display="trxmodel_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Model Trx harus diisi', disabled: true"   validType="requiredcombo['pnl_edit-cbo_trxmodel_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Request Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_request_dept_id" class="easyui-combo" style="width: 400px" mapping="request_dept_id" display="request_dept_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Departemen Requestor harus diisi', disabled: true"   validType="requiredcombo['pnl_edit-cbo_request_dept_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_orderout_descr" class="easyui-textbox" mapping="orderout_descr"  maxlength="90" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Descr harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row"  id="pnl_edit-request_dtstart" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Date Start</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_orderout_dtstart" class="easyui-datebox" style="width: 400px" mapping="orderout_dtstart" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" id="pnl_edit-request_dtend" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Date End</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_orderout_dtend" class="easyui-datebox" style="width: 400px" mapping="orderout_dtend" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Currency</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_curr_id" class="easyui-combo" style="width: 400px" mapping="curr_id" display="curr_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Currency harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_curr_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Rate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_curr_rate" class="easyui-numberbox" mapping="curr_rate" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">PPN</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_ppn_taxtype_id" class="easyui-combo" style="width: 400px" mapping="ppn_taxtype_id" display="ppn_taxtype_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">PPh</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_pph_taxtype_id" class="easyui-combo" style="width: 400px" mapping="pph_taxtype_id" display="pph_taxtype_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<?=$this->Section('Partner', true, true)?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Partner</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partner_id" class="easyui-combo" style="width: 400px" mapping="partner_id" display="partner_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Partner Harus diisi', disabled: false"   validType="requiredcombo['pnl_edit-cbo_partner_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Order Contract</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_ordercontract_id" class="easyui-combo" style="width: 400px" mapping="ordercontract_id" display="ordercontract_descr" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Quotation Ref</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_orderout_quot" class="easyui-textbox" mapping="orderout_quot"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Tipe Pembayaran</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_paymtype_id" class="easyui-combo" style="width: 400px" mapping="paymtype_id" display="paymtype_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Tipe Pembayaran harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_paymtype_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Partner Bank</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partnerbank_id" class="easyui-combo" style="width: 400px" mapping="partnerbank_id" display="partnerbank_accnum" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Paymto Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partnerbank_name" class="easyui-textbox" mapping="partnerbank_name" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Paymto Account</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partnerbank_bankacc" class="easyui-textbox" mapping="partnerbank_bankacc" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Paymto Account Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partnerbank_bankaccname" class="easyui-textbox" mapping="partnerbank_bankaccname" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Paymto Bank Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partnerbank_bankname" class="easyui-textbox" mapping="partnerbank_bankname" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Partner Contact</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partnercontact_id" class="easyui-combo" style="width: 400px" mapping="partnercontact_id" display="partnercontact_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partnercontact_upname" class="easyui-textbox" mapping="partnercontact_upname" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Position</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partnercontact_position" class="easyui-textbox" mapping="partnercontact_position" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">HP</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partnercontact_upphone" class="easyui-textbox" mapping="partnercontact_upphone" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Email</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partnercontact_email" class="easyui-textbox" mapping="partnercontact_email" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , validType: ['email'], disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		</div>
					
		<?=$this->Section('Budget', true, true)?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Project</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_project_id" class="easyui-combo" style="width: 400px" mapping="project_id" display="project_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE', disabled: true"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Project Task</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_projecttask_id" class="easyui-combo" style="width: 400px" mapping="projecttask_id" display="projecttask_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Budget</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_projbudget_id" class="easyui-combo" style="width: 400px" mapping="projbudget_id" display="projbudget_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Budget Task</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_projbudgettask_id" class="easyui-combo" style="width: 400px" mapping="projbudgettask_id" display="projecttask_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_orderout_isunbudgetted" class="easyui-checkbox c1" mapping="orderout_isunbudgetted" data-options="label: 'UnBudgetted', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		</div>
					
		<?=$this->Section('Deliver To', true, true)?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Site</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_site_id" class="easyui-combo" style="width: 400px" mapping="site_id" display="site_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Site harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_site_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">User Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_user_dept_id" class="easyui-combo" style="width: 400px" mapping="user_dept_id" display="user_dept_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Receiver Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_recv_dept_id" class="easyui-combo" style="width: 400px" mapping="recv_dept_id" display="recv_dept_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Departemen harus diisi'"   validType="requiredcombo['pnl_edit-cbo_recv_dept_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">To Address</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_deliver_siteaddress" class="easyui-textbox" mapping="deliver_siteaddress"  maxlength="250" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">To City</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_deliver_city" class="easyui-textbox" mapping="deliver_city" uppercase="true" maxlength="60" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">To UP Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_deliver_upname" class="easyui-textbox" mapping="deliver_upname" uppercase="true" maxlength="60" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">To UP Telp</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_deliver_uptelp" class="easyui-textbox" mapping="deliver_uptelp" uppercase="true" maxlength="60" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		</div>
					
		<?=$this->Section('Order Information', true, true)?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Inquiry</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_inquiry_id" class="easyui-combo" style="width: 400px" mapping="inquiry_id" display="inquiry_descr" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE', disabled: true"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_orderout_ismultirequest" class="easyui-checkbox c1" mapping="orderout_ismultirequest" data-options="label: 'Allow Multiple Request', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Inquiry Model</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquirymodel_id" class="easyui-textbox" mapping="inquirymodel_id"  maxlength="1" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Inquiry Model harus diisi', disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Inquiry Select</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiryselect_id" class="easyui-textbox" mapping="inquiryselect_id"  maxlength="1" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Inquiry Select harus diisi', disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>


		<div class="form_row" >
				<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Inquiry Select Field</div>
				<div class="form_input_col" style="border: 0px solid black">
					<input id="pnl_edit-txt_inquiry_selectfield" class="easyui-textbox" mapping="inquiry_selectfield"  maxlength="90" style="width: 400px" data-options="multiline: false, disabled: true  ">
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
			</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Item Manage As</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemmanage_id" class="easyui-textbox" mapping="itemmanage_id"  maxlength="2" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Item Manage Model harus diisi', disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Owner Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_owner_dept_id" class="easyui-textbox" mapping="owner_dept_id"  maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Owner Dept harus diisi', disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Orderout Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_orderout_dept_id" class="easyui-textbox" mapping="orderout_dept_id"  maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Orderout Dept harus diisi', disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Order Doc</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_doc_id" class="easyui-combo" style="width: 400px" mapping="doc_id" display="doc_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'ID harus diisi', disabled: true"   validType="requiredcombo['pnl_edit-cbo_doc_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Doc Version</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_orderout_version" class="easyui-numberbox" mapping="orderout_version" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_orderout_isdateinterval" class="easyui-checkbox c1" mapping="orderout_isdateinterval" data-options="label: 'Date Interval', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_orderout_iscommit" class="easyui-checkbox c1" mapping="orderout_iscommit" data-options="label: 'Commit', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">CommitBy</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_orderout_commitby" class="easyui-textbox" mapping="orderout_commitby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">CommitDate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_orderout_commitdate" class="easyui-textbox" mapping="orderout_commitdate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_orderout_isapprovalprogress" class="easyui-checkbox c1" mapping="orderout_isapprovalprogress" data-options="label: 'Progress', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_orderout_isapproved" class="easyui-checkbox c1" mapping="orderout_isapproved" data-options="label: 'Approved', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Approve By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_orderout_approveby" class="easyui-textbox" mapping="orderout_approveby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Approve Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_orderout_approvedate" class="easyui-textbox" mapping="orderout_approvedate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_orderout_isdeclined" class="easyui-checkbox c1" mapping="orderout_isdeclined" data-options="label: 'Declined', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Decline By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_orderout_declineby" class="easyui-textbox" mapping="orderout_declineby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Decline Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_orderout_declinedate" class="easyui-textbox" mapping="orderout_declinedate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_orderout_isclose" class="easyui-checkbox c1" mapping="orderout_isclose" data-options="label: 'Close', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Close By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_orderout_closeby" class="easyui-textbox" mapping="orderout_closeby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Close Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_orderout_closedate" class="easyui-textbox" mapping="orderout_closedate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_orderout_isadvance" class="easyui-checkbox c1" mapping="orderout_isadvance" data-options="label: 'Use Advance Request', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_orderout_isautogenerated" class="easyui-checkbox c1" mapping="orderout_isautogenerated" data-options="label: 'Auto Generated', labelPosition: 'after', checked: false , labelWidth: '300px', disabled: true">
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_orderout_isitemdeptuser" class="easyui-checkbox c1" mapping="orderout_isitemdeptuser" data-options="label: 'Item Related to User Dept', labelPosition: 'after', checked: false , labelWidth: '300px', disabled: true">
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_orderout_isitemdeptowner" class="easyui-checkbox c1" mapping="orderout_isitemdeptowner" data-options="label: 'Item Related to Owner Dept', labelPosition: 'after', checked: false , labelWidth: '300px', disabled: true">
			</div>
		</div>

		</div>
					
	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col detilbox" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_edititemsgrid')">
					<div id="pnl_edit-txt_items_title" class="detilgrid-text">Items</div>
					<div id="pnl_edit-txt_items_value" class="detilgrid-value">&nbsp;</div>
				</div>
				<!-- <div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editmultiadd')">
					<div id="pnl_edit-txt_multiadd_title" class="detilgrid-text">Items Add</div>
					<div id="pnl_edit-txt_multiadd_value" class="detilgrid-value">&nbsp;</div>
				</div> -->
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editfilesgrid')">
					<div id="pnl_edit-txt_files_title" class="detilgrid-text">Files</div>
					<div id="pnl_edit-txt_files_value" class="detilgrid-value">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editapprovalgrid')">
					<div id="pnl_edit-txt_approval_title" class="detilgrid-text">Approval</div>
					<div id="pnl_edit-txt_approval_value" class="detilgrid-value">&nbsp;</div>
				</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		<a id="pnl_edit-btn_print" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'icon-print'">print</a>
		
			<a id="pnl_edit-btn_commit" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'fgta-icon-commit'">Commit</a>			
			<a id="pnl_edit-btn_uncommit" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'fgta-icon-uncommit'">UnCommit</a>
			
		
				<a id="pnl_edit-btn_approve" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="plain:true,iconCls:'fgta-icon-posting'">Approve</a>
				<a id="pnl_edit-btn_decline" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="plain:true,iconCls:'fgta-icon-unposting'">Decline</a>
				
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

