<div id="pnl_list">
	<div class="fgta-page-title">Daftar Order</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<!-- Simple Query -->
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<tr>
					<th mapping="orderout_id">orderout_id</th>
					<th mapping="projbudget_name">projbudget_name</th>
					<th mapping="orderout_descr">orderout_descr</th>
					<th mapping="orderout_dtstart">orderout_dtstart</th>
					<th mapping="orderout_quot">orderout_quot</th>
					<th mapping="orderout_isapproved" type="checkbox">orderout_isapproved</th>
					<th mapping="orderout_isclose" type="checkbox">orderout_isclose</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 200px; border-bottom: 1px solid #000000">Budget</td>
					<td class="fgtable-head" style="border-bottom: 1px solid #000000">Descr</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date Start</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Quotation Ref</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Approved</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Close</td>

				</tr>
			</thead>
		</table>
	</div>



</div>