<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Rekening Bank</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_bankrekening_id" class="easyui-textbox" mapping="bankrekening_id" uppercase="true" maxlength="20" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'ID harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Nama Rekening</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_bankrekening_name" class="easyui-textbox" mapping="bankrekening_name" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Nama Rekening harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Kode Rekening</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_bankrekening_code" class="easyui-textbox" mapping="bankrekening_code"  maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Kode Rekening harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Nama di buku</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_bankrekening_namabuku" class="easyui-textbox" mapping="bankrekening_namabuku" uppercase="true" maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Kode Rekening harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_bankrekening_isdisabled" class="easyui-checkbox c1" mapping="bankrekening_isdisabled" data-options="label: 'Disabled', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Tanggal Pembukaan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_bankrekening_opendate" class="easyui-datebox" style="width: 400px" mapping="bankrekening_opendate" data-options="editable:false , required: true, invalidMessage: 'Tanggal buka rekening harus diisi'">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>


<div id="dt_bankrekening_closedate_container">


		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Tanggal Tutup</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_bankrekening_closedate" class="easyui-datebox" style="width: 400px" mapping="bankrekening_closedate" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>
</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_bankrekening_descr" class="easyui-textbox" mapping="bankrekening_descr"  maxlength="255" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Bank</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_bank_id" class="easyui-combo" style="width: 400px" mapping="bank_id" display="bank_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Bank harus diisi'"   validType="requiredcombo['pnl_edit-cbo_bank_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Currency</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_curr_id" class="easyui-combo" style="width: 400px" mapping="curr_id" display="curr_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Currency harus diisi'"   validType="requiredcombo['pnl_edit-cbo_curr_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>
		

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">COA</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_coa_id" class="easyui-combo" style="width: 400px" mapping="coa_id" display="coa_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'COA harus diisi'"   validType="requiredcombo['pnl_edit-cbo_coa_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>



	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="width">Hapus</a>
		</div>
	</div>

</div>

