<thead>
	<tr>
		<th mapping="itemctg_id">itemctg_id</th>
		<th mapping="itemctg_group">itemctg_group</th>
		<th mapping="itemctg_name">itemctg_name</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="width: 200px; border-bottom: 1px solid #000000">Group Name</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Category Name</td>
	</tr>
</thead>