<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Item Asset Move</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row txt_itemassetmove_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemassetmove_id" class="easyui-textbox" mapping="itemassetmove_id"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_inquiry_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Inquiry</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_inquiry_id" class="easyui-combo" style="width: 400px" mapping="inquiry_id" display="inquiry_descr" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemassetmove_isunreferenced" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemassetmove_isunreferenced" class="easyui-checkbox c1" mapping="itemassetmove_isunreferenced" data-options="label: 'Unreferenced', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_itemassetmovemodel_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Asset Move Model</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_itemassetmovemodel_id" class="easyui-combo" style="width: 400px" mapping="itemassetmovemodel_id" display="itemassetmovemodel_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Model asset move harus diisi'"   validType="requiredcombo['pnl_edit-cbo_itemassetmovemodel_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_itemassetmovetype_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Asset Move Type</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_itemassetmovetype_id" class="easyui-combo" style="width: 400px" mapping="itemassetmovetype_id" display="itemassetmovetype_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'tipe asset move harus diisi'"   validType="requiredcombo['pnl_edit-cbo_itemassetmovetype_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row dt_itemassetmove_dtstart" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Start Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_itemassetmove_dtstart" class="easyui-datebox" style="width: 400px" mapping="itemassetmove_dtstart" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row dt_itemassetmove_dtexpected" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Expected Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_itemassetmove_dtexpected" class="easyui-datebox" style="width: 400px" mapping="itemassetmove_dtexpected" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row dt_itemassetmove_dtend" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">End Date </div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_itemassetmove_dtend" class="easyui-datebox" style="width: 400px" mapping="itemassetmove_dtend" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_itemassetmove_descr" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemassetmove_descr" class="easyui-textbox" mapping="itemassetmove_descr"  maxlength="90" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Descr harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<?=$this->Section('Sender Information', true, true)?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edit_row cbo_user_dept_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">User Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_user_dept_id" class="easyui-combo" style="width: 400px" mapping="user_dept_id" display="user_dept_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Departemen User harus diisi'"   validType="requiredcombo['pnl_edit-cbo_user_dept_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_from_site_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">From Site</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_from_site_id" class="easyui-combo" style="width: 400px" mapping="from_site_id" display="from_site_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Site harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_from_site_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_from_room_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">From Room</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_from_room_id" class="easyui-combo" style="width: 400px" mapping="from_room_id" display="from_room_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Room harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_from_room_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_from_empl_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Responsible Empl</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_from_empl_id" class="easyui-combo" style="width: 400px" mapping="from_empl_id" display="from_empl_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		</div>
					
		<?=$this->Section('Recipient Information', true, true)?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edit_row cbo_to_dept_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">To Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_to_dept_id" class="easyui-combo" style="width: 400px" mapping="to_dept_id" display="to_dept_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Departemen penerima harus diisi'"   validType="requiredcombo['pnl_edit-cbo_to_dept_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_to_site_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">To Site</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_to_site_id" class="easyui-combo" style="width: 400px" mapping="to_site_id" display="to_site_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Site penerima harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_to_site_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_to_room_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">To Room</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_to_room_id" class="easyui-combo" style="width: 400px" mapping="to_room_id" display="to_room_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Room harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_to_room_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row cbo_to_empl_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Responsible Empl</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_to_empl_id" class="easyui-combo" style="width: 400px" mapping="to_empl_id" display="to_empl_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		</div>
					
		<div class="form_row pnl_edit_row cbo_doc_id" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Doc</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_doc_id" class="easyui-combo" style="width: 400px" mapping="doc_id" display="doc_name" data-options="editable:false, valueField:'id', textField:'text' , disabled: true, required: true, invalidMessage: 'ID harus diisi'"   validType="requiredcombo['pnl_edit-cbo_doc_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_itemassetmove_version" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Doc Version</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemassetmove_version" class="easyui-numberbox" mapping="itemassetmove_version" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemassetmove_isdateinterval" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemassetmove_isdateinterval" class="easyui-checkbox c1" mapping="itemassetmove_isdateinterval" data-options="label: 'Date Interval', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemassetmove_isdept" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemassetmove_isdept" class="easyui-checkbox c1" mapping="itemassetmove_isdept" data-options="label: 'Dept', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemassetmove_isemployee" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemassetmove_isemployee" class="easyui-checkbox c1" mapping="itemassetmove_isemployee" data-options="label: 'Employee', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemassetmove_issite" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemassetmove_issite" class="easyui-checkbox c1" mapping="itemassetmove_issite" data-options="label: 'Site', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemassetmove_isroom" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemassetmove_isroom" class="easyui-checkbox c1" mapping="itemassetmove_isroom" data-options="label: 'Room', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemassetmove_isreturn" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemassetmove_isreturn" class="easyui-checkbox c1" mapping="itemassetmove_isreturn" data-options="label: 'Return', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemassetmove_iscommit" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemassetmove_iscommit" class="easyui-checkbox c1" mapping="itemassetmove_iscommit" data-options="label: 'Commit', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_itemassetmove_commitby" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">CommitBy</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemassetmove_commitby" class="easyui-textbox" mapping="itemassetmove_commitby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_itemassetmove_commitdate" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">CommitDate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemassetmove_commitdate" class="easyui-textbox" mapping="itemassetmove_commitdate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemassetmove_issend" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemassetmove_issend" class="easyui-checkbox c1" mapping="itemassetmove_issend" data-options="label: 'Send', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_itemassetmove_sendby" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">SendBy</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemassetmove_sendby" class="easyui-textbox" mapping="itemassetmove_sendby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_itemassetmove_senddate" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">SendDate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemassetmove_senddate" class="easyui-textbox" mapping="itemassetmove_senddate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row chk_itemassetmove_isrcv" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemassetmove_isrcv" class="easyui-checkbox c1" mapping="itemassetmove_isrcv" data-options="label: 'Received', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_itemassetmove_rcvby" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ReceivedBy</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemassetmove_rcvby" class="easyui-textbox" mapping="itemassetmove_rcvby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row txt_itemassetmove_rcvdate" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ReceivedDate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemassetmove_rcvdate" class="easyui-textbox" mapping="itemassetmove_rcvdate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col detilbox" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_edititemsgrid')">
					<div id="pnl_edit-txt_items_title" class="detilgrid-text">Items</div>
					<div id="pnl_edit-txt_items_value" class="detilgrid-value">&nbsp;</div>
				</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
			<a id="pnl_edit-btn_print" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'icon-print'">print</a>
			
			<a id="pnl_edit-btn_commit" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'fgta-icon-commit'">Commit</a>			
			<a id="pnl_edit-btn_uncommit" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'fgta-icon-uncommit'">UnCommit</a>
			
			
			
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

