<div id="pnl_edititemsgrid">
	<div class="fgta-page-title">Daftar Items</div>
	<div id="pnl_edititemsgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_edititemsgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_edititemsgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_edititemsgrid-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_edititemsgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<?php
				$customview = __DIR__.'/itemassetmove-itemsgrid-customview.phtml'; 
				if (is_file($customview)) {
					include $customview;
				} else { ?>
				<tr>
<th type="check">chk</th>					
					<th mapping="itemassetmovedetil_id">itemassetmovedetil_id</th>
					<th mapping="itemasset_name">itemasset_name</th>
					<th mapping="itemassetmovedetil_qty" style="text-align: right" formatter="row_format_number">itemassetmovedetil_qty</th>
					<th mapping="send_itemassetstatus_name">send_itemassetstatus_name</th>

					<th mapping=""></th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
<td class="fgtable-head" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Item Asset</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Qty</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Send Status</td>

					<td class="fgtable-head" style="border-bottom: 1px solid #000000; text-align: center">&nbsp;</td>
				</tr>
				<?php } ?>
			</thead>
		</table>
	</div>

	<div id="pnl_edititemsgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_edititemsgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_edititemsgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>


</div>	
