<div id="pnl_list">
	<div class="fgta-page-title">Daftar Saldo Awal Pettycash</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<?php
		$customsearch = __DIR__.'/pettycashsaldo-list-customsearch.phtml'; 
		if (is_file($customsearch)) {
			include $customsearch;
		} else { ?>
		<!-- Simple Query -->
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
		<?php } ?>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<?php
				$customview = __DIR__.'/pettycashsaldo-list-customview.phtml'; 
				if (is_file($customview)) {
					include $customview;
				} else { ?>
				<tr>
					<th mapping="pettycashsaldo_id">pettycashsaldo_id</th>
					<th mapping="pettycashsaldo_date">pettycashsaldo_date</th>
					<th mapping="site_name">site_name</th>
					<th mapping="pettycashsaldo_awal" style="text-align: right"  formatter="row_format_number">pettycashsaldo_awal</th>
					<th mapping="pettycashsaldo_mutasi" style="text-align: right"  formatter="row_format_number">pettycashsaldo_mutasi</th>
					<th mapping="pettycashsaldo_akhir" style="text-align: right"  formatter="row_format_number">pettycashsaldo_akhir</th>
					<th mapping="pettycashsaldo_isclosed" type="checkbox">pettycashsaldo_isclosed</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Site</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Saldo Awal</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Mutasi</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Saldo Akhir</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Closed</td>

				</tr>
				<?php } ?>
			</thead>
		</table>
	</div>



</div>