<div id="obj_framecontainer" class="page-frame-container">
</div>

<div id="obj_pageheader" class="hidden-element">
	<div class="page-descr"><?=$this->reporttitle?></div>
	<div class="page-paging">page x of y</div>
</div>


<div id="wrapper" class="report-wrapper">

	<div id="obj_report_header" class="report-header fullwidth">
		<div style="display: flex; justify-content: space-between">
			<div>
				<div class="report-title"><?=$this->reporttitle?></div>
				<div><?=$this->reportsubtitle?></div>
				<div>per <?=$this->reportdate?></div>
			</div>
			<div>
				<div style="text-align: right; font-weight: bold; margin-bottom: 2mm"><?=__COMPANY_NAME__?></div>
				<div class="page-paging" style="text-align: right">generat date: <?=date('d/m/Y')?></div>
				<div id="obj_paging_page_1" class="page-paging" style="text-align: right">page x of y</div>
			</div>
		</div>
	</div>

	<!-- 
		for formating tabletoexcel, cek:
		https://github.com/linways/table-to-excel
	//-->		
	<table id="obj_reporttable" class="report-table fullwidth" cellpadding="0" cellspacing="0" data-cols-width="5,15,50,15,15,15,15,15,15,15,15,15,15,15,15"> 
		<thead id="obj_reporttable_header" class="report-page-header">
			<tr style="display:none">
				<td data-f-bold="true"><?=$this->reporttitle?></th>
			</tr>
			<tr style="display:none">
				<td data-f-bold="true"><?=$this->reportsubtitle?></th>
			</tr>
			<tr style="display:none">
				<td>per <?=$this->reportdate?></th>
			</tr>
			
			<tr>
				<th class="cell-header col-no" data-fill-color="CCCCCC" data-f-bold="true">No</th>
				<th class="cell-header col-coa" data-fill-color="CCCCCC" data-f-bold="true">Jurnal ID</th>
				<th class="cell-header col-descr" data-fill-color="CCCCCC" data-f-bold="true">Descr</th>
				<th class="cell-header col-amount" data-fill-color="CCCCCC" data-f-bold="true">Saldo Awal</th>
				<th class="cell-header col-amount" data-fill-color="CCCCCC" data-f-bold="true">Debet</th>
				<th class="cell-header col-amount" data-fill-color="CCCCCC" data-f-bold="true">Kredit</th>
				<th class="cell-header col-amount" data-fill-color="CCCCCC" data-f-bold="true">Saldo Akhir</th>

				<!-- hanya muncul di spreadsheet -->
				<th class="col-hidden" data-fill-color="CCCCCC" data-f-bold="true" data-a-h="center">JurnalDetil ID</th>
				<th class="col-hidden" data-fill-color="CCCCCC" data-f-bold="true" data-a-h="center">Jurnal Date</th>
				<th class="col-hidden" data-fill-color="CCCCCC" data-f-bold="true">Coa ID</th>
				<th class="col-hidden" data-fill-color="CCCCCC" data-f-bold="true">Coa Name</th>
				<th class="col-hidden" data-fill-color="CCCCCC" data-f-bold="true">Unit</th>
				<th class="col-hidden" data-fill-color="CCCCCC" data-f-bold="true">Dept</th>
				<th class="col-hidden" data-fill-color="CCCCCC" data-f-bold="true">Partner</th>
				<th class="col-hidden" data-fill-color="CCCCCC" data-f-bold="true">Project</th>

			</tr>
		</thead>

		<tfoot id="obj_reporttable_footer" class="report-page-footer">
			<tr id="obj_reporttable_loadinginfo">
				<td>
					<div id="obj_reporttable_loadingmessage" class="footerstatusbox" style="position: absolute; padding-top: 10px; font-weight: bold">Wait, report are still loading ...</div>
				</td>
			</tr>
		</tfoot>

		<tbody id="obj_reporttable_body">
		</tbody>
	</table>



	<div id="obj_report_footer" class="fullwidth report-footer report-footer-initial">
		<div class="report-footer-content">
		</div>
	</div>


</div>