<div id="pnl_report" style="position: absolute; top: 5px; bottom: 5px; right: 5px; left: 5px; display: flex; flex-direction: column;">
	<div style="display: flex; justify-content: space-between; margin-top: 5px ">


		<div style="display: flex; flex-direction: column; flex-grow:1; margin-right: 5px; border: 0px solid red">
			<div>
				<span class="label-text">Type</span>
				<input id="pnl_report-cbo_reporttype" class="easyui-combo" style="width: 300px" data-options="required: true">
			</div>

			<div style="display: flex; flex-wrap: wrap; row-gap: 10px; column-gap: 5px">
				<div>
					<span class="label-text">COA</span>
					<input id="pnl_report-cbo_coa_id" class="easyui-combo" style="width: 300px" >
				</div>
				<div id="pnl_report-pnl_filter">
					<span id="pnl_report-lbl_filtercaption" class="label-text">Filter</span>
					<input id="pnl_report-cbo_filter" class="easyui-combo" style="width: 200px" data-options="required: true">
				</div>
				<div>
					<span class="label-text">Per Tanggal</span>
					<input id="pnl_report-dt_report_date" class="easyui-datebox" style="width: 130px" data-options="editable:false ">
				</div>
				<div>
					<a href="javascript:void(0)" id="pnl_report-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
				</div>
			</div>
		</div>
		<div style="display: flex; flex-direction: column; row-gap: 10px; border: 0px solid red">
			<a href="javascript:void(0)" id="pnl_report-btn_export" class="easyui-linkbutton c8" style="width: 80px">Export</a>
			<a href="javascript:void(0)" id="pnl_report-btn_print" class="easyui-linkbutton c8" style="width: 80px">Print</a>
		</div>








		<!-- 
		<div style="display: flex; flex-wrap: wrap; row-gap: 10px; column-gap: 5px">
			<div>
				<span class="label-text">Type</span>
				<input id="pnl_report-cbo_reporttype" class="easyui-combo" style="width: 300px" data-options="required: true">
			</div>

			<div id="pnl_report-pnl_filter">
				<span id="pnl_report-lbl_filtercaption" class="label-text">Filter</span>
				<input id="pnl_report-cbo_filter" class="easyui-combo" style="width: 200px" data-options="required: true">
			</div>
			<div>
				<span class="label-text">Per Tanggal</span>
				<input id="pnl_report-dt_report_date" class="easyui-datebox" style="width: 130px" data-options="editable:false ">
			</div>
			<div>
				<a href="javascript:void(0)" id="pnl_report-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>

		</div>
		<div style="display: flex; flex-wrap: wrap; row-gap: 10px; column-gap: 5px; justify-content: flex-end;">
			<a href="javascript:void(0)" id="pnl_report-btn_export" class="easyui-linkbutton c8" style="width: 80px">Export</a>
			<a href="javascript:void(0)" id="pnl_report-btn_print" class="easyui-linkbutton c8" style="width: 80px">Print</a>
		</div>
		-->
	</div>
	<div id="pnl_report-rpt_container" style="margin-top: 10px; border: 1px solid #000; flex: 1">
		<iframe id="pnl_report-obj_reportiframe" style="border: 0px; width:100%; height:100%;-webkit-transform:scale(1);-moz-transform-scale(1);">
		</iframe>
	</div>	
</div>	