<div id="pnl_list">
	<div class="fgta-page-title">Daftar Asset Service</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<!-- Simple Query -->
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<tr>
					<th mapping="assetservice_id">assetservice_id</th>
					<th mapping="itemasset_name">itemasset_name</th>
					<th mapping="itemclass_name">itemclass_name</th>
					<th mapping="assetservice_descr">assetservice_descr</th>
					<th mapping="assetservice_date">assetservice_date</th>
					<th mapping="assetservice_dateest">assetservice_dateest</th>
					<th mapping="assetservice_datecompletion">assetservice_datecompletion</th>
					<th mapping="recv_id">recv_id</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Item Asset</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Item Class</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Descr</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Service Date</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Completion Est Date </td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Actual Completion Date </td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Recv</td>

				</tr>
			</thead>
		</table>
	</div>



</div>