<div id="pnl_editdetilgrid">
	<div class="fgta-page-title">Daftar Detil</div>
	<div id="pnl_editdetilgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_editdetilgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_editdetilgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_editdetilgrid-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_editdetilgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<tr>
					<th mapping="bankbook_date">bankbook_date</th>
					<th mapping="bankbookdetil_ref">bankbookdetil_ref</th>
					<th mapping="jurnal_id">jurnal_id</th>
					<th mapping="acc_fin">acc_fin</th>
					<th mapping="bankbookdetil_notes">bankbookdetil_notes</th>
					<th mapping="bankbookdetil_validrd" style="text-align: right" formatter="row_format_number">bankbookdetil_validrd</th>
					<th mapping="bankbookdetil_validrk" style="text-align: right" formatter="row_format_number">bankbookdetil_validrk</th>
					<th mapping="bankbookdetil_validrsaldo" style="text-align: right" formatter="row_format_number">bankbookdetil_validrsaldo</th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Ref</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Link PV/OR</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Account Fin</td>
					<td class="fgtable-head" style="border-bottom: 1px solid #000000">Notes</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">IDR Debet</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">IDR Kredit</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">IDR Saldo</td>
				</tr>
			</thead>
		</table>
	</div>

	<div id="pnl_editdetilgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_editdetilgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_editdetilgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>


</div>	
