<div id="pnl_editjurnaltypeform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editjurnaltypeform-caption">{{STATE_BEG}}Jurnal Type{{STATE_END}}</div>
		<a id="pnl_editjurnaltypeform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editjurnaltypeform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editjurnaltypeform-form">

		<div class="form_row pnl_editjurnaltypeform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editjurnaltypeform-txt_jurnalsourcetype_id" class="easyui-textbox" mapping="jurnalsourcetype_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editjurnaltypeform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Type</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editjurnaltypeform-cbo_jurnaltype_id" class="easyui-combo" style="width: 400px" mapping="jurnaltype_id" display="jurnaltype_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Jurnal Type harus diisi', prompt: '-- PILIH --'"  validType="requiredcombo['pnl_editjurnaltypeform-cbo_jurnaltype_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editjurnaltypeform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Source</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editjurnaltypeform-txt_jurnalsource_id" class="easyui-textbox" mapping="jurnalsource_id"  maxlength="10"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editjurnaltypeform-autoadd" type="checkbox"><label for="pnl_editjurnaltypeform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editjurnaltypeform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editjurnaltypeform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editjurnaltypeform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editjurnaltypeform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editjurnaltypeform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
