<thead>
	<tr>
		<th mapping="inquiry_id">inquiry_id</th>
		<th mapping="inquiry_dtstart">inquiry_dtstart</th>
		<th mapping="inquiry_descr">inquiry_descr</th>
		<th mapping="request_dept_name">request_dept_name</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Descr</td>
		<td class="fgtable-head" style="width: 200px; border-bottom: 1px solid #000000">Inquiry To</td>
	</tr>
</thead>