<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Inquiry</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiry_id" class="easyui-textbox" mapping="inquiry_id"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row inquirytype-selector" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Inquiry Type</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_inquirytype_id" class="easyui-combo" style="width: 400px" mapping="inquirytype_id" display="inquirytype_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'type inquiry harus diisi'"   validType="requiredcombo['pnl_edit-cbo_inquirytype_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Inquiry To</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_request_dept_id" class="easyui-combo" style="width: 400px" mapping="request_dept_id" display="request_dept_name" data-options="editable:false, valueField:'id', textField:'text' , disabled: true, required: true, invalidMessage: 'Inquiry To Departemen harus diisi'"   validType="requiredcombo['pnl_edit-cbo_request_dept_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiry_descr" class="easyui-textbox" mapping="inquiry_descr"  maxlength="255" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Descr harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div id="pnl_edit-inquiry_dtstart" class="form_row pnl_edit_row head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Date Start</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_inquiry_dtstart" class="easyui-datebox" style="width: 400px" mapping="inquiry_dtstart" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div id="pnl_edit-inquiry_dtend" class="form_row pnl_edit_row head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Date End</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_inquiry_dtend" class="easyui-datebox" style="width: 400px" mapping="inquiry_dtend" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">User Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_user_dept_id" class="easyui-combo" style="width: 400px" mapping="user_dept_id" display="user_dept_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Departemen User harus diisi'"   validType="requiredcombo['pnl_edit-cbo_user_dept_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Responsible Empl</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_empl_id" class="easyui-combo" style="width: 400px" mapping="empl_id" display="empl_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row head-step2 head-step2-hidden" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiry_isadvance" class="easyui-checkbox c1" mapping="inquiry_isadvance" data-options="label: 'Request Advance Payment', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row paymentpanel paymentpanel-hidden head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Partner</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partner_id" class="easyui-combo" style="width: 400px" mapping="partner_id" display="partner_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row paymentpanel paymentpanel-hidden head-step2 head-step2-hidden" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Dibayar Kepada</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_name" class="easyui-textbox" mapping="partner_name"  maxlength="60" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row paymentpanel paymentpanel-hidden head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Tipe Pembayaran</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_paymtype_id" class="easyui-combo" style="width: 400px" mapping="paymtype_id" display="paymtype_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Tipe Pembayaran harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_paymtype_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row head-step2 head-step2-hidden" style="display: none">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_paymtype_isviabank" class="easyui-checkbox c1" mapping="paymtype_isviabank" data-options="label: 'Via Bank', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row bankpanel bankpanel-hidden paymentpanel paymentpanel-hidden head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Bank Account</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partnerbank_id" class="easyui-combo" style="width: 400px" mapping="partnerbank_id" display="partnerbank_accnum" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row bankpanel bankpanel-hidden  paymentpanel paymentpanel-hidden head-step2 head-step2-hidden" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Account</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_paymto_bankacc" class="easyui-textbox" mapping="paymto_bankacc"  maxlength="90" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row bankpanel bankpanel-hidden paymentpanel paymentpanel-hidden head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Nama Account</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_paymto_bankaccname" class="easyui-textbox" mapping="paymto_bankaccname"  maxlength="90" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row bankpanel bankpanel-hidden paymentpanel paymentpanel-hidden head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Nama Bank</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_paymto_bankname" class="easyui-textbox" mapping="paymto_bankname"  maxlength="90" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row paymentpanel paymentpanel-hidden head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Partner Contact</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partnercontact_id" class="easyui-combo" style="width: 400px" mapping="partnercontact_id" display="partnercontact_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row paymentpanel paymentpanel-hidden head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partnercontact_upname" class="easyui-textbox" mapping="partnercontact_upname" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row paymentpanel paymentpanel-hidden head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Position</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partnercontact_position" class="easyui-textbox" mapping="partnercontact_position" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row paymentpanel paymentpanel-hidden head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">HP</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partnercontact_upphone" class="easyui-textbox" mapping="partnercontact_upphone" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row paymentpanel paymentpanel-hidden head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Email</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partnercontact_email" class="easyui-textbox" mapping="partnercontact_email" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , validType: ['email'] ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row projectpanel head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Project</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_project_id" class="easyui-combo" style="width: 400px" mapping="project_id" display="project_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Project harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_project_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row projectpanel head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Project Task</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_projecttask_id" class="easyui-combo" style="width: 400px" mapping="projecttask_id" display="projecttask_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row head-step2 head-step2-hidden" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiry_isunbudgetted" class="easyui-checkbox c1" mapping="inquiry_isunbudgetted" data-options="label: 'UnBudgetted', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row budgetpanel budgetpanel-hidden head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Budget</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_projbudget_id" class="easyui-combo" style="width: 400px" mapping="projbudget_id" display="projbudget_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Budget harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_projbudget_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row budgetpanel budgetpanel-hidden head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Budget Task</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_projbudgettask_id" class="easyui-combo" style="width: 400px" mapping="projbudgettask_id" display="projbudgettask_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Deliver To</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_site_id" class="easyui-combo" style="width: 400px" mapping="site_id" display="site_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Site harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_site_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">To Address</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_deliver_siteaddress" class="easyui-textbox" mapping="deliver_siteaddress"  maxlength="250" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">To City</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_deliver_city" class="easyui-textbox" mapping="deliver_city" uppercase="true" maxlength="60" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">To UP Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_deliver_upname" class="easyui-textbox" mapping="deliver_upname" uppercase="true" maxlength="60" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row head-step2 head-step2-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">To UP Telp</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_deliver_uptelp" class="easyui-textbox" mapping="deliver_uptelp" uppercase="true" maxlength="60" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Doc</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_doc_id" class="easyui-combo" style="width: 400px" mapping="doc_id" display="doc_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'ID harus diisi', disabled: true"   validType="requiredcombo['pnl_edit-cbo_doc_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Doc Version</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiry_version" class="easyui-numberbox" mapping="inquiry_version" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Reject Notes</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiry_rejectnotes" class="easyui-textbox" mapping="inquiry_rejectnotes"  maxlength="255" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<?=$this->Section('Inquiry Settings', true, true, '')?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Inquiry Model</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquirymodel_id" class="easyui-textbox" mapping="inquirymodel_id"  maxlength="1" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Inquiry Model harus diisi', disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Item Manage As</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemmanage_id" class="easyui-textbox" mapping="itemmanage_id"  maxlength="2" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Item Manage Model harus diisi', disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col">Current Setting</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiry_isindependentsetting" class="easyui-checkbox c1" mapping="inquiry_isindependentsetting" data-options="label: 'Independent', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col">Selection</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiryselect_isshowitemasset" class="easyui-checkbox c1" mapping="inquiryselect_isshowitemasset" data-options="label: 'Show Itemasset', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiryselect_isshowitem" class="easyui-checkbox c1" mapping="inquiryselect_isshowitem" data-options="label: 'Show Item', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiryselect_isshowitemstock" class="easyui-checkbox c1" mapping="inquiryselect_isshowitemstock" data-options="label: 'Show Itemstock', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiryselect_isshowpartner" class="easyui-checkbox c1" mapping="inquiryselect_isshowpartner" data-options="label: 'Show Partner', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiryselect_isshowitemclass" class="easyui-checkbox c1" mapping="inquiryselect_isshowitemclass" data-options="label: 'Show Itemclass', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiryselect_isitemclassdisabled" class="easyui-checkbox c1" mapping="inquiryselect_isitemclassdisabled" data-options="label: 'Itemclass Disabled', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col">Metrics</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_isuseqty" class="easyui-checkbox c1" mapping="inquirytype_isuseqty" data-options="label: 'Use Qty', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_isusedays" class="easyui-checkbox c1" mapping="inquirytype_isusedays" data-options="label: 'Use Days', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_isusetask" class="easyui-checkbox c1" mapping="inquirytype_isusetask" data-options="label: 'Use Task', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col">Range</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_isdateinterval" class="easyui-checkbox c1" mapping="inquirytype_isdateinterval" data-options="label: 'Date Interval', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col">Followup</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_istoberequest" class="easyui-checkbox c1" mapping="inquirytype_istoberequest" data-options="label: 'Mark As To be Request', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_isautorequest" class="easyui-checkbox c1" mapping="inquirytype_isautorequest" data-options="label: 'Auto create Request when processed', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_isautoorder" class="easyui-checkbox c1" mapping="inquirytype_isautoorder" data-options="label: 'Auto create Order when processed', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_ismovinginit" class="easyui-checkbox c1" mapping="inquirytype_ismovinginit" data-options="label: 'Auto create Moving Init when processed', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col">Restrict To Budget</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_islimitqty" class="easyui-checkbox c1" mapping="inquirytype_islimitqty" data-options="label: 'Limit Qty by Budget', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_islimitdays" class="easyui-checkbox c1" mapping="inquirytype_islimitdays" data-options="label: 'Limit Days by Budget', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_islimittask" class="easyui-checkbox c1" mapping="inquirytype_islimittask" data-options="label: 'Limit Task by Budget', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_islimitvalue" class="easyui-checkbox c1" mapping="inquirytype_islimitvalue" data-options="label: 'Limit Value By Budget', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_isallowunbudget" class="easyui-checkbox c1" mapping="inquirytype_isallowunbudget" data-options="label: 'Allow Request UnBudgeted', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_isallowitemunbudget" class="easyui-checkbox c1" mapping="inquirytype_isallowitemunbudget" data-options="label: 'Allow Items UnBudgeted', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_isallowoverbudget" class="easyui-checkbox c1" mapping="inquirytype_isallowoverbudget" data-options="label: 'Allow Request Over Budget', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col">Advance Request</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_isallowadvance" class="easyui-checkbox c1" mapping="inquirytype_isallowadvance" data-options="label: 'Allowed', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col">AR Partner</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquirytype_isemplaspartner" class="easyui-checkbox c1" mapping="inquirytype_isemplaspartner" data-options="label: 'Use Responsible Employee', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Max Advance Value</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquirytype_maxadvancevalue" class="easyui-numberbox" mapping="inquirytype_maxadvancevalue" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		</div>
					
		<?=$this->Section('Status', true, true, '')?>
		<div class="fgta_section_collapsible " style="display: none">
					
		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiry_iscommit" class="easyui-checkbox c1" mapping="inquiry_iscommit" data-options="label: 'Commit', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">CommitBy</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiry_commitby" class="easyui-textbox" mapping="inquiry_commitby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">CommitDate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiry_commitdate" class="easyui-textbox" mapping="inquiry_commitdate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiry_isapprovalprogress" class="easyui-checkbox c1" mapping="inquiry_isapprovalprogress" data-options="label: 'Progress', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiry_isapproved" class="easyui-checkbox c1" mapping="inquiry_isapproved" data-options="label: 'Approved', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Approve By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiry_approveby" class="easyui-textbox" mapping="inquiry_approveby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Approve Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiry_approvedate" class="easyui-textbox" mapping="inquiry_approvedate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiry_isdeclined" class="easyui-checkbox c1" mapping="inquiry_isdeclined" data-options="label: 'Declined', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Decline By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiry_declineby" class="easyui-textbox" mapping="inquiry_declineby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Decline Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiry_declinedate" class="easyui-textbox" mapping="inquiry_declinedate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiry_ispreparing" class="easyui-checkbox c1" mapping="inquiry_ispreparing" data-options="label: 'Preparing', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiry_isprepared" class="easyui-checkbox c1" mapping="inquiry_isprepared" data-options="label: 'Prepared', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Prepared By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiry_preparedby" class="easyui-textbox" mapping="inquiry_preparedby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Prepared Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiry_prepareddate" class="easyui-textbox" mapping="inquiry_prepareddate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiry_isreject" class="easyui-checkbox c1" mapping="inquiry_isreject" data-options="label: 'Reject', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Reject By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiry_rejectby" class="easyui-textbox" mapping="inquiry_rejectby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Reject Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiry_rejectdate" class="easyui-textbox" mapping="inquiry_rejectdate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiry_iscomplete" class="easyui-checkbox c1" mapping="inquiry_iscomplete" data-options="label: 'Complete', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiry_isclose" class="easyui-checkbox c1" mapping="inquiry_isclose" data-options="label: 'Close', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Close By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiry_closeby" class="easyui-textbox" mapping="inquiry_closeby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Close Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_inquiry_closedate" class="easyui-textbox" mapping="inquiry_closedate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_inquiry_isautogenerated" class="easyui-checkbox c1" mapping="inquiry_isautogenerated" data-options="label: 'Auto Generated', labelPosition: 'after', checked: false , labelWidth: '300px', disabled: true">
			</div>
		</div>

		</div>
					
	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col detilbox" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_edititemgrid')">
					<div id="pnl_edit-txt_item_title" class="detilgrid-text">Item</div>
					<div id="pnl_edit-txt_item_value" class="detilgrid-value">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editfilesgrid')">
					<div id="pnl_edit-txt_files_title" class="detilgrid-text">Files</div>
					<div id="pnl_edit-txt_files_value" class="detilgrid-value">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editapprovalgrid')">
					<div id="pnl_edit-txt_approval_title" class="detilgrid-text">Approval</div>
					<div id="pnl_edit-txt_approval_value" class="detilgrid-value">&nbsp;</div>
				</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol-tombol xtion disini -->
			<?php
			$customheaderxtion = __DIR__.'/inquiry-edit-customxtion.phtml'; 
			if (is_file($customheaderxtion)) {
				include $customheaderxtion;
			} else { ?>
			<a id="pnl_edit-btn_print" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'icon-print'">print</a>
			
			<a id="pnl_edit-btn_commit" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'fgta-icon-commit'">Commit</a>			
			<a id="pnl_edit-btn_uncommit" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'fgta-icon-uncommit'">UnCommit</a>
			
			
				<a id="pnl_edit-btn_approve" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="plain:true,iconCls:'fgta-icon-posting'">Approve</a>
				<a id="pnl_edit-btn_decline" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="plain:true,iconCls:'fgta-icon-unposting'">Decline</a>
				
			
			<?php } ?>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5 fgta-button-delete" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

