<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Item Model</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemmodel_id" class="easyui-textbox" mapping="itemmodel_id" uppercase="true" maxlength="10" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'ID harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Item Model</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemmodel_name" class="easyui-textbox" mapping="itemmodel_name" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Nama model harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemmodel_descr" class="easyui-textbox" mapping="itemmodel_descr"  maxlength="255" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemmodel_isintangible" class="easyui-checkbox c1" mapping="itemmodel_isintangible" data-options="label: 'Intangiable', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemmodel_issellable" class="easyui-checkbox c1" mapping="itemmodel_issellable" data-options="label: 'Sellable', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemmodel_isnonitem" class="easyui-checkbox c1" mapping="itemmodel_isnonitem" data-options="label: 'Non Item', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Manage As</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_itemmanage_id" class="easyui-combo" style="width: 400px" mapping="itemmanage_id" display="itemmanage_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Manage As harus diisi'"   validType="requiredcombo['pnl_edit-cbo_itemmanage_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemmanage_isasset" class="easyui-checkbox c1" mapping="itemmanage_isasset" data-options="label: 'Manage As Asset ', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemmodel_ismultidept" class="easyui-checkbox c1" mapping="itemmodel_ismultidept" data-options="label: 'Own By Multidept', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_dept_id" class="easyui-combo" style="width: 400px" mapping="dept_id" display="dept_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_itemmodel_ishasmainteinerdept" class="easyui-checkbox c1" mapping="itemmodel_ishasmainteinerdept" data-options="label: 'Has Maintainer Dept', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Depresiasi</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_depremodel_id" class="easyui-combo" style="width: 400px" mapping="depremodel_id" display="depremodel_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Depre Model harus diisi'"   validType="requiredcombo['pnl_edit-cbo_depremodel_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_depremodel_isautocalc" class="easyui-checkbox c1" mapping="depremodel_isautocalc" data-options="label: 'Auto Calculation', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row deprevaluepanel deprevaluepanel-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Depre Age</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemmodel_depreage" class="easyui-numberbox" mapping="itemmodel_depreage" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row deprevaluepanel deprevaluepanel-hidden" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Depre Residu</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_itemmodel_depreresidu" class="easyui-numberbox" mapping="itemmodel_depreresidu" style="width: 400px; text-align:right" data-options="precision: 2, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol-tombol xtion disini -->
			<?php
			$customheaderxtion = __DIR__.'/itemmodel-edit-customxtion.phtml'; 
			if (is_file($customheaderxtion)) {
				include $customheaderxtion;
			} else { ?>
			
			
			
			
			<?php } ?>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

