<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_edit-caption">{{STATE_BEG}}Jurnal Type{{STATE_END}}</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_jurnaltype_id" class="easyui-textbox" mapping="jurnaltype_id" uppercase="true" maxlength="10" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'ID harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Model</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_jurnalmodel_id" class="easyui-combo" style="width: 400px" mapping="jurnalmodel_id" display="jurnalmodel_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Model Jurnal harus diisi'"   validType="requiredcombo['pnl_edit-cbo_jurnalmodel_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Type Jurnal</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_jurnaltype_name" class="easyui-textbox" mapping="jurnaltype_name" uppercase="true" maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Tipe Jurnal harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_jurnaltype_descr" class="easyui-textbox" mapping="jurnaltype_descr"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Prefix</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_jurnaltype_prefix" class="easyui-textbox" mapping="jurnaltype_prefix" uppercase="true" maxlength="2" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Prefix Jurnal harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Column</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_jurnaltype_col" class="easyui-textbox" mapping="jurnaltype_col"  maxlength="1" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;">jiki diisi D atau K, saat jurnal disimpan akan otomatis membuat satu baris di jurnal detil sesuai dengan sub account header.<br>Kosongkan apabila tidak memerlukan fungsi ini.</div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col">Status</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_jurnaltype_isdisabled" class="easyui-checkbox c1" mapping="jurnaltype_isdisabled" data-options="label: 'Disabled', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col">Setting</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_jurnaltype_ishasduedate" class="easyui-checkbox c1" mapping="jurnaltype_ishasduedate" data-options="label: 'Due Date', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_jurnaltype_ishasheadvalue" class="easyui-checkbox c1" mapping="jurnaltype_ishasheadvalue" data-options="label: 'Header Value', labelPosition: 'after', checked: false , labelWidth: '150px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_jurnaltype_ishasheadaccount" class="easyui-checkbox c1" mapping="jurnaltype_ishasheadaccount" data-options="label: 'Header Account', labelPosition: 'after', checked: false , labelWidth: '150px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_jurnaltype_ishasheadunit" class="easyui-checkbox c1" mapping="jurnaltype_ishasheadunit" data-options="label: 'Header Unit', labelPosition: 'after', checked: false , labelWidth: '150px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_jurnaltype_ishasheaddept" class="easyui-checkbox c1" mapping="jurnaltype_ishasheaddept" data-options="label: 'Header Dept', labelPosition: 'after', checked: false , labelWidth: '150px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_jurnaltype_ishasheadpartner" class="easyui-checkbox c1" mapping="jurnaltype_ishasheadpartner" data-options="label: 'Header Partner', labelPosition: 'after', checked: false , labelWidth: '150px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_jurnaltype_ishasdetunit" class="easyui-checkbox c1" mapping="jurnaltype_ishasdetunit" data-options="label: 'Detil Unit', labelPosition: 'after', checked: false , labelWidth: '150px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_jurnaltype_ishasdetdept" class="easyui-checkbox c1" mapping="jurnaltype_ishasdetdept" data-options="label: 'Detil Dept', labelPosition: 'after', checked: false , labelWidth: '150px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_jurnaltype_ishasdetpartner" class="easyui-checkbox c1" mapping="jurnaltype_ishasdetpartner" data-options="label: 'Detil Partner', labelPosition: 'after', checked: false , labelWidth: '150px'">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col detilbox" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editcoagrid')">
					<div id="pnl_edit-txt_coa_title" class="detilgrid-text">Chart of Accounts</div>
					<div id="pnl_edit-txt_coa_value" class="detilgrid-value coa_totalvalue">&nbsp;</div>
				</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol-tombol xtion disini -->
			<?php
			$customheaderxtion = __DIR__.'/jurnaltype-edit-customxtion.phtml'; 
			if (is_file($customheaderxtion)) {
				include $customheaderxtion;
			} else { ?>
			
			
			
			
			<?php } ?>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5 fgta-button-delete" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

